# -*- coding: utf-8 -*-
"""
fv_candidates.py —— 「完整片」从 14 扩到 100 的**候选清单**。

## 选片口径：风格辨识度

不是「film-grab 有什么就收什么」。每条候选都必须在 `why` 里回答一句：
**凭什么说它画面辨识度高**。答不出来的不收 —— 否则 100 张卡里会混进大量
风格平淡的商业片，把库里「以术语为准」的价值稀释掉。

具体按四类取：
  1. **作者性导演**：画面即签名（塔可夫斯基、王家卫、库布里克这类已在库里）
  2. **摄影标杆**：Deakins / Doyle / Khondji / Lubezki 这类被反复引用的
  3. **强风格类型片**：恐怖、黑色电影、西部、赛博朋克等有明确视觉语法的
  4. **动画与实验**：赛璐珞、定格、手绘长片等媒介本身就是风格

## 这个文件**不含 film-grab URL**

URL 必须解析出来（读导演分类页），不能手写 —— 实测手写的 10 个里 8 个 404
（URL 里的日期是画廊发布时间，不是上映年份）。解析器在 `fv_resolve.py`。

所以这个文件只管「选哪些片、为什么选」，URL 由解析器填进 `fv_data.FILMS`。

## 分组

按 `director_slug` 分组：一个导演页能解析出他的全部片目，
所以同一导演的多部片只花一次抓取（对站点也客气）。
"""

# 字段说明
#   slug             最终要用的稳定标识（<导演>-<片名>）
#   director_zh/en   导演名
#   director_slug    film-grab 的导演分类页 slug（解析用）
#   title_zh/en      片名（en 用于在导演页里匹配）
#   year             年份（辅助判断，不参与匹配）
#   why              **凭什么说它画面辨识度高**（口径的落点，不能空）

CANDIDATES = [
    # ---------------------------------------------------- 塔可夫斯基
    {"slug": "tarkovsky-solaris", "director_zh": "安德烈·塔可夫斯基",
     "director_en": "Andrei Tarkovsky", "director_slug": "andrei-tarkovsky",
     "title_zh": "飞向太空", "title_en": "Solaris", "year": 1972,
     "why": "把科幻拍成水、草与记忆的质感；失重段落用极慢的环绕与长镜，是「内向科幻」的影像范本"},
    {"slug": "tarkovsky-nostalghia", "director_zh": "安德烈·塔可夫斯基",
     "director_en": "Andrei Tarkovsky", "director_slug": "andrei-tarkovsky",
     "title_zh": "乡愁", "title_en": "Nostalghia", "year": 1983,
     "why": "湿冷石墙、长镜里举烛横穿水池 —— 用单一动作撑满一个镜头时间的极端案例"},

    # ---------------------------------------------------- 王家卫
    {"slug": "wong-kar-wai-2046", "director_zh": "王家卫",
     "director_en": "Wong Kar Wai", "director_slug": "wong-kar-wai",
     "title_zh": "2046", "title_en": "2046", "year": 2004,
     "why": "把《花样年华》的红绿推到更饱和的暖金与霓虹，未来感全靠色温而非布景"},
    {"slug": "wong-kar-wai-fallen-angels", "director_zh": "王家卫",
     "director_en": "Wong Kar Wai", "director_slug": "wong-kar-wai",
     "title_zh": "堕落天使", "title_en": "Fallen Angels", "year": 1995,
     "why": "超广角贴脸畸变的极致；霓虹绿与黑，杜可风最激进的一次手持"},
    {"slug": "wong-kar-wai-happy-together", "director_zh": "王家卫",
     "director_en": "Wong Kar Wai", "director_slug": "wong-kar-wai",
     "title_zh": "春光乍泄", "title_en": "Happy Together", "year": 1997,
     "why": "黑白与高饱和彩色段落交替；伊瓜苏瀑布的蓝绿是港片里少见的自然色块"},

    # ---------------------------------------------------- 库布里克
    {"slug": "kubrick-2001", "director_zh": "斯坦利·库布里克",
     "director_en": "Stanley Kubrick", "director_slug": "stanley-kubrick",
     "title_zh": "2001 太空漫游", "title_en": "2001: A Space Odyssey", "year": 1968,
     "why": "一点透视的走廊与对称舱室、纯色块与硬边几何 —— 后世科幻构图的公共祖先"},
    {"slug": "kubrick-clockwork-orange", "director_zh": "斯坦利·库布里克",
     "director_en": "Stanley Kubrick", "director_slug": "stanley-kubrick",
     "title_zh": "发条橙", "title_en": "A Clockwork Orange", "year": 1971,
     "why": "广角畸变 + 对称构图 + 高饱和撞色，把暴力拍成装饰艺术"},

    # ---------------------------------------------------- 黑泽明
    {"slug": "kurosawa-rashomon", "director_zh": "黑泽明",
     "director_en": "Akira Kurosawa", "director_slug": "akira-kurosawa",
     "title_zh": "罗生门", "title_en": "Rashomon", "year": 1950,
     "why": "让阳光穿过树叶直接进镜头 —— 第一次把自然光当戏剧主角"},
    {"slug": "kurosawa-seven-samurai", "director_zh": "黑泽明",
     "director_en": "Akira Kurosawa", "director_slug": "akira-kurosawa",
     "title_zh": "七武士", "title_en": "Seven Samurai", "year": 1954,
     "why": "多机位长焦拍雨与泥；横幅式群像调度的教科书"},
    {"slug": "kurosawa-throne-of-blood", "director_zh": "黑泽明",
     "director_en": "Akira Kurosawa", "director_slug": "akira-kurosawa",
     "title_zh": "蜘蛛巢城", "title_en": "Throne of Blood", "year": 1957,
     "why": "能剧式静止与雾中森林；把麦克白做成浮世绘般的构图"},

    # ---------------------------------------------------- 今村昌平 / 小林正树
    {"slug": "kobayashi-harakiri", "director_zh": "小林正树",
     "director_en": "Masaki Kobayashi", "director_slug": "masaki-kobayashi",
     "title_zh": "切腹", "title_en": "Harakiri", "year": 1962,
     "why": "宽银幕黑白 + 极简室内几何，把武家秩序拍成冷峻的平面设计"},

    # ---------------------------------------------------- 芬奇
    {"slug": "fincher-fight-club", "director_zh": "大卫·芬奇",
     "director_en": "David Fincher", "director_slug": "david-fincher",
     "title_zh": "搏击俱乐部", "title_en": "Fight Club", "year": 1999,
     "why": "漂白般的冷绿与脏黄；把现代办公与地下空间的两种脏度拍得泾渭分明"},
    {"slug": "fincher-zodiac", "director_zh": "大卫·芬奇",
     "director_en": "David Fincher", "director_slug": "david-fincher",
     "title_zh": "十二宫", "title_en": "Zodiac", "year": 2007,
     "why": "数字摄影的极干净冷调；70 年代加州被拍成一种无光泽的灰"},

    # ---------------------------------------------------- 维伦纽瓦
    {"slug": "villeneuve-arrival", "director_zh": "丹尼斯·维伦纽瓦",
     "director_en": "Denis Villeneuve", "director_slug": "denis-villeneuve",
     "title_zh": "降临", "title_en": "Arrival", "year": 2016,
     "why": "雾、灰绿与竖构图；把外星接触拍成天气，而不是特效"},
    {"slug": "villeneuve-sicario", "director_zh": "丹尼斯·维伦纽瓦",
     "director_en": "Denis Villeneuve", "director_slug": "denis-villeneuve",
     "title_zh": "边境杀手", "title_en": "Sicario", "year": 2015,
     "why": "Deakins 的黄昏热噪声与夜视绿 —— 两种色温各承担一半的紧张"},
    {"slug": "villeneuve-prisoners", "director_zh": "丹尼斯·维伦纽瓦",
     "director_en": "Denis Villeneuve", "director_slug": "denis-villeneuve",
     "title_zh": "囚徒", "title_en": "Prisoners", "year": 2013,
     "why": "永不停雨的灰绿小镇；Deakins 用大头灯与雨把中景压成暗调"},

    # ---------------------------------------------------- 奉俊昊 / 朴赞郁
    {"slug": "bong-memories-of-murder", "director_zh": "奉俊昊",
     "director_en": "Bong Joon-ho", "director_slug": "joon-ho-bong",
     "title_zh": "杀人回忆", "title_en": "Memories of Murder", "year": 2003,
     "why": "把韩国乡野的土黄与稻田拍成压抑的色谱；尾声直视镜头的构图是名场面"},
    {"slug": "bong-snowpiercer", "director_zh": "奉俊昊",
     "director_en": "Bong Joon-ho", "director_slug": "joon-ho-bong",
     "title_zh": "雪国列车", "title_en": "Snowpiercer", "year": 2013,
     "why": "一节车厢一种色彩系统，横向推进的空间即阶级叙事"},
    {"slug": "park-chan-wook-oldboy", "director_zh": "朴赞郁",
     "director_en": "Park Chan-wook", "director_slug": "chan-wook-park",
     "title_zh": "老男孩", "title_en": "Oldboy", "year": 2003,
     "why": "高饱和绿与紫的对撞、长镜横移的走廊打斗 —— 韩式暴力美学的高峰"},
    {"slug": "park-chan-wook-the-handmaiden", "director_zh": "朴赞郁",
     "director_en": "Park Chan-wook", "director_slug": "chan-wook-park",
     "title_zh": "小姐", "title_en": "The Handmaiden", "year": 2016,
     "why": "日据时期宅邸的深绿与金；对称构图与镜面分割讲双重叙事"},

    # ---------------------------------------------------- 李沧东 / 罗泓轸
    {"slug": "lee-chang-dong-burning", "director_zh": "李沧东",
     "director_en": "Lee Chang-dong", "director_slug": "chang-dong-lee",
     "title_zh": "燃烧", "title_en": "Burning", "year": 2018,
     "why": "黄昏的橙与夜的黑并列；把「不安」拍成一种持续的暮色"},

    # ---------------------------------------------------- 侯孝贤 / 杨德昌
    {"slug": "yang-edward-yi-yi", "director_zh": "杨德昌",
     "director_en": "Edward Yang", "director_slug": "edward-yang",
     "title_zh": "一一", "title_en": "Yi Yi", "year": 2000,
     "why": "玻璃反射构图；城市中产的冷白日光与办公室荧光"},

    # ---------------------------------------------------- 蔡明亮 / 陈凯歌 / 张艺谋
    {"slug": "zhang-yimou-hero", "director_zh": "张艺谋",
     "director_en": "Zhang Yimou", "director_slug": "zhang-yimou",
     "title_zh": "英雄", "title_en": "Hero", "year": 2002,
     "why": "每个叙事层一种主色（红/蓝/白/绿），把色彩当叙事结构的极端案例"},
    {"slug": "zhang-yimou-raise-the-red-lantern", "director_zh": "张艺谋",
     "director_en": "Zhang Yimou", "director_slug": "zhang-yimou",
     "title_zh": "大红灯笼高高挂", "title_en": "Raise the Red Lantern", "year": 1991,
     "why": "红灯笼与灰墙的四合院对称；构图本身就是制度的形状"},
    {"slug": "wong-kar-wai-the-grandmaster", "director_zh": "王家卫",
     "director_en": "Wong Kar Wai", "director_slug": "wong-kar-wai",
     "title_zh": "一代宗师", "title_en": "The Grandmaster", "year": 2013,
     "why": "雨夜打斗的银灰与金；把武侠拍成布料与雨水的质感研究"},

    # ---------------------------------------------------- 日本
    {"slug": "mizoguchi-ugetsu", "director_zh": "沟口健二",
     "director_en": "Kenji Mizoguchi", "director_slug": "kenji-mizoguchi",
     "title_zh": "雨月物语", "title_en": "Ugetsu", "year": 1953,
     "why": "一卷式长镜横移；雾与湖面把志怪拍成水墨"},
    {"slug": "miike-audition", "director_zh": "三池崇史",
     "director_en": "Takashi Miike", "director_slug": "takashi-miike",
     "title_zh": "切肤之爱", "title_en": "Audition", "year": 1999,
     "why": "前段温和的电视质感与后段的过曝白形成断裂；用画质切换做恐怖转场"},
    {"slug": "shinkai-your-name", "director_zh": "新海诚",
     "director_en": "Makoto Shinkai", "director_slug": "makoto-shinkai",
     "title_zh": "你的名字", "title_en": "Your Name", "year": 2016,
     "why": "逆光与镜头光晕的极致；把黄昏拍成动画里的独立色温层"},
    {"slug": "miyazaki-spirited-away", "director_zh": "宫崎骏",
     "director_en": "Hayao Miyazaki", "director_slug": "hayao-miyazaki",
     "title_zh": "千与千寻", "title_en": "Spirited Away", "year": 2001,
     "why": "暖色灯笼与深绿植被；手绘背景的密度本身就是风格"},

    # ---------------------------------------------------- 欧洲作者
    {"slug": "bergman-the-seventh-seal", "director_zh": "英格玛·伯格曼",
     "director_en": "Ingmar Bergman", "director_slug": "ingmar-bergman",
     "title_zh": "第七封印", "title_en": "The Seventh Seal", "year": 1957,
     "why": "高对比黑白与过曝天空；把中世纪寓言拍成极简的明暗对照"},
    {"slug": "bergman-persona", "director_zh": "英格玛·伯格曼",
     "director_en": "Ingmar Bergman", "director_slug": "ingmar-bergman",
     "title_zh": "假面", "title_en": "Persona", "year": 1966,
     "why": "脸与脸重叠的正面特写；Sven Nykvist 的柔光把皮肤拍成地形"},
    {"slug": "fellini-8-half", "director_zh": "费德里科·费里尼",
     "director_en": "Federico Fellini", "director_slug": "federico-fellini",
     "title_zh": "八部半", "title_en": "8½", "year": 1963,
     "why": "黑白里的超现实群像调度；梦境段落的过曝与深黑"},
    {"slug": "antonioni-blow-up", "director_zh": "米开朗基罗·安东尼奥尼",
     "director_en": "Michelangelo Antonioni", "director_slug": "michelangelo-antonioni",
     "title_zh": "放大", "title_en": "Blow-Up", "year": 1966,
     "why": "60 年代伦敦的高调冷色与草地绿；构图里大量空与几何"},
    {"slug": "godard-contempt", "director_zh": "让-吕克·戈达尔",
     "director_en": "Jean-Luc Godard", "director_slug": "jean-luc-godard",
     "title_zh": "蔑视", "title_en": "Contempt", "year": 1963,
     "why": "Raoul Coutard 的红蓝黄原色块与宽银幕；地中海蓝被推成饱和色板"},
    {"slug": "godard-pierrot-le-fou", "director_zh": "让-吕克·戈达尔",
     "director_en": "Jean-Luc Godard", "director_slug": "jean-luc-godard",
     "title_zh": "狂人皮埃罗", "title_en": "Pierrot le Fou", "year": 1965,
     "why": "把原色当拼贴材料；红蓝黄在宽银幕里被切成漫画分格"},
    {"slug": "melville-le-samourai", "director_zh": "让-皮埃尔·梅尔维尔",
     "director_en": "Jean-Pierre Melville", "director_slug": "jean-pierre-melville",
     "title_zh": "独行杀手", "title_en": "Le Samouraï", "year": 1967,
     "why": "灰蓝与米色的极简冷调；风衣与帽子的剪影配色是黑色电影的现代版"},
    {"slug": "wenders-paris-texas", "director_zh": "维姆·文德斯",
     "director_en": "Wim Wenders", "director_slug": "wim-wenders",
     "title_zh": "德州巴黎", "title_en": "Paris, Texas", "year": 1984,
     "why": "Robby Müller 的霓虹与沙漠；红帽与绿衬衫在灰蓝里的一点撞色"},
    {"slug": "tarkovsky-ivan", "director_zh": "安德烈·塔可夫斯基",
     "director_en": "Andrei Tarkovsky", "director_slug": "andrei-tarkovsky",
     "title_zh": "伊万的童年", "title_en": "Ivan's Childhood", "year": 1962,
     "why": "黑白里的水面与白桦林；梦境段落的过曝是塔可夫斯基的起点"},

    # ---------------------------------------------------- 好莱坞经典
    {"slug": "welles-citizen-kane", "director_zh": "奥逊·威尔斯",
     "director_en": "Orson Welles", "director_slug": "orson-welles",
     "title_zh": "公民凯恩", "title_en": "Citizen Kane", "year": 1941,
     "why": "深焦与低角度天花板；把明暗对照搬进现代室内"},
    {"slug": "welles-touch-of-evil", "director_zh": "奥逊·威尔斯",
     "director_en": "Orson Welles", "director_slug": "orson-welles",
     "title_zh": "历劫佳人", "title_en": "Touch of Evil", "year": 1958,
     "why": "开场三分钟长镜；高对比黑白与广角畸变的黑色电影终章"},
    {"slug": "hitchcock-vertigo", "director_zh": "阿尔弗雷德·希区柯克",
     "director_en": "Alfred Hitchcock", "director_slug": "alfred-hitchcock",
     "title_zh": "迷魂记", "title_en": "Vertigo", "year": 1958,
     "why": "绿与红的病态对撞、滤镜化的旧金山 —— 彩色黑色电影的样板"},
    {"slug": "hitchcock-rear-window", "director_zh": "阿尔弗雷德·希区柯克",
     "director_en": "Alfred Hitchcock", "director_slug": "alfred-hitchcock",
     "title_zh": "后窗", "title_en": "Rear Window", "year": 1954,
     "why": "单场景 + 长焦窥视；把「看」这件事本身做成构图结构"},
    {"slug": "lynch-blue-velvet", "director_zh": "大卫·林奇",
     "director_en": "David Lynch", "director_slug": "david-lynch",
     "title_zh": "蓝丝绒", "title_en": "Blue Velvet", "year": 1986,
     "why": "艳红窗帘与暗绿草坪的撞色；把美国小镇拍成夜里的高饱和噩梦"},
    {"slug": "lynch-mulholland-drive", "director_zh": "大卫·林奇",
     "director_en": "David Lynch", "director_slug": "david-lynch",
     "title_zh": "穆赫兰道", "title_en": "Mulholland Drive", "year": 2001,
     "why": "暖琥珀的夜与冷蓝的幻；同一场戏换一套色温就是另一层现实"},
    {"slug": "michael-mann-heat", "director_zh": "迈克尔·曼",
     "director_en": "Michael Mann", "director_slug": "michael-mann",
     "title_zh": "盗火线", "title_en": "Heat", "year": 1995,
     "why": "洛杉矶的蓝灰夜景被拍成冷金属；枪战段落没有配乐只有空间"},
    {"slug": "coppola-apocalypse-now", "director_zh": "弗朗西斯·福特·科波拉",
     "director_en": "Francis Ford Coppola", "director_slug": "francis-ford-coppola",
     "title_zh": "现代启示录", "title_en": "Apocalypse Now", "year": 1979,
     "why": "橙色的火与烟、直升机剪影对着天空 —— 把战争拍成色温的轰炸"},
    {"slug": "coppola-godfather", "director_zh": "弗朗西斯·福特·科波拉",
     "director_en": "Francis Ford Coppola", "director_slug": "francis-ford-coppola",
     "title_zh": "教父", "title_en": "The Godfather", "year": 1972,
     "why": "Gordon Willis 的「黑里还有黑」；室内只用顶光，眼窝永远在阴影里"},
    {"slug": "scorsese-taxi-driver", "director_zh": "马丁·斯科塞斯",
     "director_en": "Martin Scorsese", "director_slug": "martin-scorsese",
     "title_zh": "出租车司机", "title_en": "Taxi Driver", "year": 1976,
     "why": "钠灯的黄绿把纽约夜景染成病态；红色在灰里只出现一次"},

    # ---------------------------------------------------- 恐怖与类型
    {"slug": "kubrick-killers-kiss", "director_zh": "斯坦利·库布里克",
     "director_en": "Stanley Kubrick", "director_slug": "stanley-kubrick",
     "title_zh": "杀手之吻", "title_en": "Killer's Kiss", "year": 1955,
     "why": "黑白里的低照度工厂与屋顶；库布里克最早的明暗对照实验"},
    {"slug": "carpenter-halloween", "director_zh": "约翰·卡朋特",
     "director_en": "John Carpenter", "director_slug": "john-carpenter",
     "title_zh": "月光光心慌慌", "title_en": "Halloween", "year": 1978,
     "why": "宽银幕里的蓝色夜与空街；把「画框边缘」变成恐怖装置"},
    {"slug": "friedkin-the-exorcist", "director_zh": "威廉·弗莱德金",
     "director_en": "William Friedkin", "director_slug": "william-friedkin",
     "title_zh": "驱魔人", "title_en": "The Exorcist", "year": 1973,
     "why": "冷灰蓝的卧室与单一光源；恐怖发生在最普通的居室照明下"},
    {"slug": "ridley-scott-alien", "director_zh": "雷德利·斯科特",
     "director_en": "Ridley Scott", "director_slug": "ridley-scott",
     "title_zh": "异形", "title_en": "Alien", "year": 1979,
     "why": "工业蒸汽与频闪；把飞船内部拍成有湿度的厂房"},
    {"slug": "ridley-scott-blade-runner", "director_zh": "雷德利·斯科特",
     "director_en": "Ridley Scott", "director_slug": "ridley-scott",
     "title_zh": "银翼杀手", "title_en": "Blade Runner", "year": 1982,
     "why": "烟、雨、霓虹与金字塔式光束 —— 赛博朋克视觉的定义者"},
    {"slug": "ridley-scott-legend", "director_zh": "雷德利·斯科特",
     "director_en": "Ridley Scott", "director_slug": "ridley-scott",
     "title_zh": "诡秘怪谈", "title_en": "Legend", "year": 1985,
     "why": "雾、金粉与森林绿；童话布景的密度与光斑"},

    # ---------------------------------------------------- 动画
    {"slug": "kon-paprika", "director_zh": "今敏",
     "director_en": "Satoshi Kon", "director_slug": "satoshi-kon",
     "title_zh": "红辣椒", "title_en": "Paprika", "year": 2006,
     "why": "游行队伍的饱和撞色与场景无缝切换；把剪辑做成视觉奇观"},
    {"slug": "kon-millennium-actress", "director_zh": "今敏",
     "director_en": "Satoshi Kon", "director_slug": "satoshi-kon",
     "title_zh": "千年女优", "title_en": "Millennium Actress", "year": 2001,
     "why": "跨时代场景的连续转场；每个时代一套色板，靠色彩完成时间跳跃"},
    {"slug": "anime-akira", "director_zh": "大友克洋",
     "director_en": "Katsuhiro Otomo", "director_slug": "katsuhiro-otomo",
     "title_zh": "阿基拉", "title_en": "Akira", "year": 1988,
     "why": "新东京的霓虹红与工业灰；赛璐珞时代最高密度的城市夜景"},
    {"slug": "anime-ghost-in-the-shell", "director_zh": "押井守",
     "director_en": "Mamoru Oshii", "director_slug": "mamoru-oshii",
     "title_zh": "攻壳机动队", "title_en": "Ghost in the Shell", "year": 1995,
     "why": "香港式招牌与冷绿水面；把赛博朋克拍成安静的城市观察"},
    {"slug": "takahata-kaguya", "director_zh": "高畑勋",
     "director_en": "Isao Takahata", "director_slug": "isao-takahata",
     "title_zh": "辉夜姬物语", "title_en": "The Tale of Princess Kaguya", "year": 2013,
     "why": "淡墨与炭笔线条的留白动画；把素描的呼吸感做成整片语言"},
    # ---------------------------------------------------- 补足到 100（第二批）
    {"slug": "bertolucci-the-conformist", "director_zh": "贝纳尔多·贝托鲁奇",
     "director_en": "Bernardo Bertolucci", "director_slug": "bernardo-bertolucci",
     "title_zh": "同流者", "title_en": "The Conformist", "year": 1970,
     "why": "Vittorio Storaro 的琥珀与冷蓝对峙；光线像从百叶窗里被切成条，政治与欲望同色"},
    {"slug": "bertolucci-last-emperor", "director_zh": "贝纳尔多·贝托鲁奇",
     "director_en": "Bernardo Bertolucci", "director_slug": "bernardo-bertolucci",
     "title_zh": "末代皇帝", "title_en": "The Last Emperor", "year": 1987,
     "why": "紫禁城的金红与阴影；用色温区分「门内/门外」两个中国"},
    {"slug": "leone-once-upon-a-time-in-the-west", "director_zh": "赛尔乔·莱昂内",
     "director_en": "Sergio Leone", "director_slug": "sergio-leone",
     "title_zh": "西部往事", "title_en": "Once Upon a Time in the West", "year": 1968,
     "why": "极端大远景与脸的特写两极切换；土黄与天空的横向色带是西部片的色板原型"},
    {"slug": "leone-the-good-the-bad-and-the-ugly", "director_zh": "赛尔乔·莱昂内",
     "director_en": "Sergio Leone", "director_slug": "sergio-leone",
     "title_zh": "黄金三镖客", "title_en": "The Good, the Bad and the Ugly", "year": 1966,
     "why": "烈日下的过曝与土黄；把「干」拍成一种可见的质感"},
    {"slug": "kubrick-paths-of-glory", "director_zh": "斯坦利·库布里克",
     "director_en": "Stanley Kubrick", "director_slug": "stanley-kubrick",
     "title_zh": "光荣之路", "title_en": "Paths of Glory", "year": 1957,
     "why": "战壕横移长镜与对称的军事法庭；黑白里的空间即权力"},
    {"slug": "kubrick-dr-strangelove", "director_zh": "斯坦利·库布里克",
     "director_en": "Stanley Kubrick", "director_slug": "stanley-kubrick",
     "title_zh": "奇爱博士", "title_en": "Dr. Strangelove", "year": 1964,
     "why": "作战室的顶光与环形桌对称；把冷战拍成高对比的黑白几何"},
    {"slug": "tarkovsky-andrei-rublev", "director_zh": "安德烈·塔可夫斯基",
     "director_en": "Andrei Tarkovsky", "director_slug": "andrei-tarkovsky",
     "title_zh": "安德烈·卢布廖夫", "title_en": "Andrei Rublev", "year": 1966,
     "why": "黑白里的中世纪泥与火；最后一段突然转彩色壁画，是全片唯一的颜色"},
    {"slug": "bergman-wild-strawberries", "director_zh": "英格玛·伯格曼",
     "director_en": "Ingmar Bergman", "director_slug": "ingmar-bergman",
     "title_zh": "野草莓", "director_en_alt": "Wild Strawberries",
     "title_en": "Wild Strawberries", "year": 1957,
     "why": "高调黑白的过曝梦境；把回忆拍成没有中间调的亮"},
    {"slug": "fellini-la-dolce-vita", "director_zh": "费德里科·费里尼",
     "director_en": "Federico Fellini", "director_slug": "federico-fellini",
     "title_zh": "甜蜜的生活", "title_en": "La Dolce Vita", "year": 1960,
     "why": "罗马夜里的强反差黑白；喷泉与路灯把人物围在光环里"},
    {"slug": "antonioni-l-avventura", "director_zh": "米开朗基罗·安东尼奥尼",
     "director_en": "Michelangelo Antonioni", "director_slug": "michelangelo-antonioni",
     "title_zh": "奇遇", "title_en": "L'Avventura", "year": 1960,
     "why": "火山岩岛与灰海；用大面积空白构图表现「人不见了」"},
    {"slug": "godard-weekend", "director_zh": "让-吕克·戈达尔",
     "director_en": "Jean-Luc Godard", "director_slug": "jean-luc-godard",
     "title_zh": "周末", "title_en": "Weekend", "year": 1967,
     "why": "原色与长横移车流；把公路拍成色彩拼贴的政治寓言"},
    {"slug": "akerman-jeanne-dielman", "director_zh": "香特尔·阿克曼",
     "director_en": "Chantal Akerman", "director_slug": "chantal-akerman",
     "title_zh": "让娜·迪尔曼", "title_en": "Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles",
     "year": 1975,
     "why": "固定机位与走廊中景的重复；把家务拍成结构，颜色只有墙的黄与围裙的蓝"},
    {"slug": "kieslowski-three-colours-blue", "director_zh": "克日什托夫·基耶斯洛夫斯基",
     "director_en": "Krzysztof Kieślowski", "director_slug": "krzysztof-kieslowski",
     "title_zh": "蓝", "title_en": "Three Colours: Blue", "year": 1993,
     "why": "整片被一种蓝统治（泳池、吊灯、纸）；把颜色做成情绪的唯一出口"},
    {"slug": "kieslowski-three-colours-red", "director_zh": "克日什托夫·基耶斯洛夫斯基",
     "director_en": "Krzysztof Kieślowski", "director_slug": "krzysztof-kieslowski",
     "title_zh": "红", "title_en": "Three Colours: Red", "year": 1994,
     "why": "红色在每一个画面里都出现一次；暖红与冷绿的对位是本片语法"},
    {"slug": "wong-kar-wai-days-of-being-wild", "director_zh": "王家卫",
     "director_en": "Wong Kar Wai", "director_slug": "wong-kar-wai",
     "title_zh": "阿飞正传", "title_en": "Days of Being Wild", "year": 1990,
     "why": "墨绿与暗金；杜可风最早的降格慢动作与热带植物前景"},
    {"slug": "fincher-the-social-network", "director_zh": "大卫·芬奇",
     "director_en": "David Fincher", "director_slug": "david-fincher",
     "title_zh": "社交网络", "title_en": "The Social Network", "year": 2010,
     "why": "冷绿与琥珀的两种室内；用极低照度的数字摄影把对话拍成暗调"},
    {"slug": "ridley-scott-thelma-and-louise", "director_zh": "雷德利·斯科特",
     "director_en": "Ridley Scott", "director_slug": "ridley-scott",
     "title_zh": "末路狂花", "title_en": "Thelma & Louise", "year": 1991,
     "why": "沙漠的橙与天空的蓝把公路切成横向色带；末帧的过曝是全片唯一的高调"},
    {"slug": "villeneuve-enemy", "director_zh": "丹尼斯·维伦纽瓦",
     "director_en": "Denis Villeneuve", "director_slug": "denis-villeneuve",
     "title_zh": "宿敌", "title_en": "Enemy", "year": 2013,
     "why": "整片琥珀黄滤镜；把多伦多拍成一个没有蓝色的城市"},
    {"slug": "melville-army-of-shadows", "director_zh": "让-皮埃尔·梅尔维尔",
     "director_en": "Jean-Pierre Melville", "director_slug": "jean-pierre-melville",
     "title_zh": "影子部队", "title_en": "Army of Shadows", "year": 1969,
     "why": "整体压成葬礼般的冷蓝灰；室内几何空镜与静止构图，把抵抗运动拍成沉默的等待而非战斗"},
    {"slug": "welles-the-trial", "director_zh": "奥逊·威尔斯",
     "director_en": "Orson Welles", "director_slug": "orson-welles",
     "title_zh": "审判", "title_en": "The Trial", "year": 1962,
     "why": "废弃火车站的巨大空旷空间 + 极广角畸变，把卡夫卡拍成可触摸的噩梦几何"},
    {"slug": "satoshi-kon-tokyo-godfathers", "director_zh": "今敏", "director_en": "Satoshi Kon",
     "director_slug": "satoshi-kon", "title_zh": "东京教父", "title_en": "Tokyo Godfathers", "year": 2003,
     "why": "今敏最写实的一部：冬夜东京的冷蓝与暖灯分区，背景密度极高，与他的超现实作品形成对照"},
    {"slug": "kurosawa-ikiru", "director_zh": "黑泽明", "director_en": "Akira Kurosawa",
     "director_slug": "akira-kurosawa", "title_zh": "生之欲", "title_en": "Ikiru", "year": 1952,
     "why": "官僚办公室的平灰与雨夜霓虹高对比并置，把「活着」拍成文件堆的几何"},
    {"slug": "kurosawa-high-and-low", "director_zh": "黑泽明", "director_en": "Akira Kurosawa",
     "director_slug": "akira-kurosawa", "title_zh": "天国与地狱", "title_en": "High and Low", "year": 1963,
     "why": "前半一间客厅的横向群像、后半一整座城的追踪密度 —— 构图密度的对撞就是阶级"},
    {"slug": "kobayashi-kwaidan", "director_zh": "小林正树", "director_en": "Masaki Kobayashi",
     "director_slug": "masaki-kobayashi", "title_zh": "怪谈", "title_en": "Kwaidan", "year": 1964,
     "why": "人造绘景 + 平涂纯色块，把怪谈拍成会动的浮世绘；色彩刻意不真实"},
    {"slug": "bong-the-host", "director_zh": "奉俊昊", "director_en": "Bong Joon-ho",
     "director_slug": "joon-ho-bong", "title_zh": "汉江怪物", "title_en": "The Host", "year": 2006,
     "why": "怪物出现在明亮的阴天白日，日常的小吃摊黄与河滩绿灰 —— 恐怖不靠黑暗"},
    {"slug": "bong-mother", "director_zh": "奉俊昊", "director_en": "Bong Joon-ho",
     "director_slug": "joon-ho-bong", "title_zh": "母亲", "title_en": "Mother", "year": 2009,
     "why": "草药绿与土黄的低饱和田野 + 自然侧逆光；把惊悚埋在日常的明亮里"},

    # ---------------------------------------- 替换 9 部（film-grab 上不存在）
    {
        "slug": "hou-hsiao-hsien-flowers-of-shanghai",
        "director_zh": "侯孝贤",
        "director_en": "Hou Hsiao-hsien",
        "director_slug": "hsiao-hsien-hou",
        "title_zh": "海上花",
        "title_en": "Flowers of Shanghai",
        "year": 1998,
        "why": "全片室内油灯、**没有一场日光**；长镜穿过一道道门，鸦片烟把光变成雾 —— 侯孝贤最极端的封闭空间实验"
    },
    {
        "slug": "hou-hsiao-hsien-millennium-mambo",
        "director_zh": "侯孝贤",
        "director_en": "Hou Hsiao-hsien",
        "director_slug": "hsiao-hsien-hou",
        "title_zh": "千禧曼波",
        "title_en": "Millennium Mambo",
        "year": 2001,
        "why": "与他惯常的固定长镜相反：手持、霓虹、台北夜店的高饱和 —— 同一位导演的另一套视觉语法"
    },
    {
        "slug": "yang-edward-the-terrorizers",
        "director_zh": "杨德昌",
        "director_en": "Edward Yang",
        "director_slug": "edward-yang",
        "title_zh": "恐怖分子",
        "title_en": "The Terrorizers",
        "year": 1986,
        "why": "都市疏离的冷调 + 大量玻璃反射与远景，结尾那场戏用静止与距离把暴力推到画外"
    },
    {
        "slug": "ozu-floating-weeds",
        "director_zh": "小津安二郎",
        "director_en": "Yasujiro Ozu",
        "director_slug": "yasujiro-ozu",
        "title_zh": "浮草",
        "title_en": "Floating Weeds",
        "year": 1959,
        "why": "小津罕见的**彩色片**：饱和的红与彩绘布景，配上他标志性的低机位静止构图，颜色在他作品里几乎是孤例"
    },
    {
        "slug": "kiyoshi-kurosawa-pulse",
        "director_zh": "黑泽清",
        "director_en": "Kiyoshi Kurosawa",
        "director_slug": "kiyoshi-kurosawa",
        "title_zh": "脉冲",
        "title_en": "Pulse",
        "year": 2001,
        "why": "早期网络鬼故事：灰绿平光、空房间、门后的黑影 —— 把「连接」拍成一种可见的孤独"
    },
    {
        "slug": "antonioni-the-passenger",
        "director_zh": "米开朗基罗·安东尼奥尼",
        "director_en": "Michelangelo Antonioni",
        "director_slug": "michelangelo-antonioni",
        "title_zh": "过客",
        "title_en": "The Passenger",
        "year": 1975,
        "why": "结尾那个七分钟不剪断的镜头是影史名场面；北非的白墙、沙漠与蓝窗，色块比对话更响"
    },
    {
        "slug": "bresson-a-man-escaped",
        "director_zh": "罗贝尔·布列松",
        "director_en": "Robert Bresson",
        "director_slug": "robert-bresson",
        "title_zh": "死囚越狱",
        "title_en": "A Man Escaped",
        "year": 1956,
        "why": "只拍手、门、勺与绳索；画外音与声音先于画面 —— 极简到把「等待」拍成动作本身"
    },
    {
        "slug": "bresson-mouchette",
        "director_zh": "罗贝尔·布列松",
        "director_en": "Robert Bresson",
        "director_slug": "robert-bresson",
        "title_zh": "穆谢特",
        "title_en": "Mouchette",
        "year": 1967,
        "why": "灰调乡野、泥、雨与陷阱；用无人称的远景记录一个被围困的孩子，结尾的翻滚是全片唯一的大动作"
    },
    {
        "slug": "kobayashi-the-human-condition-i",
        "director_zh": "小林正树",
        "director_en": "Masaki Kobayashi",
        "director_slug": "masaki-kobayashi",
        "title_zh": "人间的条件 I：纯爱篇",
        "title_en": "The Human Condition I: No Greater Love",
        "year": 1959,
        "why": "宽银幕黑白里的满洲：泥、雪、矿场与人群的横向铺陈，把体制的碾压迫进每一个远景"
    },

    # ---------------------------------- 替换 3 部（站上没有/只有别的片）
    {
        "slug": "tsai-ming-liang-goodbye-dragon-inn",
        "director_zh": "蔡明亮",
        "director_en": "Tsai Ming-liang",
        "director_slug": "tsai-ming-liang",
        "title_zh": "不散",
        "title_en": "Goodbye Dragon Inn",
        "year": 2003,
        "why": "全片几乎都在一座将拆的电影院里：固定机位、几乎无对白、屋外大雨 —— 把「看电影」拍成一个将消失的空间"
    },
    {
        "slug": "refn-the-neon-demon",
        "director_zh": "尼古拉斯·温丁·雷弗恩",
        "director_en": "Nicolas Winding Refn",
        "director_slug": "nicolas-winding-refn",
        "title_zh": "霓虹恶魔",
        "title_en": "The Neon Demon",
        "year": 2016,
        "why": "把品红与青推成唯一光源，对称构图与慢速推镜 —— 当代霓虹美学的极端样本"
    },
    {
        "slug": "malick-days-of-heaven",
        "director_zh": "泰伦斯·马力克",
        "director_en": "Terrence Malick",
        "director_slug": "terrence-malick",
        "title_zh": "天堂之日",
        "title_en": "Days of Heaven",
        "year": 1978,
        "why": "全片在魔幻时刻实拍：麦田的金、天空的橙紫与逆光剪影 —— 自然光摄影的公共标杆"
    },
]
