# -*- coding: utf-8 -*-
"""
流派定义 —— 核心 18 个（西方古典 + 现代主义主干）。

字段说明：

字段说明：
  visual   : 视觉语言六层拆解（色彩/光影/笔触/构图/材质/情绪）
  prompt   : 可直接拼接的提示词层。subject 由你自己填，其余是风格层。
  video    : AI 视频额外需要的镜头/运动层
  sources  : 去哪些开放数据源搜图。cc0=True 表示只取 CC0 / 公共领域。
"""

CATEGORY = "西方古典与近代"

MOVEMENTS = [
# ---------------------------------------------------------------- 文艺复兴
{
 "slug": "renaissance",
 "name_zh": "文艺复兴",
 "name_en": "Renaissance",
 "period": "1400–1600",
 "region": "意大利 / 北欧",
 "tier": "A",
 "one_liner": "用解剖学、透视法和古典比例，把神请回人间。",
 "core": [
   "线性透视 + 空气透视，画面有可测量的纵深",
   "人体解剖准确，姿态来自古典雕塑",
   "金字塔式构图，主体稳定地坐在画面中心",
   "明暗对照（chiaroscuro）取代中世纪平面化布光",
 ],
 "visual": {
   "色彩": "赭石、土黄、暗红、赭绿为主；低饱和但层次厚，金箔点缀",
   "光影": "统一的单向光源，从侧上方来；暗部保留细节而非死黑，sfumato 让边缘雾化",
   "笔触": "几乎看不见笔触，表面如釉；这是后世最容易被 AI 弄错的一点",
   "构图": "金字塔 / 三角构图，地平线压低，背景常有理想化风景或建筑",
   "材质": "木板蛋彩 → 布面油画；亚麻纹理、清漆暖黄",
   "情绪": "庄严、克制、理性；神圣感来自秩序而不是夸张",
 },
 "palette": [("#8C6A3F","赭石"),("#A8322D","威尼斯红"),("#2E3B2F","橄榄绿"),
             ("#3B3630","暗褐"),("#D9C7A3","亚麻白"),("#B08D2E","金箔")],
 "artists": [("列奥纳多·达·芬奇","1452–1519"),("拉斐尔","1483–1520"),
             ("米开朗基罗","1475–1564"),("提香","1488–1576"),("波提切利","1445–1510")],
 "prompt": {
   "style": "renaissance oil painting, high renaissance, classical realism, old master technique, smooth sfumato blending, invisible brushwork",
   "lighting": "single directional light from upper side, chiaroscuro, soft volumetric shading, subtle ambient occlusion",
   "color": "muted earth palette, ochre, venetian red, olive green, warm varnish tone, low saturation with deep tonal range",
   "composition": "pyramidal composition, symmetrical balance, low horizon, idealised landscape background, architectural perspective",
   "medium": "oil on wood panel, aged varnish, fine craquelure, linen texture",
   "mood": "solemn, serene, dignified, devotional",
   "camera": "eye-level, medium shot, 50mm, deep focus",
 },
 "positive": " renaissance oil painting, high renaissance, classical realism, old master technique, smooth sfumato blending, invisible brushwork, single directional light from upper side, chiaroscuro, muted earth palette, ochre and venetian red and olive green, warm varnish tone, pyramidal composition, low horizon, idealised landscape background, solemn and serene mood, oil on wood panel, aged varnish, fine craquelure",
 "negative": "visible brushstrokes, impasto, modern clothing, neon colors, anachronism, anime, 3d render, plastic skin, hdr, oversaturated",
 "video": {
   "motion": "极慢的呼吸式微动；人物几乎静止，只有衣褶与烛火轻晃",
   "camera": "static shot 或极缓 dolly in；不要手持、不要快切",
   "note": "文艺复兴的镜头语言是「静止的画」——动得越少越对",
 },
 "pitfalls": [
   "AI 默认给油画加厚涂笔触 → 必须写 invisible brushwork / smooth blending",
   "现代人的脸和姿势 → 加 classical proportions, idealized features",
   "色彩过艳 → 明确 muted earth palette 并压低 saturation",
 ],
 "sources": {"cleveland": ["renaissance", "raphael", "titian"], "met": ["renaissance painting", "raphael"]},
 "see_also": ["baroque", "neoclassicism"],
},
# ---------------------------------------------------------------- 巴洛克
{
 "slug": "baroque",
 "name_zh": "巴洛克",
 "name_en": "Baroque",
 "period": "1600–1750",
 "region": "意大利 / 佛兰德斯 / 荷兰 / 西班牙",
 "tier": "A",
 "one_liner": "把光当成主角，用戏剧性明暗和动势制造情绪高潮。",
 "core": [
   "tenebrism：大面积黑，一束光劈开画面",
   "对角线动势，构图永远在「正在发生」",
   "织物质感极度华丽，褶皱是炫技战场",
   "宗教与权力叙事，情绪压倒理性",
 ],
 "visual": {
   "色彩": "深褐、沥青黑打底，暖金、猩红、深蓝点缀；高对比低饱和",
   "光影": "单一强光源从画外射入，暗部大面积吞没；烛光、天光、舞台光",
   "笔触": "松弛、可见、有速度感；鲁本斯式肥厚笔触",
   "构图": "对角线 / S 形动势，画面被切出画外，观者被拉进场景",
   "材质": "厚重亚麻布、天鹅绒、锦缎、大理石、镀金木",
   "情绪": "戏剧、激昂、感官、压迫感",
 },
 "palette": [("#1A1512","沥青黑"),("#6B4423","焦褐"),("#C9A227","暖金"),
             ("#8E1B1B","深猩红"),("#1F3A5F","普鲁士蓝"),("#E8DCC0","烛光白")],
 "artists": [("卡拉瓦乔","1571–1610"),("伦勃朗","1606–1669"),("鲁本斯","1577–1640"),
             ("委拉斯开兹","1599–1660"),("维米尔","1632–1675")],
 "prompt": {
   "style": "baroque oil painting, dramatic chiaroscuro, tenebrism, caravaggesque lighting, loose visible brushwork, lush drapery",
   "lighting": "single hard light source from off-frame, deep crushed shadows, candlelight rim light, theatrical spotlight, strong value contrast",
   "color": "bitumen black background, warm gold, deep crimson, prussian blue accents, low saturation but rich darks",
   "composition": "diagonal dynamic composition, s-curve, figure cut by frame edge, dramatic asymmetry",
   "medium": "oil on canvas, visible impasto, heavy linen weave, aged varnish",
   "mood": "dramatic, intense, sensual, theatrical",
   "camera": "slight low angle, medium close-up, 85mm, shallow depth of field",
 },
 "positive": " baroque oil painting, dramatic chiaroscuro, tenebrism, caravaggesque lighting, loose visible brushwork, lush drapery, single hard light source from off-frame, deep crushed shadows, candlelight rim light, bitumen black background, warm gold and deep crimson, diagonal dynamic composition, s-curve, theatrical and sensual mood, oil on canvas, heavy linen weave, aged varnish",
 "negative": "flat even lighting, pastel colors, cartoon, cel shading, minimalism, clean digital look, anime",
 "video": {
   "motion": "烛火摇曳、布料翻动、人物转身；动作有加速度",
   "camera": "缓慢 dolly in 逼近脸部；可用 low angle 强化压迫",
   "note": "光源必须单一且有方向，多光源会立刻杀死巴洛克感",
 },
 "pitfalls": [
   "写「dark」不够 → 必须写 tenebrism / chiaroscuro / crushed shadows",
   "多光源会让画面变成普通暗调摄影",
   "过饱和会变成奇幻插画而非巴洛克",
 ],
 "sources": {"cleveland": ["baroque", "rembrandt", "rubens"], "met": ["baroque painting", "rembrandt"]},
 "see_also": ["renaissance", "rococo"],
},
# ---------------------------------------------------------------- 洛可可
{
 "slug": "rococo",
 "name_zh": "洛可可",
 "name_en": "Rococo",
 "period": "1730–1780",
 "region": "法国 / 德意志",
 "tier": "A",
 "one_liner": "把巴洛克的重量换成糖霜：粉彩、曲线、享乐与轻浮。",
 "core": [
   "贝壳曲线（rocaille）与 C 形 S 形装饰主导",
   "粉彩高明度配色，几乎没有真正的黑",
   "主题是贵族休闲：宴饮、秋千、梳妆、花园",
   "画面轻盈到飘起来，构图常偏心、不对称",
 ],
 "visual": {
   "色彩": "粉红、天青、薄荷绿、奶油白、浅金；高明度低对比",
   "光影": "柔和漫射光，近乎无影；像午后花园的散射光",
   "笔触": "轻快、羽毛般的触感，笔触松但不厚",
   "构图": "不对称、斜向、框景（树木/帷幕框住主体），人物小而环境大",
   "材质": "丝绸、缎带、瓷器、镀金灰泥、花园绿植",
   "情绪": "愉悦、轻佻、亲密、无忧",
 },
 "palette": [("#F3C6D2","玫瑰粉"),("#A8CFE0","天青"),("#BFD9C0","薄荷绿"),
             ("#F5EBDC","奶油白"),("#D8B978","浅金"),("#C98BA5","藕荷")],
 "artists": [("华托","1684–1721"),("布歇","1703–1770"),("弗拉戈纳尔","1732–1806"),
             ("夏尔丹","1699–1779")],
 "prompt": {
   "style": "rococo painting, fête galante, pastel palette, rocaille ornament, light feathery brushwork, decorative elegance",
   "lighting": "soft diffused daylight, almost shadowless, gentle ambient glow, hazy garden light",
   "color": "pastel palette, rose pink, powder blue, mint green, cream white, pale gold, high key low contrast",
   "composition": "asymmetric composition, framing trees or drapery, small figures in lush garden, diagonal sweep",
   "medium": "oil on canvas, thin glazes, porcelain-like finish",
   "mood": "playful, flirtatious, intimate, carefree, hedonistic",
   "camera": "eye-level, wide shot, 35mm, deep focus",
 },
 "positive": " rococo painting, fete galante, pastel palette, rocaille ornament, light feathery brushwork, decorative elegance, soft diffused daylight, almost shadowless, hazy garden light, rose pink and powder blue and mint green and cream white, high key low contrast, asymmetric composition, framing trees, small figures in lush garden, playful and flirtatious mood, oil on canvas, thin glazes, porcelain-like finish",
 "negative": "dark shadows, tenebrism, harsh contrast, heavy impasto, monochrome, gritty, cyberpunk, muted earth tones",
 "video": {
   "motion": "裙摆飘动、扇子轻摇、树叶晃动；动作轻而慢",
   "camera": "缓慢 pan 跟随人物在花园中穿行；arc shot 环绕",
   "note": "保持画面高调，任何压暗都会让它变成普通古典画",
 },
 "pitfalls": [
   "AI 会把 pastel 做成低饱和灰调 → 强调 high key, low contrast, luminous",
   "容易滑向巴洛克 → negative 里明确写 tenebrism, harsh shadows",
 ],
 "sources": {"cleveland": ["rococo", "boucher", "fragonard"], "met": ["rococo painting", "fragonard"]},
 "see_also": ["baroque", "romanticism"],
},
# ---------------------------------------------------------------- 新古典主义
{
 "slug": "neoclassicism",
 "name_zh": "新古典主义",
 "name_en": "Neoclassicism",
 "period": "1760–1830",
 "region": "法国 / 英国",
 "tier": "A",
 "one_liner": "用古希腊罗马的直线和硬边，给革命时代一个道德样板。",
 "core": [
   "轮廓清晰、边缘锐利，反洛可可的软",
   "考古式准确：罗马服饰、柱式、器物",
   "浅浮雕式构图，人物像舞台上的群像",
   "理性、克制、说教，情绪被压到最低",
 ],
 "visual": {
   "色彩": "冷调、克制：大理石白、石灰灰、钢蓝、暗红点缀",
   "光影": "均匀的顶光 / 侧顶光，像石膏模型打光；阴影干净锐利",
   "笔触": "高度抛光、几乎无笔触，追求雕塑感",
   "构图": "水平带状构图，人物横向排开，建筑背景作为舞台",
   "材质": "大理石、石膏、抛光油画、青铜",
   "情绪": "庄严、冷静、道德感、英雄主义",
 },
 "palette": [("#E4E2DC","大理石白"),("#9AA0A6","石灰灰"),("#3E5C76","钢蓝"),
             ("#8A2B2B","庞贝红"),("#B99C6B","青铜"),("#2B2B2B","炭黑")],
 "artists": [("大卫","1748–1825"),("安格尔","1780–1867"),("卡诺瓦","1757–1822"),
             ("格罗","1771–1835")],
 "prompt": {
   "style": "neoclassical oil painting, academic art, sharp crisp contours, sculptural figures, greco-roman setting, polished surface",
   "lighting": "even top and side light, clean sharp shadows, plaster-cast lighting, no atmosphere haze",
   "color": "cool restrained palette, marble white, limestone grey, steel blue, pompeian red accent",
   "composition": "horizontal frieze composition, figures in a row, architectural stage set, balanced symmetry",
   "medium": "polished oil on canvas, invisible brushwork, marble-like finish",
   "mood": "solemn, stoic, heroic, moralising",
   "camera": "eye-level, wide establishing shot, 50mm, deep focus",
 },
 "positive": " neoclassical oil painting, academic art, sharp crisp contours, sculptural figures, greco-roman setting, polished surface, even top and side light, clean sharp shadows, plaster-cast lighting, cool restrained palette, marble white and limestone grey and steel blue, pompeian red accent, horizontal frieze composition, architectural stage set, solemn and heroic mood, polished oil on canvas, invisible brushwork",
 "negative": "soft edges, sfumato, pastel pink, rococo ornament, impressionist brushwork, modern clothing, neon, blurry",
 "video": {
   "motion": "近乎雕塑式的静止；只有旗帜、布料、烟尘在动",
   "camera": "static wide shot 或极缓 crane up；对称构图",
   "note": "新古典的镜头应像纪念碑摄影——正、稳、远",
 },
 "pitfalls": [
   "AI 会加软边和雾 → negative 明确 sfumato, soft edges, atmospheric haze",
   "容易和文艺复兴混淆：新古典更冷、更硬、更「像石膏」",
 ],
 "sources": {"cleveland": ["neoclassical", "david", "ingres"], "met": ["neoclassical painting"]},
 "see_also": ["renaissance", "romanticism"],
},
# ---------------------------------------------------------------- 浪漫主义
{
 "slug": "romanticism",
 "name_zh": "浪漫主义",
 "name_en": "Romanticism",
 "period": "1800–1850",
 "region": "法国 / 英国 / 德国",
 "tier": "A",
 "one_liner": "把渺小的人放进狂暴的自然里，用崇高感（sublime）压倒你。",
 "core": [
   "崇高（sublime）：自然的尺度让人战栗",
   "强调个人情感、风暴、废墟、异域",
   "大气透视与湿润空气，远景没入雾中",
   "笔触奔放，色彩为情绪服务而非写实",
 ],
 "visual": {
   "色彩": "暗调基底 + 炽热高光：落日橙、血红、铅灰、墨绿",
   "光影": "逆光与剪影，光源常在画面深处；光晕、丁达尔光",
   "笔触": "明显、有速度、有方向；风暴感来自笔触运动",
   "构图": "人小景大，垂直崇高感或斜向动势，地平线低",
   "材质": "粗亚麻布、厚涂、可见画布纹理",
   "情绪": "敬畏、孤独、激越、忧郁、向往",
 },
 "palette": [("#3A2E2A","铅灰褐"),("#C6552B","落日橙"),("#7A1F1F","血红"),
             ("#2F4032","墨绿"),("#D9B26A","云隙光"),("#1B2430","风暴蓝黑")],
 "artists": [("弗里德里希","1774–1840"),("透纳","1775–1851"),("德拉克罗瓦","1798–1863"),
             ("籍里柯","1791–1824"),("康斯特布尔","1776–1837")],
 "prompt": {
   "style": "romanticism oil painting, sublime landscape, dramatic atmospheric perspective, expressive brushwork, stormy sky",
   "lighting": "backlight and silhouette, distant luminous source, god rays through clouds, hazy glow, low key with hot highlights",
   "color": "moody dark base with fiery highlights, sunset orange, blood red, leaden grey, deep forest green",
   "composition": "tiny figure against vast nature, low horizon, vertical sublime scale, diagonal turbulence",
   "medium": "oil on coarse linen, thick expressive brushwork, visible canvas texture",
   "mood": "awe, solitude, turbulent, melancholic, yearning",
   "camera": "extreme wide shot, low angle, 24mm, deep focus",
 },
 "positive": " romanticism oil painting, sublime landscape, dramatic atmospheric perspective, expressive brushwork, stormy sky, backlight and silhouette, distant luminous source, god rays through clouds, moody dark base with fiery highlights, sunset orange and blood red, tiny figure against vast nature, low horizon, awe and yearning mood, oil on coarse linen, thick expressive brushwork",
 "negative": "neoclassical sharpness, flat even light, studio lighting, close-up, small scale, pastel, cute, clean vector",
 "video": {
   "motion": "云层翻涌、衣袍狂舞、海浪拍击；持续的大幅运动",
   "camera": "缓慢 crane up 揭示尺度；或 static 让环境自己动",
   "note": "浪漫主义的力量来自「尺度对比」，镜头一定要给到远景",
 },
 "pitfalls": [
   "AI 容易只给「美丽日落」→ 必须写 sublime, vast scale, tiny figure",
   "缺了大气透视会变成普通风景照 → 加 atmospheric perspective, aerial haze",
 ],
 "sources": {"cleveland": ["romanticism", "turner", "friedrich"], "met": ["romantic landscape painting"]},
 "see_also": ["neoclassicism", "realism", "symbolism"],
},
# ---------------------------------------------------------------- 现实主义
{
 "slug": "realism",
 "name_zh": "现实主义",
 "name_en": "Realism",
 "period": "1840–1880",
 "region": "法国 / 俄罗斯",
 "tier": "A",
 "one_liner": "不美化、不神化，把农民、工人和日常劳动搬上大画布。",
 "core": [
   "题材来自当下日常：劳作、市集、街巷",
   "拒绝理想化，保留粗糙与不体面",
   "色调偏暗、偏土，接近自然光下的真实",
   "尺幅巨大但内容平凡，形成张力",
 ],
 "visual": {
   "色彩": "土色系：棕、灰、赭、暗绿；低饱和，几乎不用鲜艳色",
   "光影": "自然散射光，阴天/室内窗光；没有戏剧化打光",
   "笔触": "克制、写实但不炫技；库尔贝式厚涂偶尔出现",
   "构图": "平视、无戏剧性；截取日常的一角，常有「未完成感」",
   "材质": "粗糙亚麻、厚涂、泥土质感",
   "情绪": "质朴、沉重、诚实、有社会批判性",
 },
 "palette": [("#5A4632","土褐"),("#6E6A5E","石灰绿灰"),("#3D3A33","暗炭"),
             ("#8B6B4A","皮革棕"),("#A89B7C","干草色"),("#4A5A4A","暗橄榄")],
 "artists": [("库尔贝","1819–1877"),("米勒","1814–1875"),("列宾","1844–1930"),
             ("杜米埃","1808–1879")],
 "prompt": {
   "style": "realism oil painting, 19th century social realism, unidealised depiction, muted earthy palette, honest observation",
   "lighting": "natural diffused daylight, overcast sky, window light, no theatrical lighting",
   "color": "earthy muted palette, brown, grey, ochre, dark olive, very low saturation",
   "composition": "eye-level flat composition, cropped everyday scene, no dramatic staging, documentary framing",
   "medium": "oil on coarse linen, restrained brushwork, occasional impasto, dirt and wear texture",
   "mood": "honest, sombre, dignified labour, socially critical",
   "camera": "eye-level, medium wide shot, 35mm, deep focus, documentary",
 },
 "positive": " realism oil painting, 19th century social realism, unidealised depiction, muted earthy palette, honest observation, natural diffused daylight, overcast sky, window light, earthy brown and grey and ochre, very low saturation, eye-level flat composition, cropped everyday scene, documentary framing, sombre and dignified mood, oil on coarse linen, restrained brushwork",
 "negative": "idealised beauty, glamour, golden hour glow, dramatic lighting, pastel, fantasy, glossy skin, instagram filter",
 "video": {
   "motion": "劳动动作重复、人群走动、尘土飞扬；朴素不加修饰",
   "camera": "handheld 轻微晃动或 static 长镜头；模仿纪录片",
   "note": "不要给现实主义加电影感调色——那会立刻毁掉它的诚实",
 },
 "pitfalls": [
   "AI 默认加 golden hour 和美颜 → negative 明确 idealised beauty, glamour, golden hour",
   "容易变成「复古照片」→ 强调 oil painting, visible canvas, brushwork",
 ],
 "sources": {"cleveland": ["realism", "courbet", "millet"], "met": ["realism painting", "courbet"]},
 "see_also": ["romanticism", "impressionism"],
},
# ---------------------------------------------------------------- 印象派
{
 "slug": "impressionism",
 "name_zh": "印象派",
 "name_en": "Impressionism",
 "period": "1865–1885",
 "region": "法国",
 "tier": "A",
 "one_liner": "不管物体长什么样，只记录光在那一秒的样子。",
 "core": [
   "外光写生，捕捉瞬间光色变化",
   "阴影不用黑，用互补色（紫、蓝）",
   "笔触碎、快、可见，颜色在视网膜上混合",
   "轮廓溶解，形体让位于光感",
 ],
 "visual": {
   "色彩": "高明度、高亮度：粉紫阴影、柠檬黄阳光、钴蓝天光",
   "光影": "明亮外光，阴影通透有颜色；几乎不用纯黑",
   "笔触": "短促碎笔、厚涂（impasto）、湿画法；笔触本身就是内容",
   "构图": "摄影式随机裁切，人物被画框切掉，视点抬高或压低",
   "材质": "粗糙画布、明显笔触堆叠、颜料厚重",
   "情绪": "轻快、即时、愉悦、日常的闲适",
 },
 "palette": [("#E8D5A8","阳光黄"),("#A8B8D8","天光蓝"),("#C9A8C0","阴影紫"),
             ("#7A9E7E","草地绿"),("#E07B54","橙红"),("#F2EDE4","高光白")],
 "artists": [("莫奈","1840–1926"),("雷诺阿","1841–1919"),("德加","1834–1917"),
             ("毕沙罗","1830–1903"),("西斯莱","1839–1899")],
 "prompt": {
   "style": "impressionism oil painting, plein air, broken visible brushstrokes, impasto, optical color mixing, dissolved contours",
   "lighting": "bright outdoor daylight, luminous coloured shadows, no black shadows, dappled light through foliage",
   "color": "high key luminous palette, pastel violet shadows, lemon yellow sunlight, cobalt blue sky, complementary color vibration",
   "composition": "photographic random cropping, off-centre subject, high or low viewpoint, figures cut by frame edge",
   "medium": "oil on rough canvas, heavy impasto, wet-on-wet, visible brush hairs",
   "mood": "lighthearted, spontaneous, leisurely, immediate",
   "camera": "eye-level, wide shot, 35mm, snapshot framing",
 },
 "positive": " impressionism oil painting, plein air, broken visible brushstrokes, impasto, optical colour mixing, dissolved contours, bright outdoor daylight, luminous coloured shadows, no black shadows, dappled light through foliage, high key luminous palette, pastel violet shadows and lemon yellow sunlight and cobalt blue sky, photographic random cropping, off-centre subject, lighthearted and spontaneous mood, oil on rough canvas, heavy impasto",
 "negative": "black shadows, smooth blending, sharp outlines, studio lighting, photorealistic, hd, crisp detail, dark and moody",
 "video": {
   "motion": "水面波光闪动、树叶沙沙、人群走动；细碎而连续",
   "camera": "轻微 handheld 或慢速 pan；像随手拍的短片",
   "note": "印象派的动感应来自「光在闪」而不是物体在跑",
 },
 "pitfalls": [
   "AI 默认给黑色阴影 → 必须写 no black shadows, coloured shadows",
   "容易变成「模糊的照片」→ 强调 brushstrokes, impasto, oil painting 而非 blur",
   "过写实会失去印象派 → negative 写 photorealistic, crisp detail",
 ],
 "sources": {"cleveland": ["impressionism", "monet", "renoir"], "met": ["impressionism", "monet"]},
 "see_also": ["realism", "post-impressionism", "neo-impressionism"],
},
# ---------------------------------------------------------------- 后印象派
{
 "slug": "post-impressionism",
 "name_zh": "后印象派",
 "name_en": "Post-Impressionism",
 "period": "1885–1905",
 "region": "法国",
 "tier": "A",
 "one_liner": "从印象派出发，但把光和色换成结构、象征和情绪。",
 "core": [
   "不再只画所见，开始画所感",
   "色块化、平面化，牺牲立体感换表现力",
   "笔触有方向性，成为情绪的语言",
   "塞尚的结构、梵高的漩涡、高更的平涂，三条路",
 ],
 "visual": {
   "色彩": "高饱和、非自然：梵高的铬黄与钴蓝，高更的纯色平涂",
   "光影": "光被内化为色彩强度，不再依赖真实光源",
   "笔触": "厚涂 + 明确方向：短促排列、漩涡、色块边界",
   "构图": "平面化空间，多视点，装饰性边框，留白与色块并置",
   "材质": "极厚 impasto，颜料堆成沟壑；或高更式的平坦哑光",
   "情绪": "强烈、主观、不安或神秘",
 },
 "palette": [("#F0C420","铬黄"),("#2B4C9B","钴蓝"),("#1E7A5A","翡翠绿"),
             ("#C1272D","朱红"),("#6B3FA0","紫罗兰"),("#E8A33D","赭橙")],
 "artists": [("梵高","1853–1890"),("塞尚","1839–1906"),("高更","1848–1903"),
             ("修拉","1859–1891"),("图卢兹-劳特累克","1864–1901")],
 "prompt": {
   "style": "post-impressionism oil painting, expressive colour, flattened planes, directional brushwork, bold outlines, subjective vision",
   "lighting": "light expressed as colour intensity rather than realistic source, strong local colour, minimal shadow modelling",
   "color": "highly saturated non-naturalistic palette, chrome yellow, cobalt blue, emerald green, vermilion, violet",
   "composition": "flattened pictorial space, decorative patterning, multiple viewpoints, colour blocks side by side",
   "medium": "oil on canvas, thick impasto ridges, or flat matte planes, visible brush direction",
   "mood": "intense, subjective, restless or mystical",
   "camera": "eye-level, medium shot, 50mm, slightly flattened perspective",
 },
 "positive": " post-impressionism oil painting, expressive colour, flattened planes, directional brushwork, bold outlines, subjective vision, light expressed as colour intensity, highly saturated non-naturalistic palette, chrome yellow and cobalt blue and emerald green and vermilion, flattened pictorial space, decorative patterning, intense and subjective mood, oil on canvas, thick impasto ridges",
 "negative": "photorealism, naturalistic colour, soft gradients, airbrush, 3d render, muted desaturated, black shadows",
 "video": {
   "motion": "笔触般的流动：麦浪、星空漩涡、云层旋转",
   "camera": "缓慢旋转（arc shot）配合画面本身的漩涡动势",
   "note": "梵高式的动是「画面整体在呼吸/旋转」，不是物体位移",
 },
 "pitfalls": [
   "AI 会把后印象派做成普通厚涂 → 必须写 non-naturalistic saturated colour",
   "梵高风格容易被过度模板化 → 加具体约束（短促方向性笔触 rather than 泛泛的 swirl）",
 ],
 "sources": {"cleveland": ["post-impressionism", "van gogh", "cezanne"], "met": ["van gogh", "cezanne"]},
 "see_also": ["impressionism", "expressionism", "symbolism"],
},
# ---------------------------------------------------------------- 象征主义
{
 "slug": "symbolism",
 "name_zh": "象征主义",
 "name_en": "Symbolism",
 "period": "1885–1910",
 "region": "法国 / 比利时 / 奥地利",
 "tier": "A",
 "one_liner": "不画世界的样子，画梦境、神话与欲望的隐喻。",
 "core": [
   "拒绝写实与自然光，转向内心与神秘",
   "女性形象常被塑造成致命美人（femme fatale）",
   "金箔、装饰纹样、平面化空间",
   "暧昧多义的叙事，拒绝单一解读",
 ],
 "visual": {
   "色彩": "宝石色与暗金：孔雀蓝、祖母绿、深紫、金箔",
   "光影": "非自然光，发光体自明；人物像从内部发光",
   "笔触": "平滑装饰性笔触，或精细到接近插画",
   "构图": "平面化、装饰性、对称或仪式感排列，常有框中之框",
   "材质": "金箔、蛋彩、哑光油画、装饰线条",
   "情绪": "神秘、迷醉、危险、忧郁的感官性",
 },
 "palette": [("#1B4D3E","祖母绿"),("#1F6F8B","孔雀蓝"),("#4B2E6B","深紫"),
             ("#C9A227","金箔"),("#8B1A3A","酒红"),("#2A2A35","夜蓝黑")],
 "artists": [("莫罗","1826–1898"),("克里姆特","1862–1918"),("雷东","1840–1916"),
             ("夏凡纳","1824–1898"),("鲁东","1840–1916")],
 "prompt": {
   "style": "symbolism painting, art nouveau decorative detail, dreamlike mythological allegory, flat ornamental space, gold leaf accents",
   "lighting": "non-natural self-luminous glow, figures lit from within, no realistic light source, dusky ambience",
   "color": "jewel tones, emerald green, peacock blue, deep violet, gold leaf, wine red, low key but richly saturated",
   "composition": "flat decorative arrangement, ritual symmetry, frame within frame, ornamental border",
   "medium": "oil with gold leaf, tempera, matte decorative finish, fine ornamental linework",
   "mood": "mysterious, intoxicating, dangerous, sensuous melancholy",
   "camera": "eye-level, medium shot, 50mm, flattened depth",
 },
 "positive": " symbolism painting, art nouveau decorative detail, dreamlike mythological allegory, flat ornamental space, gold leaf accents, non-natural self-luminous glow, jewel tones, emerald green and peacock blue and deep violet and gold leaf, flat decorative arrangement, ritual symmetry, ornamental border, mysterious and intoxicating mood, oil with gold leaf, fine ornamental linework",
 "negative": "realistic daylight, photographic, plain background, mundane subject, modern clothing, stock photo, oversharpened",
 "video": {
   "motion": "缓慢漂浮、飘落的羽毛/花瓣、水面涟漪；梦的逻辑",
   "camera": "极缓 dolly in，或 static 让光晕呼吸",
   "note": "象征主义的动感应「不合物理」，像梦里的慢动作",
 },
 "pitfalls": [
   "AI 容易做成奇幻插画 → 加 flat ornamental space, gold leaf, decorative linework",
   "光要「不自然」：明确 no realistic light source",
 ],
 "sources": {"cleveland": ["symbolism", "moreau", "klimt"], "met": ["symbolism painting", "gustav klimt"]},
 "see_also": ["romanticism", "art-nouveau", "surrealism"],
},
# ---------------------------------------------------------------- 新艺术运动
{
 "slug": "art-nouveau",
 "name_zh": "新艺术运动",
 "name_en": "Art Nouveau",
 "period": "1890–1910",
 "region": "法国 / 比利时 / 奥地利 / 西班牙",
 "tier": "A",
 "one_liner": "把植物藤蔓变成设计语言：一切都是鞭线、曲线和装饰框。",
 "core": [
   "鞭线（whiplash line）：S 形、鞭状的有机曲线",
   "平面装饰 + 粗轮廓线，海报美学的源头",
   "自然母题：藤蔓、百合、孔雀、蝴蝶、女性长发",
   "艺术与工艺合一：绘画、建筑、家具同一套语言",
 ],
 "visual": {
   "色彩": "柔和而有装饰性：鼠尾草绿、芥末黄、暗金、藕荷、孔雀蓝",
   "光影": "平面化，几乎无体积光；靠色块和线条分隔",
   "笔触": "平坦色块 + 粗细变化的装饰轮廓线（Mucha 式）",
   "构图": "中央主体被装饰性圆环/拱形框住，纵向海报比例",
   "材质": "石版画、海报纸、彩色玻璃、锻铁、木雕",
   "情绪": "优雅、繁复、感官、带有自然的神秘",
 },
 "palette": [("#8A9A5B","鼠尾草绿"),("#D4A82A","芥末黄"),("#B08D57","暗金"),
             ("#B08BA8","藕荷"),("#2E6E7E","孔雀蓝"),("#E8DCC8","米纸白")],
 "artists": [("穆夏","1860–1939"),("霍塔","1861–1947"),("高迪","1852–1926"),
             ("比亚兹莱","1872–1898"),("蒂芙尼","1848–1933")],
 "prompt": {
   "style": "art nouveau poster, alphonse mucha style, whiplash organic curves, flat decorative colour, bold ornamental outline, botanical motifs",
   "lighting": "flat graphic lighting, no volumetric shading, colour separated by line",
   "color": "soft decorative palette, sage green, mustard yellow, antique gold, mauve, peacock blue, cream paper",
   "composition": "central figure framed by ornamental arch or halo, vertical poster format, symmetrical decorative border",
   "medium": "lithograph poster, matte paper, stained glass and wrought iron details",
   "mood": "elegant, ornate, sensuous, botanical mystery",
   "camera": "eye-level, vertical portrait composition, flat depth",
 },
 "positive": " art nouveau poster, alphonse mucha style, whiplash organic curves, flat decorative colour, bold ornamental outline, botanical motifs, flat graphic lighting, soft decorative palette, sage green and mustard yellow and antique gold and mauve, central figure framed by ornamental arch, vertical poster format, symmetrical decorative border, elegant and ornate mood, lithograph poster, matte paper",
 "negative": "3d render, realistic lighting, photograph, gritty texture, dark horror, minimalism, neon cyberpunk",
 "video": {
   "motion": "藤蔓生长、发丝飘动、边框纹样流动；装饰性循环动画",
   "camera": "static 或极缓 zoom；重点是画面内元素的有机运动",
   "note": "新艺术的动是「装饰在生长」，镜头本身不需要动",
 },
 "pitfalls": [
   "AI 会把 Art Nouveau 和 Art Deco 混淆 → Deco 是几何直线，Nouveau 是有机曲线，提示词必须写明 whiplash organic curves",
   "不加 poster / lithograph 会变成普通唯美插画",
 ],
 "sources": {"cleveland": ["art nouveau", "mucha"], "met": ["art nouveau poster", "alphonse mucha"]},
 "see_also": ["symbolism", "art-deco", "pre-raphaelite"],
},
# ---------------------------------------------------------------- 浮世绘
{
 "slug": "ukiyo-e",
 "name_zh": "浮世绘",
 "name_en": "Ukiyo-e",
 "period": "1670–1900",
 "region": "日本",
 "tier": "A",
 "one_liner": "江户的平面设计：无阴影、粗轮廓、大胆裁切，直接塑造了梵高和现代海报。",
 "core": [
   "无西方透视，用层叠平面和斜线制造纵深",
   "平涂色块 + 清晰墨线轮廓，完全没有明暗塑造",
   "大胆的非对称裁切，主体常被画框切断",
   "题材：美人、歌舞伎、名所风景、妖怪",
 ],
 "visual": {
   "色彩": "靛蓝（普鲁士蓝）、朱红、赭黄、墨黑、米纸底；色块干净平整",
   "光影": "无阴影、无体积光；光靠颜色和留白暗示",
   "笔触": "版画式的平涂 + 有力度的墨线；线条本身有粗细节奏",
   "构图": "非对称、斜向、被裁切的前景元素（帘、枝、浪）框住主题",
   "材质": "木版画、和纸纤维、墨线、套色印刷的轻微错位",
   "情绪": "明快、装饰性、有时幽默或怪诞",
 },
 "palette": [("#1F3A6E","普鲁士蓝"),("#B03A2E","朱红"),("#C9A227","赭黄"),
             ("#2B2B2B","墨黑"),("#E8DCC0","和纸米"),("#4A7C6F","青绿")],
 "artists": [("葛饰北斋","1760–1849"),("歌川广重","1797–1858"),("喜多川歌麿","1753–1806"),
             ("月冈芳年","1839–1892")],
 "prompt": {
   "style": "ukiyo-e woodblock print, japanese edo period, flat colour planes, bold ink outlines, no shading, hokusai and hiroshige style",
   "lighting": "no shading, no cast shadows, flat unmodulated colour, light implied by white paper",
   "color": "indigo prussian blue, vermilion red, ochre yellow, sumi black ink, washi paper cream, clean flat blocks",
   "composition": "asymmetric diagonal composition, bold cropping, foreground element framing subject, layered planes for depth",
   "medium": "woodblock print, washi paper fibre, ink linework, subtle registration offset",
   "mood": "brisk, decorative, sometimes humorous or grotesque",
   "camera": "wide shot, flattened perspective, elevated viewpoint",
 },
 "positive": " ukiyo-e woodblock print, japanese edo period, flat colour planes, bold ink outlines, no shading, hokusai and hiroshige style, no cast shadows, flat unmodulated colour, indigo prussian blue and vermilion red and ochre yellow and sumi black ink, washi paper cream, asymmetric diagonal composition, bold cropping, foreground element framing subject, layered planes for depth, decorative mood, woodblock print, washi paper fibre",
 "negative": "3d shading, cast shadows, gradient mesh, oil painting texture, western perspective, photorealistic, glow, bokeh",
 "video": {
   "motion": "海浪翻卷、雨丝斜落、云层平移；平面化的运动",
   "camera": "static 或横向 pan，模仿绘卷展开",
   "note": "不要加景深和光晕——浮世绘是平面的，任何 3D 感都是错的",
 },
 "pitfalls": [
   "AI 会加渐变和阴影 → negative 明确 3d shading, cast shadows, gradient",
   "容易被做成「动漫风」→ 加 edo period woodblock print, washi paper, ink outlines",
 ],
 "sources": {"cleveland": ["ukiyo-e", "hokusai", "hiroshige"], "met": ["ukiyo-e", "hokusai"]},
 "see_also": ["art-nouveau", "impressionism"],
},
# ---------------------------------------------------------------- 拉斐尔前派
{
 "slug": "pre-raphaelite",
 "name_zh": "拉斐尔前派",
 "name_en": "Pre-Raphaelite",
 "period": "1848–1890",
 "region": "英国",
 "tier": "A",
 "one_liner": "回到拉斐尔之前：超饱和的宝石色、密到窒息的细节、红发女主角。",
 "core": [
   "拒绝学院派的棕色调，用湿白底让颜色发光",
   "极致细节：每片叶子、每根头发都画完",
   "文学与神话题材，中世纪与亚瑟王传说",
   "标志性的红发女性形象与忧郁气质",
 ],
 "visual": {
   "色彩": "高饱和宝石色：翡翠绿、朱红、钴蓝、金褐；在暗底上发光",
   "光影": "均匀明亮的自然光，细节全开；阴影少而透",
   "笔触": "极细、几乎无笔触，局部厚涂；表面如珐琅",
   "构图": "平面化装饰构图 + 密集的自然细节背景；常有框景与纹样",
   "材质": "湿白底油画、细密笔触、珐琅般表面、织毯与刺绣纹样",
   "情绪": "浪漫、忧郁、感官、文学性、略带病态",
 },
 "palette": [("#1E6B4F","翡翠绿"),("#B02A2A","朱红"),("#2B4C9B","钴蓝"),
             ("#8B5E2A","金褐"),("#4A2B3A","暗酒红"),("#E8D5B0","象牙白")],
 "artists": [("罗塞蒂","1828–1882"),("米莱","1829–1896"),("亨特","1827–1910"),
             ("伯恩-琼斯","1833–1898"),("沃特豪斯","1849–1917")],
 "prompt": {
   "style": "pre-raphaelite painting, hyper-detailed, jewel-like saturated colour, literary and mythological subject, medieval revival, ornate natural detail",
   "lighting": "even bright natural light, glowing colour on wet white ground, few but transparent shadows",
   "color": "jewel saturated palette, emerald green, vermilion, cobalt blue, gold brown, deep wine, luminous on dark ground",
   "composition": "flat decorative composition, dense botanical background, framed portrait, ornamental patterning",
   "medium": "oil on wet white ground, enamel-smooth finish, minute brushwork, embroidery and tapestry detail",
   "mood": "romantic, melancholic, sensuous, literary, faintly morbid",
   "camera": "eye-level, medium close-up portrait, 85mm, shallow depth",
 },
 "positive": " pre-raphaelite painting, hyper-detailed, jewel-like saturated colour, literary and mythological subject, medieval revival, ornate natural detail, even bright natural light, glowing colour on wet white ground, emerald green and vermilion and cobalt blue and gold brown, flat decorative composition, dense botanical background, framed portrait, romantic and melancholic mood, oil on wet white ground, enamel-smooth finish",
 "negative": "loose brushwork, impressionist, minimal detail, brown varnish academic palette, blurry, low resolution, muddy colours",
 "video": {
   "motion": "几乎静止；发丝微动、水面轻颤、花瓣飘落",
   "camera": "static 特写，极慢 dolly in；沉默感",
   "note": "拉斐尔前派适合「会呼吸的静止画面」，动多了解体成奇幻",
 },
 "pitfalls": [
   "AI 会降低细节密度 → 必须写 hyper-detailed, minute brushwork, ornate",
   "容易变成现代奇幻插画 → 加 19th century british, medieval revival, wet white ground",
 ],
 "sources": {"cleveland": ["pre-raphaelite", "rossetti", "waterhouse"], "met": ["pre-raphaelite painting"]},
 "see_also": ["romanticism", "symbolism", "art-nouveau"],
},
# ---------------------------------------------------------------- 表现主义
{
 "slug": "expressionism",
 "name_zh": "表现主义",
 "name_en": "Expressionism",
 "period": "1905–1930",
 "region": "德国 / 奥地利 / 挪威",
 "tier": "B",
 "one_liner": "把内心的扭曲直接画出来：歪斜的线、尖叫的颜色、被挤压的空间。",
 "core": [
   "主观情绪压倒客观再现，比例被故意扭曲",
   "颜色不描述物体，直接表达情绪（桥社 / 青骑士）",
   "线条粗硬、有棱角，空间被压扁",
   "城市焦虑、性、死亡、精神危机是母题",
 ],
 "visual": {
   "色彩": "刺目、不和谐：酸绿、毒黄、血红、瘀青紫并置",
   "光影": "硬边、无过渡；光像刀切开画面",
   "笔触": "粗野、快速、有力；木刻式的硬线条",
   "构图": "倾斜、挤压、视角扭曲，人物被拉长或压扁",
   "材质": "粗布、厚涂、木刻版画的刀痕质感",
   "情绪": "焦虑、愤怒、不安、被压抑的欲望",
 },
 "palette": [("#A8C020","酸绿"),("#E8C020","毒黄"),("#B01E2E","血红"),
             ("#4A2B5A","瘀青紫"),("#1E1E1E","焦黑"),("#3A6B7A","冷青")],
 "artists": [("蒙克","1863–1944"),("基尔希纳","1880–1938"),("诺尔德","1867–1956"),
             ("席勒","1890–1918"),("康定斯基（早期）","1866–1944")],
 "prompt": {
   "style": "german expressionism, die brucke, woodcut angular linework, distorted proportions, jarring non-naturalistic colour, psychological intensity",
   "lighting": "harsh hard-edged light, no gradient, light cuts across the form, clashing local colour instead of modelling",
   "color": "clashing acidic palette, acid green, toxic yellow, blood red, bruised violet, jet black",
   "composition": "tilted squeezed space, distorted perspective, elongated or flattened figures, claustrophobic framing",
   "medium": "oil on rough canvas, aggressive brushwork, woodcut gouge marks",
   "mood": "anxious, angry, alienated, repressed desire",
   "camera": "dutch angle, close-up, wide-angle distortion, 24mm",
 },
 "positive": " german expressionism, die brucke, woodcut angular linework, distorted proportions, jarring non-naturalistic colour, psychological intensity, harsh hard-edged light, no gradient, clashing acidic palette, acid green and toxic yellow and blood red and bruised violet, tilted squeezed space, distorted perspective, elongated figures, anxious and alienated mood, oil on rough canvas, aggressive brushwork",
 "negative": "realistic proportions, soft gradient, pastel, calm, idyllic, photorealistic, smooth airbrush, gentle mood",
 "video": {
   "motion": "抽搐式、不平滑的运动；画面轻微抖动、线条扭曲",
   "camera": "handheld 抖动、dutch angle、突然的推近",
   "note": "表现主义的镜头应该「不舒服」——稳定的运镜是反效果的",
 },
 "pitfalls": [
   "AI 会把 expressionism 理解成「表现力强」→ 必须写 distorted proportions, clashing colour, angular linework",
   "注意区分抽象表现主义（Abstract Expressionism），那是完全不同的东西",
 ],
 "sources": {"cleveland": ["expressionism", "munch", "kirchner"], "met": ["german expressionism"]},
 "see_also": ["post-impressionism", "cubism", "surrealism"],
},
# ---------------------------------------------------------------- 立体主义
{
 "slug": "cubism",
 "name_zh": "立体主义",
 "name_en": "Cubism",
 "period": "1907–1920",
 "region": "法国 / 西班牙",
 "tier": "B",
 "one_liner": "把对象拆成几何面，再在同一个平面上同时展示所有视角。",
 "core": [
   "多视点同时并置，取消单一透视",
   "形体被分解为几何切面（facet）",
   "分析立体主义近乎单色，综合立体主义引入拼贴",
   "画面是「建构」出来的，不是「看」到的",
 ],
 "visual": {
   "色彩": "分析期：赭、灰、褐、墨绿等有限色；综合期：拼贴纸的平色块",
   "光影": "没有真实光源，明暗只用来区分切面",
   "笔触": "平涂的几何块面，边缘清晰；拼贴元素有硬边",
   "构图": "中心发散、碎片化、网格化；主体与背景互相渗透",
   "材质": "报纸拼贴、沙砾肌理、木纹纸、平面色块",
   "情绪": "理性、冷静、智性、去情绪化",
 },
 "palette": [("#8A7A63","赭石"),("#6E6E6E","中灰"),("#4A3B2A","深褐"),
             ("#5A6B4A","暗橄榄"),("#C9C0A8","纸本米"),("#2B2B33","炭蓝黑")],
 "artists": [("毕加索","1881–1973"),("布拉克","1882–1963"),("格里斯","1887–1927"),
             ("莱热","1881–1955")],
 "prompt": {
   "style": "cubism, analytical cubism, fragmented geometric facets, simultaneous multiple viewpoints, collage elements, picasso and braque style",
   "lighting": "no realistic light source, tonal variation only to separate facets, flat plane shading",
   "color": "restricted analytic palette, ochre, grey, umber, dark olive, paper cream, monochrome-leaning",
   "composition": "faceted grid composition, shattered planes, figure and ground interpenetrating, centrifugal structure",
   "medium": "oil with sand texture, newspaper collage, hard flat edges, matte surface",
   "mood": "rational, detached, intellectual, de-emotionalised",
   "camera": "flat frontal view, no perspective, orthographic",
 },
 "positive": " cubism, analytical cubism, fragmented geometric facets, simultaneous multiple viewpoints, collage elements, picasso and braque style, no realistic light source, restricted analytic palette, ochre and grey and umber and dark olive, faceted grid composition, shattered planes, figure and ground interpenetrating, rational and detached mood, oil with sand texture, newspaper collage, matte surface",
 "negative": "realistic perspective, single viewpoint, soft shading, 3d render, photorealistic, depth of field, bokeh, conventional portrait",
 "video": {
   "motion": "切面依次重排、拼贴元素平移换位；结构性的运动",
   "camera": "static，或极缓的平面推移；绝不用景深",
   "note": "立体主义是反镜头的——它是平面的智性游戏，不要给空间感",
 },
 "pitfalls": [
   "AI 会把 cubism 做成「几何风格插画」→ 加 simultaneous multiple viewpoints, faceted, figure-ground interpenetration",
   "容易被加上景深和光影，这在立体主义里是错的",
 ],
 "sources": {"cleveland": ["cubism", "picasso", "braque"], "met": ["cubism", "picasso"]},
 "see_also": ["expressionism", "surrealism", "bauhaus"],
},
# ---------------------------------------------------------------- 超现实主义
{
 "slug": "surrealism",
 "name_zh": "超现实主义",
 "name_en": "Surrealism",
 "period": "1924–1950",
 "region": "法国 / 西班牙 / 比利时",
 "tier": "B",
 "one_liner": "用最写实的手法画最不可能的事，让梦看起来像照片。",
 "core": [
   "逼真的技法 + 荒诞的组合（dislocation）",
   "物体脱离原有语境，产生「不可思议」",
   "空间和尺度被玩弄：漂浮、融化、无限延伸",
   "弗洛伊德式的欲望、潜意识与自动书写",
 ],
 "visual": {
   "色彩": "达利式的清澈蓝天 + 焦黄荒地；马格利特式的冷静均匀色",
   "光影": "清晰、锐利、不真实的完美光照；像广告摄影一样干净",
   "笔触": "极度平滑写实（达利、马格利特），或自动主义的有机形态（米罗、马松）",
   "构图": "空旷背景 + 孤立物体；极端纵深或完全平面",
   "材质": "光滑油画表面、摄影般的清晰度、怪异材质的错置",
   "情绪": "怪诞、不安、幽默、迷幻、冷静的疯狂",
 },
 "palette": [("#7BA8C9","达利天空蓝"),("#D4B483","焦黄荒地"),("#4A4A52","石墨灰"),
             ("#C25B3A","锈橙"),("#2E4A3A","暗绿"),("#EDE6D6","骨白")],
 "artists": [("达利","1904–1989"),("马格利特","1898–1967"),("恩斯特","1891–1976"),
             ("米罗","1893–1983"),("唐吉","1900–1955")],
 "prompt": {
   "style": "surrealism, hyper-realistic rendering of impossible scenes, dream logic, uncanny dislocation of objects, dali and magritte style",
   "lighting": "sharp impossibly clean light, no atmospheric haze, crisp cast shadows on empty ground, advertising-photography clarity",
   "color": "clear surreal palette, pale cerulean sky, ochre desert ground, graphite grey, rust orange, bone white",
   "composition": "vast empty background with isolated object, extreme depth or absolute flatness, unexpected scale shifts",
   "medium": "ultra-smooth oil on canvas, photographic sharpness, matte impossible materials",
   "mood": "uncanny, unsettling, darkly humorous, oneiric",
   "camera": "eye-level, wide shot, deep focus, deadpan framing",
 },
 "positive": " surrealism, hyper-realistic rendering of impossible scenes, dream logic, uncanny dislocation of objects, dali and magritte style, sharp impossibly clean light, crisp cast shadows on empty ground, clear surreal palette, pale cerulean sky and ochre desert ground and graphite grey, vast empty background with isolated object, extreme depth, unexpected scale shifts, uncanny and oneiric mood, ultra-smooth oil on canvas, photographic sharpness",
 "negative": "photograph of ordinary scene, busy composition, muddy brushwork, impressionist, cute, generic fantasy art, glowing magic effects",
 "video": {
   "motion": "违反物理的连续变形：融化、漂浮、无限复制、物体错位",
   "camera": "极缓 dolly in 制造不安；稳定的镜头让荒诞显得可信",
   "note": "关键是「一本正经地拍荒诞」——镜头越冷静越有效",
 },
 "pitfalls": [
   "AI 会把 surreal 做成「奇幻特效大片」→ 加 deadpan, everyday setting, impossible juxtaposition",
   "必须保留超高写实度：不写 hyper-realistic 就变成抽象幻想画",
 ],
 "sources": {"cleveland": ["surrealism", "dali", "magritte"], "met": ["surrealism"]},
 "see_also": ["symbolism", "cubism", "expressionism"],
},
# ---------------------------------------------------------------- 装饰艺术
{
 "slug": "art-deco",
 "name_zh": "装饰艺术",
 "name_en": "Art Deco",
 "period": "1920–1939",
 "region": "法国 / 美国",
 "tier": "B",
 "one_liner": "把机器时代变成奢侈品：几何、对称、金属、速度感。",
 "core": [
   "几何化：扇形、放射线、阶梯状、锯齿形",
   "对称与重复，强烈的建筑感",
   "奢华材质：黑漆、镀铬、象牙、鲨鱼皮",
   "摩登都市、爵士、速度与工业崇拜",
 ],
 "visual": {
   "色彩": "高对比金属色 + 深底：黑金、铬银、祖母绿、酒红、象牙白",
   "光影": "硬朗的几何光斑，放射状光晕，金属高光",
   "笔触": "无笔触，硬边几何平涂（海报/插画媒介）",
   "构图": "严格对称、中央放射、阶梯式上升、纵向拔高",
   "材质": "黑漆、镀铬、磨砂玻璃、象牙、几何图案镶嵌",
   "情绪": "摩登、奢华、自信、冷艳、带未来感",
 },
 "palette": [("#111111","黑漆"),("#C9A227","金"),("#B8B8B8","铬银"),
             ("#0F5C4A","祖母绿"),("#7A1F2B","酒红"),("#EDE3CE","象牙白")],
 "artists": [("埃尔特","1892–1990"),("塔玛拉·德·兰碧卡","1898–1980"),
             ("保罗·波烈","1879–1944"),("卡桑德尔","1901–1968")],
 "prompt": {
   "style": "art deco, 1920s, geometric ornament, stepped zigzag and sunburst motifs, symmetrical architectural composition, streamlined machine age glamour",
   "lighting": "hard geometric light patterns, radial sunburst glow, polished metallic specular highlights",
   "color": "high contrast metallic and deep tones, lacquer black, gold, chrome silver, emerald, wine red, ivory",
   "composition": "strict symmetry, central radial arrangement, stepped upward motion, tall vertical format",
   "medium": "hard-edged flat gouache or poster print, lacquer, chrome, frosted glass, inlay",
   "mood": "modern, luxurious, confident, coolly glamorous, futuristic",
   "camera": "low angle, symmetrical framing, wide shot, 35mm",
 },
 "positive": " art deco, 1920s, geometric ornament, stepped zigzag and sunburst motifs, symmetrical architectural composition, streamlined machine age glamour, hard geometric light patterns, radial sunburst glow, polished metallic specular highlights, lacquer black and gold and chrome silver and emerald, strict symmetry, central radial arrangement, stepped upward motion, luxurious and futuristic mood, hard-edged flat poster print",
 "negative": "organic whiplash curves, art nouveau vines, soft watercolour, rustic wood, pastoral landscape, grunge texture",
 "video": {
   "motion": "几何元素规律地开合、光晕脉动、镜头沿对称轴推进",
   "camera": "对称 dolly in、垂直升降；机械般精准的运镜",
   "note": "Art Deco 的运动应该是「机械的、节拍的」，不是有机流动的",
 },
 "pitfalls": [
   "最容易和 Art Nouveau 混淆 → 明确 geometric, stepped, zigzag, symmetrical",
   "不加 black lacquer / chrome / gold 会失去 Deco 的奢华感",
 ],
 "sources": {"cleveland": ["art deco", "1920s design"], "met": ["art deco"]},
 "see_also": ["art-nouveau", "bauhaus"],
},
# ---------------------------------------------------------------- 包豪斯
{
 "slug": "bauhaus",
 "name_zh": "包豪斯",
 "name_en": "Bauhaus",
 "period": "1919–1933",
 "region": "德国",
 "tier": "B",
 "one_liner": "形式追随功能：去掉一切装饰，只留下原色、几何与网格。",
 "core": [
   "功能主义：装饰即罪恶（Loos 语）",
   "三原色 + 黑白灰，几乎不用间色",
   "基本几何形：圆、方、三角",
   "网格系统、无衬线字体、不对称但平衡的版式",
 ],
 "visual": {
   "色彩": "红黄蓝三原色 + 黑、白、灰；高纯度平涂",
   "光影": "完全平面，无光影无体积",
   "笔触": "零笔触：印刷/丝网/几何硬边",
   "构图": "网格化、不对称平衡、大量留白、字号层级明确",
   "材质": "纸张、丝网印、钢管、玻璃、混凝土",
   "情绪": "理性、冷静、实用、乌托邦式的乐观",
 },
 "palette": [("#D32027","原色红"),("#F2C300","原色黄"),("#1B4F9C","原色蓝"),
             ("#111111","黑"),("#FFFFFF","白"),("#BFBFBF","灰")],
 "artists": [("康定斯基","1866–1944"),("克利","1879–1940"),("莫霍利-纳吉","1895–1946"),
             ("约瑟夫·阿尔伯斯","1888–1976"),("赫伯特·拜耶","1900–1985")],
 "prompt": {
   "style": "bauhaus design, functionalism, primary colour geometry, grid based layout, sans serif typography, constructivist abstraction",
   "lighting": "fully flat, no shading, no volume, pure graphic planes",
   "color": "primary red yellow blue with black white grey only, high purity flat fill",
   "composition": "modular grid, asymmetric balance, generous negative space, clear typographic hierarchy",
   "medium": "silkscreen print, matte paper, steel tube and concrete construction",
   "mood": "rational, functional, utopian, impersonal",
   "camera": "flat orthographic frontal view, no perspective",
 },
 "positive": " bauhaus design, functionalism, primary colour geometry, grid based layout, sans serif typography, constructivist abstraction, fully flat, no shading, primary red yellow blue with black white grey only, modular grid, asymmetric balance, generous negative space, rational and utopian mood, silkscreen print on matte paper",
 "negative": "ornament, ornamentation, gradient, drop shadow, texture, bevel, glossy, hand-drawn, watercolour, decorative flourishes",
 "video": {
   "motion": "几何图形按网格位移、旋转、缩放；机械而精确",
   "camera": "static 平面构图；只有元素动，镜头不动",
   "note": "包豪斯的动是「版式动画」而非摄影动画，参考 Moholy-Nagy 的光影实验",
 },
 "pitfalls": [
   "AI 会加渐变和投影 → negative 必须写 gradient, drop shadow, bevel",
   "三原色常被 AI 扩成彩虹色 → 明确 primary red yellow blue ONLY",
 ],
 "sources": {"cleveland": ["bauhaus"], "met": ["bauhaus design"]},
 "see_also": ["art-deco", "cubism"],
},
# ---------------------------------------------------------------- 赛博朋克
{
 "slug": "cyberpunk",
 "name_zh": "赛博朋克",
 "name_en": "Cyberpunk",
 "period": "1980–今",
 "region": "全球（起源于美/日）",
 "tier": "B",
 "one_liner": "高科技，低生活：霓虹、雨夜、巨型广告、被资本吞噬的身体。",
 "core": [
   "垂直都市：巨构建筑压着狭窄街巷",
   "霓虹作为唯一主光源，湿地面负责反射",
   "义体、全息广告、监控与拥挤的人潮",
   "色调被《银翼杀手》定型：青蓝 + 品红 + 琥珀",
 ],
 "visual": {
   "色彩": "青蓝（cyan）与品红（magenta）对撞，琥珀/橙作为人类温度的点缀，大面积黑",
   "光影": "霓虹为主光，湿表面镜面反射，体积雾 + 光晕（bloom），高对比",
   "笔触": "取决于媒介：概念设定为厚涂 + 硬边；电影感为干净写实",
   "构图": "低角度仰视巨构、密集招牌层叠、纵深峡谷式街道",
   "材质": "湿沥青、铬、全息投影、LED、塑料、蒸汽",
   "情绪": "疏离、压抑、迷幻、危险的诱惑",
 },
 "palette": [("#00E5FF","霓虹青"),("#FF2D95","品红"),("#FFA53D","琥珀"),
             ("#0A0E14","夜黑"),("#3B1F5E","深紫"),("#8CFFE0","全息绿")],
 "artists": [("西德·米德","1933–2019"),("士郎正宗","1961–"),("大友克洋","1954–"),
             ("雷德利·斯科特《银翼杀手》","1982")],
 "prompt": {
   "style": "cyberpunk, neo-noir concept art, blade runner aesthetic, dense neon signage, high tech low life, megastructure city",
   "lighting": "neon as primary light source, wet reflective surfaces, volumetric fog, anamorphic bloom, harsh rim light, high contrast night",
   "color": "cyan and magenta clash, amber accent for human warmth, deep black shadows, saturated neon against darkness",
   "composition": "low angle looking up at megastructures, layered signage depth, canyon-like street perspective, crowded foreground",
   "medium": "digital concept painting, wet asphalt, chrome, holographic projection, LED, steam",
   "mood": "alienated, oppressive, intoxicating, dangerous",
   "camera": "low angle, wide shot, 24mm anamorphic, shallow depth of field, lens flare",
 },
 "positive": " cyberpunk, neo-noir concept art, blade runner aesthetic, dense neon signage, high tech low life, megastructure city, neon as primary light source, wet reflective surfaces, volumetric fog, anamorphic bloom, cyan and magenta clash, amber accent, deep black shadows, low angle looking up at megastructures, canyon-like street perspective, alienated and intoxicating mood, digital concept painting, 24mm anamorphic",
 "negative": "daylight, pastoral, clean minimal, rural, historical costume, watercolour, pastel, low contrast, flat lighting",
 "video": {
   "motion": "雨丝下落、蒸汽升腾、全息广告闪烁、人流穿梭",
   "camera": "缓慢 track 前进穿过街道、手持跟拍、anamorphic 变形宽银幕",
   "note": "一定要有「湿地面反射霓虹」——这是赛博朋克最核心的视觉签名",
 },
 "pitfalls": [
   "AI 容易只给「霓虹城市」而丢了 noir 的压抑 → 加 oppressive, alienated, high tech LOW life",
   "常见错误是变成白天或变成纯紫调 → 强调 night, cyan+magenta, wet reflections",
 ],
 "sources": {"cleveland": [], "met": []},
 "see_also": ["art-deco", "expressionism"],
},
]

BY_SLUG = {m["slug"]: m for m in MOVEMENTS}


# ---------------------------------------------------------------------------
# 关联艺术家关键词 —— 用于过滤 API 返回的结果。
# 只有艺术家名字里含有这些片段的作品才会被收进仓库，
# 否则泛化的风格查询会混进大量无关作品（实测：一幅「圣杰罗姆的忏悔」
# 会出现在几乎所有流派的搜索结果里）。
# ---------------------------------------------------------------------------
ARTIST_KEYS = {
 "renaissance": ["leonardo", "da vinci", "michelangelo", "raphael", "titian", "botticelli",
                 "lippi", "bellini", "mantegna", "giorgione", "correggio", "del sarto",
                 "pontormo", "signorelli", "piero", "veronese", "tintoretto", "dürer", "durer"],
 "baroque": ["caravaggio", "rembrandt", "rubens", "velázquez", "velazquez", "vermeer",
             "dolci", "magnasco", "murillo", "jordaens", "van dyck", "frans hals",
             "poussin", "lorrain", "la tour", "artemisia", "gentileschi", "ribera",
             "zurbarán", "zurbaran", "guercino", "reni"],
 "rococo": ["watteau", "boucher", "fragonard", "chardin", "tiepolo", "ricci", "hogarth",
            "gainsborough", "reynolds", "crespi", "longhi", "guardì", "guardi", "pater"],
 "neoclassicism": ["jacques-louis david", "jacques louis david", "david, jacques", "ingres", "canova", "gros", "vien", "west", "hamilton",
                   "kauffmann", "thorvaldsen", "françois gérard", "gerard, françois", "girodet", "prud'hon"],
 "romanticism": ["friedrich", "turner", "delacroix", "géricault", "gericault", "constable",
                 "blake", "girodet", "fuseli", "amerling", "fantin", "böcklin", "bocklin",
                 "chassériau", "chasseriau", "cottet", "runge"],
 "realism": ["courbet", "millet", "repin", "daumier", "eakins", "le nain", "corot",
             "manet", "homer", "bonheur", "kramskoy", "perov", "liebermann"],
 "impressionism": ["monet", "renoir", "degas", "pissarro", "sisley", "morisot", "bazille",
                   "cassatt", "manet", "hayet", "caillebotte", "guillaumin", "boudin",
                   "lepère", "lepere", "signac"],
 "post-impressionism": ["van gogh", "cezanne", "cézanne", "gauguin", "seurat", "toulouse",
                        "lautrec", "rousseau", "bernard", "vuillard", "bonnard", "denis",
                        "cross", "laurencin"],
 "symbolism": ["gustave moreau", "moreau, gustave", "klimt", "redon", "puvis", "chavannes", "ryder", "böcklin",
               "bocklin", "khnopff", "von stuck", "stuck", "whistler", "carrière",
               "carriere", "hodler", "munch", "cot"],
 "art-nouveau": ["mucha", "horta", "gaudí", "gaudi", "beardsley", "tiffany", "gallé",
                 "galle", "majorelle", "guimard", "mackintosh", "van de velde",
                 "eckmann", "grasset"],
 "ukiyo-e": ["hokusai", "hiroshige", "utamaro", "kuniyoshi", "yoshitoshi", "sharaku",
             "zeshin", "seitoku", "kagei", "eisen", "kunisada", "harunobu", "koryūsai",
             "koryusai", "sukenobu"],
 "pre-raphaelite": ["rossetti", "millais", "hunt", "burne-jones", "waterhouse", "sandys",
                    "ford madox brown", "morris", "deverell", "hughes", "collinson", "stillman"],
 "expressionism": ["munch", "kirchner", "nolde", "schiele", "kandinsky", "heckel",
                   "schmidt-rottluff", "barlach", "beckmann", "kokoschka", "jawlensky",
                   "mueller", "müller", "pechstein", "kollwitz"],
 "cubism": ["picasso", "braque", "gris", "léger", "leger", "marcoussis", "metzinger",
            "gleizes", "delaunay", "lipchitz", "la fresnaye"],
 "surrealism": ["dalí", "dali", "magritte", "max ernst", "ernst, max", "miró", "miro", "tanguy", "delvaux",
                "masson", "man ray", "chirico", "picabia", "arp"],
 "art-deco": ["erté", "erte", "lempicka", "poiret", "cassandre", "fehér", "feher",
              "ruhlmann", "dupas", "barbier", "puiforcat"],
 "bauhaus": ["klee", "kandinsky", "moholy-nagy", "moholy", "albers", "bayer", "feininger",
             "schlemmer", "itten", "breuer", "brandt"],
 "cyberpunk": [],
}

for _m in MOVEMENTS:
    _m["artist_keys"] = ARTIST_KEYS.get(_m["slug"], [])
