# -*- coding: utf-8 -*-
"""流派定义 —— 摄影与图像（6 个）。

原来的仓库只覆盖绘画与设计，缺了整个摄影谱系。
这里面画意摄影、直接摄影、纪实摄影都有大量公共领域作品，能配图。
"""

CATEGORY = "摄影与图像"

MOVEMENTS = [
# ---------------------------------------------------------------- 画意摄影
{
 "slug": "pictorialism", "name_zh": "画意摄影", "name_en": "Pictorialism",
 "period": "1885–1915", "region": "欧美", "tier": "A",
 "one_liner": "让照片看起来像画：柔焦、手工印相、刮擦与涂绘。",
 "core": ["主张摄影应当模仿绘画的审美价值",
          "柔焦镜头、控制景深、暗房手工干预",
          "铂金印相、溴化银、树胶重铬酸盐等工艺",
          "题材多为风景、裸体、肖像与寓言"],
 "visual": {"色彩": "单色：铂金的暖灰、蓝晒的蓝、碳印的深褐",
            "光影": "柔和的漫射光，高光晕开（halation），边缘虚化",
            "笔触": "照片上的手工痕迹：刮擦、涂绘、笔刷感",
            "构图": "绘画式构图，常有装饰性边框与签名",
            "材质": "铂金印相纸、树胶、碳素、粗糙纹理纸",
            "情绪": "诗意、朦胧、怀旧、世纪末的感伤"},
 "palette": [("#8B7A5A","铂金灰"),("#6B5A4A","暖褐"),("#A89878","米灰"),
             ("#3A3632","深影"),("#D9CFC0","高光白"),("#1F3A5C","蓝晒蓝")],
 "artists": [("阿尔弗雷德·斯蒂格利茨","1864–1946"),("爱德华·斯泰肯","1879–1973"),
             ("格特鲁德·卡塞比尔","1852–1934"),("罗伯特·德马奇","1862–1943"),
             ("克拉伦斯·怀特","1871–1925")],
 "prompt": {"style": "pictorialist photography, soft focus, platinum print, hand manipulated darkroom print, painterly photographic aesthetics",
            "lighting": "soft diffused light, halation glow around highlights, gentle vignetting",
            "color": "monochrome platinum warm grey, sepia, blue cyanotype, deep carbon brown",
            "composition": "painterly composition with decorative border and signature",
            "medium": "platinum print, gum bichromate, carbon transfer, textured paper",
            "mood": "poetic, hazy, nostalgic, fin-de-siecle melancholy",
            "camera": "large format, soft focus lens, shallow depth of field, long exposure"},
 "negative": "sharp digital clarity, high contrast, saturated colour, documentary neutrality, snapshot",
 "video": {"motion": "几乎没有；或极慢的树叶与水面移动",
           "camera": "static；柔焦与轻微漏光",
           "note": "画意摄影的动感应像褪色的记忆，不要清晰"},
 "pitfalls": ["AI 会做得太清晰 → 加 soft focus, halation, platinum print, hand manipulated",
              "容易变成普通复古滤镜 → 强调 painterly composition, decorative border"],
 "sources": {"cleveland": ["pictorialism", "stieglitz", "steichen"],
             "met": ["alfred stieglitz", "edward steichen", "pictorialism"],
             "commons": ["Clarence H. White photograph", "Robert Demachy photograph", "Gertrude Kasebier photograph", "Pictorialist photograph platinum"]},
 "see_also": ["tonalism", "symbolism", "wet-plate", "documentary-photography"],
},
# ---------------------------------------------------------------- 直接摄影
{
 "slug": "straight-photography", "name_zh": "直接摄影", "name_en": "Straight Photography",
 "period": "1910–1950", "region": "美国", "tier": "A",
 "one_liner": "反画意：不柔焦、不加工，用最清晰的细节呈现物体本身。",
 "core": ["拒绝画意摄影的手工干预与模仿绘画",
          "强调摄影媒介自身的清晰、锐利与客观",
          "精确的构图与影调层次（zone system 的前身）",
          "题材：自然形态、工业结构、日常物件"],
 "visual": {"色彩": "丰富的黑白灰层次，从纯黑到纯白的完整影调",
            "光影": "清晰锐利的光，强调形体的体积与质感",
            "笔触": "无；就是银盐颗粒与镜头的解析力",
            "构图": "精确的框取、强烈的形式感、常抽象化日常物",
            "材质": "黑白底片、明胶银盐印相、光面纸",
            "情绪": "冷静、精确、形式主义的庄严"},
 "palette": [("#0F0F0F","纯黑"),("#4A4A4A","深灰"),("#8A8A85","中灰"),
             ("#C9CFD4","浅灰"),("#FFFFFF","纯白"),("#2B2B33","暗部")],
 "artists": [("爱德华·韦斯顿","1886–1958"),("安塞尔·亚当斯","1902–1984"),
             ("保罗·斯特兰德","1890–1976"),("伊莫金·坎宁安","1883–1976"),
             ("爱德华·史泰钦（后期）","1879–1973")],
 "prompt": {"style": "straight photography, f/64 group, sharp focus large format, full tonal range, objective precise framing, weston and adams",
            "lighting": "crisp directional light revealing volume and texture, complete zone system tonality",
            "color": "rich black and white, full range from pure black to pure white, silver gelatin",
            "composition": "precise framing, strong formal abstraction of ordinary objects",
            "medium": "large format negative, gelatin silver print, glossy fibre paper",
            "mood": "cool, precise, formalist solemnity",
            "camera": "large format, small aperture, extreme depth of field, front rise"},
 "negative": "soft focus, hand manipulation, blur, pictorialism, colour, romantic haze",
 "video": {"motion": "几乎静止；只有自然元素的细微变化",
           "camera": "static 大画幅视角；绝不用柔焦",
           "note": "直接摄影的核心是「极致的清晰」——任何柔化都是背叛"},
 "pitfalls": ["和画意摄影搞反 → 直接摄影要锐利、完整影调、无手工干预",
              "AI 会加颗粒与柔光 → negative 写 soft focus, blur, pictorialism"],
 "sources": {"cleveland": ["edward weston", "ansel adams", "straight photography"],
             "met": ["edward weston", "paul strand", "ansel adams"],
             "commons": ["Edward Weston photograph", "Paul Strand photograph", "Imogen Cunningham photograph", "Ansel Adams photograph"]},
 "see_also": ["pictorialism", "precisionism", "documentary-photography"],
},
# ---------------------------------------------------------------- 纪实摄影
{
 "slug": "documentary-photography", "name_zh": "纪实摄影", "name_en": "Documentary Photography",
 "period": "1930–今", "region": "全球", "tier": "A",
 "one_liner": "用照片作证：大萧条、战争、贫民窟，镜头负有道义责任。",
 "core": ["以记录社会现实为目的，常带改革诉求",
          "政府项目（FSA）与新闻摄影推动其制度化",
          "黑白、自然光、不干预现场",
          "构图服务于信息传达而非形式美感"],
 "visual": {"色彩": "黑白为主（早期），后期彩色也偏纪实的中性色",
            "光影": "自然现场光，包括不完美的阴天与室内光",
            "笔触": "无；颗粒感与现场的粗糙",
            "构图": "快速抓取、不完美的构图、主体在环境之中",
            "材质": "35mm 或中画幅黑白底片、银盐印相、杂志印刷",
            "情绪": "沉重、同情、见证、有尊严的记录"},
 "palette": [("#2B2B33","深黑"),("#6B6B60","中灰"),("#A89878","尘土褐"),
             ("#D9CFC0","灰白"),("#8B6B4A","土地"),("#4A5A6B","阴天蓝")],
 "artists": [("多萝西娅·兰格","1895–1965"),("沃克·埃文斯","1903–1975"),
             ("亨利·卡蒂埃-布列松","1908–2004"),("罗伯特·卡帕","1913–1954"),
             ("奥古斯特·桑德","1876–1964")],
 "prompt": {"style": "documentary photography, social documentary, fsa photography, unposed real situation, dorothea lange and walker evans",
            "lighting": "available natural light including flat overcast and imperfect interior light",
            "color": "black and white, or neutral restrained documentary colour",
            "composition": "quick unposed framing, subject embedded in environment, imperfect but meaningful",
            "medium": "35mm or medium format negative, gelatin silver print, magazine reproduction",
            "mood": "grave, sympathetic, witnessing, dignified",
            "camera": "35mm, handheld, eye-level, deep focus, no posing"},
 "negative": "studio lighting, posed glamour, artistic manipulation, saturated colour, staged perfection",
 "video": {"motion": "现场的自然运动：人群、劳作、风雨；镜头保持观察",
           "camera": "handheld 跟随，不干预；长镜头观察",
           "note": "纪实摄影的伦理是「不干预」——镜头要退后一步"},
 "pitfalls": ["AI 会加戏剧性打光 → negative 写 studio lighting, staged perfection",
              "必须保留「不完美构图」——太完美就失去纪实感"],
 "sources": {"cleveland": ["documentary photography", "dorothea lange"],
             "met": ["walker evans", "dorothea lange", "august sander"],
             "commons": ["Dorothea Lange photograph", "Walker Evans photograph", "August Sander photograph", "Lewis Hine photograph"]},
 "see_also": ["pictorialism", "social-realism", "street-photography"],
},
# ---------------------------------------------------------------- 街头摄影
{
 "slug": "street-photography", "name_zh": "街头摄影", "name_en": "Street Photography",
 "period": "1930–今", "region": "全球", "tier": "A",
 "one_liner": "决定性瞬间：在街上等待，直到所有元素恰好排成一张好照片。",
 "core": ["在公共空间抓取未经安排的瞬间",
          "「决定性瞬间」：形式与事件同时到达顶点",
          "35mm 小型相机 + 快速反应",
          "幽默、偶然、几何巧合与人的姿态"],
 "visual": {"色彩": "黑白经典，也有彩色街头（偏暖或偏冷的地域色）",
            "光影": "强烈的街道光：斜射阳光、橱窗反光、雨后倒影",
            "笔触": "无；颗粒与轻微动态模糊",
            "构图": "几何化框取、多层前后景、被切断的行人",
            "材质": "35mm 黑白或彩色底片、银盐或染料印相",
            "情绪": "机智、观察、都市的诗意与荒诞"},
 "palette": [("#1A1A1A","深黑"),("#7A7A75","街灰"),("#D9CFC0","石墙白"),
             ("#C9A25A","暖阳"),("#4A6B8B","橱窗蓝"),("#A8432A","砖红")],
 "artists": [("卡蒂埃-布列松","1908–2004"),("布拉塞","1899–1984"),
             ("加里·温诺格兰德","1928–1984"),("李·弗里德兰德","1934–"),
             ("薇薇安·迈尔","1926–2009"),("何藩","1931–2016")],
 "prompt": {"style": "street photography, decisive moment, candid urban scene, geometric framing of passers-by, cartier-bresson and winogrand",
            "lighting": "strong street light, raking sun, shop window reflection, wet pavement reflection",
            "color": "classic black and white, or regionally tinted street colour",
            "composition": "geometric framing, layered foreground and background, cropped pedestrians",
            "medium": "35mm film, gelatin silver or dye print, visible grain",
            "mood": "witty, observational, urban poetry and absurdity",
            "camera": "35mm, handheld, eye-level, quick reflex framing"},
 "negative": "posed studio portrait, staged setup, soft focus, symmetrical perfection, empty scene",
 "video": {"motion": "行人穿行、车流、光影移动；镜头等待瞬间",
           "camera": "handheld 街头视角，快速 pan 抓取",
           "note": "街头摄影的灵魂是「等待」——让画面自己组成"},
 "pitfalls": ["AI 会做成摆拍 → 加 candid, unposed, snapshot, decisive moment",
              "容易缺少层次 → 明确 layered foreground and background"],
 "sources": {"cleveland": ["street photography", "henri cartier-bresson"],
             "met": ["street photography", "brassai", "cartier-bresson"],
             "commons": ["Eugene Atget Paris photograph", "Street photography 1900s", "Andre Kertesz photograph", "Paul Martin street photograph"]},
 "see_also": ["documentary-photography", "ashcan-school", "film-noir"],
},
# ---------------------------------------------------------------- 超现实摄影
{
 "slug": "surrealist-photography", "name_zh": "超现实摄影", "name_en": "Surrealist Photography",
 "period": "1924–1950", "region": "法国 / 美国", "tier": "A",
 "one_liner": "用相机制造不可能：负片叠印、变形、无脸的身体与漂浮的物件。",
 "core": ["把超现实主义的潜意识策略用于摄影媒介",
          "暗房技法：多重曝光、负片、日晒（solarisation）",
          "身体被切割、扭曲、去身份化",
          "日常物被置于陌生语境而变得诡异"],
 "visual": {"色彩": "黑白为主，或早期手工着色的奇异色调",
            "光影": "戏剧性的硬光，或完全反物理的光影关系",
            "笔触": "暗房干预：负像、叠印、刮擦、过度显影",
            "构图": "身体局部特写、镜像、重复、物理上不可能的空间",
            "材质": "黑白底片、明胶银盐、摄影蒙太奇、实物拼贴",
            "情绪": "怪诞、色情与恐惧交织、无意识的不安"},
 "palette": [("#0F0F12","纯黑"),("#5A5A5A","银灰"),("#D9CFC0","高光白"),
             ("#8B6B4A","调色褐"),("#4A3A5A","暗紫"),("#C9A25A","手着色黄")],
 "artists": [("曼·雷","1890–1976"),("布拉塞","1899–1984"),
             ("克劳德·卡恩","1894–1954"),("汉斯·贝尔默","1902–1975"),
             ("朵拉·玛尔","1907–1997"),("李·米勒","1907–1977")],
 "prompt": {"style": "surrealist photography, rayograph photogram, solarisation, multiple exposure, uncanny body fragmentation, man ray and claude cahun",
            "lighting": "dramatic hard light or physically impossible light relationships",
            "color": "black and white, or strange hand-tinted early colour",
            "composition": "body fragment close-up, mirroring, repetition, impossible space",
            "medium": "black and white negative, gelatin silver print, photomontage, collage",
            "mood": "uncanny, erotic and fearful, unconscious unease",
            "camera": "extreme close-up, unusual angles, deliberate distortion"},
 "negative": "straight documentary, naturalistic portrait, colour realism, conventional lighting, safe imagery",
 "video": {"motion": "违反物理的变形、身体局部缓慢移动、影像叠化",
           "camera": "缓慢的叠化与多重曝光感；不要稳定的写实运镜",
           "note": "超现实摄影靠暗房技法——提示词里要写 photogram, solarisation"},
 "pitfalls": ["和超现实主义绘画区分：这里的手段是暗房与光学，不是画笔",
              "AI 容易做得太干净 → 加 solarisation, photogram, multiple exposure"],
 "sources": {"cleveland": ["man ray", "surrealist photography"],
             "met": ["man ray", "surrealist photography"], "commons": ["Man Ray photograph"]},
 "see_also": ["surrealism", "dada", "pictorialism", "magic-realism"],
},
# ---------------------------------------------------------------- 时尚编辑摄影
{
 "slug": "fashion-editorial", "name_zh": "时尚编辑摄影", "name_en": "Fashion Editorial",
 "period": "1930–今", "region": "全球", "tier": "B",
 "one_liner": "把衣服拍成叙事：影棚、异域、超现实布景，模特是画布也是角色。",
 "core": ["时装作为叙事与欲望的载体",
          "影棚布景与实景外拍的两种传统",
          "模特的身体姿态与服装同样重要",
          "与超现实主义、电影、绘画持续互相借用"],
 "visual": {"色彩": "高饱和的编辑色调，或精准的黑白高级灰",
            "光影": "明确的影棚布光（蝴蝶光、伦勃朗光）或戏剧性外景光",
            "笔触": "无；但造型、妆发、布景提供质感",
            "构图": "全身竖构图、动态姿态、强烈的姿势导向",
            "材质": "织物、绸缎、羽毛、金属配饰、布景道具",
            "情绪": "优雅、欲望、力量、被构造的完美"},
 "palette": [("#C1272D","唇红"),("#111111","黑"),("#E8DCC8","象牙"),
             ("#C9A227","金"),("#4A6B8B","冷蓝"),("#F2A8C8","粉")],
 "artists": [("理查德·阿维顿","1923–2004"),("欧文·佩恩","1917–2009"),
             ("赫尔穆特·牛顿","1920–2004"),("盖伊·伯丁","1928–1991"),
             ("蒂姆·沃克","1970–")],
 "prompt": {"style": "fashion editorial photography, vogue magazine spread, constructed set design, dramatic model pose, avadon and penn",
            "lighting": "defined studio lighting, butterfly or rembrandt key, or dramatic location light",
            "color": "saturated editorial colour grade or precise high key black and white",
            "composition": "full length vertical figure, dynamic pose, strong pose-driven framing",
            "medium": "large format film, studio set, silk and feather and metal accessories",
            "mood": "elegant, desiring, powerful, constructed perfection",
            "camera": "medium format, 80mm, f/8, studio strobe, sharp"},
 "negative": "candid snapshot, everyday clothing, flat lighting, documentary neutrality, unposed",
 "video": {"motion": "模特转身、布料飘动、风吹发丝",
           "camera": "缓慢环绕或 dolly，模仿时装影片",
           "note": "时尚编辑的权力在「构造」——布景与姿态缺一不可"},
 "pitfalls": ["和街头/纪实区分：时尚编辑是完全被构造的",
              "只存提示词，不收作品图"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["art-deco", "surrealist-photography", "polaroid-film", "kitsch"],
},
]

ARTIST_KEYS = {
 "pictorialism": ["pictorialis", "stieglitz", "steichen", "kasebier", "käsebier", "demachy", "clarence white", "coburn", "day, holland", "eugene", "eugène", "platinum print"],
 "straight-photography": ["weston", "ansel adams", "paul strand", "cunningham", "f/64", "f64", "straight photo", "gelatin silver"],
 "documentary-photography": ["dorothea lange", "lange, dorothea", "walker evans",
                              "august sander", "lewis hine", "robert capa",
                              "documentary", "farm security administration"],
 "street-photography": ["atget", "kertesz", "kertész", "paul martin", "street photo", "cartier-bresson", "brassai", "brassaï", "winogrand"],
 "surrealist-photography": ["man ray", "cahun", "claude cahun", "bellmer", "dora maar",
                             "lee miller", "rayograph", "solaris", "photogram"],
 "fashion-editorial": ["avedon", "irving penn", "helmut newton", "bourdin",
                        "tim walker", "vogue", "fashion"],
}
