# -*- coding: utf-8 -*-
"""流派定义 —— 数字 / 亚文化 / 摄影美学（23 个）。

这一类大多是当代风格，几乎找不到可自由分发的实图。
其中 19 世纪摄影工艺（蓝晒、湿版）和部分黑色电影剧照属于公共领域，能配图。
"""

CATEGORY = "数字·亚文化·摄影美学"

MOVEMENTS = [
# ---------------------------------------------------------------- 蒸汽朋克
{
 "slug": "steampunk", "name_zh": "蒸汽朋克", "name_en": "Steampunk",
 "period": "1980–今", "region": "英美（维多利亚架空）", "tier": "B",
 "one_liner": "如果维多利亚时代发明了电脑：黄铜、齿轮、蒸汽和皮质护目镜。",
 "core": ["维多利亚时代美学 + 架空蒸汽科技",
          "齿轮、管道、压力表、铆钉构成视觉词汇",
          "材质为王：黄铜、铜绿、皮革、深色木材",
          "浓厚的煤烟与工业雾霾氛围"],
 "visual": {"色彩": "黄铜金、铜绿、深棕皮革、煤烟灰、暗红天鹅绒",
            "光影": "暖黄煤气灯 + 蒸汽散射；高对比，光柱明显",
            "笔触": "取决于媒介；概念设定多为厚涂写实",
            "构图": "机械结构充满画面、对称的仪器面板、仰视巨大的机械",
            "材质": "黄铜、紫铜、铸铁、皮革、齿轮、玻璃压力表、蒸汽",
            "情绪": "怀旧的冒险感、机械浪漫、脏而精致的工艺感"},
 "palette": [("#B8860B","黄铜"),("#4A7A6B","铜绿"),("#5A3A2A","皮革棕"),
             ("#2B2B2B","煤烟灰"),("#7A1F2B","天鹅绒红"),("#C9A227","暖金")],
 "artists": [("儒勒·凡尔纳（文学源头）","1828–1905"),("H.G.威尔斯","1866–1946"),
             ("伊恩·麦凯格（插画）","1960–"),("詹姆斯·格尔尼","1958–")],
 "prompt": {"style": "steampunk, victorian retro-futurism, brass and gear machinery, leather and copper, goggles and pressure gauges, industrial fantasy concept art",
            "lighting": "warm gaslight and steam diffusion, visible volumetric light shafts, high contrast, soot haze",
            "color": "brass gold, verdigris, dark leather brown, soot grey, deep velvet red",
            "composition": "machinery filling the frame, symmetrical instrument panels, low angle on giant engines",
            "medium": "digital concept painting, polished brass, patina copper, leather and dark wood",
            "mood": "adventurous nostalgia, mechanical romance, grimy craftsmanship",
            "camera": "low angle, wide shot, 35mm, slight lens flare from lamps"},
 "negative": "modern technology, plastic, neon, minimalism, clean digital, contemporary clothing, flat design",
 "video": {"motion": "齿轮转动、活塞往复、蒸汽喷出、仪表指针摆动",
           "camera": "缓慢 track 穿过机械内部，或低角度 crane up",
           "note": "蒸汽朋克的运动必须有「机械节奏」——往复、顿挫"},
 "pitfalls": ["AI 会加现代元素 → negative 写 modern technology, plastic, neon",
              "材质感不足会变成普通奇幻 → 强调 brass, patina, leather, rivets"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["dieselpunk", "cyberpunk", "art-nouveau"],
},
# ---------------------------------------------------------------- 柴油朋克
{
 "slug": "dieselpunk", "name_zh": "柴油朋克", "name_en": "Dieselpunk",
 "period": "2000–今", "region": "欧美（二战架空）", "tier": "B",
 "one_liner": "蒸汽朋克走进二十世纪：铆钉、柴油机、飞艇和灰绿色的战争机器。",
 "core": ["1920–1950 年代的工业美学：流线型 + 铆钉",
          "巨大、笨重、实用主义的战争机械",
          "灰绿、铁锈、铬与皮革的材质组合",
          "威权、阴郁、总体战的时代气氛"],
 "visual": {"色彩": "军绿、铁锈橙、铬银、煤灰黑、暗棕皮革",
            "光影": "阴天散射光 + 探照灯；冷硬且压抑",
            "笔触": "概念设定为厚涂写实；海报为装饰艺术式平涂",
            "构图": "巨构机械压迫、低角度仰视、对称的军事阵列",
            "材质": "铆接钢板、铸铁、柴油机、帆布、皮革、铬",
            "情绪": "肃杀、工业化、威权、笨重的力量"},
 "palette": [("#4A5A3A","军绿"),("#A8432A","铁锈橙"),("#8A8A85","铬银"),
             ("#2B2B2B","煤灰黑"),("#5A3A2A","皮革棕"),("#C9A227","黄铜")],
 "artists": [("迪塞尔朋克概念画师","2000s"),("《天空上尉》视觉团队","2004"),
             ("《钢铁苍穹》美术组","2012")],
 "prompt": {"style": "dieselpunk, interwar retro-futurism, riveted steel machinery, diesel engines and airships, streamlined 1930s industrial design, authoritarian grandeur",
            "lighting": "overcast diffuse light with searchlights, cold hard contrast, oppressive haze",
            "color": "military green, rust orange, chrome silver, coal black, leather brown",
            "composition": "giant machinery looming, low angle, symmetrical military arrays",
            "medium": "digital concept painting, riveted steel plate, cast iron, canvas and leather",
            "mood": "severe, industrial, authoritarian, heavy power",
            "camera": "low angle, wide, 28mm, deep focus"},
 "negative": "clean modern design, plastic, neon, fantasy magic, pastel, minimalist, sleek curves",
 "video": {"motion": "螺旋桨旋转、履带碾压、飞艇缓慢移动、探照灯扫过",
           "camera": "低角度缓慢推进，或航拍巨大的机械",
           "note": "柴油朋克的一切都要「重」——慢、笨、有质量"},
 "pitfalls": ["和蒸汽朋克混淆 → 柴油朋克更冷、更军事、更 20 世纪",
              "AI 会画得太干净 → 加 rust, rivets, soot, weathered steel"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["steampunk", "art-deco", "wasteland"],
},
# ---------------------------------------------------------------- 太阳朋克
{
 "slug": "solarpunk", "name_zh": "太阳朋克", "name_en": "Solarpunk",
 "period": "2010–今", "region": "全球", "tier": "B",
 "one_liner": "反乌托邦的反面：绿色城市、太阳能、社区与真正的希望。",
 "core": ["乐观未来主义，明确拒绝赛博朋克的绝望",
          "自然与高科技共生：建筑上长满植物",
          "去中心化能源与社区自治",
          "新艺术运动与装饰艺术的复兴式混搭"],
 "visual": {"色彩": "明快的白、天蓝、植物绿、暖阳黄 + 玻璃与黄铜点缀",
            "光影": "充足的自然阳光、斑驳树影、明亮通透",
            "笔触": "数字概念画，干净明亮；或装饰性平涂",
            "构图": "开阔的城市景观、垂直绿化、圆形与有机曲线",
            "材质": "玻璃、太阳能板、木材、藤蔓、白墙、黄铜细节",
            "情绪": "希望、明亮、社区温暖、可持续的丰盛"},
 "palette": [("#F2EDE4","白墙"),("#7FC8E8","天蓝"),("#5FA85F","植物绿"),
             ("#F2C230","暖阳黄"),("#B8860B","黄铜"),("#A8D5BA","薄荷")],
 "artists": [("太阳朋克宣言作者","2014–"),("Studio Ghibli（视觉先声）","1985–"),
             ("Luc Schuiten","1944–")],
 "prompt": {"style": "solarpunk, optimistic eco-futurism, lush vertical gardens on white architecture, solar panels, community utopia, art nouveau revival curves",
            "lighting": "abundant natural sunlight, dappled leaf shadows, bright airy transparency",
            "color": "bright white, sky blue, plant green, warm sun yellow, brass accents, clean and luminous",
            "composition": "open city vista, vertical greenery, circular and organic curves, generous sky",
            "medium": "digital concept painting, glass, solar panels, timber, climbing vines",
            "mood": "hopeful, bright, communal warmth, sustainable abundance",
            "camera": "eye-level or slight high angle, wide, 24mm, bright exposure"},
 "negative": "dystopian, grimy, neon, dark cyberpunk, post-apocalyptic, pollution, concrete brutalism, despair",
 "video": {"motion": "树叶随风、阳光斑驳移动、飞行器安静滑过",
           "camera": "缓慢向前飞行穿过绿植覆盖的街道",
           "note": "太阳朋克的动必须是「安静、干净、有生机」的"},
 "pitfalls": ["AI 会自动加赛博朋克元素 → negative 写 dystopian, neon, dark cyberpunk",
              "容易变成普通乌托邦概念图 → 加强 vertical gardens, solar, community scale"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["cyberpunk", "art-nouveau", "cottagecore"],
},
# ---------------------------------------------------------------- 生物朋克
{
 "slug": "biopunk", "name_zh": "生物朋克", "name_en": "Biopunk",
 "period": "1990–今", "region": "全球", "tier": "B",
 "one_liner": "不是金属义体，而是活体组织：培养槽、菌丝、血肉建筑。",
 "core": ["生物技术失控：基因编辑、克隆、器官培养",
          "有机材质取代机械：湿、暖、会呼吸的科技",
          "身体恐怖（body horror）与异化",
          "湿滑、黏腻、半透明的视觉质感"],
 "visual": {"色彩": "肉粉、暗红、粘液绿、培养液琥珀、苍白米白",
            "光影": "培养槽的内发光、湿润表面的高光、昏暗实验室",
            "笔触": "厚涂写实，强调湿润与半透明质感",
            "构图": "封闭的实验空间、对称的培养容器阵列、人体与机械融合",
            "材质": "培养液、生物膜、软骨、菌丝体、玻璃槽、导管",
            "情绪": "不适、病态的美、伦理焦虑、湿润的恐惧"},
 "palette": [("#D98B8B","肉粉"),("#8B1A2A","暗红"),("#7AA85F","粘液绿"),
             ("#C9A227","培养液琥珀"),("#E8DCC8","苍白米白"),("#2B2B33","暗室黑")],
 "artists": [("大卫·柯南伯格（电影）","1943–"),("H.R.吉格尔","1940–2014"),
             ("《攻壳机动队》美术组","1995"),("生物艺术实验室","2000s")],
 "prompt": {"style": "biopunk, organic technology, flesh architecture, genetic engineering gone wrong, wet translucent biological surfaces, body horror",
            "lighting": "glow from inside culture tanks, wet specular highlights, dim laboratory ambience",
            "color": "flesh pink, dark blood red, mucus green, amber culture fluid, pallid cream",
            "composition": "enclosed laboratory, symmetrical rows of culture vessels, human fused with organic machine",
            "medium": "digital realistic painting, culture fluid, biofilm, cartilage, mycelium, glass tank",
            "mood": "unsettling, morbid beauty, ethical anxiety, wet dread",
            "camera": "close-up, shallow depth of field, 85mm, clinical framing"},
 "negative": "clean chrome, dry mechanical, bright cheerful, cartoon, flat design, minimalist, pastoral",
 "video": {"motion": "组织缓慢搏动、液体中气泡上升、薄膜蠕动",
           "camera": "极缓 push in 到湿润表面；稳定而临床",
           "note": "生物朋克的动是「内部在搏动」，缓慢得令人不适"},
 "pitfalls": ["和赛博朋克混淆 → 生物朋克是湿的、有机的、肉质的，不是金属霓虹",
              "AI 会画得太干净 → 加 wet, translucent, mucus, membrane"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["cyberpunk", "surrealism", "steampunk"],
},
# ---------------------------------------------------------------- 蒸汽波
{
 "slug": "vaporwave", "name_zh": "蒸汽波", "name_en": "Vaporwave",
 "period": "2010–今", "region": "网络文化", "tier": "B",
 "one_liner": "90 年代消费主义的幽灵：粉紫渐变、罗马雕像、日文招牌和商场音乐。",
 "core": ["挪用 80–90 年代的商业图像与早期 3D 渲染",
          "粉紫青色渐变是绝对签名",
          "希腊罗马雕像 + 棕榈树 + 老式电脑 + 日文汉字",
          "怀旧与空虚并存，对消费社会的反讽"],
 "visual": {"色彩": "粉、紫、青三色渐变；荧光但不刺眼，带灰的褪色感",
            "光影": "无真实光源，一切自带柔和渐变光晕",
            "笔触": "零笔触，数字合成与低分辨率像素感并存",
            "构图": "居中对称的孤立体、网格地板、无限延伸的走廊",
            "材质": "早期 3D 渲染、VHS 噪点、大理石雕塑、CRT 屏幕",
            "情绪": "怀旧、空虚、迷幻的平静、消费主义的忧郁"},
 "palette": [("#F23D8E","霓虹粉"),("#7B3FA0","紫"),("#29D6E8","青"),
             ("#2B1B4A","深夜蓝紫"),("#E8DCC8","大理石白"),("#F2EDE4","光晕白")],
 "artists": [("Vektroid / Macintosh Plus","2011"),("Blank Banshee","2012"),
             ("2814","2014"),("猫 シ Corp.","2013")],
 "prompt": {"style": "vaporwave aesthetic, 90s consumer nostalgia, pink purple cyan gradient, classical marble statue, early 3d render, VHS glitch, japanese signage",
            "lighting": "no real light source, everything bathed in soft gradient glow, chromatic bloom",
            "color": "neon pink, violet, cyan gradients, faded and hazy, deep blue-violet background",
            "composition": "centred solitary object, infinite grid floor, endless corridor, symmetrical",
            "medium": "digital composite, early 3D render, VHS noise, marble sculpture, CRT scanlines",
            "mood": "nostalgic, empty, hypnotically calm, consumerist melancholy",
            "camera": "static centred, wide, slight VHS softness"},
 "negative": "sharp realistic detail, natural lighting, warm cosy, hand-painted texture, gritty realism, historical accuracy",
 "video": {"motion": "缓慢的无限缩放、网格地板向后流动、雕像缓缓旋转",
           "camera": "极缓 zoom in 或向前滑行；VHS 抖动",
           "note": "蒸汽波的动是「慢速漂移 + 视频故障」，不要清晰的运镜"},
 "pitfalls": ["AI 会画得太清晰 → 加 VHS, low resolution, gradient haze, glitch",
              "三色渐变是核心 → 必须明确 pink purple cyan gradient"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["synthwave", "y2k", "dreamcore", "cyberpunk"],
},
# ---------------------------------------------------------------- 合成器浪潮
{
 "slug": "synthwave", "name_zh": "合成器浪潮", "name_en": "Synthwave",
 "period": "2005–今", "region": "网络文化", "tier": "B",
 "one_liner": "80 年代科幻海报的复活：霓虹日落、网格地平线、铬与激光。",
 "core": ["80 年代动作片与科幻海报的视觉复兴",
          "巨大霓虹太阳 + 条纹地平线 + 透视网格",
          "镀铬字体与激光描边",
          "跑车、日落、棕榈树、无尽公路"],
 "visual": {"色彩": "品红、青、橙黄日落渐变；深紫夜空",
            "光影": "强烈霓虹背光、激光描边、镜面反射",
            "笔触": "零笔触：喷枪渐变 + 硬边几何",
            "构图": "水平地平线居中、透视网格延伸、对称的日落",
            "材质": "数字喷枪、镀铬、镜面、霓虹灯管",
            "情绪": "速度、怀旧的亢奋、孤独的夜色浪漫"},
 "palette": [("#F23D8E","品红"),("#29D6E8","青"),("#F2A93B","日落橙"),
             ("#2B1B4A","深紫夜空"),("#8A8A85","铬银"),("#F2C230","激光黄")],
 "artists": [("Kavinsky","2006–"),("The Midnight","2012–"),
             ("James White","2005–"),("TRON 美术组","1982")],
 "prompt": {"style": "synthwave, 80s retro-futurism, neon sunset with striped horizon, perspective grid, chrome lettering, laser outlines, outrun aesthetic",
            "lighting": "intense neon backlight, laser rim lighting, mirror reflections, glowing sunset",
            "color": "magenta, cyan, sunset orange gradient, deep purple night sky, chrome silver",
            "composition": "centred horizon, receding perspective grid, symmetrical sunset, wide cinematic",
            "medium": "digital airbrush gradient, chrome, mirror surface, neon tube",
            "mood": "fast, nostalgically excited, lonely nocturnal romance",
            "camera": "low wide angle, anamorphic, slow forward motion on a road"},
 "negative": "daylight, pastoral, natural textures, muted colour, hand-painted, historical, dull",
 "video": {"motion": "网格向观者奔来、太阳缓慢下沉、跑车驶向地平线",
           "camera": "向前疾驰的推进镜头；anamorphic 变形宽银幕",
           "note": "合成器浪潮必须有「向前的速度」和地平线网格"},
 "pitfalls": ["和蒸汽波混淆 → 合成器浪潮更冷硬、有速度感；蒸汽波更软、更迷糊",
              "容易丢掉透视网格 → composition 里明确 perspective grid, receding horizon"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["vaporwave", "cyberpunk", "y2k", "art-deco"],
},
# ---------------------------------------------------------------- 像素艺术
{
 "slug": "pixel-art", "name_zh": "像素艺术", "name_en": "Pixel Art",
 "period": "1980–今", "region": "全球", "tier": "B",
 "one_liner": "每一个像素都是决定：用极少的格子画出可辨识的世界。",
 "core": ["低分辨率网格作为表达媒介而非限制",
          "有限调色板（常 8–32 色）与抖动（dithering）",
          "等距视角（isometric）是经典呈现方式",
          "受 8/16 位游戏时代的硬件限制塑造"],
 "visual": {"色彩": "有限的索引调色板，高饱和且互相呼应；抖动产生中间色",
            "光影": "用色块阶跃表现光照，无渐变；网格对齐的阴影",
            "笔触": "硬边像素方块；轮廓线（outline）常为深色单像素",
            "构图": "等距或正交视角、瓦片（tile）重复、清晰的网格感",
            "材质": "数字像素网格、CRT 扫描线、索引色板",
            "情绪": "怀旧、精确、可爱或紧张（取决于题材）"},
 "palette": [("#2B2B33","轮廓黑"),("#5A6B7A","中灰"),("#7FC8E8","天蓝"),
             ("#5FA85F","草绿"),("#F2C230","亮黄"),("#D98B8B","肤粉")],
 "artists": [("宫本茂团队","1985–"),("Henk Nieborg","1990s"),
             ("Paul Robertson","2000s"),("eBoy","1997–")],
 "prompt": {"style": "pixel art, 16-bit sprite, limited indexed palette, dithering gradients, isometric view, crisp hard-edged pixels, retro game aesthetic",
            "lighting": "stepped colour ramps, no smooth gradient, grid-aligned shadows, dithered transition",
            "color": "restricted palette of 8 to 32 colours, saturated and carefully harmonised",
            "composition": "isometric or orthographic grid, tile repetition, clear silhouette",
            "medium": "digital pixel grid, indexed colour palette, CRT scanlines",
            "mood": "nostalgic, precise, charming or tense depending on subject",
            "camera": "isometric or flat orthographic, no perspective, no depth of field"},
 "negative": "smooth gradient, anti-aliasing, blurry edges, high resolution detail, photorealistic, vector art",
 "video": {"motion": "逐帧动画（低帧率）、瓦片滚动、精灵图切换",
           "camera": "整像素对齐的平移，绝不平滑",
           "note": "像素动画要「卡顿」——低帧率是风格的一部分"},
 "pitfalls": ["AI 会生成伪像素（假方块）→ 加 true pixel grid, no anti-aliasing, hard pixel edges, limited palette",
              "分辨率不统一是最常见问题 → 强调整齐的网格对齐"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["retro-anime", "y2k", "memphis-design"],
},
# ---------------------------------------------------------------- 日式赛璐璐
{
 "slug": "anime-cel", "name_zh": "日式动画赛璐璐", "name_en": "Anime Cel",
 "period": "1980–今", "region": "日本", "tier": "B",
 "one_liner": "平涂色块 + 硬边阴影 + 清晰线稿：一整套被全球模仿的视觉语法。",
 "core": ["赛璐璐上色：色块平涂，阴影是硬边色块",
          "统一的黑色或深色线稿勾边",
          "背景可以是手绘写实，与平涂人物形成对比",
          "眼睛、头发高光有高度程式化的画法"],
 "visual": {"色彩": "明快平涂，肤色统一，头发高光为固定色块",
            "光影": "两级阴影（明/暗）+ 少量高光；阴影边界清晰",
            "笔触": "均匀线稿 + 平涂；无笔触肌理",
            "构图": "角色居中、特写镜头多、背景透视写实",
            "材质": "赛璐璐胶片、数码平涂、手绘水彩背景",
            "情绪": "明亮、情绪化、戏剧性、青春感"},
 "palette": [("#F2C9A8","肤色"),("#3A5A9B","制服蓝"),("#E85D75","高光粉"),
             ("#F2E33D","亮黄"),("#5FA85F","背景绿"),("#1A1A1A","线稿黑")],
 "artists": [("宫崎骏","1941–"),("大友克洋","1954–"),("贞本义行","1962–"),
             ("新海诚","1973–"),("今敏","1963–2010")],
 "prompt": {"style": "anime cel shading, japanese animation cel, flat colour fill with hard-edged shadow blocks, clean line art, hand-painted background",
            "lighting": "two-tone hard shadow, crisp shadow boundary, small specular highlights on hair",
            "color": "bright flat fill, uniform skin tone, fixed hair highlight colour, saturated backgrounds",
            "composition": "character-centred framing, frequent close-ups, realistic painted background perspective",
            "medium": "cel paint on acetate, digital flat fill, watercolour background painting",
            "mood": "bright, emotional, dramatic, youthful",
            "camera": "eye-level, medium close-up, 50mm, slight depth of field on background"},
 "negative": "photorealistic skin, soft gradient shading, oil painting texture, western realistic rendering, 3d render, muddy colour",
 "video": {"motion": "有限的帧数（每 2–3 帧一张）、速度线、定格特写",
           "camera": "快速 pan、突然的推近、夸张的镜头运动",
           "note": "关键在「有限动画」——帧率不足是风格，不是缺陷"},
 "pitfalls": ["AI 会把赛璐璐和像素/3D 混起来 → 明确 flat colour fill, hard-edged shadow blocks, clean line art",
              "背景也要写 hand-painted background，否则人物和环境会脱节"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["retro-anime", "superflat", "ukiyo-e"],
},
# ---------------------------------------------------------------- 复古动画
{
 "slug": "retro-anime", "name_zh": "90 年代复古动画", "name_en": "Retro 90s Anime",
 "period": "1985–1999", "region": "日本", "tier": "B",
 "one_liner": "胶片颗粒、柔和色偏、复杂到过分的机械设定——OVA 时代的质感。",
 "core": ["胶片颗粒与轻微色偏（偏青或偏品红）",
          "高密度机械与城市细节（cyberpunk OVA 传统）",
          "柔和的大气透视与层叠的城市天际线",
          "赛璐璐上色 + 手绘背景的黄金组合"],
 "visual": {"色彩": "偏青的冷调或偏暖的棕调，整体柔和不刺眼",
            "光影": "柔和的自然光 + 霓虹反射；胶片颗粒覆盖全画面",
            "笔触": "线稿略粗，色块平涂；背景极精细",
            "构图": "复杂的城市纵深、机械特写、人物置身巨大环境中",
            "材质": "赛璐璐、手绘背景、35mm 胶片颗粒、CRT 播放质感",
            "情绪": "怀旧、忧郁、都市孤独、科技的诗意"},
 "palette": [("#3A5A6B","冷青"),("#8B5E2A","复古棕"),("#E85D75","霓虹粉"),
             ("#2B2B33","暗影黑"),("#C9A227","窗光黄"),("#5A7A8B","远景蓝")],
 "artists": [("大友克洋《阿基拉》","1988"),("押井守《攻壳机动队》","1995"),
             ("渡边信一郎《星际牛仔》","1998"),("庵野秀明《EVA》","1995")],
 "prompt": {"style": "1990s japanese anime OVA, cel animation with 35mm film grain, detailed hand-painted city background, retro colour cast, cyberpunk urban density",
            "lighting": "soft natural light with neon reflections, atmospheric haze, film grain over everything",
            "color": "cool cyan cast or warm brown cast, muted retro tones, neon accents",
            "composition": "complex urban depth, machinery close-ups, small figure against huge environment",
            "medium": "cel animation, hand-painted background, 35mm film grain, CRT playback",
            "mood": "nostalgic, melancholy, urban solitude, technological poetry",
            "camera": "slow pan across city, eye-level, 35mm, slight grain and softness"},
 "negative": "modern digital anime, crisp 4k, flat vector, oversaturated, clean lines, 3d render",
 "video": {"motion": "有限帧率、缓慢的横向 pan、雨与霓虹的自然运动",
           "camera": "缓慢 pan 展示城市纵深；轻微的胶片抖动",
           "note": "胶片颗粒和色偏是签名——不加就只是普通动画"},
 "pitfalls": ["AI 会画成现代动画 → 加 35mm film grain, retro colour cast, cel animation",
              "容易丢掉背景密度 → 明确 detailed hand-painted city background"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["anime-cel", "cyberpunk", "vaporwave"],
},
# ---------------------------------------------------------------- 黑色电影
{
 "slug": "film-noir", "name_zh": "黑色电影", "name_en": "Film Noir",
 "period": "1940–1958", "region": "美国 / 法国", "tier": "A",
 "one_liner": "黑白、雨夜、百叶窗的影子：道德模糊被拍成了光影结构。",
 "core": ["高对比黑白摄影，大面积死黑",
          "百叶窗、栏杆、烟雾投射的条纹阴影",
          "低角度与倾斜构图（dutch angle）制造不安",
          "蛇蝎美人、私家侦探、注定失败的宿命感"],
 "visual": {"色彩": "纯黑白，极端对比（高光过曝、暗部全黑）",
            "光影": "硬光单源、百叶窗阴影、烟雾中的光柱、霓虹招牌的湿反光",
            "笔触": "不适用——摄影媒介，颗粒感明显",
            "构图": "倾斜构图、低角度、人物被阴影切割、镜子与倒影",
            "材质": "黑白胶片颗粒、湿沥青、烟雾、雨、玻璃",
            "情绪": "宿命、疏离、危险、道德模糊的忧郁"},
 "palette": [("#0A0A0A","死黑"),("#E8E8E8","过曝白"),("#5A5A5A","中灰"),
             ("#2B2B2B","暗灰"),("#8A8A85","烟雾灰"),("#FFFFFF","灯白")],
 "artists": [("约翰·休斯顿","1906–1987"),("比利·怀尔德","1906–2002"),
             ("奥逊·威尔斯","1915–1985"),("尼古拉斯·雷","1911–1979"),
             ("弗里茨·朗","1890–1976")],
 "prompt": {"style": "film noir, 1940s black and white cinematography, chiaroscuro lighting, venetian blind shadows, dutch angle, smoky atmosphere, hardboiled mood",
            "lighting": "single hard key light, blinds stripe shadows, volumetric light through smoke, wet street neon reflection, deep crushed blacks",
            "color": "pure monochrome, extreme contrast, blown highlights, deep black shadows",
            "composition": "tilted dutch angle, low angle, figure sliced by shadow, mirrors and reflections",
            "medium": "35mm black and white film, visible grain, wet asphalt, smoke, rain",
            "mood": "fatalistic, alienated, dangerous, morally ambiguous melancholy",
            "camera": "low angle, dutch tilt, 35mm, deep focus, high contrast"},
 "negative": "colour, bright cheerful lighting, flat even exposure, daylight comedy, pastel, low contrast, modern digital clean",
 "video": {"motion": "烟雾缓慢上升、雨丝斜落、百叶窗阴影扫过脸部、香烟的火光",
           "camera": "缓慢 push in 到脸部，或低角度仰拍；手持轻微",
           "note": "关键是「阴影要动」——百叶窗、风扇、烟雾都是为了让光动起来"},
 "pitfalls": ["AI 会加彩色 → negative 写 colour, 明确 pure monochrome, black and white",
              "对比度不够会变成普通黑白照 → 加 extreme contrast, crushed blacks, blown highlights"],
 "sources": {"cleveland": ["film noir still"], "met": ["film noir photograph"],
             "commons": ["Film noir publicity still"]},
 "see_also": ["ashcan-school", "cyberpunk", "expressionism"],
},
# ---------------------------------------------------------------- 蓝晒法
{
 "slug": "cyanotype", "name_zh": "蓝晒法", "name_en": "Cyanotype",
 "period": "1842–今", "region": "英国 / 全球", "tier": "A",
 "one_liner": "铁盐见光变蓝：世界上第一种让普通人能自己印照片的工艺。",
 "core": ["铁氰化物感光，水洗显影，产生普鲁士蓝",
          "接触印相：物体直接放在纸上曝光（photogram）",
          "蓝白两色，无中间灰或灰调极窄",
          "植物标本、建筑蓝图、人体影像是经典题材"],
 "visual": {"色彩": "普鲁士蓝 + 纸白；单一色相，靠密度区分层次",
            "光影": "接触印相产生的硬边轮廓；无景深概念",
            "笔触": "不适用——涂布痕迹与刷痕会成为画面的一部分",
            "构图": "平面排列（标本式）、建筑蓝图式、对称",
            "材质": "水彩纸、铁盐涂层、手工涂布刷痕、纸纤维",
            "情绪": "科学、怀旧、冷静、植物学的诗意"},
 "palette": [("#0F2A5C","普鲁士蓝深"),("#1F4A8B","标准蓝"),("#4A7AB8","浅蓝"),
             ("#8FAFD0","雾蓝"),("#E8E4DA","纸白"),("#D9CFC0","旧纸黄")],
 "artists": [("安娜·阿特金斯","1799–1871"),("约翰·赫歇尔","1792–1871"),
             ("罗伯特·亚当森","1821–1848")],
 "prompt": {"style": "cyanotype photogram, prussian blue contact print, 19th century alternative photographic process, botanical specimen arrangement, hand-coated paper",
            "lighting": "contact print hard-edged silhouette, no depth, UV exposure",
            "color": "monochrome prussian blue on paper white, density variation only, no other hue",
            "composition": "flat specimen arrangement, blueprint layout, symmetrical placement",
            "medium": "iron salt coated watercolour paper, visible brush coating marks, paper fibre",
            "mood": "scientific, nostalgic, cool, botanical poetry",
            "camera": "flat scan-like frontal, no perspective, edge to edge"},
 "negative": "full colour, glossy photo, digital clean, depth of field, bokeh, warm tones, modern photograph",
 "video": {"motion": "几乎静止；或曝光过程中影像「慢慢浮现」",
           "camera": "static 平面；像翻看标本册",
           "note": "蓝晒的动是「显影」——影像从虚到实的过程"},
 "pitfalls": ["AI 会给整张图加蓝色滤镜但保留照片质感 → 加 contact print, flat silhouette, no depth of field",
              "必须只有蓝白两色 → negative 写 full colour, warm tones"],
 "sources": {"cleveland": ["cyanotype"], "met": ["cyanotype", "anna atkins"],
             "commons": ["Anna Atkins cyanotype photogram"]},
 "see_also": ["wet-plate", "polaroid-film", "wabi-sabi"],
},
# ---------------------------------------------------------------- 湿版摄影
{
 "slug": "wet-plate", "name_zh": "湿版摄影", "name_en": "Wet Plate Collodion",
 "period": "1851–1880", "region": "欧美", "tier": "A",
 "one_liner": "必须在湿润的几分钟内完成曝光：于是每个人都得僵住不动。",
 "core": ["火棉胶湿版工艺，需现场涂布与即时显影",
          "长曝光导致人物姿态僵硬、表情严肃",
          "边缘流痕、化学污渍、暗角是工艺签名",
          "极高的分辨率与独特的银灰调"],
 "visual": {"色彩": "银灰、暗褐、乳白；色调偏冷或偏暖的单一色相",
            "光影": "硬光或柔和的北向光；暗角明显，边缘有化学流痕",
            "笔触": "不适用——涂布不均、尘埃、划痕构成肌理",
            "构图": "肖像多为胸像或全身，正面或四分之三侧，背景素净",
            "材质": "玻璃或黑铝板、火棉胶、银盐、清漆、金属边框",
            "情绪": "庄重、肃穆、时间的重量、被凝固的瞬间"},
 "palette": [("#3A3632","暗褐黑"),("#6B6560","银灰"),("#9A938A","中灰"),
             ("#D9CFC0","乳白"),("#2B2B2B","深影"),("#8B7A5A","旧银黄")],
 "artists": [("弗雷德里克·斯科特·阿彻","1813–1857"),("朱莉娅·玛格丽特·卡梅隆","1815–1879"),
             ("罗杰·芬顿","1819–1869"),("马修·布雷迪","1822–1896")],
 "prompt": {"style": "wet plate collodion photograph, 19th century tintype, long exposure portrait, chemical edge stains, vignetting, silver gelatin tones",
            "lighting": "hard or soft north light, pronounced vignette, uneven chemical flow at edges, long exposure stillness",
            "color": "silver grey, sepia brown, milk white, single monochrome hue",
            "composition": "bust or full-length portrait, frontal or three-quarter, plain background",
            "medium": "collodion on glass or black aluminium, silver salts, varnish, dust and scratches",
            "mood": "solemn, grave, weight of time, arrested moment",
            "camera": "large format, shallow depth of field, slight focus falloff at edges"},
 "negative": "modern colour photo, sharp digital clean, smiling casual pose, bright even lighting, no texture, smartphone look",
 "video": {"motion": "几乎完全静止；人物必须保持不动（长曝光的痕迹）",
           "camera": "static；只能有极轻微的呼吸",
           "note": "湿版的动是「不动的紧张感」——僵住本身就是内容"},
 "pitfalls": ["AI 会做成干净的复古滤镜 → 加 chemical edge stains, vignetting, dust and scratches",
              "人物姿态太自然 → 强调 stiff pose, long exposure stillness"],
 "sources": {"cleveland": ["wet plate collodion", "tintype", "julia margaret cameron"],
             "met": ["wet plate collodion", "tintype photograph", "roger fenton"],
             "commons": ["Wet collodion tintype portrait"]},
 "see_also": ["cyanotype", "polaroid-film", "gothic-subculture"],
},
# ---------------------------------------------------------------- 宝丽来与胶片
{
 "slug": "polaroid-film", "name_zh": "宝丽来与胶片", "name_en": "Polaroid & Film",
 "period": "1948–今", "region": "全球", "tier": "B",
 "one_liner": "不完美的即时感：色偏、漏光、柔焦和一条白边框。",
 "core": ["即时成像的化学色偏（偏青、偏黄或偏品红）",
          "低对比、柔和的过曝白与发灰的黑",
          "漏光、光晕、边缘模糊、白框签名",
          "日常瞬间的私密感与怀旧温度"],
 "visual": {"色彩": "褪色的低饱和色，高光泛黄，暗部发青或发灰",
            "光影": "柔和的过曝高光、光晕、轻微漏光条纹",
            "笔触": "不适用——胶片颗粒与化学不均匀",
            "构图": "随手抓拍、构图松散、白框居中或留白边",
            "材质": "即时相纸、胶片颗粒、化学显影不均",
            "情绪": "亲密、怀旧、温柔、时间的私人纪念"},
 "palette": [("#8FA8B8","青灰"),("#E8D5A8","泛黄高光"),("#C9A8A0","褪色粉"),
             ("#5A6B5A","灰绿"),("#E8E4DA","白框"),("#2B2B33","发灰黑")],
 "artists": [("埃德温·兰德","1909–1991"),("安迪·沃霍尔（宝丽来）","1928–1987"),
             ("荒木经惟","1940–"),("威廉·埃格尔斯顿","1939–")],
 "prompt": {"style": "polaroid instant photo, faded film colour shift, light leak, soft focus, white border frame, 1970s amateur snapshot, grain",
            "lighting": "soft blown highlights, gentle halation glow, light leak streaks, low contrast",
            "color": "desaturated with yellow highlights and cyan shadows, warm faded nostalgia",
            "composition": "casual snapshot framing, loose and unposed, centred subject",
            "medium": "instant film, chemical development unevenness, visible grain, white paper border",
            "mood": "intimate, nostalgic, tender, private memory",
            "camera": "point and shoot, 35mm equivalent, slight softness, direct flash possible"},
 "negative": "sharp digital, high contrast, HDR, colour graded modern, studio lighting, crisp detail",
 "video": {"motion": "轻微的手持晃动、缓慢的焦点漂移",
           "camera": "handheld home-movie style；不要稳定的滑轨",
           "note": "胶片感的动是「不完美的手持」，稳定运镜会杀掉它"},
 "pitfalls": ["AI 会做成「复古滤镜」但太干净 → 加 light leak, halation, grain, chemical unevenness",
              "白框是宝丽来的签名 → 明确 white border frame"],
 "sources": {"cleveland": ["polaroid photograph"], "met": ["polaroid photograph"],
             "commons": ["Polaroid instant photograph"]},
 "see_also": ["cyanotype", "wet-plate", "cottagecore", "dreamcore"],
},
# ---------------------------------------------------------------- 侘寂
{
 "slug": "wabi-sabi", "name_zh": "侘寂", "name_en": "Wabi-Sabi",
 "period": "1400–今", "region": "日本", "tier": "B",
 "allow_3d": True,
 "one_liner": "美在残缺与无常：裂缝、锈迹、不对称，和一件被用旧了的器物。",
 "core": ["侘（简素孤寂）+ 寂（时间侵蚀的痕迹）",
          "不对称、不完美、不完整、不做作",
          "金缮（kintsugi）：用金修补裂缝，让伤痕成为亮点",
          "朴素材质与自然老化"],
 "visual": {"色彩": "极低饱和的土色：灰褐、苔绿、铁锈、褪色的米白",
            "光影": "柔和的自然侧光，强调肌理的凹凸；留出深沉的阴影",
            "笔触": "材质本身即笔触：陶土颗粒、木纹、锈斑、裂痕",
            "构图": "极简、不对称、大量留白、单一器物居中或偏侧",
            "材质": "粗陶、生锈铁器、风化木、麻布、和纸、金缮漆",
            "情绪": "静、寂、谦逊、时间带来的温柔"},
 "palette": [("#8A7A6A","灰褐"),("#6B7A5A","苔绿"),("#A8432A","铁锈"),
             ("#D9CFC0","褪米白"),("#C9A227","金缮"),("#3A3632","深影")],
 "artists": [("千利休","1522–1591"),("日本陶艺家","16–20世纪"),
             ("河井宽次郎","1890–1966"),("滨田庄司","1894–1978")],
 "prompt": {"style": "wabi-sabi aesthetic, japanese rustic simplicity, kintsugi gold repair, weathered and imperfect object, coarse ceramic texture, asymmetric minimalism",
            "lighting": "soft natural side light revealing texture, deep quiet shadow, no drama",
            "color": "very low saturation earth tones, grey brown, moss green, rust, faded cream",
            "composition": "extremely minimal, asymmetric, generous empty space, single object",
            "medium": "coarse stoneware, rusted iron, weathered wood, linen, washi paper, urushi lacquer",
            "mood": "quiet, solitary, humble, tenderness of time",
            "camera": "close-up, 50mm, shallow depth of field, soft natural light"},
 "negative": "glossy, pristine, symmetrical, saturated colour, plastic, new and shiny, busy composition",
 "video": {"motion": "几乎静止；光缓慢扫过器物表面、蒸汽升起",
           "camera": "static 特写，极缓 dolly in",
           "note": "侘寂的动是「光在肌理上爬行」，慢到几乎察觉不到"},
 "pitfalls": ["AI 会加光泽和新感 → negative 写 glossy, pristine, new and shiny",
              "容易变成普通静物 → 加 kintsugi, weathered, imperfect, asymmetric"],
 "sources": {"cleveland": ["japanese tea bowl", "wabi sabi"], "met": ["japanese tea bowl raku"],
             "commons": ["Japanese tea bowl Raku", "Kintsugi repaired bowl", "Japanese wabi sabi ceramic"]},
 "see_also": ["suiboku-ga", "ink-wash-xieyi", "minimalist-design"],
},
# ---------------------------------------------------------------- 极简设计
{
 "slug": "minimalist-design", "name_zh": "极简主义设计", "name_en": "Minimalist Design",
 "period": "1960–今", "region": "全球", "tier": "B",
 "one_liner": "去掉所有能去掉的：一点颜色、一个形状、大量空白。",
 "core": ["功能优先，装饰被系统性移除",
          "大量负空间是构图的主体",
          "有限的字体与色彩系统",
          "精确的对齐与网格"],
 "visual": {"色彩": "一到两个主色 + 大量白/灰；低饱和或单一强调色",
            "光影": "极柔和或完全无阴影的均匀光",
            "笔触": "零笔触；矢量般的干净边缘",
            "构图": "大量留白、严格对齐、单一视觉焦点",
            "材质": "哑光纸、无衬线字体、平滑表面、浅色木材",
            "情绪": "冷静、清晰、克制、高级感"},
 "palette": [("#FFFFFF","纯白"),("#F2F0EC","暖白"),("#D9D5CC","浅灰"),
             ("#8A8A85","中灰"),("#1A1A1A","近黑"),("#C9A227","单一强调色")],
 "artists": [("迪特·拉姆斯","1932–"),("深泽直人","1956–"),
             ("原研哉","1958–"),("乔纳森·艾维","1967–")],
 "prompt": {"style": "minimalist design, extreme negative space, single focal object, neutral restrained palette, precise alignment, matte finish",
            "lighting": "very soft or completely shadowless even illumination, no drama",
            "color": "one or two neutrals plus a single accent, off-white, light grey, near black",
            "composition": "vast empty space, strict alignment, one visual focus, generous margins",
            "medium": "matte paper, sans serif type, smooth surface, pale wood",
            "mood": "calm, clear, restrained, quiet sophistication",
            "camera": "flat frontal, centred, generous framing"},
 "negative": "clutter, ornament, many colours, gradient, texture noise, busy pattern, decoration, drop shadow",
 "video": {"motion": "元素的极简位移或淡入；克制而精确",
           "camera": "static 或极缓的直线平移",
           "note": "极简设计的动要「几乎没有」，靠时间而非运动"},
 "pitfalls": ["AI 会自动填满画面 → negative 写 clutter, ornament, busy pattern",
              "留白不足是最常见问题 → 强调 vast empty space, generous margins"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["swiss-style", "minimalism-art", "wabi-sabi", "bauhaus"],
},
# ---------------------------------------------------------------- 瑞士国际主义
{
 "slug": "swiss-style", "name_zh": "瑞士国际主义", "name_en": "Swiss Style",
 "period": "1950–1970", "region": "瑞士", "tier": "B",
 "one_liner": "网格、无衬线、左对齐、大留白：现代平面设计的语法基础。",
 "core": ["数学化的网格系统（grid system）",
          "无衬线字体（Helvetica、Univers）为主角",
          "非对称但严格对齐的版面",
          "客观、去个人化的信息传达"],
 "visual": {"色彩": "通常黑白 + 一个高纯度强调色（红最常见）",
            "光影": "无光影，纯平面印刷",
            "笔触": "零笔触；印刷与摄影拼贴",
            "构图": "严格网格、左对齐、大面积留白、字号层级分明",
            "材质": "胶版印刷、哑光或光面纸、摄影拼贴",
            "情绪": "客观、理性、精确、现代主义的中立"},
 "palette": [("#111111","黑"),("#FFFFFF","白"),("#D32027","瑞士红"),
             ("#8A8A85","灰"),("#F2F0EC","纸白"),("#1B4F9C","蓝")],
 "artists": [("约瑟夫·米勒-布罗克曼","1914–1996"),("马克斯·比尔","1908–1994"),
             ("扬·奇肖尔德","1902–1974"),("阿明·霍夫曼","1920–2020")],
 "prompt": {"style": "swiss international typographic style, mathematical grid layout, helvetica sans serif, asymmetric but strictly aligned, objective modernist poster",
            "lighting": "flat print, no shadow",
            "color": "black and white with one high purity accent, usually red",
            "composition": "strict modular grid, left aligned, large white space, clear typographic hierarchy",
            "medium": "offset lithograph, matte or gloss paper, photographic collage",
            "mood": "objective, rational, precise, modernist neutrality",
            "camera": "flat orthographic, no perspective"},
 "negative": "decorative ornament, hand lettering, centred symmetry, many fonts, gradient, clutter, retro flourish",
 "video": {"motion": "网格元素精确位移、文字逐行出现",
           "camera": "static 平面；版式动画",
           "note": "瑞士风格的动必须精确到网格——任何随意都是错的"},
 "pitfalls": ["AI 会加装饰元素 → negative 写 decorative ornament, hand lettering, clutter",
              "网格必须是真的 → 加 mathematical grid, strict alignment, modular"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["bauhaus", "minimalist-design", "constructivism"],
},
# ---------------------------------------------------------------- 孟菲斯
{
 "slug": "memphis-design", "name_zh": "孟菲斯设计", "name_en": "Memphis Design",
 "period": "1981–1988", "region": "意大利", "tier": "B",
 "one_liner": "80 年代的反叛设计：故意难看、故意冲突、故意不像设计。",
 "core": ["刻意打破现代主义的规则与品味",
          "几何形状随意拼贴：波浪、圆点、三角、锯齿",
          "高饱和撞色，故意不协调",
          "塑料层压板、廉价材质被赋予设计价值"],
 "visual": {"色彩": "高饱和撞色：粉、青、黄、黑、白粗暴并置",
            "光影": "无光影，纯平面图形",
            "笔触": "零笔触；几何图形与图案填充",
            "构图": "元素散落、不对称、刻意的拥挤与失衡",
            "材质": "塑料层压板、水磨石、霓虹灯管、金属网格",
            "情绪": "玩闹、挑衅、乐观、故意的廉价感"},
 "palette": [("#F23D8E","粉"),("#29D6E8","青"),("#F2E33D","黄"),
             ("#111111","黑"),("#FFFFFF","白"),("#7B3FA0","紫")],
 "artists": [("埃托雷·索特萨斯","1917–2007"),("孟菲斯集团","1981–1988"),
             ("娜塔莉·杜帕斯基耶","1957–"),("马蒂内·贝丁","1952–")],
 "prompt": {"style": "memphis design, 1980s postmodern italian design, clashing geometric shapes, squiggles and dots and zigzags, deliberately kitsch, laminated plastic surface",
            "lighting": "flat graphic, no shadow",
            "color": "high saturation clashing, pink, cyan, yellow, black and white, deliberately uncoordinated",
            "composition": "scattered asymmetric elements, crowded and off-balance, playful",
            "medium": "plastic laminate, terrazzo, neon tube, metal grid",
            "mood": "playful, provocative, optimistic, deliberately cheap",
            "camera": "flat frontal, product-shot framing"},
 "negative": "tasteful restrained palette, symmetry, minimalism, natural materials, muted tones, classic elegance",
 "video": {"motion": "几何形状跳跃、旋转、突然换色",
           "camera": "static 或轻快的跳切",
           "note": "孟菲斯的动应该「活泼到有点吵」"},
 "pitfalls": ["AI 会把它做得太协调 → negative 写 tasteful restrained palette, symmetry, 加 deliberately uncoordinated",
              "80 年代不是孟菲斯的全部 → 强调 geometric shapes, squiggles, laminate"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["y2k", "vaporwave", "pop-art"],
},
# ---------------------------------------------------------------- 暗黑学院
{
 "slug": "dark-academia", "name_zh": "暗黑学院", "name_en": "Dark Academia",
 "period": "2015–今", "region": "网络文化（英美想象）", "tier": "B",
 "one_liner": "秋日、古籍、烛光与哥特建筑：对知识与忧郁的浪漫化想象。",
 "core": ["老图书馆、哥特建筑、秋日落叶的固定场景",
          "烛光、台灯、壁炉的暖色小光源",
          "古典学、诗歌、拉丁文、手写信件的符号系统",
          "忧郁、求知、略带病态的美学"],
 "visual": {"色彩": "深棕、墨绿、酒红、暗金、米黄纸；低明度暖调",
            "光影": "单一暖光源（烛/台灯/壁炉），周围沉入阴影",
            "笔触": "摄影或厚涂古典油画式，追求材质感",
            "构图": "室内静物（书、蜡烛、咖啡）、对称的图书馆纵深",
            "材质": "皮革书脊、羊皮纸、粗呢大衣、橡木、黄铜",
            "情绪": "忧郁、博学、私密、秋日的浪漫"},
 "palette": [("#3A2A1A","深棕"),("#2B3A2A","墨绿"),("#6B1F2B","酒红"),
             ("#C9A227","暗金"),("#D9CFC0","纸黄"),("#1A1512","烛影黑")],
 "artists": [("《死亡诗社》视觉组","1989"),("《故园风雨后》","1981"),
             ("唐娜·塔特《校园秘史》","1992")],
 "prompt": {"style": "dark academia aesthetic, gothic university library, candlelit study, antique leather books, autumn melancholy, warm chiaroscuro interior",
            "lighting": "single warm candle or desk lamp source, deep surrounding shadow, fireplace glow, dust motes",
            "color": "dark brown, forest green, burgundy, antique gold, aged paper cream, low key warm",
            "composition": "interior still life with books and candles, symmetric library depth, cluttered desk",
            "medium": "photographic realism or classical oil painting, leather, parchment, tweed, oak, brass",
            "mood": "melancholic, scholarly, intimate, autumnal romance",
            "camera": "eye-level, medium shot, 50mm, shallow depth of field, warm white balance"},
 "negative": "modern office, fluorescent light, plastic, bright daylight, minimalism, neon, contemporary casual clothing",
 "video": {"motion": "烛火摇曳、翻书页、尘埃在光柱中漂浮",
           "camera": "缓慢 dolly in 穿过书架；手持轻微",
           "note": "光源必须只有一个且是暖的——多光源会破坏氛围"},
 "pitfalls": ["AI 会加现代元素 → negative 写 modern office, fluorescent light, plastic",
              "容易变成普通暖调室内 → 加 candlelit, gothic library, antique leather books"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["gothic-subculture", "wet-plate", "tonalism"],
},
# ---------------------------------------------------------------- 田园风
{
 "slug": "cottagecore", "name_zh": "田园风", "name_en": "Cottagecore",
 "period": "2018–今", "region": "网络文化", "tier": "B",
 "one_liner": "逃离城市：野花、家酿、亚麻裙和一间被阳光照亮的小屋。",
 "core": ["乡村自给自足的理想化生活",
          "野花、蔬果、手工烘焙、家酿的静物符号",
          "柔和的自然光与植物繁茂的环境",
          "慢生活、手工艺、季节性的仪式感"],
 "visual": {"色彩": "柔和的自然色：草绿、奶油黄、干花紫、砖红；低对比",
            "光影": "柔和的窗光或林间斑驳光，明亮但不刺眼",
            "笔触": "摄影或柔和的插画风格，轻微颗粒感",
            "构图": "静物铺陈、花园中景、室内窗边场景",
            "材质": "亚麻、藤编、粗陶、干花、木质台面、野餐布",
            "情绪": "温柔、宁静、怀旧、被治愈的安全感"},
 "palette": [("#8FA85F","草绿"),("#F2E0B8","奶油黄"),("#B08BA8","干花紫"),
             ("#A8432A","砖红"),("#E8E4DA","亚麻白"),("#C9A227","麦黄")],
 "artists": [("碧雅翠丝·波特（先声）","1866–1943"),("塔莎·杜朵","1915–2008"),
             ("网络田园社群","2018–")],
 "prompt": {"style": "cottagecore aesthetic, idyllic rural life, wildflower still life, linen and wicker, sunlit cottage interior, handmade and homegrown",
            "lighting": "soft window light or dappled forest light, bright but gentle, warm and diffused",
            "color": "soft natural palette, grass green, cream yellow, dried flower purple, brick red, low contrast",
            "composition": "still life spread, garden middle ground, window-side interior scene",
            "medium": "photographic or soft illustration, linen, wicker, coarse pottery, dried flowers, wood",
            "mood": "gentle, peaceful, nostalgic, healing safety",
            "camera": "eye-level, medium shot, 50mm, soft focus, warm tone"},
 "negative": "urban, industrial, neon, plastic, harsh lighting, modern technology, concrete, high contrast",
 "video": {"motion": "微风吹动野花、窗帘飘动、搅拌面糊的手",
           "camera": "static 生活片段，或极缓 handheld",
           "note": "田园风的动必须「慢而温柔」，不要任何戏剧性"},
 "pitfalls": ["AI 会加城市元素 → negative 写 urban, industrial, neon, modern technology",
              "容易变成普通乡村照 → 加 handmade, homegrown, wildflower still life, linen"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["solarpunk", "dark-academia", "polaroid-film"],
},
# ---------------------------------------------------------------- 废土
{
 "slug": "wasteland", "name_zh": "废土风", "name_en": "Wasteland",
 "period": "1979–今", "region": "全球", "tier": "B",
 "one_liner": "文明之后：锈蚀的巨构、沙尘、改装车和用垃圾拼出的生存。",
 "core": ["后末日废墟：锈蚀金属、残破混凝土",
          "沙尘、热浪、褪色曝晒的色调",
          "拼凑改装（scavenged）的装备与载具",
          "孤独的幸存者在巨大废墟中的渺小感"],
 "visual": {"色彩": "土黄、铁锈橙、灰褐、褪色的天蓝；低饱和高灰尘感",
            "光影": "刺眼的直射阳光 + 沙尘散射；长阴影，无柔和过渡",
            "笔触": "概念设定为粗粝厚涂，可见刮痕",
            "构图": "巨构废墟压迫、极远地平线、小人物站在开阔荒地",
            "材质": "锈蚀钢、破损混凝土、帆布、皮革、沙尘、废弃塑料",
            "情绪": "荒凉、坚韧、孤独、粗粝的史诗感"},
 "palette": [("#C98A4A","土黄"),("#A8432A","铁锈橙"),("#8A7A6A","灰褐"),
             ("#7FA8C8","褪色天蓝"),("#3A3632","焦黑"),("#D9CFC0","沙白")],
 "artists": [("乔治·米勒《疯狂的麦克斯》","1979–"),("《辐射》美术组","1997–"),
             ("《沙丘》视觉团队","2021"),("Ian McQue","2000s")],
 "prompt": {"style": "post-apocalyptic wasteland, rusted megastructure ruins, scavenged improvised vehicle, dust storm, harsh survival, gritty concept art",
            "lighting": "blistering direct sun through dust haze, long hard shadows, no soft fill, orange atmospheric scattering",
            "color": "dust ochre, rust orange, grey brown, faded sky blue, desaturated and dusty",
            "composition": "looming ruins, extreme distant horizon, tiny figure in vast open waste",
            "medium": "digital concept painting, rusted steel, cracked concrete, canvas, leather, sand",
            "mood": "desolate, resilient, lonely, gritty epic",
            "camera": "extreme wide, low angle, 24mm, deep focus, dusty lens"},
 "negative": "clean modern city, lush greenery, bright cheerful, polished surfaces, neon, minimalism, pristine",
 "video": {"motion": "沙尘暴推进、布条狂舞、载具扬起尘土",
           "camera": "缓慢 crane up 揭示废墟规模；手持跟拍",
           "note": "尺度对比是关键——小人物 + 巨大废墟"},
 "pitfalls": ["AI 会画得太干净 → 加 rust, dust, cracked, scavenged, improvised",
              "容易丢掉尺度感 → composition 写 tiny figure, vast open waste, looming ruins"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["dieselpunk", "cyberpunk", "land-art"],
},
# ---------------------------------------------------------------- 哥特亚文化
{
 "slug": "gothic-subculture", "name_zh": "哥特亚文化", "name_en": "Gothic Subculture",
 "period": "1979–今", "region": "英美 / 全球", "tier": "B",
 "one_liner": "黑色蕾丝、教堂废墟、苍白皮肤：把维多利亚的丧服穿成态度。",
 "core": ["黑色主导，配以深红、紫与银",
          "维多利亚丧服与宗教符号的再挪用",
          "蕾丝、束腰、皮革、十字架、玫瑰",
          "浪漫化的死亡、忧郁与异教神秘主义"],
 "visual": {"色彩": "黑 + 深红/深紫/银白；高对比低饱和",
            "光影": "硬光单源、逆光剪影、蜡烛与月光",
            "笔触": "摄影或精细插画；材质反差强烈",
            "构图": "中心主体、教堂废墟或墓园环境、戏剧性姿态",
            "材质": "蕾丝、天鹅绒、皮革、银饰、蜡烛、石刻",
            "情绪": "忧郁、浪漫、神秘、戏剧性的自我呈现"},
 "palette": [("#0F0F12","黑"),("#6B1F2B","深红"),("#3A2A4A","深紫"),
             ("#B8B8B8","银"),("#E8E4DA","苍白"),("#8B1A2A","血红")],
 "artists": [("《吸血鬼》电影视觉","1980s"),("爱德华·戈里","1925–2000"),
             ("奥布里·比亚兹莱（先声）","1872–1898"),("哥特乐队视觉","1980s")],
 "prompt": {"style": "gothic subculture aesthetic, victorian mourning dress, black lace and velvet, cathedral ruins, romantic melancholy, silver religious ornament",
            "lighting": "single hard light source, backlit silhouette, candle and moonlight, deep shadow",
            "color": "black dominant with deep crimson, dark violet, silver, pallid skin",
            "composition": "centred figure, ruined church or graveyard setting, dramatic pose",
            "medium": "photographic or fine illustration, lace, velvet, leather, silver, wax, carved stone",
            "mood": "melancholic, romantic, mysterious, theatrical self-presentation",
            "camera": "eye-level, medium shot, 85mm, shallow depth of field, high contrast"},
 "negative": "bright cheerful pastel, daylight beach, sports clothing, minimalist modern interior, saturated warm, casual",
 "video": {"motion": "裙摆与面纱飘动、烛火摇曳、缓慢转身",
           "camera": "缓慢 arc 环绕，或 static 逆光剪影",
           "note": "哥特的动要「仪式化」——缓慢、有姿态感"},
 "pitfalls": ["和哥特式艺术混淆 → 哥特式是 12–15 世纪的建筑与绘画；哥特亚文化是 1980 年后的次文化",
              "AI 会加现代休闲元素 → negative 写 bright cheerful, sports clothing, casual"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["gothic", "dark-academia", "symbolism", "wet-plate"],
},
# ---------------------------------------------------------------- 梦核
{
 "slug": "dreamcore", "name_zh": "梦核", "name_en": "Dreamcore",
 "period": "2018–今", "region": "网络文化", "tier": "B",
 "one_liner": "熟悉但不对：空荡的泳池、无限的走廊，像一段记不清的童年。",
 "core": ["阈限空间（liminal space）：空无一人的过渡场所",
          "似曾相识却无法定位的怀旧感",
          "低分辨率、过度压缩、过曝或褪色的影像质感",
          "温和的不安，而非恐怖"],
 "visual": {"色彩": "褪色、过曝、色偏：泳池蓝、地毯红、日光灯黄",
            "光影": "均匀的荧光灯 / 无源的柔光，没有明确时间",
            "笔触": "低分辨率数码影像、JPEG 压缩痕迹、噪点",
            "构图": "空荡的对称室内、无限的走廊与门、无人泳池",
            "材质": "瓷砖、地毯、日光灯、旧墙纸、水面",
            "情绪": "怀旧的恍惚、温和的不安、梦的失重"},
 "palette": [("#7FC8E8","泳池蓝"),("#A8432A","地毯红"),("#F2E0B8","日光灯黄"),
             ("#8FA88F","褪绿"),("#E8E4DA","过曝白"),("#5A5A6A","压缩灰")],
 "artists": [("阈限空间社群","2019–"),("Kane Pixels（后室）","2022"),
             ("网络梦核创作者","2018–")],
 "prompt": {"style": "dreamcore, liminal space, empty swimming pool, endless corridor, faded nostalgic interior, low resolution digital image, unsettling familiarity",
            "lighting": "flat fluorescent or sourceless ambient glow, no time of day, slightly overexposed",
            "color": "faded and colour shifted, pool blue, carpet red, fluorescent yellow, washed out",
            "composition": "empty symmetrical interior, infinite hallway of doors, nobody present",
            "medium": "low resolution digital photograph, jpeg compression artefacts, noise, old wallpaper, tile",
            "mood": "nostalgic haze, gentle unease, weightless dream logic",
            "camera": "eye-level, wide, slightly crooked, low resolution"},
 "negative": "high resolution sharp, people present, dramatic lighting, vibrant saturated, horror gore, detailed texture",
 "video": {"motion": "缓慢向前漂移穿过走廊、水面静止微澜",
           "camera": "极缓向前推进；画面偶尔的噪声抖动",
           "note": "梦核的动是「梦里的漂移」——没有人，只有空间"},
 "pitfalls": ["AI 会画得太清晰太美 → 加 low resolution, jpeg artefacts, washed out, no people",
              "容易变成恐怖片 → 强调 gentle unease, not horror"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["vaporwave", "polaroid-film", "surrealism"],
},
# ---------------------------------------------------------------- Y2K
{
 "slug": "y2k", "name_zh": "Y2K 千禧美学", "name_en": "Y2K Aesthetic",
 "period": "1997–2004", "region": "全球", "tier": "B",
 "one_liner": "对未来的乐观想象：透明塑料、铬、泡泡字体和亮蓝色。",
 "core": ["千禧年对未来科技的乐观与天真",
          "透明塑料、镀铬、果冻质感的材质崇拜",
          "亮蓝、银、白、荧光色；高光泽",
          "泡泡字体、圆角界面、早期数码图形"],
 "visual": {"色彩": "亮蓝、银白、荧光绿/粉；高光泽高饱和",
            "光影": "强烈的镜面高光、彩虹色折射、bloom 光晕",
            "笔触": "零笔触；3D 渲染、金属渐变、透明材质",
            "构图": "居中产品式、漂浮元素、圆角几何",
            "材质": "透明塑料、镀铬、果冻橡胶、全息膜、iMac 彩色外壳",
            "情绪": "乐观、闪亮、天真、科技乌托邦的亢奋"},
 "palette": [("#29D6E8","亮蓝"),("#C9CFD4","铬银"),("#A8F23D","荧光绿"),
             ("#F23D8E","荧光粉"),("#FFFFFF","白"),("#7B3FA0","全息紫")],
 "artists": [("iMac G3 设计团队","1998"),("《黑客帝国》视觉组","1999"),
             ("未来石（Frutiger Aero 先声）","2004"),("千禧平面设计","2000")],
 "prompt": {"style": "y2k aesthetic, millennial futurism, transparent plastic and chrome, glossy 3d render, bubble typography, holographic iridescence, early 2000s tech optimism",
            "lighting": "strong specular highlights, rainbow refraction, heavy bloom glow, studio product light",
            "color": "bright blue, silver white, fluorescent green and pink, high gloss high saturation",
            "composition": "centred product framing, floating elements, rounded geometry",
            "medium": "3d render, transparent plastic, chrome, jelly rubber, holographic film",
            "mood": "optimistic, shiny, naive, dot-com utopian excitement",
            "camera": "flat frontal product shot, slight wide angle, bloom"},
 "negative": "muted matte surfaces, gritty grunge texture, dark dystopian mood, minimalist restraint, natural materials, vintage analogue warmth",
 "video": {"motion": "元素旋转展示、金属表面流动反光、泡泡浮现",
           "camera": "环绕产品的 turntable 镜头",
           "note": "Y2K 的动是「产品展示式的旋转」，光亮而机械"},
 "pitfalls": ["AI 会做得太暗太现代 → negative 写 dark dystopian, matte, gritty, 加 glossy, bloom, chrome",
              "和蒸汽波混淆 → Y2K 更亮、更乐观、更产品化；蒸汽波更暗、更反讽"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["vaporwave", "memphis-design", "pixel-art", "synthwave"],
},
]

ARTIST_KEYS = {
 "steampunk": ["steampunk", "verne", "wells", "mckie", "gurney"],
 "dieselpunk": ["dieselpunk", "diesel", "interwar", "retro-futuris"],
 "solarpunk": ["solarpunk", "eco-futuris", "schuiten"],
 "biopunk": ["biopunk", "cronenberg", "giger", "bio-art"],
 "vaporwave": ["vaporwave", "macintosh plus", "vektroid", "2814"],
 "synthwave": ["synthwave", "outrun", "retrowave", "kavinsky"],
 "pixel-art": ["pixel art", "sprite", "isometric pixel", "eboy"],
 "anime-cel": ["anime", "cel", "miyazaki", "kon", "shinkai", "sadamoto"],
 "retro-anime": ["akira", "ghost in the shell", "cowboy bebop", "eva", "ova"],
 "film-noir": ["film noir", "noir", "huston", "welles", "lang", "bogart"],
 "cyanotype": ["cyanotype", "atkins", "herschel", "photogram", "blueprint"],
 "wet-plate": ["wet plate", "collodion", "tintype", "ambrotype", "cameron",
                "fenton", "brady", "daguerreotype"],
 "polaroid-film": ["polaroid", "instant film", "land", "araki", "eggleston"],
 "wabi-sabi": ["wabi", "sabi", "raku", "tea bowl", "chawan", "kintsugi", "hamada",
               "kawai", "stoneware", "ceramic", "japanese bowl", "tea caddy", "mizusashi"],
 "minimalist-design": ["rams", "naoto", "fukasawa", "kenya hara", "minimalis"],
 "swiss-style": ["swiss", "muller-brockmann", "müller-brockmann", "bill", "tschichold",
                  "hofmann", "helvetica", "international typographic"],
 "memphis-design": ["memphis", "sottsass", "dupasquier", "bedin", "postmodern design"],
 "dark-academia": ["dark academia", "academia", "gothic library"],
 "cottagecore": ["cottagecore", "potter", "tasha tudor", "cottage garden"],
 "wasteland": ["wasteland", "post-apocalyp", "mad max", "fallout", "dune", "mcque"],
 "gothic-subculture": ["gothic", "goth", "victorian mourning", "gorey", "beardsley"],
 "dreamcore": ["dreamcore", "liminal", "backrooms", "poolrooms"],
 "y2k": ["y2k", "millennium", "frutiger", "imac", "holograph"],
}
