#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
reverse_prompt.py —— 把一张图的**反推结果**组装成一张卡。

## 为什么要有这个模块

用户的期待是：「上传一张图 → 打开那张图的卡 → 反推已经跑完了，提示词就在那儿」。

所以反推不该是「给你一份工具清单、你自己去装」——那是管道，不是终点。
反推应该是**图进库时自动跑的一个动作**，产物落在图自己的卡上。

这个模块负责：
  1. `record()`  —— 图进库时，把测量与匹配结果存成清单记录（扫描与投递箱共用）
  2. `compose()` —— 由记录 + 匹配到的流派，组装出那张卡的正文

## 反推出来的东西分两类，卡上会分开标

**算得出来的**（客观、可复现，不用模型）：
    七维测量、主色、CLIP 流派匹配、配色、按流派组好的七层提示词、两块视频提示词

**算不出来的**：
    主体是什么（「一个穿红裙子的女人站在窗边」）。
    这需要图像描述模型。实测过 `vit-gpt2` 量化版约 230MB 可行，但它对绘画的
    描述质量很差（只会给「a painting of a man in a suit」这种），
    而 AI 直接 `read_image` 看图比它准得多。
    所以**不引入描述模型**，主体一栏留空 —— 卡上明确标出来，不假装填好了。

## 每层的「来源」要标清楚

七层不是模型生成的，是**从匹配到的流派卡里取的**（那 141 张卡的七层是手写的，
比任何模型的输出可靠）。卡上每一层都标了它来自哪张卡，以及这张图实测下来
和那个流派的典型值差在哪 —— 这样你能看出「为什么这么写」，而不是一个黑箱。
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

LAYER_ORDER = [("style", "风格"), ("lighting", "光照"), ("color", "色彩"),
               ("composition", "构图"), ("medium", "媒介"), ("mood", "情绪"),
               ("camera", "镜头")]

def record(path, analysis, suggest=None, source=None, extra=None):
    """组装一条清单记录。扫描与投递箱归档共用这一份。

    存**完整的分析结果**而不是摘要 —— 卡是事后由 build_vault 生成的，
    那时图已经不在原处了，摘要不够用。
    """
    # 两个调用点的 suggest 形状不一样：scan_local 给的是 (slug, name, score)
    # 元组，ingest_inbox 给的是 {"slug","name","score"} 字典（那是
    # ingest_inbox.suggest() 的返回格式）。实测直接按元组解包会炸
    # （TypeError: type str doesn't define __round__ method），
    # 所以这里两种都收 —— 比在两个调用点各转一次更不容易再错。
    sug = []
    for x in (suggest or []):
        if isinstance(x, dict):
            sug.append({"slug": x.get("slug"), "name": x.get("name"),
                        "score": round(float(x.get("score") or 0), 3)})
        else:
            s_, n_, sc_ = x
            sug.append({"slug": s_, "name": n_, "score": round(float(sc_), 3)})
    rec = {
        "file": os.path.basename(path),
        "source": source or path,
        "added_at": None,                      # 由调用方填
        "size": (analysis or {}).get("size"),
        "orientation": (analysis or {}).get("orientation"),
        "analysis": analysis,
        "suggest": sug,
    }
    if extra:
        rec.update(extra)
    return rec


def _fmt_kv(v, unit="", nd=1):
    try:
        return ("%%.%df%s" % (nd, unit)) % float(v)
    except Exception:
        return str(v)


def video_blocks(rec, mv):
    """视频提示词：优先给**这张图的**（i2v），退回到流派通用版。

    为什么要有这个选择：流派通用版的主体行是占位符 `<你的主体>`，换一张
    同流派的图内容完全一样 —— 而使用者手里正拿着这张图。图的景别、位置、
    线条动势、明暗结构早就测出来了（存在 rec["analysis"] 里），
    没有理由不填进去。

    返回 (dict, 是否是这张图的)；都给不出来时返回 (None, False)。
    """
    ana = (rec or {}).get("analysis") or {}
    if ana and not ana.get("error"):
        try:
            import i2v_prompt as I2V
            return I2V.build(mv, ana), True
        except Exception as e:
            # 不让 i2v 的失败拖垮整张卡，但要**说出来** ——
            # 原来这里是 `except Exception: pass`，视频块会凭空消失，
            # 读卡的人只会以为「这个流派没有视频提示词」。
            print("  ! i2v 生成失败，退回流派通用版：%s: %s" % (type(e).__name__, e))
    try:
        import video_prompt as VP
        return VP.build(mv), False
    except Exception as e:
        print("  ! 视频提示词生成失败：%s: %s" % (type(e).__name__, e))
        return None, False


def compose(rec, mv, image_name, back=None):
    """把一条记录 + 匹配到的流派，组装成那张图的卡。

    mv 可以是 None（CLIP 没给出建议、或用户归到了 _未归类）——
    那样就只给客观测量，不给七层，并明确说明为什么。
    """
    a = rec.get("analysis") or {}
    L = ["---",
         "# auto-generated by build_vault.py —— 本文件由脚本生成，重跑会覆盖",
         "type: 我的图片",
         "图片: %s" % image_name,
         "流派: %s" % (mv["name_zh"] if mv else "未归类"),
         "加入: %s" % (rec.get("added_at") or ""),
         "标签:",
         "  - 反推",
         "  - 我的图库",
         "---", "",
         "# %s" % (rec.get("title") or image_name), "",
         "![[%s]]" % image_name, ""]

    # ---- 反推结论放在最前面：打开卡就看到 ----
    sug = rec.get("suggest") or []
    if mv:
        L += ["> [!abstract] 反推结果",
              "> 这张图进库时已经跑完反推。结论：**最接近 [[%s]]**%s。" % (
                  mv["name_zh"],
                  ("（CLIP 融合分 %.2f）" % sug[0]["score"]) if sug else ""),
              ">",
              "> 下面的七层提示词是**按那张流派卡的层**组好的（141 张卡的七层是手写的，",
              "> 比模型生成可靠），每一层都标了它来自哪里。",
              ">",
              "> **只有「主体」一栏是空的** —— 画面里具体画了什么，需要「看图」才知道。",
              "> 让 AI 看一眼这张图填进去，或你自己写。", ""]
    else:
        L += ["> [!warning] 还没归类",
              "> CLIP 没给出有把握的建议，所以这张图**只做了客观测量，没有组七层**。",
              "> 归类之后会自动补上：",
              ">",
              "> ```bash",
              "> python3 .repo/scan_local.py --list",
              "> python3 .repo/scan_local.py --file <编号> --to <流派>",
              "> python3 build_vault.py",
              "> ```", ""]

    # ---- 一、反推出的提示词 ----
    if mv:
        p = mv.get("prompt") or {}
        vis = mv.get("visual") or {}
        L += ["## 一、反推出的七层提示词", "",
              "| 层 | 内容 | 来自 |", "|---|---|---|"]
        zh_src = {
            "style": "[[%s]] 的风格层" % mv["name_zh"],
            "lighting": "[[%s]] 的光照层" % mv["name_zh"],
            "color": "[[%s]] 的色彩层" % mv["name_zh"],
            "composition": "[[%s]] 的构图层" % mv["name_zh"],
            "medium": "[[%s]] 的媒介层" % mv["name_zh"],
            "mood": "[[%s]] 的情绪层" % mv["name_zh"],
            "camera": "[[%s]] 的镜头层" % mv["name_zh"],
        }
        for k, zh in LAYER_ORDER:
            if p.get(k):
                L.append("| **%s** | `%s` | %s |" % (zh, p[k], zh_src[k]))
        L.append("")
        # 主体留空，明确标注
        L += ["> [!important] 主体要你自己补",
              "> 反推擅长「这张画得像什么风格」，不擅长「这张画的是什么」。",
              "> 主体一栏是**看图**才能填的，卡上不替你编。", "",
              "### 整段正向提示词", "",
              "```text",
              "<你的主体>，%s" % (p.get("style") or "").strip().rstrip(","),
              "```", "",
              "### 负向提示词", "",
              "```text",
              (mv.get("negative") or "").strip(),
              "```", ""]

    # ---- 二、客观测量 ----
    lu = a.get("luminance") or {}
    co = a.get("contrast") or {}
    cl = a.get("color") or {}
    hm = a.get("harmony") or {}
    cp = a.get("composition") or {}
    tx = a.get("texture") or {}
    ln = a.get("lines") or {}
    L += ["## 二、客观测量（算出来的，可复现）", ""]
    if lu:
        L.append("- **明度** %s，均值 %s，动态范围 %s%s" % (
            lu.get("key", ""), _fmt_kv(lu.get("mean")), lu.get("dynamic_range"),
            ("，暗部溢出 %s%%" % _fmt_kv(lu.get("shadow_clip_pct"))) if lu.get("shadow_clip_pct") else ""))
    if co:
        L.append("- **对比** %s（RMS %s，Michelson %s）"
                 % (co.get("level", ""), _fmt_kv(co.get("rms")), _fmt_kv(co.get("michelson"), nd=3)))
    if cl:
        L.append("- **色彩** 色温 %s，饱和度 %s，主色 %s" % (
            cl.get("temperature", ""), _fmt_kv(cl.get("saturation"), nd=3),
            "  ".join("%s %s%%" % (d["hex"], _fmt_kv(d["pct"], nd=0))
                      for d in (cl.get("dominant") or [])[:4])))
    if hm:
        L.append("- **和谐** %s（主色相 %s）" % (hm.get("scheme", ""), hm.get("mean_hue_name", "")))
    if cp:
        L.append("- **构图** %s%s ｜ 中心/全图能量比 %s"
                 % (cp.get("symmetry_hint", ""),
                    "，主体在三分交点" if cp.get("subject_on_thirds") else "",
                    _fmt_kv(cp.get("center_weight"), nd=2)))
    if tx:
        L.append("- **质感** %s（边缘密度 %s，熵 %s）"
                 % (tx.get("busyness", ""), _fmt_kv(tx.get("edge_density")), _fmt_kv(tx.get("entropy"), nd=2)))
    if ln:
        L.append("- **线条** %s%s" % (
            ln.get("orientation", ""),
            ("，主导角 %d°" % ln["dominant_angle"]) if ln.get("dominant_angle") is not None else ""))
    # 明暗对照的签名
    if co and lu and co.get("rms", 99) < 45 and co.get("michelson", 0) > 0.85:
        L.append("- ⤷ RMS 低但 Michelson 高 ＝ 大面积暗调 + 小面积高光，**明暗对照法**的签名")
    ext = (a.get("extended") or {})
    if isinstance(ext.get("saliency"), dict) and "error" not in ext["saliency"]:
        s = ext["saliency"]
        L.append("- **视觉重心** (%.2f, %.2f)，最大显著区 %s ｜ %s"
                 % (s.get("center_x", 0), s.get("center_y", 0),
                    ("%.0f%%" % (s["main_region"] * 100)) if s.get("main_region") is not None else "n/a",
                    s.get("focus", "")))
    if isinstance(ext.get("faces"), dict) and ext["faces"].get("count"):
        L.append("- **人脸** 检出 %d 张，%s" % (ext["faces"]["count"], ext["faces"].get("framing", "")))
    L.append("")

    # ---- 三、匹配到的流派 ----
    if sug:
        L += ["## 三、最接近的流派（CLIP 语义匹配）", "",
              "| 流派 | 融合分 | 与第二名的差距 |", "|---|---|---|"]
        # 融合分本身不是可解释的距离，但「第一二名的分差」能表达模型有没有把握 ——
        # 实测分差 ≥1.0 时准确率约 80%，≥0.6 约 66%，<0.3 就基本是掷硬币了。
        from movements import MOVEMENTS as _M
        _zh = {m["slug"]: m["name_zh"] for m in _M}
        for i, x in enumerate(sug[:5]):
            if i == 0 and len(sug) > 1:
                m = sug[0]["score"] - sug[1]["score"]
                conf = "%.2f（%s）" % (m, "把握高" if m >= 1.0 else "把握中" if m >= 0.6 else "把握低")
            else:
                conf = "—"
            # 链接必须用**中文名** —— 流派卡的文件名是「巴洛克.md」不是「Baroque.md」，
            # 用英文名会生成断链（实测踩过：[[Tonalism]] 解析不到 色调主义.md）。
            label = _zh.get(x.get("slug")) or x.get("name") or x.get("slug")
            L.append("| [[%s]] | %.2f | %s |" % (label, x["score"], conf))
        L += ["",
              "> [!note] 这个分数只当参考",
              "> 实测 CLIP 判「最像哪个流派」的 Top-1 只有约四成（随机基准 1.4%）。",
              "> 排序有信息量，但别当结论 —— 以你打开流派卡看到的术语为准。", ""]

    # ---- 四、视频提示词 ----
    if mv:
        vp, from_image = video_blocks(rec, mv)
        if vp:
            title = ("## 四、视频提示词（**这张图的**，可直接粘）" if from_image
                     else "## 四、视频提示词（这个流派的，可直接粘）")
            L += [title, ""]
            if from_image:
                ev = vp.get("image_evidence") or {}
                if ev:
                    L += ["<sub>主体/运动/运镜是从这张图测出来的："
                          + " ｜ ".join("%s %s" % (k, v) for k, v in ev.items())
                          + "</sub>", ""]
            L += ["### A. Seedance 2.5 五段式", "", "```text", vp["seedance"], "```", "",
                  "### B. MiniMax H3（中文自然语言）", "", "```text", vp["h3"], "```", "",
                  "> 两块格式不同不能混用，详见 [[视频提示词结构]]。", ""]

    # ---- 五、来源 ----
    L += ["## 五、这张图从哪来", "",
          "- 原始位置：`%s`" % (rec.get("source") or "—"),
          "- 加入时间：%s" % (rec.get("added_at") or "—"),
          "- 尺寸：%s" % ("×".join(str(x) for x in rec["size"]) if rec.get("size") else "—"),
          ""]
    # 来源回链：从投递箱进来的图要指回 [[Pinterest]]，
    # 这样「按来源」那条轴在图谱上也连起来（不然它只有流派一条轴）。
    src = str(rec.get("source") or "")
    if "投递箱" in src or "pinterest" in src.lower():
        L += ["> [!note] 来源",
              "> 这张是从 Pinterest 收进来的（投递箱 `pinterest/`）。",
              "> 按来源汇总在 [[Pinterest]]，那里能看到同来源的全部图。", ""]
    if back:
        L += ["← 回到 [[%s]] ｜ [[我的图库总览]]" % back, ""]
    return "\n".join(L)


def compose_compact(rec, mv, image_name):
    """紧凑版：给**板子笔记里每张图**用的内联分析块。

    和 compose() 的区别：compose() 是「一张图一整页卡」，这里是「一页里
    二十张图各带一块」，所以砍掉了客观测量明细、来源、七层表格，
    只留最有用的三样：匹配到的流派、拼好的提示词、两块视频提示词。

    返回 markdown 片段（不含图片嵌入本身 —— 那是调用方的事）。
    """
    L = []
    a = rec.get("analysis") or {}
    sug = rec.get("suggest") or []
    lu = (a.get("luminance") or {}).get("key", "")
    sat = (a.get("color") or {}).get("saturation")
    tx = (a.get("texture") or {}).get("busyness", "")

    if mv:
        score = sug[0]["score"] if sug else None
        conf = ""
        if len(sug) > 1:
            m = sug[0]["score"] - sug[1]["score"]
            conf = " · 把握%s" % ("高" if m >= 1.0 else "中" if m >= 0.6 else "低")
        L.append("**最接近 [[%s]]**（融合分 %.2f%s）" % (mv["name_zh"], score or 0, conf))
    else:
        L.append("**未归类** —— CLIP 没给出有把握的建议")
    bits = [x for x in [lu, ("饱和度 %.2f" % sat) if sat is not None else None, tx] if x]
    if bits:
        L.append("")
        L.append("`%s`" % " ｜ ".join(bits))
    L.append("")

    if not mv:
        L += ["归类后会自动补上提示词与视频分析：",
              "",
              "```bash",
              "python3 .repo/ingest_inbox.py --scan",
              "python3 .repo/ingest_inbox.py --archive",
              "```", ""]
        return "\n".join(L)

    p = mv.get("prompt") or {}
    L += ["**提示词**（按 [[%s]] 的七层拼好，`<你的主体>` 自己补）" % mv["name_zh"], "",
          "```text",
          "<你的主体>, %s" % (p.get("style") or "").strip().rstrip(","),
          "```", "",
          "<sub>光照 `%s` ｜ 色彩 `%s` ｜ 构图 `%s` ｜ 媒介 `%s` ｜ 情绪 `%s` ｜ 镜头 `%s`</sub>"
          % (p.get("lighting", ""), p.get("color", ""), p.get("composition", ""),
             p.get("medium", ""), p.get("mood", ""), p.get("camera", "")), ""]
    vp, from_image = video_blocks(rec, mv)
    if vp:
        label = "这张图" if from_image else "流派通用"
        L += ["**视频 · Seedance 2.5**（%s，直接粘）" % label, "", "```text", vp["seedance"], "```", "",
              "**视频 · MiniMax H3**（海螺，中文自然语言）", "", "```text", vp["h3"], "```", ""]
    L += ["<sub>负向 `%s`</sub>" % (mv.get("negative") or "").replace("\n", " "), ""]
    return "\n".join(L)


def analyze_images(paths, verbose=False):
    """批量给图跑分析 + 流派匹配，返回 {路径: 记录}。抓取脚本和回填都用它。"""
    import image_analysis as IA
    import clip_match as CM
    sug = CM.suggest(paths, topn=3) if paths else {}
    out = {}
    for i, p in enumerate(paths, 1):
        a = IA.analyze(p)
        if a.get("error"):
            continue
        out[p] = record(p, a, sug.get(p, []), source="Pinterest")
        if verbose and (i % 10 == 0 or i == len(paths)):
            print("    分析 %d/%d" % (i, len(paths)))
    return out
