#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_vault.py —— 用 movements.py 的数据 + _data/*.json 的抓取结果，
生成整个 Obsidian 仓库的所有 Markdown 笔记。

用法：  python3 build_vault.py
重复运行是安全的：所有自动生成的文件都会被整体覆盖。
你自己写的笔记请放在 20-我的提示词/ 下，那个目录不会被碰。
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VAULT = os.path.dirname(HERE)
DATA_DIR = os.path.join(HERE, "_data")
sys.path.insert(0, HERE)
from movements import (MOVEMENTS, CATEGORIES, by_category,  # noqa: E402
                       build_positive)
import keyword_map  # noqa: E402

WIKI_TAX = {}
try:
    WIKI_TAX = json.load(open(os.path.join(HERE, "wikiart_taxonomy.json"), encoding="utf-8"))
except Exception:
    pass

GEN_MARK = "# auto-generated by build_vault.py —— 本文件由脚本生成，重跑会覆盖"


def w(rel, text):
    p = os.path.join(VAULT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(text.rstrip() + "\n")
    return rel


def load_works(slug):
    p = os.path.join(DATA_DIR, slug + ".json")
    if not os.path.exists(p):
        return []
    try:
        return json.load(open(p, encoding="utf-8"))
    except Exception:
        return []


def swatch(hexcode):
    return ('<span style="display:inline-block;width:26px;height:14px;'
            'background:%s;border:1px solid #8888;border-radius:2px;'
            'vertical-align:-2px;margin-right:6px"></span>' % hexcode)


# ------------------------------------------------------------------ 流派卡
def movement_note(mv, works):
    slug = mv["slug"]
    lines = []
    A = lines.append
    A("---")
    A(GEN_MARK)
    A("type: 流派")
    A("流派: %s" % mv["name_zh"])
    A("英文: %s" % mv["name_en"])
    A("时期: %s" % mv["period"])
    A("地区: %s" % mv["region"])
    A("分类: %s" % mv["category"])
    A("图片授权: %s" % ("CC0 / 公共领域（自动抓取）" if works else "无可用 CC0 图，纯提示词卡"))
    A("配色: [%s]" % ", ".join('"%s"' % h for h, _ in mv["palette"]))
    A("标签:")
    A("  - 流派")
    A("  - %s" % mv["name_en"].lower().replace(" ", "-"))
    A("---")
    A("")
    A("# %s · %s" % (mv["name_zh"], mv["name_en"]))
    A("")
    A("> [!abstract] 一句话")
    A("> **%s**" % mv["one_liner"])
    A("")
    A("| 分类 | 时期 | 地区 | 代表艺术家 |")
    A("|---|---|---|---|")
    A("| %s | %s | %s | %s |" % (
        mv["category"], mv["period"], mv["region"],
        "、".join(a for a, _ in mv["artists"][:4])))
    A("")
    A("---")
    A("")
    # 一、核心主张
    A("## 一、核心主张")
    A("")
    for c in mv["core"]:
        A("- %s" % c)
    A("")
    # 二、视觉语言拆解
    A("## 二、视觉语言拆解")
    A("")
    A("> [!tip] 这一节是「看什么」。先看懂，再谈提示词。")
    A("")
    A("| 维度 | 拆解 |")
    A("|---|---|")
    for k, v in mv["visual"].items():
        A("| **%s** | %s |" % (k, v))
    A("")
    # 三、配色
    A("## 三、配色板")
    A("")
    for h, name in mv["palette"]:
        A("- %s `%s` **%s**" % (swatch(h), h, name))
    A("")
    A("> [!example] 配色提示词（直接粘）")
    A("> `%s`" % ", ".join("%s %s" % (n, h) for h, n in mv["palette"]))
    A("")
    # 四、提示词结构
    A("## 四、提示词结构")
    A("")
    A("> [!note] 六层拼装法")
    A("> `主体 + 风格 + 光照 + 色彩 + 构图 + 媒介 + 情绪 + 镜头`")
    A("> 下面每一层都可以单独拆出来复用——换主体不换风格层，就是你的风格迁移模板。")
    A("")
    A("| 层 | 可复用片段 |")
    A("|---|---|")
    order = [("style", "风格"), ("lighting", "光照"), ("color", "色彩"),
             ("composition", "构图"), ("medium", "媒介"), ("mood", "情绪"), ("camera", "镜头")]
    for key, label in order:
        A("| **%s** | `%s` |" % (label, mv["prompt"][key]))
    A("")
    A("### 整段正向提示词")
    A("")
    A("```text")
    A("%s" % build_positive(mv).strip())
    A("```")
    A("")
    A("> [!warning] 用法：这是**风格层**，不是完整提示词。")
    A("> 在前面接你自己的主体描述，例如：`<你的主体>, %s`" % mv["prompt"]["style"][:80])
    A("")
    A("### 负向提示词")
    A("")
    A("```text")
    A("%s" % mv["negative"].strip())
    A("```")
    A("")
    # 五、视频层
    A("## 五、AI 视频层")
    A("")
    A("> [!info] 文生视频 = 上面的静态描述 + 下面这三行")
    A("")
    A("| 层 | 内容 |")
    A("|---|---|")
    A("| **Motion 运动** | %s |" % mv["video"]["motion"])
    A("| **Camera 运镜** | %s |" % mv["video"]["camera"])
    A("")
    A("> [!important] 关键判断")
    A("> %s" % mv["video"]["note"])
    A("")
    # 六、代表作品
    A("## 六、代表作品（CC0 实图）")
    A("")
    if works:
        A("*全部来自开放授权数据源，图片与元数据均为 CC0 / 公共领域，可自由使用。*")
        A("")
        for i, wk in enumerate(works, 1):
            A("### %d. %s" % (i, wk["title"]))
            A("")
            if wk.get("local_image"):
                A("![[%s]]" % os.path.basename(wk["local_image"]))
                A("")
            meta = " · ".join(x for x in [wk.get("artist"), wk.get("date"), wk.get("medium")] if x)
            A("**%s**" % (meta or "—"))
            A("")
            A("来源：[%s](%s) · %s · [高清原图](%s)" % (
                wk["source"], wk.get("page_url") or "#", wk["license"], wk["image_url_hi"]))
            A("")
    else:
        A("> [!warning] 该流派暂无 CC0 可用图片")
        A("> 原因是这个流派的代表作品多在版权保护期内（例如 1930 年之后的现代作品）。")
        A("> 想找视觉参考，去 [WikiArt 该流派页面](https://www.wikiart.org/en/paintings-by-style) 看图，")
        A("> 但**不要把图下载进仓库再对外分享**——只存链接和提示词。")
        A("")
    # 七、翻车点
    A("## 七、常见翻车点")
    A("")
    for p in mv["pitfalls"]:
        A("- %s" % p)
    A("")
    # 八、关联
    A("## 八、关联流派")
    A("")
    for s in mv["see_also"]:
        tgt = next((m for m in MOVEMENTS if m["slug"] == s), None)
        A("- [[%s]]" % (tgt["name_zh"] if tgt else s))
    A("")
    A("---")
    A("")
    A("← [[流派总览]] · [[分类索引-%s]]　|　延伸阅读 [[提示词拆解方法]]" % mv["category"])
    return "\n".join(lines)



# ------------------------------------------------------------------ 技能树
# 分类下的编辑性分组（哪些流派在叙事上归属同一支）
SUBGROUPS = {
 "西方古典与近代": [
   ("中世纪与拜占庭", ["byzantine","romanesque","gothic","international-gothic"]),
   ("文艺复兴", ["early-renaissance","renaissance","early-netherlandish","venetian-school","mannerism"]),
   ("巴洛克与古典", ["baroque","caravaggisti","dutch-golden-age","rococo","classicism","neoclassicism"]),
   ("19 世纪", ["romanticism","realism","naturalism","orientalism","academic-art","pre-raphaelite"]),
   ("印象派前后", ["impressionism","neo-impressionism","post-impressionism","nabis","symbolism","japonism"]),
   ("世纪之交", ["art-nouveau","vienna-secession","arts-and-crafts"]),
   ("美国与近代诸派", ["hudson-river-school","luminism","tonalism","ashcan-school","american-realism",
                    "regionalism","precisionism","social-realism","socialist-realism","muralism",
                    "magic-realism","metaphysical-art","neo-romanticism","naive-art",
                    "classical-realism","kitsch","new-objectivity"]),
 ],
 "现代主义与战后": [
   ("表现与野兽", ["expressionism","fauvism","der-blaue-reiter"]),
   ("立体与未来", ["cubism","orphism","futurism"]),
   ("几何抽象", ["suprematism","constructivism","de-stijl","bauhaus"]),
   ("达达与超现实", ["dada","surrealism"]),
   ("战后抽象", ["abstract-expressionism","color-field","art-informel","tachisme","lyrical-abstraction"]),
   ("波普与极简", ["pop-art","op-art","minimalism-art","art-deco"]),
 ],
 "先锋·当代·后现代": [
   ("三个总纲", ["avant-garde","contemporary-art","postmodernism"]),
   ("抽象诸支", ["abstract-art","hard-edge","post-painterly-abstraction"]),
   ("反艺术与媚俗", ["neo-dada","neo-pop","transavantgarde"]),
   ("边缘与身体", ["art-brut","outsider-art","feminist-art","native-art"]),
   ("公共与空间", ["street-art","land-art","kinetic-art","light-and-space"]),
   ("新媒介与后观念", ["digital-art","hyper-realism","photorealism","conceptual-art","neo-expressionism","superflat"]),
 ],
 "数字·亚文化·摄影美学": [
   ("朋克五支", ["cyberpunk","steampunk","dieselpunk","solarpunk","biopunk"]),
   ("网络怀旧", ["vaporwave","synthwave","pixel-art","retro-anime","dreamcore","y2k"]),
   ("动画与插画", ["anime-cel"]),
   ("银盐与印相", ["cyanotype","wet-plate","polaroid-film"]),
   ("氛围与生活", ["dark-academia","cottagecore","wabi-sabi","gothic-subculture","wasteland"]),
   ("平面设计", ["minimalist-design","swiss-style","memphis-design"]),
   ("电影感", ["film-noir"]),
 ],
 "东亚·南亚·伊斯兰": [
   ("中国", ["blue-green-landscape","ink-wash-xieyi","gongbi","song-academic","dunhuang-murals"]),
   ("日本", ["ukiyo-e","rimpa","suiboku-ga","yamato-e","sosaku-hanga","shin-hanga","zen-art"]),
   ("朝鲜半岛", ["minhwa"]),
   ("波斯与伊斯兰", ["persian-miniature","safavid-painting","mughal-miniature",
                   "islamic-geometric","arabic-calligraphy"]),
   ("喜马拉雅与原住民", ["tibetan-thangka","indigenism"]),
 ],
 "摄影与图像": [
   ("两大传统", ["pictorialism","straight-photography"]),
   ("社会与街头", ["documentary-photography","street-photography"]),
   ("观念与时尚", ["surrealist-photography","fashion-editorial"]),
 ],
}

CAT_ICON = {"西方古典与近代": "🏛", "现代主义与战后": "🎨",
            "先锋·当代·后现代": "🚀", "数字·亚文化·摄影美学": "🌃",
            "东亚·南亚·伊斯兰": "🀄", "摄影与图像": "📷"}


CAT_EN = {
 "西方古典与近代": "Western Classical & Modern",
 "现代主义与战后": "Modernism & Post-war",
 "先锋·当代·后现代": "Avant-Garde · Contemporary · Postmodern",
 "数字·亚文化·摄影美学": "Digital · Subculture · Photography",
 "东亚·南亚·伊斯兰": "East Asia · South Asia · Islam",
 "摄影与图像": "Photography & Image",
}

SUBGROUPS_EN = {
 "中世纪与拜占庭": "Medieval & Byzantine", "文艺复兴": "Renaissance",
 "巴洛克与古典": "Baroque & Classical", "19 世纪": "19th Century",
 "印象派前后": "Impressionism & After", "世纪之交": "Fin de Siecle",
 "美国与近代诸派": "American & Modern Schools",
 "表现与野兽": "Expressionism & Fauvism", "立体与未来": "Cubism & Futurism",
 "几何抽象": "Geometric Abstraction", "达达与超现实": "Dada & Surrealism",
 "战后抽象": "Post-war Abstraction", "波普与极简": "Pop & Minimal",
 "三个总纲": "The Three Umbrellas", "抽象诸支": "Abstract Branches",
 "反艺术与媚俗": "Anti-Art & Kitsch", "边缘与身体": "Margins & Body",
 "公共与空间": "Public & Space", "新媒介与后观念": "New Media & Post-Conceptual",
 "朋克五支": "Five Punks", "网络怀旧": "Internet Nostalgia",
 "动画与插画": "Animation & Illustration", "银盐与印相": "Silver & Print",
 "氛围与生活": "Atmosphere & Living", "平面设计": "Graphic Design",
 "电影感": "Cinematic", "中国": "China", "日本": "Japan",
 "朝鲜半岛": "Korea", "波斯与伊斯兰": "Persia & Islam",
 "喜马拉雅与原住民": "Himalaya & Indigenous",
 "两大传统": "Two Traditions", "社会与街头": "Social & Street",
 "观念与时尚": "Conceptual & Fashion", "其他": "Others",
}


CAT_COVER_EN = {
 "西方古典与近代": "Byzantine to Ashcan School - the backbone of European painting",
 "现代主义与战后": "Fauvism to Neo-Expressionism - 20th century experiment",
 "数字·亚文化·摄影美学": "Cyberpunk, vaporwave, analogue photo processes, internet subcultures",
 "先锋·当代·后现代": "Avant-garde, contemporary, postmodern, installation / performance / digital",
 "东亚·南亚·伊斯兰": "Dunhuang murals, Tibetan thangka, ukiyo-e, Persian miniature, Islamic geometry",
 "摄影与图像": "Pictorialism, straight photography, documentary, street, surrealist photography",
}


def category_table_en():
    cats = by_category()
    L = ["| Category | Movements | Covers |", "|---|---|---|"]
    for c in CATEGORIES:
        L.append("| %s | %d | %s |" % (CAT_EN.get(c, c), len(cats[c]), CAT_COVER_EN.get(c, "")))
    L.append("| **Total** | **%d** | 6 categories |" % len(MOVEMENTS))
    return "\n".join(L)


def skill_tree_en():
    """英文版技能树，结构与中文版一一对应"""
    by = {m["slug"]: m for m in MOVEMENTS}
    cats = by_category()
    L = ["Art Aesthetic Style Library", "│"]
    for ci, cat in enumerate(CATEGORIES):
        ms = cats[cat]
        own = {m["slug"] for m in ms}
        last_cat = (ci == len(CATEGORIES) - 1)
        L.append("%s %s · %d" % ("└─" if last_cat else "├─", CAT_EN.get(cat, cat), len(ms)))
        prefix = "   " if last_cat else "│  "
        groups = [(g, [x for x in ss if x in own]) for g, ss in (SUBGROUPS.get(cat) or [])]
        claimed = {x for _, ss in groups for x in ss}
        rest = [m["slug"] for m in ms if m["slug"] not in claimed]
        if rest:
            groups.append(("其他", rest))
        groups = [(g, ss) for g, ss in groups if ss]
        for gi, (gname, slugs) in enumerate(groups):
            last_g = (gi == len(groups) - 1)
            L.append("%s%s %s" % (prefix, "└─" if last_g else "├─",
                                  SUBGROUPS_EN.get(gname, gname)))
            sub = prefix + ("    " if last_g else "│  ")
            names = [by[x]["name_en"] for x in slugs]
            for i in range(0, len(names), 3):
                L.append("%s%s %s" % (sub, "└" if i + 3 >= len(names) else "├",
                                      " . ".join(names[i:i + 3])))
    return "\n".join(L)


def skill_tree():
    """生成 Markdown 代码块里的技能树。只从本分类取成员，避免跨分类重复。"""
    by = {m["slug"]: m for m in MOVEMENTS}
    cats = by_category()
    L = ["艺术审美风格库", "│"]
    for ci, cat in enumerate(CATEGORIES):
        ms = cats[cat]
        own = {m["slug"] for m in ms}
        last_cat = (ci == len(CATEGORIES) - 1)
        L.append("%s %s %s · %d 个流派" % ("└─" if last_cat else "├─",
                                           CAT_ICON.get(cat, "▪"), cat, len(ms)))
        prefix = "   " if last_cat else "│  "
        groups = [(g, [x for x in ss if x in own]) for g, ss in (SUBGROUPS.get(cat) or [])]
        claimed = {x for _, ss in groups for x in ss}
        rest = [m["slug"] for m in ms if m["slug"] not in claimed]
        if rest:
            groups.append(("其他", rest))
        groups = [(g, ss) for g, ss in groups if ss]
        for gi, (gname, slugs) in enumerate(groups):
            last_g = (gi == len(groups) - 1)
            L.append("%s%s %s" % (prefix, "└─" if last_g else "├─", gname))
            sub = prefix + ("   " if last_g else "│  ")
            names = [by[x]["name_zh"] for x in slugs]
            for i in range(0, len(names), 4):
                L.append("%s%s %s" % (sub, "└" if i + 4 >= len(names) else "├",
                                      " · ".join(names[i:i + 4])))
    return "\n".join(L)


# ------------------------------------------------------------------ 总览
def overview_note(works_map):
    A = []
    A.append("---"); A.append(GEN_MARK); A.append("type: MOC"); A.append("---"); A.append("")
    A.append("# 流派总览")
    A.append("")
    A.append("> [!abstract] 怎么用这个仓库")
    A.append("> 1. 从下面的分类找到你要的方向")
    A.append("> 2. 点进流派卡，看「视觉语言拆解」——那是判断依据")
    A.append("> 3. 直接抄「提示词结构」里的分层片段，拼到你自己的主体描述上")
    A.append("> 4. 视频任务再加「AI 视频层」的运动 + 运镜")
    A.append("")
    A.append("> [!tip] 先读方法，再抄模板")
    A.append("> 方法在 [[提示词拆解方法]]，视频结构在 [[视频提示词结构]]，")
    A.append("> 配色速查在 [[配色速查]]，反推工具链在 [[反推工具链]]，")
    A.append("> 版权边界在 [[版权与来源]]。")
    A.append("")
    n_img = sum(1 for m in MOVEMENTS if works_map.get(m["slug"]))
    A.append("**共 %d 个流派**，其中 %d 个带 CC0 / 公共领域实图，%d 个为纯提示词卡。"
             % (len(MOVEMENTS), n_img, len(MOVEMENTS) - n_img))
    A.append("")
    A.append("## 分类")
    A.append("")
    A.append("| 分类 | 流派数 | 配图流派 | 覆盖范围 |")
    A.append("|---|---|---|---|")
    covers = {
        "西方古典与近代": "拜占庭 → 阿什坎学派，欧洲绘画史主干",
        "东亚·南亚·伊斯兰": "中国、日本、韩国、波斯、莫卧儿、伊斯兰装饰",
        "现代主义与战后": "野兽派 → 新表现主义，20 世纪实验",
        "数字·亚文化·摄影美学": "赛博朋克、蒸汽波、胶片工艺、网络亚文化",
    }
    for c in CATEGORIES:
        ms = by_category()[c]
        got = sum(1 for m in ms if works_map.get(m["slug"]))
        A.append("| [[分类索引-%s\|%s]] | %d | %d | %s |"
                 % (c, c, len(ms), got, covers.get(c, "")))
    A.append("")
    for c in CATEGORIES:
        ms = by_category()[c]
        A.append("## %s" % c)
        A.append("")
        A.append("[[分类索引-%s\|查看本类索引 →]]" % c)
        A.append("")
        A.append("| 流派 | English | 时期 | 配图 | 一句话 |")
        A.append("|---|---|---|---|---|")
        for m in ms:
            n = len(works_map.get(m["slug"]) or [])
            A.append("| [[%s]] | %s | %s | %s | %s |"
                     % (m["name_zh"], m["name_en"], m["period"],
                        ("%d 张" % n) if n else "—", m["one_liner"]))
        A.append("")
    A.append("---")
    A.append("")
    A.append("延伸：[[提示词拆解方法]] · [[视频提示词结构]] · [[配色速查]] · [[反推工具链]] · [[版权与来源]]")
    return "\n".join(A)


def category_note(cat, works_map):
    ms = by_category()[cat]
    A = []
    A.append("---"); A.append(GEN_MARK); A.append("type: MOC"); A.append("分类: %s" % cat)
    A.append("---"); A.append("")
    A.append("# %s" % cat)
    A.append("")
    A.append("← 返回 [[流派总览]]")
    A.append("")
    A.append("| 流派 | English | 时期 | 地区 | 配图 |")
    A.append("|---|---|---|---|---|")
    for m in ms:
        n = len(works_map.get(m["slug"]) or [])
        A.append("| [[%s]] | %s | %s | %s | %s |"
                 % (m["name_zh"], m["name_en"], m["period"], m["region"],
                    ("%d 张" % n) if n else "—"))
    A.append("")
    A.append("## 一句话速览")
    A.append("")
    for m in ms:
        A.append("- **[[%s]]** %s" % (m["name_zh"], m["one_liner"]))
    A.append("")
    return "\n".join(A)


# ------------------------------------------------------------------ 方法
METHOD = """---
{mark}
type: 方法
---

# 提示词拆解方法

> [!abstract] 核心思路
> 一张参考图的「风格」不是一个词，而是**七个可以独立替换的层**。
> 把图拆成层，你就能把 A 图的风格套到 B 图的主体上——这才是参考库的意义。

## 一、七层拆解法

看到任何一张图（不管是 AI 生成还是名画），按这个顺序问七个问题：

| # | 层 | 要问的问题 | 产出 |
|---|---|---|---|
| 1 | **主体 Subject** | 画的是谁/什么？姿态、服装、数量、年龄 | `a young woman in a beige trench coat` |
| 2 | **风格 Style** | 哪个流派/艺术家/媒介？ | `baroque oil painting, tenebrism` |
| 3 | **光照 Lighting** | 光源在哪？几个？硬还是软？什么时间？ | `single hard light from off-frame, candlelight rim` |
| 4 | **色彩 Color** | 主色、辅色、饱和度、明度关系 | `bitumen black, warm gold, deep crimson` |
| 5 | **构图 Composition** | 视角、对称性、主体位置、纵深 | `diagonal dynamic, low angle, shallow depth` |
| 6 | **媒介 Medium** | 什么材料？质感？颗粒？ | `oil on canvas, visible impasto, aged varnish` |
| 7 | **情绪 Mood** | 观众应该感觉到什么？ | `dramatic, intense, theatrical` |

**第 2 层是你这个仓库的主要内容。第 3–7 层每张卡里都拆好了。**

## 二、拆解顺序为什么重要

很多人写提示词失败，是因为把七层混在一起写，然后靠试错调。

正确的做法是**逐层锁定**：

1. 先只写主体，确认构图和姿态对了
2. 加风格层，看整体味道对不对
3. 加光照层——**这一层对最终质感的影响最大**，比风格词本身还大
4. 加色彩层，修正偏色
5. 最后加媒介层（`oil on canvas` / `35mm film` / `watercolour`），锁死质感

> [!warning] 最大的坑
> 只写流派名（比如 `baroque`）几乎一定会得到一张平庸的图。
> 流派名必须配上**光照 + 色彩 + 媒介**三层，模型才知道你要什么。

## 三、层与层之间的解耦

拆成层的最大好处是：**层可以混搭**。

```
主体      一个赛博朋克赏金猎人站在雨中
风格层 ←  [[巴洛克]] 的 lighting + color
构图层 ←  [[赛博朋克]] 的 low angle + wet reflection
媒介层 ←  digital concept painting
```

这就是「用古典光打未来场景」的做法。混搭记录在 [[我的提示词卡]] 里。

## 四、每层的关键词数量

| 层 | 建议词数 | 说明 |
|---|---|---|
| 主体 | 15–40 | 越具体越好 |
| 风格 | 3–8 | 太多会互相打架 |
| 光照 | 4–8 | **性价比最高的一层** |
| 色彩 | 3–6 | 给具体颜色名，不要只写 `colorful` |
| 构图 | 3–6 | 镜头语言同时管构图和运镜 |
| 媒介 | 2–5 | 决定「看起来像什么做的」 |
| 情绪 | 3–6 | 影响姿态和氛围 |

## 五、负向提示词怎么写

负向提示词要**针对这个流派的典型错误**，不是通用的一长串垃圾词。

每个流派卡最后的「常见翻车点」就是负向词的来源。例如印象派要写
`black shadows, smooth blending, photorealistic`，而文艺复兴要写
`visible brushstrokes, impasto`——**两者的负向词几乎相反**。

> [!danger] 反面教材
> `worst quality, low quality, bad anatomy, ugly, deformed, blurry, watermark, text`
> 这一串是 2022 年的遗物。现代模型基本不需要，而且会占用注意力。
> 只在真的出现问题时，加**针对性的**负向词。

## 六、配套工具

拆解流程里可以借力的开源工具见 [[反推工具链]]。
"""


VIDEO = """---
{mark}
type: 方法
---

# 视频提示词结构

> [!abstract] 文生视频 ≠ 文生图 + 「会动」
> 视频模型需要你额外说清楚三件事：**谁在动、怎么动、镜头怎么动**。
> 图像提示词只覆盖了「画面长什么样」，剩下的全靠这一页。

## 一、主公式

```
主体 + 场景 + 运动 + 美学控制 + 风格化
```

- **基础**：主体 + 场景 + 运动
- **进阶**：以上 + 光照 / 时段 / 景别 / 构图 / 镜头 / 色调
- **图生视频**：运动描述 + 运镜（因为主体和场景已经由首帧给定了）

## 二、必须显式声明的五个维度

视频模型不会自己推断这些，你不写它就随机。

### 1. 运动 Motion
`walks slowly` / `turns her head` / `hair drifts in the wind` / `rain falls steadily` / `camera tracks alongside`

### 2. 景别 Shot Size
`extreme close-up (ECU)` · `close-up (CU)` · `medium close-up (MCU)` · `medium shot (MS)`
· `medium wide shot (MWS)` · `wide shot (WS)` · `extreme wide shot (EWS)` · `establishing shot`

### 3. 机位 Camera Angle
`eye-level` · `high angle` · `low angle` · `dutch angle` · `aerial` · `bird's eye` · `over-the-shoulder`

### 4. 运镜 Camera Movement
`static shot` · `camera pushes in / dolly in` · `camera pulls back / dolly out`
· `pan left / right` · `tilt up / down` · `tracking shot` · `arc shot` · `crane shot`
· `handheld` · `steadicam` · `whip pan` · `compound move`

### 5. 时段与光照 Time & Light
时段：`sunrise` · `dawn` · `daylight` · `dusk` · `sunset` · `night`
光源：`sunny` · `overcast` · `moonlight` · `firelight` · `practical lighting` · `neon`
类型：`soft` · `hard` · `rim` · `backlight` · `silhouette` · `low contrast` · `high contrast`

## 三、把流派卡接到视频上

每个流派卡的「五、AI 视频层」已经给好了该流派的 motion 和 camera。

```
[流派卡的 style + lighting + color + medium]
+ [流派卡的 motion] + [流派卡的 camera]
+ [你要的主体在做什么]
```

> [!important] 一个流派一种运镜
> 运镜本身带风格信息。给印象派用手持快切、给表现主义用平稳滑轨，
> 都是错的——**运镜和流派必须同源**，每张卡里都标了。

## 四、常见错误

| 错误 | 后果 | 修正 |
|---|---|---|
| 只写画面不写运动 | 模型给一个几乎静止的镜头 | 显式写 motion |
| 写 `camera moves` | 运镜方向随机 | 写 `dolly in` / `pan left` 等具体术语 |
| 运动描述过多 | 画面崩坏、闪烁 | 一个镜头只做 1–2 个动作 |
| 忘了写景别 | 一会儿全身一会儿特写 | 每次生成都明确 shot size |
| 光照和流派冲突 | 风格被冲淡 | 视频的光照层直接复用流派卡里的 |

## 五、来源

本页结构参照开源社区的 Wan 2.2 提示词指南整理：
[EricRollei/Local_LLM_Prompt_Enhancer — WAN_GUIDE_REFERENCE.md](https://github.com/EricRollei/Local_LLM_Prompt_Enhancer/blob/main/docs/WAN_GUIDE_REFERENCE.md)

同类模型（Veo / Kling / Runway / HunyuanVideo）的结构基本一致，
差异主要在运镜术语的接受度上。
"""


TOOLCHAIN = """---
{mark}
type: 工具
---

# 反推工具链

> [!abstract] 用途
> 当你在网上（包括 WikiArt）看到一张图，想知道「它为什么好看」，
> 用这些开源工具把图**反推成结构化提示词**，再拆进七层表里。

## 一、图 → 提示词（核心工具）

| 工具 | 仓库 | 作用 | 适合 |
|---|---|---|---|
| **CLIP Interrogator** | [pharmapsychotic/CLIP-Interrogator](https://github.com/pharmapsychotic/CLIP-Interrogator) | BLIP 描述 + CLIP 排序，输出 SD 友好的提示词 | **首选**，古典绘画/艺术图效果好 |
| **JoyCaption** | [fpgaminer/joycaption](https://github.com/fpgaminer/joycaption) | 从零训练的图像描述 VLM，描述自然语言化 | 需要**长句描述**而非关键词堆叠时 |
| **WD14 Tagger** | [turbo-boo/stable-diffusion-webui-wd14-tagger](https://github.com/turbo-boo/stable-diffusion-webui-wd14-tagger) | Danbooru 标签体系反推 | **动漫/角色/插画**，标签粒度极细 |
| **Local LLM Prompt Enhancer** | [EricRollei/Local_LLM_Prompt_Enhancer](https://github.com/EricRollei/Local_LLM_Prompt_Enhancer) | ComfyUI 节点，用本地 LLM 扩写提示词 | 视频提示词扩写（含 Wan 指南） |

> [!note] WD14 Tagger 的模型权重在哪
> 模型本身发布在 Hugging Face 上（作者 `SmilingWolf`，模型名形如 `wd-v1-4-*`）。
> 直接在 Hugging Face 搜索 `wd-v1-4` 即可，不要从第三方镜像下权重。

> [!tip] 组合用法（推荐）
> 1. CLIP Interrogator 拿到**关键词骨架**
> 2. JoyCaption 拿到**一句话描述**，用来理解画面意图
> 3. 你自己按七层表把两者归位 + 补上流派卡里的术语
>
> 不要把工具输出直接当提示词用——它擅长「描述已有」，不擅长「指向想要」。

## 二、审美打分

| 工具 | 仓库 | 作用 |
|---|---|---|
| **Improved Aesthetic Predictor** | [christophschuhmann/improved-aesthetic-predictor](https://github.com/christophschuhmann/improved-aesthetic-predictor) | CLIP+MLP 给图打美学分，可批量筛选参考图 |
| **LAION Aesthetics** | LAION 系列 | 大规模美学评分模型，用于数据集过滤 |

用途：把收集到的几百张参考图**批量打分排序**，只留高分图进仓库。

## 三、批量抓取与数据集

| 工具 | 仓库 | 作用 |
|---|---|---|
| **img2dataset** | [rom1504/img2dataset](https://github.com/rom1504/img2dataset) | 从 URL 列表批量下载/缩放/打包成数据集 |
| **本仓库脚本** | `_scripts/fetch_art.py` | 从 CC0 美术馆 API 抓图 + 元数据 |

## 四、提示词工程总纲

| 资源 | 链接 |
|---|---|
| Prompt Engineering Guide | [dair-ai/Prompt-Engineering-Guide](https://github.com/dair-ai/Prompt-Engineering-Guide) |
| 图像反推 Skill（中文） | [luozhilzh/image-prompt-reverse](https://github.com/luozhilzh/image-prompt-reverse) |

## 五、数据集：如果你想要 WikiArt 那个量级

不想一个个爬，可以用已发布的公开艺术数据集。它们自带
style / artist / genre 标签，比你自己爬完再标注省事得多：

| 数据集 | 内容 | 去哪找 |
|---|---|---|
| **ArtBench-10** | 6 万张，10 个流派，标签干净，专为风格研究做的 | Hugging Face / 论文附带数据 |
| **WikiArt 数据集** | 约 8 万张画作，带 style / genre / artist 标签 | Hugging Face / Kaggle 搜 `wikiart` |
| **AVA** | 25 万张，带美学评分 | 搜 `AVA aesthetic visual analysis` |

> [!tip] 为什么这条路更干净
> 数据集是**研究者已经发布出来供研究使用**的，授权链条比你自己爬清楚。
> 而且标签是结构化的，直接就能对应到这个仓库的流派卡上。

## 六、数据源（找参考图用）

| 源 | 授权 | 免密钥 | 本仓库是否使用 |
|---|---|---|---|
| [克利夫兰艺术博物馆](https://openaccess-api.clevelandart.org) | **CC0** | ✅ | ✅ 主力 |
| [大都会艺术博物馆](https://collectionapi.metmuseum.org/public/collection/v1/search) | **CC0** | ✅ | ✅ 主力 |
| [维基共享资源](https://commons.wikimedia.org/w/api.php) | 逐条 | ✅ | ✅ 只取 PD/CC0 |
| [芝加哥艺术博物馆](https://api.artic.edu/docs/) | **CC0** | ✅ | ⚠️ 只取元数据（图片 CDN 有 Cloudflare） |
| [史密森尼 Open Access](https://www.si.edu/openaccess) | **CC0** | ❌ 需 key | 可扩展 |
| [Rijksmuseum](https://data.rijksmuseum.nl/) | 公共领域 | ❌ 需 key | 可扩展 |
| [Harvard Art Museums](https://harvardartmuseums.org/collections/api) | 部分 CC0 | ❌ 需 key | 可扩展 |
| [史密森尼 / Europeana](https://www.europeana.eu/en/apis) | 逐条 | ❌ 需 key | 可扩展 |
| [WikiArt](https://www.wikiart.org) | **混合** | — | ❌ 只作浏览参考，见 [[版权与来源]] |

> [!tip] 想再加数据源
> 在 `_scripts/providers.py` 里写一个函数，返回统一的字段结构
> （title / artist / date / medium / image_url / page_url / source / license / license_url），
> 注册进 `PROVIDERS`，然后在流派的 `sources` 里写上 `"提供商名": ["查询词"]` 即可。

## 七、关于 WikiArt

WikiArt 的 `robots.txt` 是 `User-agent: * / Allow: /`，技术上**允许抓取**，
页面也是服务端渲染、用 curl 就能拿到。但它**不是**开放数据源：

- 网站自己的文字、编排、分类体系受版权保护
- 版权期内的作品，WikiArt 是以「合理使用」的**低分辨率**方式展示的
- 它没有免费的官方 API（只有商业授权）

**结论：可以用它找线索，不要把它的图和文字当成可自由分发的素材。**
详见 [[版权与来源]]。
"""


LICENSE = """---
{mark}
type: 说明
---

# 版权与来源

> [!warning] 一句话原则
> **公共领域的作品可以自由下载、再分发；版权期内的作品只存链接和提示词，不存图。**

## 一、这个仓库里的图，授权是什么

`10-流派/` 里的所有图片都来自 **CC0 / 公共领域**的开放数据源：

| 来源 | 授权 | 本仓库的使用方式 |
|---|---|---|
| 克利夫兰艺术博物馆 | **CC0 1.0** | 主力源，API 免密钥，一次返回完整元数据 |
| 大都会艺术博物馆 | **CC0 1.0** (Open Access) | 主力源，`isPublicDomain=true` 过滤 |
| 芝加哥艺术博物馆 | **CC0 1.0** | 只取其元数据（它的图片 CDN 有 Cloudflare 保护，脚本抓不到） |
| 维基共享资源 | **逐条判定**，脚本只接受 Public domain / CC0 | 补全非西方流派与现代流派 |

CC0 意味着**没有版权限制**：你可以下载、修改、商用、再分发，
包括把图放进你自己的数据集训练模型。每张作品下面都标了来源和授权链接。

> [!important] 维基共享资源为什么只取 PD / CC0
> Commons 上还有大量 CC BY / CC BY-SA 的图，那些**可以用，但必须署名**。
> 脚本默认不收，是为了让整个仓库的授权状态保持单一——「随便用，不用想」。
> 如果你确实需要更大的覆盖面，运行 `python3 fetch_art.py --include-ccby`，
> 脚本会把每个文件的授权与来源页一并记录下来，署名信息不会丢。

> [!note] 为什么 1950 年后的流派没有图
> 抽象表现主义、波普、极简主义、超扁平这些流派的作品**仍在版权期内**，
> 任何开放数据源都不会提供。所以它们生成为**纯提示词卡**——
> 视觉语言和提示词结构照常拆解，只是不配图。这是授权策略的结果，不是缺失。

## 二、WikiArt 到底能不能爬

**技术上：能。**

实测结果：

| 检查项 | 结果 |
|---|---|
| `robots.txt` | `User-agent: *` / `Allow: /` —— 明确允许抓取 |
| 站点地图 | 公开 `sitemap_index.xml`，含 16 个子图，`paintings-1.xml` 一个就 4 万条 URL |
| 页面渲染 | 服务端渲染，curl 直接拿 HTML，不需要 JS |
| 图片直链 | 可下载，`!Large.jpg` 后缀约 750px |
| 反爬 | 有 Cloudflare，但普通 UA 可过；高频会触发验证 |

**法律上：不行（或者说，很灰）。**

WikiArt 的服务条款（2016 版，管辖地乌克兰）**没有**明文禁止自动化访问，
但它对版权作品的定义写得很清楚：

> "WikiArt presents both public domain and copyright protected artworks.
> The latter are showcased in accordance with fair use principle:
> as historically significant artworks · as used for informational and
> educational purposes · as readily available on the internet ·
> **as low resolution copies unsuitable for commercial use**"

也就是说，那些图在 WikiArt 上的存在**本身就是靠合理使用撑着的**：
低分辨率 + 教育目的 + 非商业。你再把它们批量下载下来重新分发，
就把这个平衡打破了——责任落到你头上。

另外，WikiArt **没有免费的官方 API**，它只有商业授权渠道。

### 所以本仓库的做法

| 做法 | 是否采用 |
|---|---|
| 从 CC0 美术馆抓图入库 | ✅ 采用，这是主力 |
| 在笔记里放 WikiArt 的**链接** | ✅ 采用，只作线索 |
| 批量下载 WikiArt 图片进仓库 | ❌ 不做 |
| 把 WikiArt 的图用于训练 | ❌ 不做 |

## 三、个人使用 vs 公开分发

Obsidian 仓库如果只是自己看、自己参考，几乎不存在风险。
风险出现在两个动作上：

1. **把仓库（含图）传到公开的 GitHub / 网盘** —— 这时候你在再分发
2. **把图喂给模型做训练然后发布模型** —— 这时候你在商业化利用

如果确实需要，就用 `_scripts/fetch_art.py` 重新抓 CC0 的图，
那些是可以随便分发的。

## 四、如果你就是想要 WikiArt 的规模

有两个合法替代路径：

1. **WikiArt 数据集**（Hugging Face / Kaggle 上有公开的影像数据集，
   本身就带 style / artist / genre 标签），用于研究目的下载使用
2. **用 CC0 数据源自己攒**：本仓库的脚本已经能跑，
   把 `movements.py` 里的 `sources` 查询词换掉就行，换个流派照样跑

## 五、自查清单

- [ ] 笔记里的每张图都来自 CC0 表里的来源
- [ ] 每张图下面有来源链接和授权标注
- [ ] 没有批量下载 WikiArt / Google Arts & Culture / Pinterest 的图
- [ ] 如果公开仓库，确认 `99-附件/` 里没有版权图
"""


PALETTE = """---
{mark}
type: 速查
---

# 配色速查

> [!abstract] 用法
> 每个流派一套六色。写提示词时给**具体颜色名**，不要只写 `colorful`。
> 下面每行都可以直接复制进提示词。

## 全流派配色

{palette_body}

## 跨流派的用色规律

| 想要的感觉 | 配色策略 | 参考流派 |
|---|---|---|
| 庄严、古老 | 低饱和土色 + 金 | [[文艺复兴]]、[[新古典主义]] |
| 戏剧、压迫 | 大面积黑 + 单点暖色 | [[巴洛克]] |
| 轻快、甜美 | 高明度粉彩、几乎无黑 | [[洛可可]] |
| 敬畏、壮阔 | 暗底 + 炽热高光 | [[浪漫主义]] |
| 诚实、沉重 | 土色系、低饱和 | [[现实主义]] |
| 明亮、即时 | 高明度 + **彩色阴影** | [[印象派]] |
| 强烈、主观 | 高饱和非自然色并置 | [[后印象派]]、[[表现主义]] |
| 神秘、奢华 | 宝石色 + 金箔 | [[象征主义]] |
| 优雅、装饰 | 柔和植物色 + 暗金 | [[新艺术运动]] |
| 平面、明快 | 靛蓝 + 朱红 + 米纸 | [[浮世绘]] |
| 浪漫、忧郁 | 宝石色在暗底上发光 | [[拉斐尔前派]] |
| 理性、智性 | 赭灰褐、近乎单色 | [[立体主义]] |
| 怪诞、清澈 | 纯净蓝天 + 焦黄荒地 | [[超现实主义]] |
| 摩登、奢华 | 黑金 + 镀铬 + 深宝石 | [[装饰艺术]] |
| 理性、功能 | **只有三原色 + 黑白灰** | [[包豪斯]] |
| 疏离、迷幻 | 青 + 品红对撞 + 琥珀点缀 | [[赛博朋克]] |

## 配色的三个技术点

1. **阴影不要用黑**。印象派之后，阴影是有颜色的（紫、蓝、青）。
   写提示词时明确 `coloured shadows, no black shadows`。
2. **决定明度关系，比决定色相更重要**。`high key low contrast`（洛可可）
   和 `low key high contrast`（巴洛克）是两种完全不同的画面，
   哪怕色相一样。**明度关系写进提示词。**
3. **点缀色只给一个**。巴洛克的暖金、赛博朋克的琥珀——
   画面里只有一个「暖点」时，其他颜色才会显得冷。
"""


# ------------------------------------------------------------------ 关键词图谱
def _wiki_rows(kind, en_key, zh_key, resolve, by_slug, limit=None):
    """把 WikiArt 的某类分类表渲染成 Markdown 表格行"""
    en = WIKI_TAX.get(en_key) or {}
    zh = WIKI_TAX.get(zh_key) or {}
    rows = []
    for slug, v in sorted(en.items(), key=lambda x: -x[1]["count"]):
        z = (zh.get(slug) or {}).get("name", "")
        tgt = resolve(slug)
        if tgt and tgt in by_slug:
            card = "[[%s]]" % by_slug[tgt]["name_zh"]
        else:
            near = keyword_map.NEAREST.get(slug)
            card = ("≈ [[%s]]" % by_slug[near]["name_zh"]) if near in by_slug else "—"
        rows.append("| %s | %s | %s | %s | %s |"
                    % (v["name"], z or "—", v["count"], card, slug))
        if limit and len(rows) >= limit:
            break
    return rows


def keyword_graph_note(works_map):
    by_slug, resolve = keyword_map.build_index(
        [{"slug": m["slug"], "name_zh": m["name_zh"], "name_en": m["name_en"]} for m in MOVEMENTS])
    A = []
    A.append("---"); A.append(GEN_MARK); A.append("type: MOC"); A.append("---"); A.append("")
    A.append("# 关键词图谱")
    A.append("")
    A.append("> [!abstract] 这一页解决什么问题")
    A.append("> 艺术网站的分类体系互不对齐：WikiArt 用 **218 个 style**，")
    A.append("> Pinterest 用扁平 tag，Art-Ba-Ba 用论坛板块。同一个概念在不同站点有不同名字。")
    A.append("> 这一页把它们**全部投影到本库的流派卡**上，并给出同义词，")
    A.append("> 让你在任何地方看到一个词，都能找到对应的视觉拆解。")
    A.append("")
    A.append("## 一、四个核心关键词的语义簇")
    A.append("")
    for cl in keyword_map.CLUSTERS:
        A.append("### %s · %s" % (cl["key"], cl["en"]))
        A.append("")
        A.append("**对应卡片：** [[%s]]" % by_slug[cl["card"]]["name_zh"] if cl["card"] in by_slug else "**对应卡片：**（未建卡）")
        A.append("")
        A.append(cl["define"])
        A.append("")
        A.append("**容易混淆的地方：**")
        A.append("")
        for t, d in cl["boundary"]:
            A.append("- **%s** —— %s" % (t, d))
        A.append("")
        A.append("**同义词 / 近义词（搜任何一个都能找到同一张卡）：**")
        A.append("")
        A.append("　".join("`%s`" % x for x in cl["synonyms"]))
        A.append("")
        A.append("**关联网卡：** " + " · ".join(
            "[[%s]]" % by_slug[c]["name_zh"] for c in cl["related_cards"] if c in by_slug))
        A.append("")
        A.append("> [!tip] 写提示词时怎么用")
        A.append("> " + cl["prompt_use"])
        A.append("")
    A.append("---")
    A.append("")
    A.append("## 二、WikiArt 全部 %d 个 style → 本库映射" % len(WIKI_TAX.get("styles_en") or {}))
    A.append("")
    A.append("> 这是 WikiArt 的完整风格分类，**没有遗漏**。")
    A.append("> 「本库卡片」列指向对应的流派卡；`—` 表示这个概念本库没有单独建卡")
    A.append("> （通常是已有流派的子变体，比如 Synthetic Cubism 属于 [[立体主义]]）。")
    A.append("")
    A.append("| WikiArt 名称 | 繁中名 | 作品数 | 本库卡片 | slug |")
    A.append("|---|---|---|---|---|")
    A += _wiki_rows("styles", "styles_en", "styles_zh", resolve, by_slug)
    A.append("")
    A.append("## 三、WikiArt 全部 %d 个 art movement" % len(WIKI_TAX.get("movements_en") or {}))
    A.append("")
    A.append("| WikiArt 名称 | 繁中名 | 作品数 | 本库卡片 | slug |")
    A.append("|---|---|---|---|---|")
    A += _wiki_rows("movements", "movements_en", "movements_zh", resolve, by_slug)
    A.append("")
    A.append("## 四、WikiArt 全部 %d 个 genre（题材分类）" % len(WIKI_TAX.get("genres_en") or {}))
    A.append("")
    A.append("> 题材不是风格，但写提示词时同样要指定——同一套风格画肖像和画风景，")
    A.append("> 提示词结构完全不同。")
    A.append("")
    A.append("| 题材 | 繁中名 | 作品数 |")
    A.append("|---|---|---|")
    en = WIKI_TAX.get("genres_en") or {}
    zh = WIKI_TAX.get("genres_zh") or {}
    for slug, v in sorted(en.items(), key=lambda x: -x[1]["count"]):
        A.append("| %s | %s | %s |" % (v["name"], (zh.get(slug) or {}).get("name", "—"), v["count"]))
    A.append("")
    A.append("---")
    A.append("")
    A.append("## 五、怎么用这张图做跨站检索")
    A.append("")
    A.append("网站分类混乱，所以不要用它们的分类词检索——**用本库的卡片名做锚点**：")
    A.append("")
    A.append("1. 在本页搜到那个陌生词，看它映射到哪张卡")
    A.append("2. 打开那张卡，抄走它的「风格 + 光照 + 色彩 + 媒介」四层")
    A.append("3. 拿这四层英文术语去任何网站搜图（WikiArt / Pinterest / 美术馆站）")
    A.append("4. 找到参考图后用 [[反推工具链]] 里的工具反推，再填回 [[提示词卡模板]]")
    A.append("")
    A.append("> [!tip] 一个实用的检索串")
    A.append("> 流派卡的「风格」层就是最好的检索词。例如搜 `tenebrism chiaroscuro`")
    A.append("> 比搜「巴洛克」能找到精确得多的参考图——因为前者是技法术语，后者是时代标签。")
    A.append("")
    A.append("## 六、关于 Pinterest 与 Art-Ba-Ba")
    A.append("")
    A.append("这两个站点**本机网络无法访问**（实测：DNS 被内网代理拦截，连接超时），")
    A.append("详细情况与替代方案见 [[数据源与访问限制]]。")
    A.append("")
    return "\n".join(A)


# ------------------------------------------------------------------ 数据源与访问限制
ACCESS = """---
{mark}
type: 说明
---

# 数据源与访问限制

> [!warning] 先说结论
> **WikiArt 已完整检索**（218 styles / 189 movements / 68 genres 全部入库，见 [[关键词图谱]]）。
> **Pinterest 与 Art-Ba-Ba 在本机网络下无法访问**——不是没试，是网络层被拦截。
> 下面是实测记录和替代方案。
>
> **想直接看「怎么用」而不是「为什么不行」→ [[外部站点接入方案]]**，
> 里面有深链跳转、官方 API 导出、第三方仓库三条路线。

## 一、WikiArt：能访问，已全量抓取

| 检查项 | 实测结果 |
|---|---|
| `robots.txt` | `User-agent: *` / `Allow: /` —— 允许抓取 |
| 站点地图 | 公开 `sitemap_index.xml`，含 6 个 paintings 分片（每片 4 万条） |
| 页面渲染 | 服务端渲染，curl 直接拿 HTML |
| 图片直链 | 可下载（`!Large.jpg` 约 750px） |
| 分类体系 | **218 styles / 189 art movements / 68 genres / 230 media** —— 已全部解析入库 |
| 反爬 | 有 Cloudflare，普通 UA 可通过，高频会触发验证 |

### 本库怎么用它

| 做法 | 是否采用 | 原因 |
|---|---|---|
| 抓取全部分类体系（名称、作品数、中英对照） | ✅ | 分类体系是事实性数据，用于建索引 |
| 在笔记里放 WikiArt 作品页链接 | ✅ | 只作线索 |
| **下载 WikiArt 的图片进仓库** | ❌ | 版权作品在 WikiArt 上是靠「合理使用」展示的低分辨率副本 |
| **把 WikiArt 的图用于训练** | ❌ | 同上 |

所以本库的策略是：**WikiArt 提供分类骨架，开放数据源提供图片**。
图片全部来自 CC0 / 公共领域（克利夫兰、大都会、维基共享资源）。

## 二、Pinterest：无法访问

| 检查项 | 实测结果 |
|---|---|
| DNS 解析 | `198.18.0.76` —— RFC 2544 保留段，说明被内网代理接管 |
| HTTPS 连接 | `http=000`，连接失败（甚至连 `robots.txt` 都拿不到） |
| 官方 API | `api.pinterest.com/v5/search/pins` 同样不可达 |

### 即使能连上，也不该爬

Pinterest 的开发者条款明确禁止抓取；其官方 API **不提供公开的图片搜索接口**
（只能访问你自己授权的 board），搜索 API 早已下线。
所以「用 API 搜关键词找图」这条路在 Pinterest 上本来就不存在，
唯一可行的是人工浏览 + 手动收藏。

### 替代方案（本库已采用）

Pinterest 的价值是**视觉发现**，不是**结构化数据**。用下面这些替代：

| 需求 | 替代工具 |
|---|---|
| 按风格找参考图 | 本库的流派卡 + [[反推工具链]] 里的开放数据源 |
| 找当代/先锋类视觉 | [Artsy](https://www.artsy.net)（本机可访问）、[WikiArt 当代部分](https://www.wikiart.org/en/paintings-by-style/contemporary) |
| 反推参考图的提示词 | CLIP Interrogator / JoyCaption（见 [[反推工具链]]） |
| 关键词扩展 | [[关键词图谱]] 里的同义簇 |

**完整的接入方案见 [[外部站点接入方案]]**，三条路线各有适用场景：

| 路线 | 能用吗 | 说明 |
|---|---|---|
| 深链跳转 | ✅ 现在就能用 | [[外部检索入口]] 已给 141 个流派生成好链接 |
| 官方 API 导出自己的收藏 | ✅ 需申请 token | `_scripts/pinterest_export.py` |
| 官方 API 搜全站 | ⚠️ beta 门禁 | `/v5/search/partner/pins`，只返回前 10 条 |
| 第三方抓取仓库 | ⚠️ 违反 ToS 且本机不通 | 见 [[外部站点接入方案]] |

## 三、Art-Ba-Ba（art-ba-ba.com）：无法访问

| 检查项 | 实测结果 |
|---|---|
| DNS 解析 | `198.18.0.70` —— 同样是内网代理段 |
| HTTP | 连接超时（15 秒无响应） |
| HTTPS | `SSL_ERROR_SYSCALL`，握手失败 |
| `robots.txt` | 拿不到 |

Art-Ba-Ba 是中国当代艺术的老牌论坛，它的价值在于**中文艺术圈的话语与关键词**，
而不在于图片（论坛图片多为展览现场与作品翻拍，版权状态复杂）。

### 替代方案

中文当代艺术的关键词扩展，已经用另一条路完成：
**WikiArt 的官方中文分类名**（`zh` 站点，218 个 style 的繁中名已全部抓取，
见 [[关键词图谱]]），加上 [[关键词图谱]] 里手工整理的同义簇。

> [!note] 如果你能提供访问方式
> 如果 Art-Ba-Ba 或 Pinterest 在你的网络下可访问，把页面保存成 HTML 放进仓库，
> 我可以写一个解析脚本把它们的话题标签也并进 [[关键词图谱]]。
> 当前 `_scripts/` 的架构已经支持新增数据源，只需要加一个解析函数。

## 四、本机网络的可达性实测

> [!danger] 重要更正：curl 不通 ≠ 站点不通
> 之前用 `curl` 测出 Pinterest 全部 `http=000`，就下了「无法访问」的结论——**这是错的**。
> 后来发现：**同一个 URL，`curl` 返回 000，Python `requests` 返回 200 并拿到 1MB 真实 HTML**。
> 出口代理在做 TLS 指纹识别，拦 `curl` 的握手但放过 Python。
>
> **结论：判断一个站点能不能用，必须用最终要用的那个客户端去测，不能用 curl 代测。**

| 站点 | curl | Python requests |
|---|---|---|
| www.pinterest.com | ❌ 000 | ✅ **200（1MB HTML）** |
| api.pinterest.com | ❌ 000 | ✅ 401（可达，只差 token） |
| i.pinimg.com（图床） | ❌ 000 | ✅ 可下载原图 |
| art-ba-ba.com | ❌ 000 | ❌ 仍不通 |
| www.google.com | ❌ 000 | — |

| 站点 | curl 结果 |
|---|---|
| www.wikiart.org | ✅ 200 |
| commons.wikimedia.org | ✅ 301 |
| www.metmuseum.org | ✅（限流 429，需退避） |
| openaccess-api.clevelandart.org | ✅ |
| www.artsy.net | ✅ 200 |
| www.bing.com | ✅ 302 |
| www.google.com | ❌ 000 |
| www.behance.net | ❌ 000（未用 Python 复测） |
| art-ba-ba.com | ❌ 000 |

> 所有域名都解析到 `198.18.0.x`，说明出口经过一层白名单代理。
> 这份表可以用来判断某个新数据源是否值得写抓取脚本。
"""


# ------------------------------------------------------------------ 外部站点接入方案
EXTERNAL = """---
{mark}
type: 说明
---

# 外部站点接入方案

> [!abstract] 结论先行
> Pinterest 有**三条**接入路径，从最稳到最野：
> **① 深链跳转 → ② 官方 API → ③ 第三方仓库 → ④ 本库自带的分类爬虫（已实测成功，212 张入库）**。
> **实测更正**：Pinterest 并非不可访问——`curl` 被代理拦截，但 **Python `requests` 完全正常**。
> 全站关键词搜索只有官方 API 的 beta 端点提供，需要单独申请。

## 一、路线 ①：深链跳转 —— 现在就能用

不需要任何 token、不违反任何条款。因为**用你自己浏览器里的登录会话去访问**，
和你在地址栏里敲是一样的性质。

已生成好：**[[外部检索入口]]**（141 个流派 × 7 个入口）。

| 入口 | URL 模式 |
|---|---|
| Pinterest 搜图 | `https://www.pinterest.com/search/pins/?q=<关键词>` |
| Pinterest 搜板 | `https://www.pinterest.com/search/boards/?q=<关键词>` |
| Artsy | `https://www.artsy.net/search?q=<关键词>` |
| WikiArt | `https://www.wikiart.org/en/paintings-by-style/<slug>` |
| 维基共享 | `https://commons.wikimedia.org/w/index.php?search=<关键词>&title=Special:MediaSearch&type=image` |
| Bing / Google 图片 | 标准图片搜索 URL |

> [!tip] 关键词怎么选最有效
> 脚本生成时用的是**技法术语**（`tenebrism chiaroscuro caravaggesque lighting`），
> 不是风格名（`baroque`）。Pinterest 的标签是用户随手打的扁平体系，
> 精确技法词的命中率明显更高。

## 二、路线 ②：官方 API —— 只能拿自己的数据，全站搜索要申请

Pinterest API v5 一共只有 **3 个 search 端点**，能力差别很大：

| 端点 | 能搜什么 | 限制 |
|---|---|---|
| `GET /v5/search/partner/pins` | **按关键词搜全站 pin** | ⚠️ **beta，需要单独申请**，且只返回 **前 10 条** |
| `GET /v5/search/pins` | 只搜**你自己账号**的 pin | 搜不到别人的 |
| `GET /v5/search/boards` | 只搜**你自己账号**的 board | 同上 |

这是官方文档的原话（`/search/partner/pins`）：

> "This endpoint is currently in beta and not available to all apps."
> "Get the top 10 Pins by a given search term."

也就是说：**「用 API 按关键词搜全站图」这条路是存在的，但被 beta 门禁挡着，
而且一次只给 10 条**。想要就得到 [developers.pinterest.com](https://developers.pinterest.com/)
申请 advanced access。

### 但「导出自己的收藏」完全可行，而且很实用

这条链路没有任何障碍。推荐工作流：

```
Pinterest 上人工策展（搜索、收藏、分板）
        ↓  官方 API：boards:read + pins:read
_scripts/pinterest_export.py
        ↓
20-我的提示词/Pinterest-<板子名>.md   （每张 pin 一条 + 原图直链）
        ↓  [[反推工具链]] 反推提示词
[[提示词卡模板]]
```

脚本已经写好了：`_scripts/pinterest_export.py`（纯标准库，无依赖）。

```bash
cd _scripts
export PINTEREST_TOKEN=你的token
python3 pinterest_export.py --boards            # 先列出你的板子
python3 pinterest_export.py --export "艺术参考"  # 导出某个板子
python3 pinterest_export.py --export-all --download   # 全部导出并下图
```

申请步骤：建 app → 申请 `boards:read` + `pins:read` scope → 走 OAuth 拿 token。
导出结果写进 `20-我的提示词/`，那个目录**不会被 build_vault.py 覆盖**。

## 三、路线 ③：第三方仓库 —— 能用，但要知道代价

GitHub 上确实有一批（实测数据，2026-09 查）：

| 仓库 | 星 | 语言 | 最近更新 | 用途 |
|---|---|---|---|---|
| [limkokhole/pinterest-downloader](https://github.com/limkokhole/pinterest-downloader) | 454★ | Python | 2024-08 | **Python 命令行脚本**，支持 username/board/section/pin 四种输入，支持 cookie 与代理 |
| [seregazhuk/php-pinterest-bot](https://github.com/seregazhuk/php-pinterest-bot) | 416★ | PHP | 2020-05 | 用自己账号操作 Pinterest（老，可能已失效） |
| [sokomishalov/skraper](https://github.com/sokomishalov/skraper) | 348★ | Kotlin | 2026-08 | 多站点抓取库（含 Pinterest），活跃 |
| [xjdeng/pinterest-image-scraper](https://github.com/xjdeng/pinterest-image-scraper) | 246★ | Python | 2020-08 | 给一个 board URL，返回全部图片链接 |
| [pinterest/api-quickstart](https://github.com/pinterest/api-quickstart) | 205★ | Python | 2026-04 | **官方**的 API 上手示例 |
| [sean1832/pinterest-dl](https://github.com/sean1832/pinterest-dl) | 196★ | Python | 2026-07 | 非官方媒体下载器，活跃 |
| [sokomishalov/skraper](https://github.com/sokomishalov/skraper) 的 CLI | 348★ | Kotlin/JVM | 2026-08 | 多站点，**需要 Java 1.8+**，本机没有 Java |
| [iamatulsingh/pinscrape](https://github.com/iamatulsingh/pinscrape) | 154★ | Python | 2026-08 | 抓 Pinterest 图片，活跃 |

> [!warning] 三条必须先知道的事
> 1. **违反 ToS**：Pinterest 开发者条款禁止未经授权的抓取。上面除 `pinterest/api-quickstart`
>    外都是非官方的，用于个人备份风险不大，用于分发或商业用途风险自担。
> 2. **本机网络不通**：这些脚本在**这台机器上全都跑不起来**——
>    `www.pinterest.com` 与 `api.pinterest.com` 的 DNS 都被内网代理劫持到 `198.18.0.x`，
>    连接直接超时。它们只有在**你自己的网络环境**下才有意义。
> 3. **图片版权归原作者**：Pinterest 是二次聚合平台，上面的图没有统一授权，
>    **不要**像本库的 CC0 图那样自由分发。只做个人参考。

### 如果要在自己机器上跑，推荐哪个

- **只想把某个板子存下来** → `limkokhole/pinterest-downloader`（Python 脚本，已放进 `_scripts/vendor/`）
- **想写成脚本批量处理** → `sokomishalov/skraper`（多站点、维护活跃）或 `iamatulsingh/pinscrape`
- **想走官方且合规** → 用本库的 `pinterest_export.py` + [pinterest/api-quickstart](https://github.com/pinterest/api-quickstart)

## 四、Art-Ba-Ba

| 检查项 | 实测结果 |
|---|---|
| DNS | `198.18.0.70`（内网代理段，黑洞） |
| HTTP / HTTPS | 超时 / `SSL_ERROR_SYSCALL` |
| `robots.txt` | 拿不到，**无法确认其抓取政策** |
| 已知的 GitHub 仓库 | 未搜到针对该站的专用工具（它是个老式 BBS，没有公开 API） |

你给的板块地址已经放进 [[外部检索入口]] 的每个流派条目里，可以直接点开。

> [!note] 如果你希望把它也接进来
> 把页面另存为 HTML 放进 `_scripts/`，我写个解析器把它的帖子标题与标签
> 并进 [[关键词图谱]]。当前架构已经支持加数据源——在 `providers.py`
> 写一个返回统一字段的解析函数即可。

## 五、一句话决策表

| 你的需求 | 走哪条 |
|---|---|
| 想按关键词看参考图 | **路线 ① 深链**（[[外部检索入口]]），浏览器里点 |
| 想把自己 Pinterest 的收藏搬进仓库 | **路线 ②** 官方 API + `pinterest_export.py` |
| 想要全站关键词搜索结果进数据集 | **路线 ②** 的 beta 端点，去申请 advanced access |
| 就不想申请、愿意担风险 | **路线 ③** 第三方仓库，但在自己网络下跑 |
| 想要能自由分发的图 | 都别用，走 [[版权与来源]] 里的 CC0 开放数据源 |
"""


# ------------------------------------------------------------------ AI 调用指南
AI_GUIDE = """---
{mark}
type: 说明
---

# AI 调用指南

> [!abstract] 这一页解决什么
> 让 AI（Claude / Cursor / DSH / 自建 agent）能**主动调取这个仓库**，
> 在你有一个创意想法时，帮你从 141 个流派里取料、拼成可用的提示词。
>
> 仓库提供了三层接口，按你的技术栈挑一个：
> **CLI（最通用）→ MCP 服务（最省事）→ JSON 导出（最灵活）**。

## 一、三层接口

| 接口 | 文件 | 谁用 |
|---|---|---|
| **命令行** | `_scripts/artvault.py` | 任何能执行 shell 的 AI，无需配置 |
| **MCP 服务** | `_scripts/mcp_server.py` | Claude Desktop / Cursor / Cline 等支持 MCP 的客户端 |
| **JSON 导出** | `artvault.py dump` | 你要自己接进别的程序或做 RAG |

三者共用 `_scripts/artvault_core.py` 的同一套逻辑，行为一致。

## 二、命令行（推荐先从这个开始）

```bash
cd "_scripts"
python3 artvault.py categories                 # 6 大分类
python3 artvault.py list --with-images          # 有实图的流派
python3 artvault.py search "霓虹 雨夜"           # 模糊检索
python3 artvault.py layers 巴洛克                # 只要七层提示词（最省 token）
python3 artvault.py show 印象派                  # 完整卡片
python3 artvault.py palette 印象派               # 配色
python3 artvault.py related 立体主义             # 关联流派
```

**给 AI 的调用约定**：任何命令加 `--json` 都会输出机器可读的 JSON。例如

```bash
python3 artvault.py --json layers 巴洛克
```

### 组合提示词：把创意想法变成分层提示词

```bash
# 自然语言：自动识别提到的流派，按意图词分配层级
python3 artvault.py compose "雨夜霓虹街头的赏金猎人，要巴洛克的光照，赛博朋克的构图" \\
        --subject "a female bounty hunter in a wet neon alley"

# 显式跨流派混搭
python3 artvault.py compose --style ukiyo-e --lighting baroque \\
        --color vaporwave --composition precisionism --subject "a lone samurai"
```

输出包含：**分层结果 + 正向提示词 + 负向提示词 + 配色 + 视频层 + 冲突警告**。

> [!warning] 跨流派混搭的真实陷阱
> 把不同流派的负向词合并会**打架**。实测例子：
> 浮世绘要求 `no cast shadows`，而巴洛克的光照层恰恰要 `deep crushed shadows`；
> 精确主义的负向词里有 `people / figures`，你的主体却是个武士。
> `compose` 会把这些冲突**逐条列出来**，用之前先删掉对应词。

## 三、MCP 服务（一次配置，长期可用）

在客户端配置里加上（以 Claude Desktop 为例，路径换成你的实际位置）：

```json
{
  "mcpServers": {
    "artvault": {
      "command": "python3",
      "args": ["{MCP_PATH}"]
    }
  }
}
```

配置文件的常见位置：

| 客户端 | 路径 |
|---|---|
| Claude Desktop (macOS) | `~/Library/Application Support/Claude/claude_desktop_config.json` |
| Cursor | `~/.cursor/mcp.json` |
| Cline / 其他 | 见各自文档 |

暴露的工具：

| 工具 | 作用 |
|---|---|
| `search_movements(query, limit)` | 检索流派 |
| `get_movement(slug)` | 完整卡片 |
| `get_layers(slug)` | 只要七层提示词（省 token） |
| `compose_prompt(brief, subject, style, lighting, …)` | **拼提示词** |
| `get_palette(slug)` | 配色 |
| `find_related(slug)` | 关联流派 |
| `list_categories()` | 分类概览 |

纯标准库实现，**不需要 `pip install mcp`**。

## 四、给 AI 的提示词怎么写

在你的 agent 系统提示里加一段：

```text
你有一个艺术风格知识库，通过 artvault 工具访问。
当用户描述一个视觉创意时：
1. 先用 search_movements 找出相关的 2–4 个流派
2. 用 get_layers 取它们的提示词层
3. 用 compose_prompt 拼成完整提示词，注意检查返回的 conflicts 字段
4. 输出时说明每一层来自哪个流派，以及为什么这样搭配

不要凭记忆编造风格词——库里有 141 个流派，覆盖从拜占庭到 Y2K，
所有术语都以库里的为准。
```

> [!tip] 为什么强调「以库里的为准」
> 大模型对艺术流派的记忆是模糊的、容易把相近的搞混（比如把 Art Nouveau
> 和 Art Deco 的视觉特征混在一起）。这个库的价值就是给出**具体到光照、
> 色彩、媒介**的可执行描述，而不是一个风格名词。

## 五、Pinterest 投递箱：人找图，AI 拆解

`pinterest/` 是投递箱。分工是：**你负责找图和判断，AI 负责拆解和归档。**

```
你把图丢进 pinterest/
        ↓  说「处理 pinterest 投递箱」
python3 _scripts/ingest_inbox.py --scan     ← 客观测量：尺寸/主色/感知哈希/配色最近的流派
        ↓  AI 逐张 read_image 看图
七层拆解 + 匹配 1–3 个流派 + 可复用提示词
        ↓  写入
20-我的提示词/投递箱-<日期>.md
        ↓
python3 _scripts/ingest_inbox.py --archive  ← 图移到 pinterest/_已归档/
```

为什么这样分工：Pinterest 的搜索是登录态、个性化的，
**你手动挑的图比任何爬虫抓的都准**（爬虫只能按分类抓，见 [[Pinterest 抓取实战]]）。
而拆解是机械劳动，正好交给 AI。

脚本做客观测量，AI 做语义判断——两者都做自己擅长的。
配色距离那类数字**只是参考信号**：实测有张土色系的调色板照片，
配色距离算出来最接近「现实主义」，但那是土色重合，不是风格相近。

## 六、和 Obsidian 里的笔记怎么配合

| 场景 | 用哪个 |
|---|---|
| 你想**读**、建立审美直觉 | Obsidian 里看 [[流派总览]] 和流派卡 |
| 你想**查**某个词是什么 | Obsidian 里搜 [[关键词图谱]] |
| 你想**用**、生成东西 | 让 AI 调 `artvault` |
| 你想**存**自己的成果 | [[提示词卡模板]] 存到 `20-我的提示词/` |

> 仓库里的 Markdown 是给人看的，`artvault` 是给机器用的。两者同源——
> 都从 `_scripts/mv_*.py` 生成，改一处两边都更新。

## 七、把这套方法复制给别人

这套流程已经打包成 skill：**`build-art-aesthetic-vault`**。

别人只要装了 Obsidian + Python，把这个 skill 丢给 AI 说一句
「用 build-art-aesthetic-vault 帮我建一个艺术审美库」，
就能得到一套**结构相同**的库（同样的 141 个流派、同样的七层结构、
同样的 AI 接口），只是图片会重新从开放数据源抓一遍。

| 内容 | 说明 |
|---|---|
| `SKILL.md` | 8 个阶段的执行流程 |
| `assets/scripts/` | 全部脚本，含 141 个流派的完整定义 |
| `assets/data/` | WikiArt 完整分类体系存档 |
| `reference/method.md` | 七层拆解法 |
| `reference/pitfalls.md` | **最值钱的一份**：所有踩过的坑 |
| `reference/sources.md` | 数据源端点与授权分级 |

分发包在 `~/Desktop/创造一切可能/艺术审美库-skill.zip`。

> [!tip] 为什么值得复制
> 这套库真正的价值不在图片——图片可以从开放数据源重抓。
> 价值在**141 个流派的七层结构**（约 5700 行定义）和
> **那份踩坑记录**：每一条都真实发生过并导致过返工。
> 照着流程走不会踩，自己重新发明一定会踩。

## 八、维护

```bash
cd _scripts
python3 artvault.py categories        # 自检：能跑通说明数据没问题
python3 build_vault.py                # 改了 mv_*.py 后重新生成笔记
python3 make_links.py                 # 重新生成外部检索入口
```

`artvault_core.py` 直接从 `movements.py` 读定义，**不依赖生成的 Markdown**，
所以你新加一个流派后，CLI 和 MCP 立刻就能搜到，不需要重新构建笔记。
"""


# ------------------------------------------------------------------ Pinterest 抓取实战
PINT = """---
{mark}
type: 说明
---

# Pinterest 抓取实战

> [!success] 结论：已经抓到 212 张真实图片
> `99-附件/images/pinterest/` 下有 **12 个板、212 张原图**，
> 对应的笔记在 `20-我的提示词/Pinterest-*.md`。
> 用 `_scripts/pinterest_grab.py` 复现，纯 Python，不需要浏览器、不需要登录、不需要 token。

## 一、最关键的一条经验

**`curl` 连不上 ≠ 站点连不上。**

| 客户端 | www.pinterest.com |
|---|---|
| `curl` | ❌ `http=000`（TLS 握手被代理拦截） |
| Python `requests` | ✅ `http=200`，1 MB 真实 HTML |
| Python `requests` → `i.pinimg.com` | ✅ 原图可直接下载 |

出口代理在做 **TLS 指纹识别**：它拦 `curl` 的握手，但放过 Python/OpenSSL。
所以之前「Pinterest 无法访问」的判断是**用错了测试工具**得出的。

> [!tip] 这条经验的通用价值
> 以后判断任何站点是否可用，**必须用你最终要用的那个客户端去测**。
> 我在这台机器上已经把 WikiArt、Commons、大都会、克利夫兰都测通了，
> 唯独漏了用 Python 复测 Pinterest。

## 二、实测能做什么、不能做什么

| 路径 | 结果 | 说明 |
|---|---|---|
| `GET /ideas/` | ✅ | 返回 10 个顶层分类 + 数字 ID |
| `GET /ideas/<分类>/<ID>/` | ✅ | **服务端渲染**，约 20 张原图 + 5 个子分类 |
| `GET i.pinimg.com/originals/...` | ✅ | 原图直接下载 |
| `GET /resource/BaseSearchResource/get/` | ❌ 403 | `Invalid Resource Request`。**已交叉验证**：`pinscrape`（2026-08 仍在维护）用的是同一个端点，同样 403；补上从页面提取的 `X-APP-VERSION=cad034b` 也无效 |
| `GET /ideas/<任意关键词>/` | ⚠️ 200 但无图 | 必须有数字 ID，关键词解析到空页 |
| `GET /search/pins/?q=X` | ⚠️ 200 但无图 | 页面是 JS 渲染，pin 数据不在 HTML 里 |
| `GET /v5/search/partner/pins` | 🔒 401 | 官方 API 可达，但需要 OAuth + beta 权限 |

**一句话：按分类抓可以，按关键词搜不行——而且这不是我的实现问题。**

为了确认这一点，我把三个第三方工具都装了一遍实测：

| 工具 | 结果 |
|---|---|
| `pinscrape`（MIT，154★，2026-08 更新） | 安装成功，`search()` 同样返回 **403 Invalid Resource Request** |
| `limkokhole/pinterest-downloader`（MIT，454★） | 依赖装好，能跑；但走的是 pin/board 页面，**没有关键词搜索功能** |
| `sokomishalov/skraper`（Apache-2.0，348★） | **跑不了**——需要 Java 1.8+，本机没有 Java，发布页也没有免 Java 的原生二进制 |

连一个专门做这件事、上个月还在更新的库都拿不到，说明 **Pinterest 已经把这个非官方端点封了**。
想要关键词搜索，只剩官方 API 的 beta 端点这一条合法通道（见 [[外部站点接入方案]]）。

关键词检索请用 [[外部检索入口]] 的深链在你自己的浏览器里做——
那才是 Pinterest 的强项（它的搜索是登录态的、个性化的）。

## 三、怎么用爬虫

> [!note] 依赖装在哪
> `requests` 等依赖装在 **`_scripts/vendor/libs/`**（约 170 MB），
> 已经写进 `.gitignore`，不进 git、也不影响 Obsidian 索引。
> 换机器时需要重装一次：
> ```bash
> cd _scripts/vendor
> pip3 install --target ./libs -r pinterest-downloader-requirements.txt requests
> ```

```bash
cd _scripts/vendor
export PYTHONPATH=./libs          # 依赖装在仓库本地，不污染系统

# 看有哪些分类
python3 ../pinterest_grab.py --discover

# 抓指定分类（含子分类）
python3 ../pinterest_grab.py --crawl art design --max-per 20

# 抓全部 10 个分类
python3 ../pinterest_grab.py --crawl-all --max-per 15

# 只抓某个具体板
python3 ../pinterest_grab.py --url /ideas/oil-painting/907077517247/
```

产出两个地方：

| 位置 | 内容 |
|---|---|
| `99-附件/images/pinterest/<板名>/` | 原图，文件名是 Pinterest 的 hash |
| `20-我的提示词/Pinterest-<板名>.md` | 每张图一条，带原图直链；**不会被 build_vault 覆盖** |

脚本内置：1.5 秒／请求的礼貌限速、失败重试、Pinterest logo 自动排除。

## 四、版权（这一条比技术重要）

> [!warning] Pinterest 的图和本库的 CC0 图性质完全不同
> - 本库 `10-流派/` 里的图来自克利夫兰、大都会、维基共享，是 **CC0 / 公共领域**，可以自由分发、可以训练模型。
> - Pinterest 上的图是**二次聚合**的，版权归各自原作者，**没有统一授权**。
>
> 所以：
> - ✅ 自己看、做审美参考、反推提示词 —— 没问题
> - ❌ 把 `99-附件/images/pinterest/` 传到公开仓库 —— 不要
> - ❌ 拿去做训练集然后发布 —— 不要
>
> 脚本抓的是**公开的 `/ideas/` 页面**（不需要登录的部分），但 Pinterest 的
> 服务条款仍然禁止未经授权的自动化访问。个人参考用途风险不大，分发就是另一回事了。

## 五、接下来怎么用这些图

抓到只是第一步。建议的回路：

```
Pinterest 上的参考图
    ↓  用 [[反推工具链]] 里的 CLIP Interrogator / JoyCaption 反推
    ↓  artvault 帮你把反推结果归到七层
python3 artvault.py compose --style ... --lighting ... --subject "..."
    ↓
存成 [[提示词卡模板]] 放进 20-我的提示词/
```

> [!tip] 让 AI 帮你做这一步
> 直接对 AI 说：「看一下 `20-我的提示词/Pinterest-oil-painting.md`，
> 把里面的图按视觉特征归类，然后给每类拼一个提示词模板」。
> AI 能读 Markdown、能调 [[AI 调用指南|artvault]]，这条路是通的。

## 六、还想抓更多？

`pinterest_grab.py` 的 `discover()` 会自动展开子分类。目前只展开了一层，
把 `discover()` 里的递归加深就能拿到更细的板（如
`/ideas/oil-painting/907077517247/` 下面还可能有更细的分类）。

另外官方 API 的 beta 端点如果申请下来，就能做**真正的关键词搜索**——
那是唯一合法的全站搜索通道。见 [[外部站点接入方案]]。
"""


README_EN = """<div align="center">

# Art Aesthetic Style Library

**141 art movements, decomposed into swappable AI prompt layers**

Byzantine to Y2K ｜ East & South Asia · Islamic ｜ Photography ｜ Digital subcultures

163 notes · 372 public-domain images · 21 ready-to-run scripts

**English** ｜ [中文](README.md)

</div>

---

## What is this

Most "art style reference" collections are just image folders. You save a few hundred
pictures, and then when it's time to actually use them you don't know what to look at
or how to describe it. The images are dead weight.

This library does something different: **it breaks each movement's visual language into
seven layers that can be swapped independently.**

```
Subject  +  Style  +  Lighting  +  Color
         +  Composition  +  Medium  +  Mood  +  Camera
```

Once it's layered, you can take the **lighting** from one painting and put it on the
**subject** of a completely different one. That's what a reference library is actually for.

> ### A note on language
> **The prompt layers are already in English** - they're what you paste into a model.
> Only the explanations (visual breakdowns, pitfalls, why-it-works notes) are in Chinese.
> If you only want the prompts, you can use this library as-is.

### See it work

Say you want a bounty hunter in a neon-lit alley, but with classical painting light:

```
python3 artvault.py compose "雨夜霓虹街头的赏金猎人，要巴洛克的光照，赛博朋克的构图" --subject "a female bounty hunter in a wet neon alley"
```

It recognises that "巴洛克" (Baroque) is followed by "光照" (lighting) and takes
Baroque's lighting layer; Cyberpunk supplies style and composition. Output:

```
a female bounty hunter in a wet neon alley,             <- your subject
cyberpunk, neo-noir concept art, dense neon signage,    <- Style layer (Cyberpunk)
single hard light source from off-frame,                <- Lighting layer (Baroque)
deep crushed shadows, candlelight rim light,
cyan and magenta clash, amber accent, deep black,       <- Color layer (Cyberpunk)
low angle looking up at megastructures,                 <- Composition layer (Cyberpunk)
alienated, oppressive, intoxicating                     <- Mood layer
```

**Same subject, every layer independently replaceable.** That's the difference between
this and piling up style keywords.

---

## Skill tree

```
{skill_tree_en}
```

---

## What's inside

| | |
|---|---|
| **Movement cards** | **141**, in 6 categories. Each has a 6-axis visual breakdown, 7 prompt layers, a 6-color palette, a video layer, and known failure modes |
| **Public-domain images** | **372** (134 MB), covering 79 movements |
| **Guides & methodology** | 18 notes (overview, keyword atlas, the 7-layer method, video structure, palette index, reverse-engineering toolkit...) |
| **Keyword atlas** | All **218 styles / 189 movements / 68 genres** mapped to a card |
| **Note templates** | 3 |
| **Scripts** | 21 - fetch, generate, search, compose, MCP server |

> **62 movements are "prompt-only cards."** Abstract Expressionism, Pop Art, Minimalism,
> Conceptual Art, Cyberpunk, Vaporwave and others are still in copyright, so no open data
> source will supply images. Their visual language and 7-layer structure are documented
> exactly the same way - just without pictures. This is deliberate, not a gap.

---

## How to use

### 1. As an Obsidian vault

Open the folder in Obsidian. Recommended entry points:

- `00-导航/提示词拆解方法.md` - **start here**, it explains the 7 layers
- `00-导航/流派总览.md` - overview of all 141 movements
- `10-流派/` - pick a movement, read its full breakdown
- `00-导航/关键词图谱.md` - look up any unfamiliar style term

### 2. From the command line (or let an AI drive it)

```bash
cd _scripts

python3 artvault.py categories              # 6 categories, 141 movements
python3 artvault.py search "neon rain"      # fuzzy search, Chinese or English
python3 artvault.py layers baroque          # just the 7 prompt layers
python3 artvault.py show ukiyo-e            # full card
python3 artvault.py palette cyberpunk       # 6-color palette
python3 artvault.py related cubism          # find related movements
python3 artvault.py --json layers baroque   # machine-readable
```

**The core feature is composition:**

```bash
# Explicit cross-era mixing
python3 artvault.py compose --style ukiyo-e --lighting baroque --color vaporwave --composition precisionism --subject "a lone samurai"
```

It **detects and prints layer conflicts.** When you mix movements, their negative prompts
fight each other - ukiyo-e forbids `cast shadows` while Baroque lighting *requires*
`deep crushed shadows`; Precisionism forbids `people` while your subject is a person.
**The model won't error**, it just produces subtly worse images that are very hard to debug.
This check saves hours.

### 3. Install as an AI skill (recommended)

The repo ships a skill. Once installed, **any skill-aware AI assistant** will consult
this library automatically for visual/aesthetic tasks instead of inventing movement
terminology from memory.

```bash
cd skill && ./install.sh
```

It **symlinks** the skill into every skill directory present on your machine:

| Directory | Read by |
|---|---|
| `~/.agents/skills/` | DSH / Codex / general convention |
| `~/.claude/skills/` | Claude Code |
| `~/.codex/skills/` | Codex |

**Why symlink:** the skill resolves its own real path via `pwd -P`, derives the repo
root from it, and therefore **finds the vault wherever it lives - no configuration,
survives moving the repo**. No path is hardcoded anywhere in the skill.

```bash
./install.sh --copy        # copy instead of symlink (breaks if you move the repo)
./install.sh --uninstall   # remove
bash locate.sh             # manual vault lookup (for troubleshooting)
```

Start a **new AI session** for it to take effect.

### 4. As an MCP server (Claude Desktop / Cursor)

```json
{
  "mcpServers": {
    "artvault": {
      "command": "python3",
      "args": ["<absolute path to this repo>/_scripts/mcp_server.py"]
    }
  }
}
```

7 tools: `search_movements` `get_movement` `get_layers` `compose_prompt`
`get_palette` `find_related` `list_categories`. Pure standard library -
**no `pip install mcp` needed**.

---

## Why it's different

### 1. Not an image pack - a composable structure

An image pack gives you "what this feels like." This gives you "how to make it."
Every layer can be lifted out on its own. Swap the subject but keep the style layer,
and you have a style-transfer template.

### 2. Lighting is pulled out as its own layer

Most people write prompts as one undifferentiated blob and then debug by trial and error.
This library makes an explicit claim: **lighting affects the final texture more than the
style keywords do.** Every movement's lighting layer is a separate snippet you can drop
onto an unrelated subject.

### 3. Every movement has *targeted* negative prompts

**The specific failure modes of that movement**:

- Impressionism → `black shadows, smooth blending, photorealistic`
- Renaissance → `visible brushstrokes, impasto` (AI defaults to thick oil paint; Renaissance surfaces are smooth)
- Ukiyo-e → `3d shading, cast shadows, gradient` (AI adds volume automatically; ukiyo-e is flat)

**Note that different movements' negative prompts are often opposites** - which is exactly
why mixing them breaks, and exactly what this library manages for you.

### 4. Usable by AI, not just by you

LLMs have fuzzy memories about art movements and routinely confuse Art Nouveau with
Art Deco, or Barbizon with Impressionism. This library pins down concrete terminology
for 141 movements, so an AI calling it won't make things up.

### 5. Completeness is verifiable

The keyword atlas maps **all 218 styles / 189 movements / 68 genres** onto cards.

### 6. Public domain only - no second thoughts

All images come from CC0 / public-domain open sources. Free to use, modify,
redistribute, and train on.

### 7. Extensible

Adding a movement means adding one entry to one Python file. Image fetching, note
generation, keyword mapping and the AI interfaces all follow automatically.

---

## Quick start

```bash
git clone --depth 1 https://github.com/YanKaFei/art-aesthetic-vault.git
cd art-aesthetic-vault

# immediate self-check
cd _scripts && python3 artvault.py categories
```

**Requirements:** Python 3.8+ and Obsidian (recommended).

**The core scripts use only the Python standard library - nothing to pip install.**

Optional dependencies (only for Pinterest grabbing and the image inbox):

```bash
pip3 install --user requests Pillow
```

---

## Regenerate / extend

```bash
cd _scripts

python3 fetch_art.py                  # fetch images for movements that lack them
python3 fetch_art.py impressionism    # one movement only
python3 fetch_art.py --per 12         # 12 images per movement
python3 build_vault.py                # regenerate every note from the mv_*.py data
python3 make_links.py                 # regenerate external search deep links
```

### Adding a movement

1. Add an entry to the right `_scripts/mv_*.py` file
2. Add filter keywords to **`ARTIST_KEYS` in the same file** ← **required, or you'll pull in unrelated works**
3. `python3 fetch_art.py <slug>` then `python3 build_vault.py`

| Data file | Category |
|---|---|
| `mv_core.py` | the original 18 core movements |
| `mv_west.py` | Western Classical & Modern |
| `mv_asia.py` / `mv_asia2.py` | East Asia · South Asia · Islam |
| `mv_modern.py` / `mv_gaps.py` | Modernism & Post-war |
| `mv_contemporary.py` | Avant-Garde · Contemporary · Postmodern |
| `mv_visual.py` | Digital · Subculture · Photography |
| `mv_photo.py` | Photography & Image |

---

## Three principles

1. **Better fewer than wrong.**
   Filtering deliberately does *not* have a "top up with whatever's available" fallback -
   if a movement yields one image, it gets one image.
   > The worst thing for a reference library isn't too few images, it's wrong ones.
   > Wrong references corrupt your instincts, and you won't notice.

2. **Lighting matters more than style keywords.**
   If you can only tune one layer, tune lighting.

3. **Don't invent movement terminology from memory.**
   LLM recall on art movements is unreliable and blurs related schools together.
   Use the concrete terms in the library.

---

## Image sources

All images come from public-domain / CC0 open sources, verified entry by entry.
Free to use and redistribute. Every work is annotated with its source and license link.

**Code** MIT ｜ **Notes** CC BY 4.0

---

<div align="center">

If this is useful, a star is appreciated - PRs adding more movements are welcome

</div>
"""

# ------------------------------------------------------------------ 许可
LICENSE_TEXT = """MIT License

Copyright (c) 2026 艺术审美风格库 contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

本仓库采用双许可：

- 代码（_scripts/ 目录下的全部脚本）：MIT License（见上）
- 笔记内容（00-导航/、10-流派/、90-模板/、README.md 等）：
  Creative Commons Attribution 4.0 International (CC BY 4.0)
  https://creativecommons.org/licenses/by/4.0/
- 图片（99-附件/images/）：来自公共领域 / CC0 开放数据源，
  各自授权见每张作品下方的标注。
"""


TEMPLATES = {
"流派卡模板.md": """---
type: 流派
流派: 
英文: 
时期: 
地区: 
配色: []
标签:
  - 流派
---

# {{流派}} · {{English}}

> [!abstract] 一句话
> 

| 时期 | 地区 | 代表艺术家 |
|---|---|---|
|  |  |  |

## 一、核心主张

- 

## 二、视觉语言拆解

| 维度 | 拆解 |
|---|---|
| 色彩 |  |
| 光影 |  |
| 笔触 |  |
| 构图 |  |
| 材质 |  |
| 情绪 |  |

## 三、配色板

- 

## 四、提示词结构

| 层 | 可复用片段 |
|---|---|
| 风格 |  |
| 光照 |  |
| 色彩 |  |
| 构图 |  |
| 媒介 |  |
| 情绪 |  |
| 镜头 |  |

### 整段正向提示词

```text

```

### 负向提示词

```text

```

## 五、AI 视频层

| 层 | 内容 |
|---|---|
| Motion 运动 |  |
| Camera 运镜 |  |

## 六、代表作品

## 七、常见翻车点

- 

## 八、关联流派

- [[]]
""",

"提示词卡模板.md": """---
type: 我的提示词
用途: 
主风格: 
混搭风格: []
模型: 
评分: 
标签:
  - 我的提示词
---

# {{标题}}

> [!abstract] 想做的效果
> 

## 参考图

```text
（把参考图拖进来）
```

## 七层拆解

| 层 | 内容 |
|---|---|
| 主体 |  |
| 风格 |  |
| 光照 |  |
| 色彩 |  |
| 构图 |  |
| 媒介 |  |
| 情绪 |  |

## 正向提示词

```text

```

## 负向提示词

```text

```

## 参数

| 项 | 值 |
|---|---|
| 模型 |  |
| 采样器 |  |
| 步数 |  |
| CFG |  |
| 尺寸 |  |
| 种子 |  |

## 结果与迭代

| 版本 | 改动 | 结果 |
|---|---|---|
| v1 |  |  |

## 学到什么

- 

## 关联流派

- [[]]
""",

"作品拆解模板.md": """---
type: 作品
作品: 
艺术家: 
年份: 
流派: 
来源: 
授权: 
标签:
  - 作品
---

# {{作品名}}

![[此处放图]]

**{{艺术家}}** · {{年份}} · {{材质}}

来源：[[]] · 授权：

## 为什么好

- 

## 七层拆解

| 层 | 内容 |
|---|---|
| 主体 |  |
| 风格 |  |
| 光照 |  |
| 色彩 |  |
| 构图 |  |
| 媒介 |  |
| 情绪 |  |

## 可以偷走的三个点

1. 
2. 
3. 

## 转成提示词

```text

```

## 所属流派

- [[]]
""",
}


MY_PROMPTS = """---
type: 索引
---

# 我的提示词卡

> [!tip] 这里是你自己的地盘
> `build_vault.py` **不会**碰这个文件夹。
> 每次调出一张满意的图，就用 [[提示词卡模板]] 新建一张卡记下来，
> 在下面加一行链接。

## 卡片列表

| 标题 | 主风格 | 混搭 | 模型 | 评分 |
|---|---|---|---|---|
|  |  |  |  |  |

## 待办

- [ ] 建第一张提示词卡
- [ ] 试着混搭两个流派的层级（例如巴洛克光照 + 赛博朋克构图）
"""


README = """<div align="center">

# 艺术审美风格库

**把 141 个艺术流派的视觉语言，拆成可以直接用的 AI 提示词层**

从拜占庭到 Y2K ｜ 东亚 · 南亚 · 伊斯兰 ｜ 摄影谱系 ｜ 数字亚文化

163 篇笔记 · 372 张公共领域实图 · 21 个即用脚本

[English](README.en.md) ｜ **中文**

</div>

---

## 这是什么

大部分人收集「艺术风格参考」的方式是存图——存了几百张，但真要用的时候不知道该看什么、
该怎么描述。图是死的。

这个库换个做法：**把每个流派的视觉语言拆成七个可以独立替换的层**。

```
主体 Subject  +  风格 Style  +  光照 Lighting  +  色彩 Color
              +  构图 Composition  +  媒介 Medium  +  情绪 Mood  +  镜头 Camera
```

拆成层之后，你才能把 A 图的光照套到 B 图的主体上。**这才是参考库真正的用处。**

### 看一眼它怎么工作

假设你想画「雨夜霓虹街头的赏金猎人」，同时想要古典绘画的光影质感：

```bash
python3 artvault.py compose \\
  "雨夜霓虹街头的赏金猎人，要巴洛克的光照，赛博朋克的构图" \\
  --subject "a female bounty hunter in a wet neon alley"
```

它会自动识别出「巴洛克」后面跟着「光照」→ 取巴洛克的光照层；
「赛博朋克」→ 取风格与构图层。然后拼成：

```
a female bounty hunter in a wet neon alley,        <- 你的主体
cyberpunk, neo-noir concept art, dense neon signage,   <- 风格层 · 赛博朋克
single hard light source from off-frame,               <- 光照层 · 巴洛克
deep crushed shadows, candlelight rim light,
cyan and magenta clash, amber accent, deep black,      <- 色彩层 · 赛博朋克
low angle looking up at megastructures,                <- 构图层 · 赛博朋克
alienated, oppressive, intoxicating                    <- 情绪层
```

**同一个主体，每一层都可以单独换掉。** 这是这个库和「风格词堆砌」的根本区别。

---

## 技能树

```
{skill_tree}
```

---

## 有多少东西

| | 数量 |
|---|---|
| **流派卡** | **141 张**，6 大分类，每张含六维视觉拆解 + 七层提示词 + 配色 + 视频层 |
| **公共领域实图** | **372 张**（134 MB），79 个流派配了图 |
| **导航与方法论** | 18 篇（流派总览、关键词图谱、七层方法、视频结构、配色速查、反推工具链…） |
| **关键词图谱** | 全部 **218 styles / 189 movements / 68 genres** 的完整映射 |
| **笔记模板** | 3 个（流派卡 / 提示词卡 / 作品拆解） |
| **脚本** | 21 个，抓图、生成、检索、提示词合成、MCP 服务 |

> **62 个流派是「纯提示词卡」**——抽象表现主义、波普、极简主义、观念艺术、
> 赛博朋克、蒸汽波这些，作品仍在版权期内，任何开放数据源都不会提供图。
> 它们的视觉语言与七层结构照常拆解，只是不配图。这是刻意的设计，不是缺失。

---

## 怎么用

### 方式一：当作 Obsidian 仓库读

用 Obsidian 打开这个文件夹。建议从这个顺序进入：

1. `00-导航/提示词拆解方法.md` —— **先读这个**，理解七层是怎么回事
2. `00-导航/流派总览.md` —— 141 个流派的总入口
3. `10-流派/` —— 挑一个你喜欢的流派，看它的完整拆解
4. `00-导航/关键词图谱.md` —— 以后看到陌生风格词就来这里查

### 方式二：让 AI 直接调用它

库不只是一堆给人看的 Markdown，还有一层**给机器用的接口**：

```bash
cd _scripts

python3 artvault.py categories              # 看 6 大分类
python3 artvault.py search "霓虹 雨夜"       # 模糊检索，中英文都行
python3 artvault.py layers 巴洛克            # 只要七层提示词（最省 token）
python3 artvault.py show 浮世绘              # 完整卡片
python3 artvault.py palette 赛博朋克         # 六色配色
python3 artvault.py related 立体主义         # 找关联流派
python3 artvault.py --json layers 巴洛克     # 机器可读
```

**核心能力是组合**：

```bash
# 自然语言，自动分层
python3 artvault.py compose "雨夜霓虹的赏金猎人，要巴洛克的光照" --subject "a bounty hunter"

# 显式指定，跨时代混搭
python3 artvault.py compose --style ukiyo-e --lighting baroque \\
  --color vaporwave --composition precisionism --subject "a lone samurai"
```

它会**检出并打印层级冲突**。跨流派混搭时负向词会互相打架——
浮世绘禁止 `cast shadows`，巴洛克光照却要求 `deep crushed shadows`；
精确主义禁止 `people`，而你的主体是个人物。
**模型不会报错**，只会表现为「出图质量莫名地差」，极难排查。这个检查能省你几个小时。

### 方式三：装成 AI skill（推荐）

仓库自带一个 skill，装上之后**任何支持 skill 的 AI 助手**在遇到视觉/审美类任务时
会自动查这个库，而不是凭记忆编造流派术语。

```bash
cd skill && ./install.sh
```

它会用**软链接**把 skill 装到本机所有可用的 skill 目录：

| 目录 | 谁读它 |
|---|---|
| `~/.agents/skills/` | DSH / Codex / 通用约定 |
| `~/.claude/skills/` | Claude Code |
| `~/.codex/skills/` | Codex |

**为什么用软链**：skill 可以用 `pwd -P` 解析出自己的真实位置，
从而推断出仓库根目录 —— **仓库放在哪、移不移动都能自动找到**，不需要任何配置。
skill 里**没有写死任何路径**。

其他用法：

```bash
./install.sh --copy        # 复制安装（不用软链，但仓库移动后要重装）
./install.sh --uninstall   # 卸载
bash locate.sh             # 手动定位仓库（排查用）
```

装完**新开一个 AI 会话**才会生效。

### 方式四：接入 MCP（Claude Desktop / Cursor）

```json
{
  "mcpServers": {
    "artvault": {
      "command": "python3",
      "args": ["<本仓库绝对路径>/_scripts/mcp_server.py"]
    }
  }
}
```

暴露 7 个工具：`search_movements` `get_movement` `get_layers` `compose_prompt`
`get_palette` `find_related` `list_categories`。纯标准库实现，**不需要 pip 安装任何东西**。

---

## 它好在哪里

### 1. 不是图包，是可组合的结构

图包给你「这是什么感觉」，这个库给你「怎么做出这种感觉」。
每一层都可以单独摘出来复用，换主体不换风格层，就是风格迁移模板。

### 2. 光照层被单独拎出来了

大多数人写提示词时把一切混在一起，靠试错调。这个库明确告诉你：
**光照对最终质感的影响比风格词本身更大。**
每个流派的光照层都是独立一段，可以直接搬到别的主题上。

### 3. 每个流派都有「针对性负向词」

**针对这个流派的典型翻车点**：

- 印象派 → `black shadows, smooth blending, photorealistic`
- 文艺复兴 → `visible brushstrokes, impasto`（AI 默认会给油画加厚涂）
- 浮世绘 → `3d shading, cast shadows, gradient`（AI 会自动加立体感）

**注意不同流派的负向词经常是相反的**——这正是混搭会打架的原因，也是库帮你管住的东西。

### 4. AI 可以用，不只是你能看

大模型对艺术流派的记忆是模糊的，常把 Art Nouveau 和 Art Deco、
巴比松和印象派搞混。这个库把 141 个流派的具体术语固化下来，
AI 调用时不会瞎编。

### 5. 完整性有保证

关键词图谱**218 styles / 189 movements / 68 genres**

### 6. 只收公共领域，用起来不用想

全部图片来自 CC0 / 公共领域开放数据源，可以自由使用、修改、再分发，
也可以放进你自己的数据集。

### 7. 能扩展

加一个新流派只需要在一个 Python 文件里加一条定义。
抓图、生成笔记、关键词映射、AI 接口都会自动跟上。

---

## 快速开始

```bash
git clone https://github.com/YanKaFei/art-aesthetic-vault.git
cd art-aesthetic-vault

# 立刻能用的自检
cd _scripts && python3 artvault.py categories
```

**环境要求**：Python 3.8+ 和 Obsidian（推荐）。

**核心脚本只用 Python 标准库，不需要 pip 安装任何东西。**

可选依赖（只有 Pinterest 抓取和图片投递箱需要）：

```bash
pip3 install --user requests Pillow
```

---

## 自己重新生成 / 扩展

```bash
cd _scripts

python3 fetch_art.py                  # 补抓所有还没有图的流派
python3 fetch_art.py impressionism    # 只抓指定流派
python3 fetch_art.py --per 12         # 每个流派 12 张
python3 build_vault.py                # 用 mv_*.py 里的数据重新生成全部笔记
python3 make_links.py                 # 重新生成外部检索深链
```

### 加一个新流派

1. 在 `_scripts/mv_*.py` 对应的分类文件里加一条定义
2. 在**同一个文件的 `ARTIST_KEYS`** 里加过滤关键词 ← **必须，否则会抓进一堆无关作品**
3. `python3 fetch_art.py <slug>` 然后 `python3 build_vault.py`

| 数据文件 | 负责的分类 |
|---|---|
| `mv_core.py` | 最初的 18 个主干流派 |
| `mv_west.py` | 西方古典与近代 |
| `mv_asia.py` / `mv_asia2.py` | 东亚·南亚·伊斯兰 |
| `mv_modern.py` / `mv_gaps.py` | 现代主义与战后 |
| `mv_contemporary.py` | 先锋·当代·后现代 |
| `mv_visual.py` | 数字·亚文化·摄影美学 |
| `mv_photo.py` | 摄影与图像 |

---

## 三条原则

1. **宁可少，不要错。**
   筛选时刻意不做「放宽补充」——某个流派只有 1 张图就 1 张。
   一个参考库最怕的不是图少，是图错。错的参考会污染你的直觉，而且你自己不会发现。

2. **光照比风格词更重要。**
   如果你只有一个层可以调，调光照。

3. **不要凭记忆编造流派术语。**
   以大模型对艺术流派的记忆为准，容易把相近的画派搞混。以库里的具体术语为准。

---

## 图片来源

全部图片来自公共领域 / CC0 开放数据源，已逐条核对，可自由使用与再分发，每张作品下方都标注了来源与授权链接。

**代码** MIT ｜ **笔记内容** CC BY 4.0

---

<div align="center">

如果这个库对你有用，欢迎 Star ⭐ 或提交 PR 补充更多流派

</div>
"""


def main():
    works_map = {m["slug"]: load_works(m["slug"]) for m in MOVEMENTS}

    for mv in MOVEMENTS:
        w("10-流派/%s.md" % mv["name_zh"], movement_note(mv, works_map[mv["slug"]]))

    w("00-导航/流派总览.md", overview_note(works_map))
    if WIKI_TAX:
        w("00-导航/关键词图谱.md", keyword_graph_note(works_map))
    for cat in CATEGORIES:
        w("00-导航/分类索引-%s.md" % cat, category_note(cat, works_map))
    w("00-导航/提示词拆解方法.md", METHOD.replace("{mark}", GEN_MARK))
    w("00-导航/视频提示词结构.md", VIDEO.replace("{mark}", GEN_MARK))
    w("00-导航/反推工具链.md", TOOLCHAIN.replace("{mark}", GEN_MARK))
    w("00-导航/版权与来源.md", LICENSE.replace("{mark}", GEN_MARK))
    w("00-导航/数据源与访问限制.md", ACCESS.replace("{mark}", GEN_MARK))
    w("00-导航/外部站点接入方案.md", EXTERNAL.replace("{mark}", GEN_MARK))
    # 注意：这里刻意用占位符而不是本机绝对路径。
    # 仓库是要发布的，写死 /Users/xxx 对任何人（包括作者换个位置 clone）都是错的。
    _guide = AI_GUIDE.replace("{mark}", GEN_MARK).replace(
        "{MCP_PATH}", "<仓库绝对路径>/_scripts/mcp_server.py")
    w("00-导航/AI 调用指南.md", _guide)
    w("00-导航/Pinterest 抓取实战.md", PINT.replace("{mark}", GEN_MARK))
    try:
        import make_links
        w("00-导航/外部检索入口.md", make_links.build())
    except Exception as e:
        print("  ! 外部检索入口生成失败:", e)

    body = []
    for cat in CATEGORIES:
        body.append("## %s" % cat)
        body.append("")
        for m in by_category()[cat]:
            body.append("### [[%s]] · %s" % (m["name_zh"], m["name_en"]))
            body.append("")
            for h, n in m["palette"]:
                body.append("- %s `%s` **%s**" % (swatch(h), h, n))
            body.append("")
            body.append("> `%s`" % ", ".join("%s %s" % (n, h) for h, n in m["palette"]))
            body.append("")
    w("00-导航/配色速查.md", PALETTE.format(mark=GEN_MARK, palette_body="\n".join(body)))

    for name, tpl in TEMPLATES.items():
        w("90-模板/%s" % name, tpl)

    w("20-我的提示词/我的提示词卡.md", MY_PROMPTS)
    _rm = (README.replace("{n_mv}", str(len(MOVEMENTS)))
                 .replace("{skill_tree}", skill_tree()))
    w("README.md", _rm)
    w("LICENSE", LICENSE_TEXT)
    _en = (README_EN.replace("{n_mv}", str(len(MOVEMENTS)))
                    .replace("{skill_tree_en}", skill_tree_en())
                    .replace("{cat_table_en}", category_table_en()))
    w("README.en.md", _en)
    w(".gitignore", """# Obsidian 运行时文件
# （app.json / appearance.json / core-plugins.json 是稳定设置，保留在仓库里；
#  下面是每次用 Obsidian 都会变的会话状态，跟着提交只会产生噪音）
.DS_Store
.trash/
.obsidian/workspace.json
.obsidian/workspace-mobile.json
.obsidian/workspace
.obsidian/cache
.obsidian/graph.json

# 脚本缓存与本地依赖
_scripts/__pycache__/
_scripts/vendor/

# 抓取过程的临时清单（每次扫描都会重写）
_scripts/_data/inbox_manifest.json

# Pinterest 抓来的图版权归原作者、无统一授权，**不要提交也不要公开**
# （10-流派/ 里的 CC0 图不受影响，那是可以随便分发的）
99-附件/images/pinterest/

# 投递箱里的图（用户自己丢进来的，同样版权归原作者）
pinterest/*
!pinterest/README.md

# 本地推送助手（含个人仓库名，不必发布）
push-to-github.sh
""")

    n_img = sum(len(v) for v in works_map.values())
    print("生成完成：")
    print("  流派卡      %d 张" % len(MOVEMENTS))
    print("  导航与方法  %d 篇" % 6)
    print("  模板        %d 个" % len(TEMPLATES))
    print("  入库作品图  %d 件" % n_img)
    empty = [m["name_zh"] for m in MOVEMENTS if not works_map[m["slug"]]]
    if empty:
        print("  无 CC0 图的流派（纯提示词卡）：%s" % "、".join(empty))


if __name__ == "__main__":
    main()
