#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_links.py —— 把仓库变成「外部检索入口」。

Pinterest / Art-Ba-Ba 这类站点不需要爬也能用：**用你浏览器里的会话去点**。
这个脚本给每个流派生成可点击的深链，检索词取自该流派的技法术语
（prompt.style 里的前几个词），而不是泛泛的风格名——命中率高得多。

输出： 00-导航/外部检索入口.md
用法： python3 make_links.py
"""

import os
import sys
import urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
VAULT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from movements import MOVEMENTS, CATEGORIES, by_category  # noqa: E402

GEN_MARK = "# auto-generated by build_vault.py —— 本文件由脚本生成，重跑会覆盖"


def terms_for(mv, n=3):
    """从 prompt.style 里挑检索词：去掉流派名本身，留下技法术语。"""
    raw = [t.strip() for t in (mv["prompt"]["style"] or "").split(",") if t.strip()]
    name_en = mv["name_en"].lower()
    out = []
    for t in raw:
        tl = t.lower()
        # 跳过就是这个流派名本身的词
        if tl == name_en or name_en in tl and len(tl) < len(name_en) + 6:
            continue
        out.append(t)
        if len(out) >= n:
            break
    if not out:
        out = [mv["name_en"]]
    return out


def q(s):
    return urllib.parse.quote_plus(s)


def links_for(mv):
    terms = terms_for(mv)
    kw = " ".join(terms)
    kw_short = terms[0]
    era = mv["name_en"]
    return {
        "kw": kw,
        "pinterest_pins": "https://www.pinterest.com/search/pins/?q=" + q(kw),
        "pinterest_boards": "https://www.pinterest.com/search/boards/?q=" + q(era),
        "artsy": "https://www.artsy.net/search?q=" + q(era),
        "wikiart": "https://www.wikiart.org/en/paintings-by-style/" + mv["slug"],
        "commons": ("https://commons.wikimedia.org/w/index.php?search="
                    + q(kw) + "&title=Special:MediaSearch&type=image"),
        "bing": "https://www.bing.com/images/search?q=" + q(kw),
        "google": "https://www.google.com/search?tbm=isch&q=" + q(kw),
        "artbaba": "http://www.art-ba-ba.com/main/main.art?forumId=8&lang=zh",
    }


HEAD = """---
{mark}
type: MOC
---

# 外部检索入口

> [!abstract] 这一页是干什么的
> Pinterest、Art-Ba-Ba 这些站点**不需要爬也能用**——你用自己浏览器里的会话点进去就行。
> 这一页给每个流派生成好深链，**检索词取自该流派的技法术语**（而不是风格名）。
>
> 为什么用技法术语？因为 `tenebrism chiaroscuro` 的命中率远高于 `baroque`。
> 前者是画法，后者是时代标签——Pinterest 上搜后者的结果会烂得多。

## 怎么用

1. 在下面找到你要的流派
2. 点「Pinterest 搜图」或「Artsy」——会在新标签打开**你自己的浏览器**
3. 看到好的参考图 → 丢进 `pinterest/` 投递箱，反推会自动跑完
4. 存进 [[提示词卡模板]]

> [!tip] Pinterest 的正确用法
> 不要在 Pinterest 里搜「风格」，要搜**画法**。它的标签体系是扁平的、由用户随手打的，
> 所以精确的技法术语反而更有效。下面的链接已经按这个原则生成好了。

## 关于「把 Pinterest 收藏夹导出进仓库」

可以，但走的是**官方 API**，而且只能导出**你自己账号里**的板子——
不能搜全站。具体做法和限制见 [[外部站点接入方案]]。

---

"""


def build():
    A = [HEAD.format(mark=GEN_MARK)]
    for cat in CATEGORIES:
        A.append("## %s" % cat)
        A.append("")
        for mv in by_category()[cat]:
            L = links_for(mv)
            A.append("### [[%s]] · %s" % (mv["name_zh"], mv["name_en"]))
            A.append("")
            A.append("**检索词：** `%s`" % L["kw"])
            A.append("")
            A.append("　".join([
                "[Pinterest 搜图](%s)" % L["pinterest_pins"],
                "[Pinterest 搜板](%s)" % L["pinterest_boards"],
                "[Artsy](%s)" % L["artsy"],
                "[WikiArt](%s)" % L["wikiart"],
                "[维基共享](%s)" % L["commons"],
                "[Bing 图片](%s)" % L["bing"],
                "[Google 图片](%s)" % L["google"],
            ]))
            A.append("")
        A.append("")
    A.append("---")
    A.append("")
    A.append("## 关于 Google / Bing 图片")
    A.append("")
    A.append("这两个在本机网络下 Google 不通、Bing 通但抓不到结果（返回的是 JS 页面），")
    A.append("**所以它们是给你在自己浏览器里点开的**，不是给脚本抓的。")
    A.append("脚本能自动抓的是 [[数据源与访问限制]] 里列的那些开放数据源。")
    A.append("")
    return "\n".join(A)


if __name__ == "__main__":
    p = os.path.join(VAULT, "00-导航", "外部检索入口.md")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", encoding="utf-8").write(build().rstrip() + "\n")
    n = sum(1 for _ in MOVEMENTS)
    print("已生成 00-导航/外部检索入口.md（%d 个流派 × 7 个入口）" % n)
