# -*- coding: utf-8 -*-
"""流派定义 —— 东亚 / 南亚 / 伊斯兰（14 个）。

注意：很多传统作品是匿名的，所以 ARTIST_KEYS 里除了画家名，
还会放作品标题/画派关键词（过滤时同时匹配作者字段和文件标题）。
"""

CATEGORY = "东亚·南亚·伊斯兰"

MOVEMENTS = [
# ---------------------------------------------------------------- 琳派
{
 "slug": "rimpa", "name_zh": "琳派", "name_en": "Rimpa",
 "period": "1600–1900", "region": "日本", "tier": "A",
 "one_liner": "日本装饰艺术的顶点：金箔底、大胆留白、把四季压缩成一个平面。",
 "core": ["金银箔底 + 极简色块，装饰性压倒叙事",
          "「たらし込み」：颜料在湿面上自然渗开的技术",
          "大胆留白与截断式构图，母题常被画框切掉",
          "四季花草、流水、鸟兽被高度图案化"],
 "visual": {"色彩": "金箔底 + 少量高纯度矿物色：朱、群青、绿青、白",
            "光影": "完全平面，无阴影无光源；金箔本身反射环境光",
            "笔触": "平涂 + 渗墨效果；轮廓柔和或干脆省略",
            "构图": "大胆留白、非对称、母题溢出画外、屏风式的连续展开",
            "材质": "金箔纸本或绢本、矿物颜料、屏风、色纸",
            "情绪": "华丽、优雅、季节感、装饰性的愉悦"},
 "palette": [("#C9A227","金箔"),("#B03A2E","朱"),("#1F3A8A","群青"),
             ("#3E7A6B","绿青"),("#E8DCC0","胡粉白"),("#2B2B2B","墨")],
 "artists": [("俵屋宗达","1600s"),("尾形光琳","1658–1716"),("尾形乾山","1663–1743"),
             ("酒井抱一","1761–1828"),("铃木其一","1796–1858")],
 "prompt": {"style": "rimpa school japanese decorative painting, gold leaf ground, tarashikomi ink bleed, bold negative space, highly stylised flora",
            "lighting": "completely flat, no shadow, no light source, gold leaf as reflective surface",
            "color": "gold leaf ground with few high purity mineral colours, vermilion, ultramarine, malachite green, shell white",
            "composition": "bold negative space, asymmetry, motif cropped by the frame, continuous screen unfolding",
            "medium": "mineral pigment and gold leaf on paper or silk, folding screen",
            "mood": "opulent, elegant, seasonal, decorative delight",
            "camera": "flat frontal, wide panoramic, no depth"},
 "negative": "3d shading, perspective, cast shadows, western oil texture, busy detail, muted grey",
 "video": {"motion": "流水缓缓蜿蜒、花瓣飘落、金箔的光泽流动",
           "camera": "横向 pan 沿屏风展开，或 static",
           "note": "琳派是屏风画，运动应该是横向展开的"},
 "pitfalls": ["AI 会加立体和阴影 → negative 明确 3d shading, perspective, cast shadows",
              "容易变成普通日本画 → 加 gold leaf ground, tarashikomi, bold negative space"],
 "sources": {"cleveland": ["rimpa", "korin", "sotatsu"], "met": ["ogata korin", "rimpa"],
             "commons": ["Ogata Korin painting"]},
 "see_also": ["ukiyo-e", "suiboku-ga", "art-nouveau"],
},
# ---------------------------------------------------------------- 日本水墨
{
 "slug": "suiboku-ga", "name_zh": "日本水墨画（禅画）", "name_en": "Suiboku-ga",
 "period": "1300–1600", "region": "日本", "tier": "A",
 "exclude_keys": ["sketchbook"],
 "one_liner": "用最少的墨画最多的空气：空白不是没画，是雾、是水、是无限。",
 "core": ["留白即内容，余白承载雾气、水面、天空",
          "墨的浓淡层次（墨分五色）取代颜色",
          "笔法即人格，禅僧的即兴泼墨",
          "受中国宋元水墨影响后的本土化，更简、更拙"],
 "visual": {"色彩": "只有墨的层次：焦、浓、重、淡、清；偶尔一点淡彩",
            "光影": "无光源，明暗由墨的浓淡与留白构成",
            "笔触": "有力、快速、不可修改；飞白、破墨、泼墨",
            "构图": "大面积极简留白，主体偏置一角，常有「边角构图」",
            "材质": "纸本或绢本水墨、粗笔、淡彩",
            "情绪": "简淡、孤寂、出尘、禅意"},
 "palette": [("#1A1A1A","焦墨"),("#4A4A4A","浓墨"),("#8A8A85","淡墨"),
             ("#D9D5CC","灰白"),("#E8E4DA","纸白"),("#7A8A7A","淡青")],
 "artists": [("雪舟","1420–1506"),("周文","1400s"),("长谷川等伯","1539–1610"),
             ("如拙","1400s"),("曾我蕭白","1730–1781")],
 "prompt": {"style": "japanese sumi-e ink painting, zen buddhist suiboku-ga, five tones of ink, vast negative space, minimal brushwork",
            "lighting": "no light source, tonal value from ink density alone, emptiness as mist and water",
            "color": "monochrome ink only, burnt black to pale grey, paper white, occasional faint colour wash",
            "composition": "extreme minimalism, subject off to one corner, vast empty space, asymmetric",
            "medium": "ink on paper or silk, expressive brush, flying white, broken ink technique",
            "mood": "spare, solitary, detached, zen tranquillity",
            "camera": "wide shot, flat depth, generous empty frame"},
 "negative": "colourful, dense detail, oil painting, 3d shading, perspective, western landscape, filled composition",
 "video": {"motion": "墨迹在纸上缓慢扩散、雾气流动、一枝轻颤",
           "camera": "static 极简；让留白占主导",
           "note": "不要填满画面——空白是这幅画的主体"},
 "pitfalls": ["AI 会把留白填满 → 必须写 vast negative space, extreme minimalism, empty",
              "容易加彩色 → negative 写 colourful, colour wash, 强调 monochrome ink"],
 "sources": {"cleveland": ["sesshu", "sumi-e", "japanese ink painting"],
             "met": ["sesshu", "hasegawa tohaku", "japanese ink"], "commons": ["Sesshu ink painting"]},
 "see_also": ["ink-wash-xieyi", "rimpa", "ukiyo-e", "wabi-sabi"],
},
# ---------------------------------------------------------------- 大和绘
{
 "slug": "yamato-e", "name_zh": "大和绘", "name_en": "Yamato-e",
 "period": "900–1600", "region": "日本", "tier": "B",
 "one_liner": "日本本土的叙事绘画：把屋顶掀掉给你看室内，用云把故事切开。",
 "core": ["吹拔屋台（掀顶俯视）：从上方看进室内",
          "云霞作为分隔与转场，切割叙事段落",
          "四季景物与文学典故（和歌）紧密结合",
          "色彩浓艳、平面化，与唐绘的中国趣味对立"],
 "visual": {"色彩": "浓艳的矿物色：朱、群青、绿青、金；平涂无过渡",
            "光影": "完全平面，无阴影",
            "笔触": "细腻平涂 + 硬边轮廓；线条均匀流畅",
            "构图": "斜向的云带切割画面、俯视视角、连续叙事展开",
            "材质": "绢本或纸本着色、绘卷、屏风、金箔",
            "情绪": "叙事性、装饰、优雅、带着物语的情调"},
 "palette": [("#B03A2E","朱"),("#1F3A8A","群青"),("#3E7A6B","绿青"),
             ("#C9A227","金"),("#E8DCC0","云白"),("#8B6B4A","土褐")],
 "artists": [("源氏物语绘卷画师","12世纪"),("土佐光信","1434–1525"),
             ("土佐光起","1617–1691"),("住吉具庆","1631–1705")],
 "prompt": {"style": "yamato-e japanese narrative painting, fukinuki yatai roofless perspective, gold cloud bands dividing scenes, emakimono scroll",
            "lighting": "entirely flat, no shadow, no light source",
            "color": "rich mineral pigments, vermilion, ultramarine, malachite, gold cloud, flat unmodulated",
            "composition": "diagonal cloud bands cutting the picture, high oblique viewpoint, continuous narrative",
            "medium": "colour on silk or paper, handscroll, folding screen, gold leaf",
            "mood": "narrative, decorative, courtly, tale-like",
            "camera": "high oblique angle, wide, flat depth"},
 "negative": "single point perspective, cast shadows, realistic interior, western oil texture, dark mood, photographic",
 "video": {"motion": "云带横向移动转场、帘幕飘动、人物在小空间内活动",
           "camera": "横向 pan 展开绘卷；俯视角",
           "note": "云带就是转场——用云的运动代替剪辑"},
 "pitfalls": ["AI 会加室内透视 → negative 写 single point perspective, realistic interior",
              "必须保留俯视掀顶视角 → composition 写 fukinuki yatai, roofless perspective"],
 "sources": {"cleveland": ["yamato-e", "tosa school"], "met": ["yamato-e", "japanese handscroll"],
             "commons": ["Yamato-e Genji scroll"]},
 "see_also": ["ukiyo-e", "rimpa", "persian-miniature"],
},
# ---------------------------------------------------------------- 青绿山水
{
 "slug": "blue-green-landscape", "name_zh": "青绿山水", "name_en": "Blue-Green Landscape",
 "period": "600–1600", "region": "中国", "tier": "A",
 "one_liner": "用石青石绿把山水画成仙境：金碧辉煌的矿物色千年不褪。",
 "core": ["石青、石绿为主色，泥金勾线，富丽堂皇",
          "散点透视，可游可居的连续空间",
          "山石用勾勒填色而非皴法，装饰性强",
          "多为宫廷或宗教用途，指向理想化的仙境"],
 "visual": {"色彩": "石青（蓝铜矿）+ 石绿（孔雀石）+ 泥金，配赭石与朱砂",
            "光影": "无光源，靠矿物色的明度与金色勾线区分层次",
            "笔触": "细线勾勒轮廓后填色；山石有装饰性纹路",
            "构图": "高远/深远/平远三法，长卷或立轴，层层递进",
            "材质": "绢本或纸本重彩、矿物颜料、泥金、青绿设色",
            "情绪": "富丽、仙气、庄严、理想化的自然"},
 "palette": [("#1F5FA8","石青"),("#3E8A6B","石绿"),("#C9A227","泥金"),
             ("#A8752A","赭石"),("#B03A2E","朱砂"),("#E8DCC0","绢白")],
 "artists": [("王希孟","1096–1119"),("展子虔","550–604"),("李思训","653–718"),
             ("赵伯驹","1120–1182"),("仇英","1494–1552")],
 "prompt": {"style": "chinese blue-green landscape painting, qinglu shanshui, mineral azurite and malachite pigments, gold outlined mountains, gongbi brushwork",
            "lighting": "no light source, hierarchy from mineral colour value and gold outlines",
            "color": "azurite blue, malachite green, gold line, ochre, cinnabar, silk cream",
            "composition": "scattered perspective, layered depth, handscroll or hanging scroll, mountains receding in stages",
            "medium": "heavy colour on silk or paper, mineral pigments, gold outlining",
            "mood": "opulent, celestial, majestic, idealised nature",
            "camera": "high aerial viewpoint, panoramic, flat depth layers"},
 "negative": "western single point perspective, 3d shading, oil impasto, monochrome ink only, grey muted, photographic",
 "video": {"motion": "云气在山间流动、水面微澜、瀑布下落",
           "camera": "极缓横向 pan 展开长卷，或缓慢 zoom out 揭示全貌",
           "note": "中国山水的运动是「游观」——镜头代表观者的眼睛在移动"},
 "pitfalls": ["AI 会做成水墨单色 → 必须写 azurite blue, malachite green, mineral pigments",
              "容易加西式透视 → negative 写 single point perspective, 3d shading"],
 "sources": {"cleveland": ["chinese landscape blue green", "qiu ying"],
             "met": ["chinese blue green landscape", "wang ximeng"],
             "commons": ["Wang Ximeng thousand li rivers mountains"]},
 "see_also": ["ink-wash-xieyi", "gongbi", "song-academic"],
},
# ---------------------------------------------------------------- 水墨写意
{
 "slug": "ink-wash-xieyi", "name_zh": "水墨写意", "name_en": "Ink Wash Xieyi",
 "period": "900–1900", "region": "中国", "tier": "A",
 "one_liner": "不求形似求神韵：几笔下去，竹子的风骨就出来了。",
 "core": ["写意：以少胜多，笔不到意到",
          "墨分五色，用浓淡干湿替代颜色",
          "文人画传统：诗、书、画、印合一",
          "笔墨即人品，讲究「气韵生动」"],
 "visual": {"色彩": "水墨为主，偶施浅绛或淡青；极少重彩",
            "光影": "无光源，虚实由墨色浓淡和留白生成",
            "笔触": "书法性用笔：中锋、侧锋、皴擦点染；速度与力度可见",
            "构图": "大面积留白，主体偏侧，题跋与印章参与构图",
            "材质": "宣纸（生纸渗墨）、绢、毛笔、墨、朱印",
            "情绪": "疏淡、孤高、文人气的清冷与自持"},
 "palette": [("#1A1A1A","焦墨"),("#5A5A55","重墨"),("#9A968C","淡墨"),
             ("#E8E4DA","宣纸白"),("#A8432A","朱印"),("#8A7A5A","浅绛")],
 "artists": [("范宽","950–1032"),("郭熙","1000–1090"),("马远","1160–1225"),
             ("夏圭","1195–1224"),("沈周","1427–1509"),("八大山人","1626–1705"),
             ("石涛","1642–1718"),("徐渭","1521–1593")],
 "prompt": {"style": "chinese literati ink wash painting, xieyi freehand brushwork, five tones of ink, calligraphic strokes, vast empty space, seal and colophon",
            "lighting": "no light source, void and solid generated by ink density and paper white",
            "color": "monochrome ink with occasional pale ochre or blue wash, vermilion seal",
            "composition": "generous negative space, subject to one side, inscription and seal as compositional elements",
            "medium": "ink on absorbent xuan paper, wolf hair brush, cun texture strokes, splashed ink",
            "mood": "spare, aloof, scholarly detachment, cool self-possession",
            "camera": "wide, flat depth, generous empty frame"},
 "negative": "colourful, realistic shading, perspective, oil painting, dense detail, photographic, western landscape",
 "video": {"motion": "墨在宣纸上缓慢晕开、竹叶随风、水波微动",
           "camera": "static，或极缓 push in 到某一笔触",
           "note": "留白是主体——镜头不要试图填满它"},
 "pitfalls": ["AI 会填满留白并加彩 → negative 写 colourful, dense detail, 强调 monochrome ink, vast empty space",
              "容易丢掉书法性用笔 → 加 calligraphic strokes, cun texture strokes"],
 "sources": {"cleveland": ["chinese ink landscape", "bada shanren"],
             "met": ["chinese ink landscape", "shitao", "fan kuan"],
             "commons": ["Chinese ink wash landscape painting"]},
 "see_also": ["suiboku-ga", "blue-green-landscape", "song-academic", "wabi-sabi"],
},
# ---------------------------------------------------------------- 工笔
{
 "slug": "gongbi", "name_zh": "工笔重彩", "name_en": "Gongbi",
 "period": "600–1900", "region": "中国", "tier": "A",
 "one_liner": "极细的线、层层罩染的色，把一朵花一只鸟画到比照片更精致。",
 "core": ["工笔：精细勾勒轮廓线（白描）后层层分染",
          "「三矾九染」：多次薄涂叠加出厚重感",
          "花鸟、仕女、宫廷生活为主要题材",
          "装饰性与写实性并重，追求「形神兼备」"],
 "visual": {"色彩": "层层罩染的浓艳色：胭脂、花青、藤黄、石绿；色不压线",
            "光影": "无光源，立体感由分染的渐变产生，极其微妙",
            "笔触": "极细均匀的游丝描、铁线描；几乎看不到笔痕",
            "构图": "主体居中或偏侧，折枝式构图，背景常留白或填以纹样",
            "材质": "绢本或熟宣、矿物与植物颜料、泥金、蛤粉",
            "情绪": "精致、典雅、静谧、带着宫廷的克制"},
 "palette": [("#B03A5A","胭脂"),("#2B4C8B","花青"),("#E8C020","藤黄"),
             ("#3E8A6B","石绿"),("#C9A227","泥金"),("#F2EDE4","蛤粉白")],
 "artists": [("宋徽宗","1082–1135"),("黄筌","900–965"),("崔白","1000–1080"),
             ("仇英","1494–1552"),("陈之佛","1896–1962")],
 "prompt": {"style": "chinese gongbi fine-line painting, meticulous outline then layered colour wash, highly detailed flower and bird, courtly refinement",
            "lighting": "no light source, volume from very gradual layered shading, line never obscured",
            "color": "layered saturated mineral and vegetable pigments, rouge, indigo, gamboge, malachite, gold, shell white",
            "composition": "single centred or offset subject, broken branch format, empty or patterned background",
            "medium": "colour on silk or sized paper, fine silk thread outline, multiple thin washes",
            "mood": "exquisite, elegant, still, courtly restraint",
            "camera": "flat frontal, close-up, no perspective"},
 "negative": "loose brushwork, visible strokes, impressionist, 3d render, perspective, muddy colour, sketchy",
 "video": {"motion": "花瓣轻颤、蝴蝶振翅、水面微动；极细微",
           "camera": "static 特写，极慢 dolly in",
           "note": "工笔的信息量在细节，镜头要停住让人看清"},
 "pitfalls": ["AI 会画成写意 → 必须写 fine-line outline, meticulous, layered washes",
              "细节密度不足 → 加 highly detailed, silk thread outline"],
 "sources": {"cleveland": ["gongbi", "chinese bird flower painting"],
             "met": ["chinese bird and flower painting", "emperor huizong"],
             "commons": ["Song dynasty bird flower painting", "Chinese silk painting bird", "Emperor Huizong painting"]},
 "see_also": ["blue-green-landscape", "ink-wash-xieyi", "song-academic"],
},
# ---------------------------------------------------------------- 敦煌壁画
{
 "slug": "dunhuang-murals", "name_zh": "敦煌壁画", "name_en": "Dunhuang Murals",
 "period": "400–1400", "region": "中国敦煌", "tier": "A",
 "one_liner": "丝绸之路上的千年颜料库：飞天、藻井、经变，土红与石青的盛大交响。",
 "core": ["飞天（apsaras）与伎乐天：飘带定义运动",
          "经变画：把整部佛经铺成一幅巨型叙事",
          "凹凸法（天竺遗法）：用色块叠晕表现体积",
          "千年层累，不同朝代风格叠加在同一窟"],
 "visual": {"色彩": "土红底 + 石青石绿 + 黑褐；因氧化变色而成就独特调子",
            "光影": "无真实光源，用色块的晕染（叠晕）暗示体积",
            "笔触": "铁线描 + 凹凸晕染；粗放有力",
            "构图": "满壁铺陈、对称的藻井图案、围绕主尊的放射式叙事",
            "材质": "土坯墙泥壁、矿物颜料、动物胶、金箔",
            "情绪": "盛大、绚丽、宗教性的迷醉、时间侵蚀的苍古"},
 "palette": [("#A8432A","土红"),("#1F5FA8","石青"),("#3E8A6B","石绿"),
             ("#2B2318","氧化褐"),("#C9A227","金"),("#D9CFC0","壁白")],
 "artists": [("敦煌无名画工","4–14世纪"),("北魏画工","5世纪"),
             ("盛唐画工","8世纪"),("西夏画工","11世纪")],
 "prompt": {"style": "dunhuang cave mural, silk road buddhist painting, flying apsaras with flowing ribbons, layered colour shading, ancient mineral pigment",
            "lighting": "no real light source, volume suggested by graded colour bands, flat cave wall surface",
            "color": "earth red ground, azurite blue, malachite green, oxidised brown, gold, aged plaster white",
            "composition": "wall-filling symmetry, caisson ceiling pattern, radial narrative around a central deity",
            "medium": "mineral pigment on mud plaster wall, animal glue binder, gold leaf, oxidised and cracked",
            "mood": "grand, gorgeous, religiously ecstatic, weathered by time",
            "camera": "wide, low angle looking up, flat depth"},
 "negative": "oil painting, 3d render, western perspective, clean digital, neon, modern clothing, pristine surfaces",
 "video": {"motion": "飘带翻飞、花瓣散落、火焰纹闪动",
           "camera": "缓慢 tilt up 沿壁画上升，或横向 pan",
           "note": "飞天的运动全在飘带上——丝带是动力的可视化"},
 "pitfalls": ["AI 会做成干净的现代插画 → 加 ancient mineral pigment, cracked plaster, oxidised",
              "色彩容易过艳 → 明确 oxidised, earth red ground, aged"],
 "sources": {"cleveland": ["dunhuang"], "met": ["dunhuang mural", "buddhist cave painting"],
             "commons": ["Dunhuang Mogao cave mural painting"]},
 "see_also": ["tibetan-thangka", "gongbi", "byzantine"],
},
# ---------------------------------------------------------------- 宋代院体
{
 "slug": "song-academic", "name_zh": "宋代院体画", "name_en": "Song Academic Painting",
 "period": "960–1279", "region": "中国", "tier": "A",
 "exclude_keys": ["sketchbook"],
 "one_liner": "中国写实绘画的巅峰：一花一鸟一山，都被观察到极致再被提纯。",
 "core": ["格物致知：对自然的观察精确到物种级别",
          "「形似」与「气韵」并重，写实但不琐碎",
          "边角构图（马一角、夏半边），大量留白",
          "诗画一律，画面背后有文学意境"],
 "visual": {"色彩": "淡雅含蓄：淡墨、花青、赭石、石绿；不事浓艳",
            "光影": "无光源，用墨色浓淡与留白营造空气与空间",
            "笔触": "皴法成熟（斧劈皴、披麻皴），笔法精密而有力",
            "构图": "边角式、对角线，大面积空白，主体精简到一两个",
            "材质": "绢本或纸本水墨淡彩、细笔、团扇与册页",
            "情绪": "清冷、精微、诗意、宇宙秩序的静观"},
 "palette": [("#3A3A38","淡墨"),("#5A7A8B","花青"),("#A8752A","赭石"),
             ("#7A9A7A","石绿"),("#D9D5CC","绢灰"),("#E8E4DA","留白")],
 "artists": [("马远","1160–1225"),("夏圭","1195–1224"),("郭熙","1000–1090"),
             ("崔白","1000–1080"),("李唐","1066–1150"),("梁楷","1140–1210")],
 "prompt": {"style": "song dynasty academic painting, precise observation, one-corner composition, mature cun texture strokes, poetic realism, silk ground",
            "lighting": "no light source, atmosphere from ink value and reserved white, subtle spatial recession",
            "color": "restrained and refined, pale ink, indigo, ochre, malachite, silk grey",
            "composition": "one-corner asymmetric composition, large empty areas, only one or two motifs, diagonal",
            "medium": "ink and light colour on silk, fine brush, fan or album leaf format",
            "mood": "cool, meticulous, poetic, cosmic stillness",
            "camera": "flat, medium wide, generous empty frame"},
 "negative": "dense composition, heavy saturated colour, western perspective, oil texture, 3d shading, busy detail",
 "video": {"motion": "风过芦苇、鸟振翅、水面微澜；极克制",
           "camera": "static 或极缓 push in",
           "note": "宋画的空白是空气——不要让画面变满"},
 "pitfalls": ["AI 会填满画面 → 必须写 one-corner composition, large empty areas",
              "容易做成日本水墨 → 加 song dynasty, silk ground, cun texture strokes"],
 "sources": {"cleveland": ["song dynasty painting", "ma yuan"],
             "met": ["song dynasty painting", "chinese silk landscape"],
             "commons": ["Song dynasty painting silk"]},
 "see_also": ["ink-wash-xieyi", "gongbi", "suiboku-ga"],
},
# ---------------------------------------------------------------- 波斯细密画
{
 "slug": "persian-miniature", "name_zh": "波斯细密画", "name_en": "Persian Miniature",
 "period": "1200–1700", "region": "伊朗 / 中亚", "tier": "A",
 "one_liner": "没有透视的彩色花园：金色天空、平面堆叠的空间、每一寸都画满。",
 "core": ["平面堆叠空间：远处的人不一定比近处小",
          "金色或宝石色天空， idealized 花园与建筑",
          "书法与绘画共存于同一页，边框装饰繁复",
          "文学叙事（列王纪、五卷诗）为主要载体"],
 "visual": {"色彩": "宝石般饱和：青金蓝、朱红、翠绿、金；平涂无过渡",
            "光影": "完全没有阴影与光源，一切平面化",
            "笔触": "极细的笔，勾线后平涂；细节密集",
            "构图": "高视点俯视、多层堆叠、装饰性边框、不填满不罢休",
            "材质": "纸本、水彩与金箔、书法墨线、装帧皮革",
            "情绪": "华美、叙事、感官、装饰性的繁复"},
 "palette": [("#1F3A8A","青金蓝"),("#B03A2E","朱红"),("#3E8A6B","翠绿"),
             ("#C9A227","金"),("#6B3FA0","紫"),("#E8DCC0","纸白")],
 "artists": [("毕扎德","1450–1535"),("苏丹·穆罕默德","1500s"),("礼萨·阿巴西","1565–1635"),
             ("阿加·米拉克","1500s"),("米尔·赛义德·阿里","1500s")],
 "prompt": {"style": "persian miniature painting, safavid manuscript illumination, stacked flat planes, gold sky, dense ornamental detail, calligraphy panel",
            "lighting": "no shadow, no light source, entirely flat and decorative",
            "color": "jewel saturated, lapis blue, vermilion, emerald, gold, flat unmodulated",
            "composition": "high aerial viewpoint, layered depth, ornate border, horror vacui",
            "medium": "watercolour and gold on paper, fine brush, illuminated manuscript binding",
            "mood": "gorgeous, narrative, sensuous, decorative profusion",
            "camera": "high oblique, flat depth, framed like a manuscript page"},
 "negative": "single point perspective, cast shadows, 3d render, photographic, minimalism, muted colour, plain background",
 "video": {"motion": "花园中的活动、马匹行进、书法线条流动",
           "camera": "static 俯视；或极缓 zoom in 到某个细节",
           "note": "细密画是「一页」——构图的边框不能丢"},
 "pitfalls": ["AI 会加透视和阴影 → negative 必须写 single point perspective, cast shadows",
              "容易被做成印度或阿拉伯风 → 强调 safavid, lapis gold sky, persian manuscript"],
 "sources": {"cleveland": ["persian miniature", "safavid manuscript"],
             "met": ["persian miniature", "shahnameh", "bihzad"],
             "commons": ["Persian miniature Shahnameh manuscript"]},
 "see_also": ["mughal-miniature", "islamic-geometric", "arabic-calligraphy", "yamato-e"],
},
# ---------------------------------------------------------------- 莫卧儿细密画
{
 "slug": "mughal-miniature", "name_zh": "莫卧儿细密画", "name_en": "Mughal Miniature",
 "period": "1550–1750", "region": "印度", "tier": "A",
 "one_liner": "波斯技法遇上印度观察力：肖像精确到胡须，花园对称到强迫症。",
 "core": ["融合波斯装饰性与印度本土的自然观察",
          "写实肖像与动物研究，精确度极高",
          "对称的查哈巴格（四分花园）与建筑景观",
          "金箔点缀、细腻晕染并存"],
 "visual": {"色彩": "温暖而饱和：赭金、朱红、青金、草绿；比波斯更暖",
            "光影": "轻微晕染塑造体积，但无强烈光源",
            "笔触": "极细笔，晕染层次比波斯细密画更柔和",
            "构图": "对称的宫廷或花园场景，或侧身肖像，边框装饰",
            "材质": "纸本水彩与金箔、细笔晕染、镶边册页",
            "情绪": "尊贵、精微、富丽、帝国的自信"},
 "palette": [("#C9A227","赭金"),("#B03A2E","朱红"),("#1F3A8A","青金"),
             ("#5A8A4A","草绿"),("#8B5E2A","暖褐"),("#E8DCC0","纸白")],
 "artists": [("巴萨万","1560–1600"),("阿布·哈桑","1580–1630"),("乌斯塔德·曼苏尔","1590–1630"),
             ("比尚达斯","1590–1630"),("法鲁克·贝格","1545–1615")],
 "prompt": {"style": "mughal miniature painting, imperial indian manuscript, precise portraiture, symmetric charbagh garden, persian-indian fusion, gold detail",
            "lighting": "gentle graduated shading giving volume, no strong light source, even illumination",
            "color": "warm saturated, ochre gold, vermilion, lapis, grass green, warm brown",
            "composition": "symmetrical court or garden scene, or profile portrait, decorated border",
            "medium": "watercolour and gold on paper, very fine brush, burnished album page",
            "mood": "regal, meticulous, opulent, imperial confidence",
            "camera": "flat frontal or profile, medium shot, decorated frame"},
 "negative": "3d render, cast shadows, western perspective, photographic realism, minimalism, plain background",
 "video": {"motion": "宫廷行列行进、猎鹰展翅、花园中的人物活动",
           "camera": "static 或极缓横向 pan（像翻册页）",
           "note": "对称花园是莫卧儿签名——构图的对称不能丢"},
 "pitfalls": ["和波斯细密画混淆 → 莫卧儿更暖、更写实、更强调肖像精确度",
              "AI 会加透视 → negative 写 western perspective, cast shadows"],
 "sources": {"cleveland": ["mughal miniature", "indian miniature"],
             "met": ["mughal miniature", "indian miniature painting"],
             "commons": ["Mughal miniature painting"]},
 "see_also": ["persian-miniature", "islamic-geometric"],
},
# ---------------------------------------------------------------- 伊斯兰几何
{
 "slug": "islamic-geometric", "name_zh": "伊斯兰几何纹样", "name_en": "Islamic Geometric",
 "period": "800–1700", "region": "伊斯兰世界", "tier": "A",
 "allow_3d": True,
 "one_liner": "用圆规和直尺生成无限：星形、多边形、互锁的永恒图案。",
 "core": ["以圆为基础生成星形与多边形，可无限延展",
          "重复单元与互锁（girih）产生视觉上的无限",
          "避免具象，抽象到什么程度都不为过",
          "瓷砖、木雕、书籍装帧、建筑表面同一套语言"],
 "visual": {"色彩": "青金蓝、绿松石、钴蓝、白、金；平涂对比明确",
            "光影": "平面无光；靠色彩的交替与线条的粗细构成节奏",
            "笔触": "无笔触——几何绘图与马赛克拼贴",
            "构图": "中心放射或无限重复的网格，边界被刻意模糊",
            "材质": "釉面瓷砖、灰泥雕刻、木格、彩绘手抄本、地毯",
            "情绪": "秩序、无限、冥想性、智性的超越"},
 "palette": [("#1F3A8A","青金蓝"),("#2E8B8B","绿松石"),("#B03A2E","砖红"),
             ("#E8DCC0","釉白"),("#C9A227","金"),("#1B4A3A","深绿")],
 "artists": [("伊斯法罕工匠","17世纪"),("撒马尔罕工匠","15世纪"),
             ("奥斯曼瓷砖匠","16世纪"),("阿尔罕布拉工匠","14世纪")],
 "prompt": {"style": "islamic geometric pattern, girih tiling, star and polygon tessellation, infinite repeating ornament, zellige tilework",
            "lighting": "flat, no light, rhythm from alternating colour and line weight",
            "color": "lapis blue, turquoise, cobalt, brick red, glaze white, gold, flat unmodulated",
            "composition": "central radial or infinite grid, deliberately unbounded edges, perfect symmetry",
            "medium": "glazed ceramic tile, carved stucco, wood lattice, illuminated manuscript, carpet",
            "mood": "ordered, infinite, meditative, intellectual transcendence",
            "camera": "flat orthographic, no perspective, pattern fills the frame"},
 "negative": "figurative subject, perspective, 3d render, cast shadows, asymmetry, organic hand-drawn wobble",
 "video": {"motion": "图案无限缩放（分形式）、瓷砖逐块显现",
           "camera": "static 或无限 zoom in/out，绝不旋转",
           "note": "伊斯兰几何的动是「无限延展」，用缩放而非移动"},
 "pitfalls": ["AI 画不出真正的几何互锁 → 加 girih tiling, tessellation, mathematically consistent",
              "容易被加立体感和阴影 → negative 写 3d render, cast shadows"],
 "sources": {"cleveland": ["islamic tile", "tile mosaic geometric"],
             "met": ["islamic tile geometric", "tile panel geometric"],
             "commons": ["Islamic tile panel", "zellige mosaic Morocco", "Iznik tile panel", "muqarnas stucco"]},
 "see_also": ["arabic-calligraphy", "persian-miniature", "bauhaus"],
},
# ---------------------------------------------------------------- 阿拉伯书法
{
 "slug": "arabic-calligraphy", "name_zh": "阿拉伯书法", "name_en": "Arabic Calligraphy",
 "period": "700–1800", "region": "伊斯兰世界", "tier": "B",
 "one_liner": "文字即图像：一笔连绵的线条既是语言，也是最高级的装饰。",
 "core": ["库法体、三一体、誊抄体等书体各有严格比例",
          "文字可塑成动物、船只、建筑的形状（图形式书法）",
          "与几何纹样、金箔共同构成书页装饰",
          "书法被视为最高等的艺术形式"],
 "visual": {"色彩": "墨黑或金 + 青金蓝与朱红装饰底；对比强烈",
            "光影": "无光影，平面",
            "笔触": "芦苇笔的粗细变化；线条流畅连贯、粗细有韵律",
            "构图": "文字本身构成构图；边框为繁复的几何与花卉纹",
            "材质": "纸本、羊皮纸、金墨、泥金装饰（ilumination）",
            "情绪": "庄严、虔诚、韵律感、抽象的美"},
 "palette": [("#C9A227","金墨"),("#1A1A1A","墨黑"),("#1F3A8A","青金"),
             ("#B03A2E","朱红"),("#2E8B8B","绿松石"),("#E8DCC0","纸白")],
 "artists": [("伊本·穆格莱","886–940"),("伊本·巴瓦卜","980–1022"),
             ("雅库特·穆斯塔西米","1200s"),("哈菲兹·奥斯曼","1600s")],
 "prompt": {"style": "arabic calligraphy, thuluth and naskh script, illumination border, gold ink on paper, rhythmic flowing line, geometric and floral margin",
            "lighting": "flat, no shadow",
            "color": "gold or black ink, lapis and vermilion illumination, turquoise, cream paper",
            "composition": "text itself forms the composition, ornate geometric border",
            "medium": "reed pen, gold and ink on paper or parchment, burnished illumination",
            "mood": "solemn, devotional, rhythmic, abstract beauty",
            "camera": "flat orthographic, macro detail"},
 "negative": "figurative scene, perspective, 3d render, latin alphabet, random scribble, illegible marks",
 "video": {"motion": "笔画依次书写显现、金墨反光流动",
           "camera": "static 或极缓横向 pan 沿文字方向",
           "note": "运动应沿书写方向（右到左）"},
 "pitfalls": ["AI 会生成乱码般的假文字 → 说明这是装饰性书法，接受抽象化，但要写 rhythmic flowing line",
              "容易缺少泥金边框 → 加 illumination border, gold ink"],
 "sources": {"cleveland": ["arabic calligraphy", "quran leaf"],
             "met": ["arabic calligraphy", "quran manuscript leaf"],
             "commons": ["Arabic calligraphy illuminated manuscript"]},
 "see_also": ["islamic-geometric", "persian-miniature"],
},
# ---------------------------------------------------------------- 韩国民画
{
 "slug": "minhwa", "name_zh": "韩国民画", "name_en": "Minhwa",
 "period": "1392–1900", "region": "朝鲜半岛", "tier": "B",
 "one_liner": "朝鲜民间的吉祥画：老虎画得像狗，山峰像花，天真得可爱。",
 "core": ["民间吉祥主题：虎、鹊、牡丹、莲花、日月、寿石",
          "造型天真、比例自由，不追求写实",
          "色彩明快、平涂无阴影",
          "屏风式成套构图（十长生、册架图、花鸟图）"],
 "visual": {"色彩": "明快平涂：朱红、靛蓝、草绿、明黄、白；对比鲜明但不刺眼",
            "光影": "完全平面，无阴影",
            "笔触": "民间画工的直率用笔，勾勒后平涂，偶有墨线",
            "构图": "屏风多幅并列、中心对称、母题重复排列",
            "材质": "纸本或绢本着色、屏风、水墨淡彩",
            "情绪": "天真、吉祥、乐观、质朴的民间趣味"},
 "palette": [("#B03A2E","朱红"),("#2B4C8B","靛蓝"),("#5A9A4A","草绿"),
             ("#E8C020","明黄"),("#E8DCC0","纸白"),("#1A1A1A","墨")],
 "artists": [("朝鲜民间画工","18–19世纪"),("金弘道","1745–1806"),
             ("申润福","1758–1813"),("沈师正","1707–1769")],
 "prompt": {"style": "korean minhwa folk painting, naively stylised tiger and magpie, auspicious symbols, flat bright colour, folding screen composition",
            "lighting": "entirely flat, no shadow, no light source",
            "color": "bright flat colour, vermilion, indigo, grass green, bright yellow, paper white",
            "composition": "multi-panel screen, central symmetry, repeated motifs, folk directness",
            "medium": "colour on paper or silk, folding screen, ink outline then flat fill",
            "mood": "naive, auspicious, cheerful, rustic charm",
            "camera": "flat frontal, panoramic screen format"},
 "negative": "photorealism, 3d shading, perspective, dark mood, western oil texture, sophisticated academic finish",
 "video": {"motion": "几乎没有；或民俗舞蹈般的轻快节奏",
           "camera": "static 或横向 pan 展开屏风",
           "note": "民画的魅力在天真，不要加技术感的运镜"},
 "pitfalls": ["AI 会把老虎画得太写实 → 强调 naively stylised, folk painting, free proportion",
              "容易丢掉屏风格式 → composition 写 multi-panel screen"],
 "sources": {"cleveland": ["korean painting minhwa"], "met": ["korean painting folk"],
             "commons": ["Minhwa Korean painting", "Korean folk painting tiger", "chaekgeori Korean screen"]},
 "see_also": ["ukiyo-e", "rimpa", "gongbi"],
},
# ---------------------------------------------------------------- 唐卡
{
 "slug": "tibetan-thangka", "name_zh": "西藏唐卡", "name_en": "Tibetan Thangka",
 "period": "1100–1900", "region": "西藏 / 喜马拉雅", "tier": "A",
 "one_liner": "用矿物颜料在布上画出整个宇宙：严格的度量、饱和的色、金色的光。",
 "core": ["严格的造像度量经（iconometry），比例不可随意",
          "中心主尊 + 环绕的坛城式构图",
          "矿物颜料饱和持久，金线勾边",
          "既是艺术品也是修行工具"],
 "visual": {"色彩": "极高饱和的矿物色：朱砂红、石青、石绿、金；对比强烈",
            "光影": "无光源，用金线和色块边界区分层次",
            "笔触": "极细勾线 + 平涂；金线勾边（描金）是标志",
            "构图": "中心对称、放射状环绕、坛城（mandala）几何结构",
            "材质": "棉布或丝绸、矿物颜料、动物胶、金箔、锦缎装裱",
            "情绪": "庄严、神圣、震慑、冥想性的强烈"},
 "palette": [("#B03A2E","朱砂红"),("#1F5FA8","石青"),("#3E8A6B","石绿"),
             ("#C9A227","金"),("#2B2B33","黑"),("#E8DCC0","白")],
 "artists": [("西藏画师","12–19世纪"),("勉唐画派","15世纪"),("钦孜画派","15世纪"),
             ("噶玛嘎孜画派","16世纪")],
 "prompt": {"style": "tibetan thangka painting, strict iconometric proportions, central deity with radiating retinue, mineral pigment, gold outlining, mandala structure",
            "lighting": "no light source, hierarchy from gold outlines and flat colour boundaries",
            "color": "highly saturated mineral pigments, cinnabar red, azurite blue, malachite green, gold, black",
            "composition": "central symmetry, radiating concentric arrangement, mandala geometry, framed in brocade",
            "medium": "mineral pigment and gold on cotton or silk, animal glue, brocade mount",
            "mood": "solemn, sacred, awe-inspiring, meditative intensity",
            "camera": "flat frontal, vertical format, no perspective"},
 "negative": "3d render, perspective, cast shadows, muted pastel, oil impasto, secular subject, photorealistic",
 "video": {"motion": "光晕脉动、火焰纹跳动、莲花缓慢开合",
           "camera": "static 或极缓 zoom in 到主尊面部",
           "note": "唐卡是冥想对象——运动要极慢，像呼吸"},
 "pitfalls": ["AI 会加透视和柔和光 → negative 写 3d render, perspective, cast shadows",
              "色彩容易不够饱和 → 明确 highly saturated mineral pigments, cinnabar, azurite"],
 "sources": {"cleveland": ["thangka", "tibetan painting"], "met": ["thangka", "tibetan buddhist painting"],
             "commons": ["Tibetan thangka painting"]},
 "see_also": ["dunhuang-murals", "byzantine", "islamic-geometric"],
},
]

ARTIST_KEYS = {
 "rimpa": ["korin", "sotatsu", "kensan", "hoitsu", "kiitsu", "rimpa", "ogata"],
 "suiboku-ga": ["sesshu", "shubun", "josetsu", "tohaku", "sumi", "suiboku", "ink",
               "shugetsu", "shūgetsu", "tōkan", "tokan", "gyokudo", "taiga", "buson"],
 "yamato-e": ["yamato-e", "yamatoe", "tosa", "genji", "sumiyoshi", "emakimono",
               "handscroll", "narrative scroll"],
 "blue-green-landscape": ["wang ximeng", "zhao boju", "qiu ying", "li sixun", "zhan ziqing",
                           "blue-green", "qinglu", "thousand li", "azurite"],
 "ink-wash-xieyi": ["fan kuan", "guo xi", "ma yuan", "xia gui", "shen zhou", "bada shanren",
                     "shitao", "xu wei", "dong qichang", "tang yin", "wen zhengming",
                     "ink", "literati", "hanging scroll"],
 "gongbi": ["huizong", "hui zong", "huang quan", "cui bai", "qiu ying", "chen zhifo", "gongbi",
             "bird and flower", "fine line", "silk", "song dynasty", "court painting"],
 "dunhuang-murals": ["dunhuang", "mogao", "cave", "apsara", "kizil", "bezeklik"],
 "song-academic": ["ma yuan", "xia gui", "guo xi", "cui bai", "li tang", "liang kai",
                    "song dynasty", "southern song", "northern song", "silk"],
 "persian-miniature": ["bihzad", "behzad", "sultan muhammad", "reza abbasi", "mirak",
                        "mir sayyid", "shahnameh", "khamsa", "persian", "safavid",
                        "miniature", "illuminated manuscript"],
 "mughal-miniature": ["basawan", "abul hasan", "mansur", "bishandas", "farrukh",
                       "mughal", "akbarnama", "padshahnama", "indian miniature"],
 "islamic-geometric": ["tile", "tiles", "zellige", "girih", "geometric", "mosaic", "stucco",
                        "muqarnas", "islamic", "star pattern", "azulejo", "mashrabiya",
                        "ispahan", "isfahan", "samarkand", "alhambra", "kashi", "ceramic"],
 "arabic-calligraphy": ["calligraph", "quran", "koran", "thuluth", "naskh", "kufic",
                         "ibn muqla", "yakut", "illuminated"],
 "minhwa": ["minhwa", "min hwa", "korean", "korea", "kim hongdo", "sin yunbok", "shen sajeong",
             "tiger", "magpie", "folk painting", "chaekgeori", "irwol"],
 "tibetan-thangka": ["thangka", "tangka", "tibetan", "mandala", "menla", "tsongkhapa",
                      "buddhist", "himalayan"],
}
