# -*- coding: utf-8 -*-
"""流派定义 —— 东亚·南亚·伊斯兰补充（5 个）。"""

CATEGORY = "东亚·南亚·伊斯兰"

MOVEMENTS = [
# ---------------------------------------------------------------- 创作版画
{
 "slug": "sosaku-hanga", "name_zh": "创作版画", "name_en": "Sōsaku-hanga",
 "period": "1900–1970", "region": "日本", "tier": "A",
 "one_liner": "一个人完成全部工序：自己画、自己刻、自己印，版画从此是个人表达。",
 "core": ["「自画自刻自印」：艺术家独立完成全流程",
          "反对传统版画的分工制（画师/雕师/印师）",
          "受西方表现主义与个人主义影响",
          "木刻的刀痕与自发的力度被强调"],
 "visual": {"色彩": "少套色或单色，保留木纹与刀痕；有时极简",
            "光影": "平面化，靠黑白对比与刀痕密度",
            "笔触": "刀刻的棱角与飞白，手感强烈",
            "构图": "个体视角、粗犷有力、常带表现主义扭曲",
            "材质": "木版、和纸、水性颜料或油画颜料手印",
            "情绪": "粗粝、个人、有力、现代的自我主张"},
 "palette": [("#2B2B2B","墨黑"),("#8B6B4A","木褐"),("#D9CFC0","和纸白"),
             ("#A8432A","朱"),("#4A5A6B","蓝灰"),("#6B7A5A","暗绿")],
 "artists": [("栋方志功","1903–1975"),("平冢运一","1905–1986"),
             ("恩地孝四郎","1891–1955"),("山本悍右","1914–1987")],
 "prompt": {"style": "sosaku-hanga, japanese creative woodblock print, self-carved and self-printed, bold gouge marks, expressionist individuality",
            "lighting": "flat, contrast from black and white and gouge density",
            "color": "few blocks or monochrome, wood grain and gouge marks visible, washi paper white",
            "composition": "individual viewpoint, forceful coarse forms, expressionist distortion",
            "medium": "woodblock, washi paper, water-based or oil pigment hand printed",
            "mood": "coarse, personal, forceful, modern self-assertion",
            "camera": "flat frontal, paper edge visible"},
 "negative": "commercial printing, fine registration, delicate ukiyo-e refinement, digital, smooth gradient",
 "video": {"motion": "刻刀移动、木屑落下、印刷时纸张被按压",
           "camera": "static 特写，或缓慢 pan 展示刀痕",
           "note": "创作版画的重点是「一个人的全部工序」"},
 "pitfalls": ["和浮世绘区分：创作版画是艺术家独立完成，浮世绘是分工生产",
              "AI 会自动精细化 → negative 写 fine registration, delicate refinement"],
 "sources": {"cleveland": ["sosaku hanga", "munakata"], "met": ["sosaku hanga", "munakata shiko"],
             "commons": ["Sosaku-hanga woodblock print"]},
 "see_also": ["ukiyo-e", "shin-hanga", "expressionism"],
},
# ---------------------------------------------------------------- 新版画
{
 "slug": "shin-hanga", "name_zh": "新版画", "name_en": "Shin-hanga",
 "period": "1915–1960", "region": "日本", "tier": "A",
 "one_liner": "浮世绘的复活：保留传统分工，但加上西方光影与浪漫情绪。",
 "core": ["保留传统分工制（画师/雕师/印师）",
          "引入西方的透视、光影与氛围描写",
          "题材：风景、美人、歌舞伎，带黄昏与夜景的抒情",
          "出口欧美市场，川濑巴水与吉田博为代表"],
 "visual": {"色彩": "柔和的渐变（ぼかし）：暮色紫、月白、靛青",
            "光影": "电灯、月光、雨雾的氛围光——这是浮世绘没有的",
            "笔触": "精细的雕版与渐变印刷，线条干净",
            "构图": "写实透视与日式构图并存、孤独的旅人、雨雪夜色",
            "材质": "木版、和纸、多色渐变印刷、云母粉",
            "情绪": "抒情、孤独、怀旧、旅途的惆怅"},
 "palette": [("#3A4A6B","暮色蓝"),("#8B7A9A","月光紫"),("#1F3A6E","靛青"),
             ("#C9A25A","灯火黄"),("#E8E4DA","雪白"),("#5A6B5A","雨雾绿")],
 "artists": [("川濑巴水","1883–1957"),("吉田博","1876–1950"),
             ("桥口五叶","1883–1921"),("伊东深水","1898–1972"),
             ("笠松紫浪","1898–1991")],
 "prompt": {"style": "shin-hanga, japanese woodblock print, western-influenced atmospheric landscape, bokashi colour gradation, lonely traveller at dusk",
            "lighting": "atmospheric lamplight, moonlight, rain and mist glow, dusk ambience",
            "color": "soft graded dusk blue, moon violet, indigo, lamp yellow, snow white",
            "composition": "realist perspective combined with japanese framing, solitary figure, rain or snow night",
            "medium": "woodblock print with graded bokashi inking, washi paper, mica dust",
            "mood": "lyrical, solitary, nostalgic, travel melancholy",
            "camera": "flat frontal, wide landscape format"},
 "negative": "flat ukiyo-e colour without atmosphere, harsh western chiaroscuro, oil texture, modern digital",
 "video": {"motion": "雨丝斜落、雪片飘落、灯火闪烁、水面微澜",
           "camera": "static 或极缓 pan；保留版画的平面感",
           "note": "新版画的签名是「渐变＋氛围光」——浮世绘没有这两样"},
 "pitfalls": ["和浮世绘区分：新版画有西方的氛围光与渐变，浮世绘是平涂",
              "AI 会丢掉渐变 → 明确 bokashi gradation, atmospheric lighting"],
 "sources": {"cleveland": ["shin-hanga", "kawase hasui", "yoshida hiroshi"],
             "met": ["shin-hanga", "kawase hasui"], "commons": ["Kawase Hasui woodblock print"]},
 "see_also": ["ukiyo-e", "sosaku-hanga", "tonalism"],
},
# ---------------------------------------------------------------- 萨法维绘画
{
 "slug": "safavid-painting", "name_zh": "萨法维绘画", "name_en": "Safavid Painting",
 "period": "1501–1736", "region": "伊朗", "tier": "A",
 "one_liner": "波斯细密画的高峰：塔赫马斯普的《列王纪》里，每一页都是一座花园。",
 "core": ["萨法维王朝宫廷书坊的黄金时代",
          "《列王纪》等史诗的巨型插图项目",
          "色彩更艳、线条更细密、装饰更繁复",
          "单页画（muraqqa）与肖像画兴起"],
 "visual": {"色彩": "青金蓝、朱红、翠绿、金；饱和度极高且平涂",
            "光影": "无阴影，平面堆叠；金箔与银箔点缀",
            "笔触": "极细的毛笔，勾线后平涂；细节密度惊人",
            "构图": "高视点俯瞰、多层堆叠、装饰边框与书法并存",
            "材质": "纸本、水彩与金箔、泥金装饰、皮革装帧",
            "情绪": "华美、叙事、宫廷的富丽与文学性"},
 "palette": [("#1F3A8A","青金蓝"),("#B03A2E","朱红"),("#3E8A6B","翠绿"),
             ("#C9A227","金箔"),("#6B3FA0","紫"),("#E8DCC0","纸白")],
 "artists": [("苏丹·穆罕默德","1500s"),("阿加·米拉克","1500s"),
             ("米尔·穆萨","1400s"),("礼萨·阿巴西","1565–1635"),
             ("穆罕默德·扎曼","1500s")],
 "prompt": {"style": "safavid persian miniature, court manuscript illumination, tahmasp shahnameh, extreme fine detail, gold leaf, layered flat planes",
            "lighting": "no shadow, entirely flat and decorative, gold leaf reflective",
            "color": "lapis blue, vermilion, emerald, gold leaf, extremely saturated flat fill",
            "composition": "high aerial viewpoint, layered stacked planes, ornamental border with calligraphy",
            "medium": "watercolour and gold on paper, finest brush, illuminated manuscript binding",
            "mood": "gorgeous, narrative, courtly opulence, literary",
            "camera": "high oblique, flat depth, manuscript page framing"},
 "negative": "single point perspective, cast shadows, 3d render, photographic, minimalism, muted colour",
 "video": {"motion": "花园中的活动、马队行进、书法线条流动",
           "camera": "static 俯视，或极缓 zoom 到细节",
           "note": "萨法维的核心是「细密到极限」——提示词要强调 detail density"},
 "pitfalls": ["和波斯细密画区分：萨法维是其中一个王朝时期，色彩更艳、项目更大",
              "AI 会加透视 → negative 写 single point perspective, cast shadows"],
 "sources": {"cleveland": ["safavid", "persian miniature safavid"],
             "met": ["safavid", "shahnameh tahmasp"], "commons": ["Safavid miniature Shahnameh"]},
 "see_also": ["persian-miniature", "mughal-miniature", "islamic-geometric"],
},
# ---------------------------------------------------------------- 原住民艺术
{
 "slug": "native-art", "name_zh": "原住民艺术", "name_en": "Native Art",
 "period": "古代–今", "region": "美洲 / 澳洲 / 大洋洲", "tier": "B",
 "one_liner": "不是装饰，是地图、是律法、是祖先：图案本身就是知识载体。",
 "core": ["图案承载地理、谱系、律法与仪式知识",
          "点画（dot painting）、图腾、树皮画等独特语汇",
          "抽象与象征高度统一，没有「纯装饰」",
          "与土地所有权和口述传统直接绑定"],
 "visual": {"色彩": "澳洲原住民：赭红、土黄、白、黑；北美：绿松石、朱红、黑、米白",
            "光影": "平面化，无光影；靠图案的密度与色点区分",
            "笔触": "点、线、同心圆、U 形、动物足迹的符号系统",
            "构图": "俯瞰式地图构图、对称或辐射、图案无限重复",
            "材质": "树皮、沙地、身体彩绘、织物、木雕、珠饰",
            "情绪": "神圣、集体、与土地连接的深沉感"},
 "palette": [("#A8432A","赭红"),("#C9A25A","土黄"),("#E8E4DA","白"),
             ("#2B2B2B","黑"),("#2E8B8B","绿松石"),("#8B5E2A","树皮褐")],
 "artists": [("澳洲中部原住民艺术家","古代–今"),("艾米丽·凯姆·恩加瓦雷","1910–1996"),
             ("纳马特吉拉群落","1970s"),("北美普韦布洛陶艺家","古代–今"),
             ("玛丽亚·马丁内斯","1887–1980")],
 "prompt": {"style": "indigenous australian aboriginal dot painting, aerial map composition, symbolic iconography, earth ochre on bark, ancestral knowledge",
            "lighting": "entirely flat, no shadow, pattern density creates visual rhythm",
            "color": "earth ochre red, yellow, white, black, turquoise",
            "composition": "aerial map-like composition, concentric circles and journey lines, symmetrical or radiating",
            "medium": "natural ochre on bark or canvas, body paint, woven fibre, carved wood",
            "mood": "sacred, collective, profound connection to country",
            "camera": "flat overhead view, pattern filling the frame"},
 "negative": "western perspective, cast shadow, figurative realism, decorative ornament without meaning, 3d render",
 "video": {"motion": "点画逐个落下、图案缓慢铺展、沙画被绘制",
           "camera": "俯视 static 或极缓 zoom out 揭示全图",
           "note": "必须尊重：这些图案有具体含义，不要当作纯装饰挪用"},
 "pitfalls": ["伦理提醒：原住民图案常有神圣含义与社群版权，商业挪用是敏感问题",
              "AI 容易做成泛化的「部落风」→ 加 specific iconography, ancestral, map-like"],
 "sources": {"cleveland": ["aboriginal art", "native american art"],
             "met": ["native american art", "pueblo pottery", "aboriginal"],
             "commons": ["Aboriginal Australian dot painting"]},
 "see_also": ["outsider-art", "art-brut", "islamic-geometric"],
},
# ---------------------------------------------------------------- 本土主义
{
 "slug": "indigenism", "name_zh": "本土主义（拉丁美洲）", "name_en": "Indigenism",
 "period": "1920–1950", "region": "墨西哥 / 秘鲁 / 安第斯", "tier": "B",
 "one_liner": "把原住民放回画面的中心：不是奇观，而是民族的主体。",
 "core": ["以原住民为民族认同的核心与艺术主体",
          "与壁画运动并行，但更聚焦安第斯与中美洲",
          "融合前哥伦布艺术的造型与色彩",
          "常带政治解放与社会正义的诉求"],
 "visual": {"色彩": "浓烈的土色与织物色：赭红、靛蓝、玉米黄、黑",
            "光影": "平面化与块面化，常无立体塑造",
            "笔触": "块面明确、形体概括、带民间艺术的直接性",
            "构图": "纪念碑式的人物、集体场景、织物纹样填充",
            "材质": "布面油画、壁画、版画、织物",
            "情绪": "庄严、集体、有尊严的抗争与土地情感"},
 "palette": [("#A8432A","赭红"),("#2B4C8B","靛蓝"),("#E8C020","玉米黄"),
             ("#2B2B2B","黑"),("#5A8A4A","龙舌兰绿"),("#C98A4A","土黄")],
 "artists": [("何塞·萨沃加尔","1897–1980"),("迭戈·里维拉（相关）","1886–1957"),
             ("卡米洛·埃加斯","1889–1962"),("马丁·查姆比","1949–")],
 "prompt": {"style": "indigenism, latin american modernist painting, monumental indigenous figures, pre-columbian forms, dignified collective subjects",
            "lighting": "flattened block illumination, form from colour planes rather than modelling",
            "color": "intense earth and textile colour, ochre red, indigo, corn yellow, black",
            "composition": "monumental figures, collective scene, textile pattern filling the surface",
            "medium": "oil on canvas, mural, print, woven textile",
            "mood": "solemn, collective, dignified struggle and land attachment",
            "camera": "eye-level, wide, slight low angle on figures"},
 "negative": "exoticised spectacle, european salon style, romanticised noble savage, light decorative touch",
 "video": {"motion": "集体劳作、游行、织物摆动",
           "camera": "缓慢 pan 或低角度仰拍纪念碑式人物",
           "note": "本土主义的关键是「主体而非奇观」——人物要有尊严与分量"},
 "pitfalls": ["和壁画运动区分：本土主义更聚焦原住民身份与安第斯传统",
              "避免异域化 → 加 dignified, monumental, subject not spectacle"],
 "sources": {"cleveland": ["indigenism", "siqueiros"], "met": ["indigenism", "latin american art"],
             "commons": ["Jose Sabogal painting", "Indigenism painting Peru", "Andean painting indigenist"]},
 "see_also": ["muralism", "social-realism", "native-art"],
},
]

ARTIST_KEYS = {
 "sosaku-hanga": ["sosaku hanga", "munakata", "hiratsuka", "onchi", "yamamoto",
                   "sekiya", "a zechi"],
 "shin-hanga": ["shin-hanga", "shinhanga", "hasui", "kawase", "yoshida hiroshi",
                 "shinsui", "kasamatsu", "hashiguchi", "koitsu", "tsuchiya"],
 "safavid-painting": ["safavid", "shahnameh", "tahmasp", "sultan muhammad",
                       "aga mirak", "reza abbasi", "persian miniature", "muraqqa"],
 "native-art": ["aboriginal", "dot painting", "bark painting", "native american",
                 "pueblo", "navajo", "haida", "dreaming", "indigenous"],
 "indigenism": ["sabogal", "indigenis", "egas", "chambi", "andean"],
}
