# -*- coding: utf-8 -*-
"""流派定义 —— 先锋 · 当代 · 后现代（22 个）。

这一批直接回应用户提出的关键词：先锋艺术、当代艺术、后现代艺术、超现实主义。
多数作品仍在版权期内，因此以纯提示词卡为主——视觉语言与七层结构照常拆解。
"""

CATEGORY = "先锋·当代·后现代"

MOVEMENTS = [
# ---------------------------------------------------------------- 先锋艺术
{
 "slug": "avant-garde", "name_zh": "先锋艺术", "name_en": "Avant-Garde",
 "period": "1850–今", "region": "全球", "tier": "B",
 "one_liner": "不是一种风格，而是一种姿态：走在观众前面，故意让他们跟不上。",
 "core": ["先锋不是画法，而是「与体制对立」的位置",
          "不断自我否定：每一代先锋都要推翻上一代",
          "宣言、丑闻、论战是作品的一部分",
          "横跨达达、构成主义、超现实主义、观念艺术等"],
 "visual": {"色彩": "没有固定色彩——先锋性来自策略而非调色板",
            "光影": "同样不固定；但它偏好「打破既有布光惯例」",
            "笔触": "取决于具体流派，共同点是拒绝既定技法",
            "构图": "打破惯例：不对称、拼贴、去中心、反审美",
            "材质": "从油画到现成品、印刷品到身体",
            "情绪": "挑衅、急切、智性、与时代搏斗的紧张感"},
 "palette": [("#C1272D","宣言红"),("#111111","黑"),("#F2EDE4","白"),
             ("#1F5FD6","蓝"),("#C9A227","黄"),("#8A8A85","灰")],
 "artists": [("杜尚","1887–1968"),("马列维奇","1879–1935"),("布勒东","1896–1966"),
             (" situationist 情境主义国际","1957–1972"),("居伊·德波","1931–1994")],
 "prompt": {"style": "avant-garde art, deliberate provocation, anti-convention stance, manifesto aesthetics, breaking established technique",
            "lighting": "unconventional lighting that breaks photographic norms, or deliberately crude illumination",
            "color": "provocative high contrast or deliberately ugly clashing colour",
            "composition": "asymmetric, collage-based, decentred, anti-aesthetic arrangement",
            "medium": "mixed media, found object, printed manifesto, performance documentation",
            "mood": "provocative, urgent, intellectual, in conflict with its time",
            "camera": "unconventional framing, tilted, deliberately awkward"},
 "negative": "tasteful, harmonious, conventional beauty, academic finish, decorative, safe, commercial",
 "video": {"motion": "突兀的、破坏性的动作；刻意让观众不适",
           "camera": "刻意的错误运镜：跳跃、失焦、突然中断",
           "note": "先锋是一种态度——提示词要写「反惯例」，而不是具体风格"},
 "pitfalls": ["「先锋」不是一个视觉风格，写提示词时必须同时指定具体流派（达达/构成主义…）",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["avant-garde"], "met": ["avant-garde"], "commons": []},
 "see_also": ["dada", "constructivism", "surrealism", "conceptual-art"],
},
# ---------------------------------------------------------------- 当代艺术
{
 "slug": "contemporary-art", "name_zh": "当代艺术", "name_en": "Contemporary Art",
 "period": "1970–今", "region": "全球", "tier": "B",
 "one_liner": "什么都可能：媒介无限、风格并存、市场与理论各说各话。",
 "core": ["没有统一风格，只有统一的时间段与体制语境",
          "媒介无限：装置、影像、行为、社会参与、生物艺术",
          "全球化与双年展体系塑造的生产方式",
          "理论话语（身份、后殖民、生态、去人类中心）与作品并行"],
 "visual": {"色彩": "完全开放；常出现「非艺术材料」的本色",
            "光影": "展厅照明、投影、屏幕光成为作品的一部分",
            "笔触": "从零笔触到极端手工并存",
            "构图": "空间化：作品占据房间而非画框",
            "材质": "任何材料：现成品、数字、生物、社会关系",
            "情绪": "多元、开放、有时晦涩、与理论高度绑定"},
 "palette": [("#E8E4DA","展厅白"),("#8A8A85","水泥灰"),("#1A1A1A","黑"),
             ("#29ABE2","屏幕蓝"),("#F23D8E","霓虹粉"),("#5FA85F","植物绿")],
 "artists": [("博伊斯","1921–1986"),("辛迪·舍曼","1954–"),("杰夫·昆斯","1955–"),
             ("艾未未","1957–"),("徐冰","1955–"),("蔡国强","1957–")],
 "prompt": {"style": "contemporary art installation, mixed media, gallery context, conceptual and globalised, no single style",
            "lighting": "gallery lighting or projection light, screen glow, architectural illumination",
            "color": "open palette including raw industrial and non-art material colours",
            "composition": "spatial installation occupying a room, viewer inside the work",
            "medium": "anything: readymade, digital, biological, social practice, video",
            "mood": "plural, open, sometimes opaque, theory-bound",
            "camera": "wide gallery view, eye-level, architectural documentation"},
 "negative": "single historical style, easel painting convention, unified movement aesthetic, nostalgia",
 "video": {"motion": "观众在空间中走动、影像播放、机械元件运转",
           "camera": "缓慢 track 穿过展厅；多个视角并置",
           "note": "当代艺术的关键是「空间与观众」，不是画面"},
 "pitfalls": ["「当代艺术」是时间段不是风格 → 写提示词必须叠加具体形式（装置/影像/行为）",
              "版权：几乎全在版权期内，只存提示词"],
 "sources": {"cleveland": ["contemporary art"], "met": ["contemporary art"], "commons": []},
 "see_also": ["postmodernism", "conceptual-art", "neo-dada", "avant-garde"],
},
# ---------------------------------------------------------------- 后现代主义
{
 "slug": "postmodernism", "name_zh": "后现代主义", "name_en": "Postmodernism",
 "period": "1960–1990", "region": "全球", "tier": "B",
 "one_liner": "对宏大叙事的怀疑：拼贴、引用、戏仿，把一切风格都当成素材。",
 "core": ["拒绝现代主义的原创性与进步叙事",
          "拼贴（pastiche）与引用：把历史风格当符号使用",
          "去中心、多重解读、反讽",
          "高雅与通俗的界限被取消"],
 "visual": {"色彩": "风格杂糅：历史色板与商业色板并置",
            "光影": "混合光源，刻意不统一",
            "笔触": "有时引用旧技法，有时完全机械复制",
            "构图": "并置、拼贴、嵌套、引号式的使用符号",
            "材质": "混合媒介、照片、印刷品、商业材料、复制品",
            "情绪": "反讽、疏离、戏谑、拒绝真诚"},
 "palette": [("#F23D8E","霓虹粉"),("#29ABE2","亮蓝"),("#E8C020","亮黄"),
             ("#8B6B4A","仿古褐"),("#111111","黑"),("#E8E4DA","白")],
 "artists": [("罗伯特·劳森伯格","1925–2008"),("芭芭拉·克鲁格","1945–"),
             ("辛迪·舍曼","1954–"),("罗伯特·文丘里（建筑）","1925–2018"),
             ("谢丽·莱文","1947–")],
 "prompt": {"style": "postmodern art, pastiche and appropriation, ironic quotation of historical styles, high and low culture mixed, simulacrum",
            "lighting": "mixed inconsistent light sources, deliberately unharmonised",
            "color": "clashing historic and commercial palettes side by side",
            "composition": "juxtaposition, collage, nesting, quotation marks around symbols",
            "medium": "mixed media, photography, print, commercial material, reproduction",
            "mood": "ironic, detached, playful, refusing sincerity",
            "camera": "eclectic, deliberately mixing conventions"},
 "negative": "single coherent style, sincerity, originality claim, unified light, modernist purity",
 "video": {"motion": "不同来源的影像并置、循环、重复引用",
           "camera": "混合不同镜头的惯例，刻意不统一",
           "note": "后现代的手法核心是「引用」——把别人的风格当素材用"},
 "pitfalls": ["后现代是态度不是风格 → 必须叠加具体形式（拼贴/戏仿/挪用）",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["postmodernism", "robert rauschenberg"],
             "met": ["postmodernism"], "commons": []},
 "see_also": ["contemporary-art", "pop-art", "neo-dada", "avant-garde"],
},
# ---------------------------------------------------------------- 抽象艺术
{
 "slug": "abstract-art", "name_zh": "抽象艺术", "name_en": "Abstract Art",
 "period": "1910–今", "region": "全球", "tier": "B",
 "one_liner": "不再画任何东西：颜色、形状、线条自己构成意义。",
 "core": ["彻底放弃可辨识的具象对象",
          "分为几何抽象与抒情抽象两大路径",
          "强调形式、色彩、节奏本身的表现力",
          "是 20 世纪所有前卫运动共享的出口"],
 "visual": {"色彩": "从单色到纯色对撞，全部可能",
            "光影": "无外部光源；色彩关系本身制造空间感",
            "笔触": "从零笔触的硬边到极厚的表现性笔触",
            "构图": "满幅、中心、分散——取决于子流派",
            "材质": "油画、丙烯、纸本、数字",
            "情绪": "取决于子流派：从冷静到激烈"},
 "palette": [("#D32027","红"),("#1B4F9C","蓝"),("#F2C300","黄"),
             ("#111111","黑"),("#FFFFFF","白"),("#8A8A85","灰")],
 "artists": [("康定斯基","1866–1944"),("蒙德里安","1872–1944"),("马列维奇","1879–1935"),
             ("德库宁","1904–1997"),("罗斯科","1903–1970")],
 "prompt": {"style": "abstract art, non-representational, form and colour as subject, geometric or lyrical abstraction",
            "lighting": "no external light source, spatial effect from colour relationships only",
            "color": "open palette from monochrome to pure saturated contrast",
            "composition": "all-over, centred, or dispersed depending on sub-style",
            "medium": "oil, acrylic, paper, digital",
            "mood": "varies from cool and rational to violently expressive",
            "camera": "flat frontal, surface filling the frame"},
 "negative": "recognisable object, figure, landscape, narrative content, illustration",
 "video": {"motion": "形态持续变形、色彩流动、几何元素位移",
           "camera": "static 平面构图；让画面内部运动",
           "note": "抽象是一个大类——提示词里要说明是几何抽象还是抒情抽象"},
 "pitfalls": ["太笼统 → 必须指定子类型（geometric / lyrical / gestural）",
              "版权：20 世纪作品多数在版权期内，只存提示词"],
 "sources": {"cleveland": ["abstract art"], "met": ["abstract art"], "commons": []},
 "see_also": ["suprematism", "de-stijl", "abstract-expressionism", "art-informel"],
},
# ---------------------------------------------------------------- 无形式艺术
{
 "slug": "art-informel", "name_zh": "无形式艺术", "name_en": "Art Informel",
 "period": "1945–1960", "region": "法国 / 欧洲", "tier": "B",
 "one_liner": "战后欧洲的伤口：没有形状，只有材料的堆叠与手势的痕迹。",
 "core": ["与抽象表现主义同时但更欧洲、更物质",
          "放弃几何，强调材料的肉体性与时间痕迹",
          "厚涂、刮擦、烧灼、拼贴织物与沙",
          "常与战后创伤与存在主义相关"],
 "visual": {"色彩": "暗淡的土色、灰、锈红、沥青黑；低饱和",
            "光影": "厚涂表面产生真实的凹凸阴影",
            "笔触": "极厚 impasto、刮刀、手指、倾倒",
            "构图": "无中心、无边界、材料自行蔓延",
            "材质": "厚颜料、沙、石膏、织物拼贴、烧灼痕迹",
            "情绪": "沉重、创伤、物质性的焦灼"},
 "palette": [("#5A4A3A","泥褐"),("#3A3A38","沥青黑"),("#A8432A","锈红"),
             ("#8A8A85","灰"),("#6B7A5A","暗绿"),("#D9CFC0","石膏白")],
 "artists": [("福特里耶","1898–1964"),("塔皮埃斯","1923–2012"),
             ("杜布菲（部分）","1901–1985"),("布里","1911–1995"),("沃尔","1914–1973")],
 "prompt": {"style": "art informel, tachisme, matter painting, thick impasto and scraped surface, post-war existential materiality",
            "lighting": "real raking light revealing the relief of the paint surface, deep material shadow",
            "color": "dull earth tones, grey, rust red, bitumen black, low saturation",
            "composition": "no centre, no boundary, material spreading across the surface",
            "medium": "thick oil, sand, plaster, cloth collage, scorch marks, palette knife",
            "mood": "heavy, traumatic, material anguish",
            "camera": "flat frontal, close, texture filling the frame"},
 "negative": "clean geometry, flat colour, neat design, representational subject, digital smoothness",
 "video": {"motion": "材料缓慢堆积、颜料流动、表面被刮擦",
           "camera": "极缓 push in 贴近表面质感",
           "note": "无形式艺术的重点是「物质的重量」"},
 "pitfalls": ["和抽象表现主义混淆 → 无形式艺术更欧洲、更哑光、更物质",
              "AI 会做成干净的抽象 → 加 thick impasto, sand, scraped, matter"],
 "sources": {"cleveland": ["art informel", "tachisme", "tapies"],
             "met": ["art informel", "jean dubuffet"], "commons": ["Art informel painting"]},
 "see_also": ["tachisme", "abstract-expressionism", "lyrical-abstraction", "art-brut"],
},
# ---------------------------------------------------------------- 斑点主义
{
 "slug": "tachisme", "name_zh": "斑点主义", "name_en": "Tachisme",
 "period": "1945–1960", "region": "法国", "tier": "B",
 "one_liner": "用色斑代替笔触：颜料自己落在画布上，像一场有控制的意外。",
 "core": ["tache（斑点）：色块、滴落、泼洒直接落在画布",
          "从书法性手势转向「自动性」的偶然",
          "比无形式艺术更轻盈、更有韵律",
          "法国对抽象表现主义的对应物"],
 "visual": {"色彩": "明亮的自由色彩，常带透明感与层叠",
            "光影": "无光源；色斑之间的重叠制造深度",
            "笔触": "滴、泼、洒、按压；手势轻快而非沉重",
            "构图": "散布式、无中心、如星群或苔藓",
            "材质": "稀释油画、丙烯、纸本",
            "情绪": "轻盈、即兴、诗意的偶然"},
 "palette": [("#2B6BB8","钴蓝"),("#C1272D","红"),("#E8C020","黄"),
             ("#5FA85F","绿"),("#8B3FA0","紫"),("#F2EDE4","留白")],
 "artists": [("哈同","1904–1989"),("马修","1921–2012"),
             ("苏拉热","1919–2022"),("布丹","1922–"),("德戈特","1914–1978")],
 "prompt": {"style": "tachisme, lyrical stain painting, dripped and splashed colour spots, calligraphic gesture, automatic improvisation",
            "lighting": "no light source, depth from overlapping translucent stains",
            "color": "bright free colour, cobalt, red, yellow, green, violet, with transparency",
            "composition": "scattered, no centre, like a constellation or lichen growth",
            "medium": "thinned oil, acrylic, paper, poured and pressed marks",
            "mood": "light, improvised, poetic accident",
            "camera": "flat frontal, surface filling the frame"},
 "negative": "geometric precision, hard edges, representational, heavy impasto, neat design, symmetry",
 "video": {"motion": "色斑缓慢扩散、墨迹晕开、颜色互相渗透",
           "camera": "static 或极缓 zoom；让颜色自己在动",
           "note": "斑点主义的动是「扩散」，不是笔在动"},
 "pitfalls": ["和无形式艺术混淆 → 斑点主义更轻、更透明、更有音乐性",
              "AI 会画得太实 → 加 translucent, stain, dripped, automatic"],
 "sources": {"cleveland": ["tachisme", "hans hartung", "soulages"],
             "met": ["tachisme", "pierre soulages"], "commons": ["Tachisme painting"]},
 "see_also": ["art-informel", "lyrical-abstraction", "abstract-expressionism"],
},
# ---------------------------------------------------------------- 抒情抽象
{
 "slug": "lyrical-abstraction", "name_zh": "抒情抽象", "name_en": "Lyrical Abstraction",
 "period": "1960–1975", "region": "美国 / 欧洲", "tier": "B",
 "one_liner": "抽象但温柔：柔和的色雾、流动的边缘、没有攻击性的笔触。",
 "core": ["对极简主义与硬边的反动，重回感官与情绪",
          "柔和的色彩与模糊的边界，接近水彩的透明",
          "常被视为「女性化」的抽象（也是批评的靶子）",
          "与色域绘画有重叠但更流动、更感性"],
 "visual": {"色彩": "柔和的粉、紫、青、乳白；透明层叠，低至中等饱和",
            "光影": "弥漫的光，无明确光源；颜色像雾一样扩散",
            "笔触": "柔软、晕染、喷枪式的过渡",
            "构图": "满幅的色雾、流动的边缘、无几何结构",
            "材质": "丙烯、稀释颜料渗染、喷枪、大画布",
            "情绪": "温柔、感官、冥想、略带忧郁的愉悦"},
 "palette": [("#E8B8D0","柔粉"),("#B8A8D8","淡紫"),("#A8D8E8","雾青"),
             ("#F2EDE4","乳白"),("#C9D8B8","嫩绿"),("#E8C8A8","暖沙")],
 "artists": [("弗兰肯塔勒","1928–2011"),("奥利茨基","1927–2007"),
             ("路易斯","1912–1962"),("詹金斯","1923–2012"),("纳特金","1930–")],
 "prompt": {"style": "lyrical abstraction, soft stained colour veils, fluid edges, sensual and atmospheric, post-minimalist warmth",
            "lighting": "diffused ambient glow, no defined source, colour spreading like mist",
            "color": "soft pink, lavender, misty cyan, cream, translucent layered washes",
            "composition": "full-field colour haze, flowing edges, no geometric armature",
            "medium": "acrylic soaked into canvas, spray gun, large unstretched canvas",
            "mood": "tender, sensuous, meditative, faintly melancholic pleasure",
            "camera": "flat frontal, soft focus, surface filling the frame"},
 "negative": "hard edges, geometric precision, saturated contrast, representational, minimal restraint, aggressive gesture",
 "video": {"motion": "色雾缓慢流动、颜色互相渗透、边缘持续移动",
           "camera": "极缓 push in 或 static；柔和无锐度",
           "note": "抒情抽象的运动应该像呼吸，不是手势"},
 "pitfalls": ["和色域绘画区分：抒情抽象更流动、更柔软、边缘不清晰",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["lyrical abstraction"], "met": ["lyrical abstraction"], "commons": []},
 "see_also": ["color-field", "tachisme", "post-painterly-abstraction"],
},
# ---------------------------------------------------------------- 硬边绘画
{
 "slug": "hard-edge", "name_zh": "硬边绘画", "name_en": "Hard-Edge Painting",
 "period": "1958–1970", "region": "美国", "tier": "B",
 "one_liner": "边缘像刀切：色块之间没有任何过渡，画面干净到发冷。",
 "core": ["色块边界锐利清晰，无渐变无笔触",
          "整个画面被分成少数几块纯色区域",
          "与波普、极简、色域绘画同源",
          "反对抽象表现主义的情绪化笔触"],
 "visual": {"色彩": "高纯度平涂的少数几色，对比强烈且干净",
            "光影": "完全没有明暗，纯平面",
            "笔触": "零笔触，机械般精确的边界",
            "构图": "几何分割、简洁有力、常不对称",
            "材质": "丙烯、平涂、遮罩胶带、光滑表面",
            "情绪": "冷峻、精确、理性、拒绝情感表达"},
 "palette": [("#D32027","正红"),("#1B4F9C","正蓝"),("#F2C300","正黄"),
             ("#111111","黑"),("#FFFFFF","白"),("#5FA85F","正绿")],
 "artists": [("凯利","1923–2015"),("斯特拉","1936–"),("诺兰","1924–2010"),
             ("利伯曼","1923–2012"),("霍尔登","1936–")],
 "prompt": {"style": "hard-edge painting, crisp sharp colour boundaries, flat unmodulated colour areas, no brushwork, geometric precision",
            "lighting": "no shading at all, completely flat",
            "color": "few high purity flat colours, strong clean contrast",
            "composition": "geometric division, simple and forceful, often asymmetric",
            "medium": "acrylic on canvas, masking tape edges, smooth matte surface",
            "mood": "cool, precise, rational, refusing emotional expression",
            "camera": "flat orthographic, no depth, no shadow"},
 "negative": "gradient, brushwork, soft edge, texture, shading, expressive gesture, atmospheric depth",
 "video": {"motion": "色块精确地滑动、替换、旋转",
           "camera": "static 平面；版式动画式运动",
           "note": "硬边的动必须精确到像素——任何柔和都是错的"},
 "pitfalls": ["和极简主义区分：硬边仍有色彩关系与几何张力，极简更彻底地减少",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["hard-edge painting", "ellsworth kelly"],
             "met": ["hard edge painting", "frank stella"], "commons": []},
 "see_also": ["color-field", "minimalism-art", "de-stijl", "post-painterly-abstraction"],
},
# ---------------------------------------------------------------- 后绘画性抽象
{
 "slug": "post-painterly-abstraction", "name_zh": "后绘画性抽象", "name_en": "Post-Painterly Abstraction",
 "period": "1964–1975", "region": "美国", "tier": "B",
 "one_liner": "把手从画布上拿开：颜色渗进布面，没有笔触，也没有情绪。",
 "core": ["格林伯格命名的路线：反对抽象表现主义的「绘画性」",
          "染色法（staining）：稀释颜料渗入未打底的画布",
          "形状清晰、色彩平实、无手势痕迹",
          "通向极简主义与硬边绘画"],
 "visual": {"色彩": "清亮的纯色，渗染进布面，边缘略毛但整体清晰",
            "光影": "无光影，颜色就是全部",
            "笔触": "几乎无笔触，颜料像被布吸收而非被画上去",
            "构图": "简单的几何形状或条纹，满幅铺陈",
            "材质": "丙烯渗染未打底画布、生布纹理可见",
            "情绪": "冷静、清澈、去情绪化的视觉愉悦"},
 "palette": [("#5FA8D8","清蓝"),("#C9D84A","黄绿"),("#E85D75","珊瑚粉"),
             ("#F2EDE4","生布白"),("#8B5EA8","紫"),("#E8C020","柠黄")],
 "artists": [("路易斯","1912–1962"),("诺兰","1924–2010"),("奥利茨基","1927–2007"),
             ("弗兰肯塔勒","1928–2011"),("斯特拉（早期）","1936–")],
 "prompt": {"style": "post-painterly abstraction, colour staining into raw canvas, no gesture, clear simple shapes, greenbergian flatness",
            "lighting": "no shading, colour as the sole visual event",
            "color": "clear bright pure colour soaked into fabric, raw canvas cream",
            "composition": "simple geometric shapes or stripes, full-field",
            "medium": "thinned acrylic soaked into unprimed canvas, visible weave, no impasto",
            "mood": "cool, limpid, de-emotionalised visual pleasure",
            "camera": "flat frontal, surface filling the frame"},
 "negative": "gestural brushwork, impasto, expressive emotion, dark mood, representational, layered depth",
 "video": {"motion": "颜色在布面上极缓扩散、条纹平移",
           "camera": "static 或极缓 pan；几乎没有运动",
           "note": "这一派的关键是「没有手」——不要出现笔触的运动"},
 "pitfalls": ["和色域绘画区分：后绘画性抽象更强调染色技法与清晰形状",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["post-painterly abstraction"], "met": ["post painterly abstraction"],
             "commons": []},
 "see_also": ["color-field", "hard-edge", "minimalism-art", "lyrical-abstraction"],
},
# ---------------------------------------------------------------- 新达达
{
 "slug": "neo-dada", "name_zh": "新达达", "name_en": "Neo-Dada",
 "period": "1950–1970", "region": "美国 / 欧洲", "tier": "B",
 "one_liner": "达达的第二次生命：把日常物件、报纸和床铺直接搬进美术馆。",
 "core": ["重新启用达达的现成品与拼贴策略",
          "日常物与废弃物进入作品",
          "模糊艺术与生活的边界",
          "是波普艺术与观念艺术的直接前身"],
 "visual": {"色彩": "日常物的杂色：报纸灰、包装色、旧布料",
            "光影": "真实环境光；物件保留自己的材质与阴影",
            "笔触": "拼贴、涂抹、现成物组合",
            "构图": "组合式、堆叠、反构图",
            "材质": "现成品、报纸、床铺、轮胎、颜料与石膏",
            "情绪": "玩世、反讽、粗粝、对体制的嘲弄"},
 "palette": [("#D9CFC0","报纸灰"),("#8B6B4A","旧木褐"),("#111111","黑"),
             ("#C1272D","印章红"),("#A8B8C8","旧布蓝"),("#E8DCC8","石膏白")],
 "artists": [("劳森伯格","1925–2008"),("贾斯珀·琼斯","1930–"),
             ("克莱因（伊夫）","1928–1962"),("曼佐尼","1933–1963"),("帕伊克","1931–")],
 "prompt": {"style": "neo-dada combine painting, readymade and found object, everyday debris, anti-art gesture, rauschenberg combine",
            "lighting": "real ambient light, objects keep their own material shadow",
            "color": "everyday mixed colour, newsprint grey, packaging tones, old cloth",
            "composition": "assemblage, stacked, anti-compositional",
            "medium": "found object, newspaper, bed, tyre, paint and plaster combine",
            "mood": "playful, ironic, coarse, mocking the institution",
            "camera": "eye-level, medium shot, documentary"},
 "negative": "tasteful harmony, refined craft, single medium purity, elegant abstraction, precious materials",
 "video": {"motion": "物件被移动、堆叠、颜料被涂抹上去",
           "camera": "documentary handheld；避免审美化的运镜",
           "note": "新达达的动是「操作物件」的过程记录"},
 "pitfalls": ["和达达区分：新达达更温和、更接近绘画，政治性更弱",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["neo-dada", "rauschenberg", "jasper johns"],
             "met": ["neo-dada", "robert rauschenberg"], "commons": []},
 "see_also": ["dada", "pop-art", "conceptual-art", "postmodernism"],
},
# ---------------------------------------------------------------- 新波普
{
 "slug": "neo-pop", "name_zh": "新波普", "name_en": "Neo-Pop",
 "period": "1980–今", "region": "全球", "tier": "B",
 "one_liner": "波普进入品牌时代：卡通、玩具、奢侈品与艺术市场彻底合流。",
 "core": ["把波普的消费图像策略用于品牌与明星文化",
          "卡通、玩具、广告美学被直接采用",
          "作品与商品、衍生品的界限消失",
          "常与超扁平、媚俗艺术重叠"],
 "visual": {"色彩": "高饱和的商业色：荧光粉、亮金、糖果色",
            "光影": "产品摄影式的完美布光，高光泽",
            "笔触": "零笔触或商业插画式的平滑",
            "构图": "居中产品式、图案重复、装饰边框",
            "材质": "丙烯、树脂、不锈钢、限量版玩具",
            "情绪": "闪亮、玩世、消费主义的兴奋与空虚"},
 "palette": [("#F23D8E","荧光粉"),("#E8C020","亮金"),("#29D6E8","糖果蓝"),
             ("#FFFFFF","白"),("#111111","黑"),("#A8F23D","荧光绿")],
 "artists": [("村上隆","1962–"),("杰夫·昆斯","1955–"),("KAWS","1974–"),
             ("草间弥生（相关）","1929–"),("罗梅罗·布里托","1963–")],
 "prompt": {"style": "neo-pop art, brand and toy aesthetics, cartoon imagery, glossy commercial finish, high art meets merchandise",
            "lighting": "flawless product-shot lighting, strong glossy specular highlights",
            "color": "high saturation commercial colour, fluorescent pink, gold, candy blue",
            "composition": "centred product framing, repeated pattern, decorative border",
            "medium": "acrylic, resin, stainless steel, limited edition vinyl toy",
            "mood": "shiny, playful, consumerist excitement and emptiness",
            "camera": "flat product shot, centred, glossy"},
 "negative": "matte, muted, gritty, handcrafted imperfection, political critique, restraint",
 "video": {"motion": "产品旋转展示、图案循环、闪光粒子",
           "camera": "完美的环绕展示镜头",
           "note": "新波普的动要像广告片一样无瑕"},
 "pitfalls": ["和波普区分：新波普与品牌、市场深度绑定，缺少原波普的批判距离",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["neo-pop"], "met": ["neo pop art"], "commons": []},
 "see_also": ["pop-art", "superflat", "kitsch", "contemporary-art"],
},
# ---------------------------------------------------------------- 超前卫
{
 "slug": "transavantgarde", "name_zh": "超前卫", "name_en": "Transavantgarde",
 "period": "1979–1990", "region": "意大利", "tier": "B",
 "one_liner": "意大利对观念艺术的反动：重新拿起画笔，画神话、身体与历史。",
 "core": ["回到绘画、形象与手工性",
          "混合神话、艺术史引用与个人符号",
          "色彩浓烈、笔触自由、尺幅巨大",
          "与德国新表现主义、美国新意象绘画同期"],
 "visual": {"色彩": "浓烈饱和的混合色，常不协调且大胆",
            "光影": "无统一光源，情绪化的明暗",
            "笔触": "自由、快速、可见，带装饰性",
            "构图": "中心形象 + 碎片化的背景引用",
            "材质": "大画布、丙烯与油画、拼贴元素",
            "情绪": "狂喜、神话性、感官的、反智性的"},
 "palette": [("#C1272D","朱红"),("#E8C020","金黄"),("#2B6BB8","钴蓝"),
             ("#5FA85F","翠绿"),("#8B3FA0","紫"),("#E8DCC8","生白")],
 "artists": [("基亚","1946–"),("库基","1949–"),("克莱门特","1952–"),
             ("帕拉迪诺","1948–"),("德·马里亚（相关）","1954–")],
 "prompt": {"style": "transavanguardia, italian neo-expressionist painting, mythological imagery, free chromatic brushwork, art history quotation",
            "lighting": "inconsistent emotional light, no unified source",
            "color": "intense saturated mixed colour, bold and clashing",
            "composition": "central figure against fragmented quoted background",
            "medium": "large canvas, acrylic and oil, collage elements",
            "mood": "ecstatic, mythic, sensuous, anti-intellectual",
            "camera": "eye-level, wide, coarse texture visible"},
 "negative": "cool conceptual restraint, minimalism, photographic flatness, muted palette, single light logic",
 "video": {"motion": "画面元素旋转、笔触生长、形象漂浮",
           "camera": "handheld 或缓慢环绕",
           "note": "超前卫的动应该像酒神节，不要克制"},
 "pitfalls": ["和新表现主义区分：超前卫更装饰、更神话、更意大利",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["transavantgarde"], "met": ["transavanguardia"], "commons": []},
 "see_also": ["neo-expressionism", "new-objectivity", "postmodernism"],
},
# ---------------------------------------------------------------- 原生艺术
{
 "slug": "art-brut", "name_zh": "原生艺术", "name_en": "Art Brut",
 "period": "1945–今", "region": "法国 / 全球", "tier": "B",
 "one_liner": "杜布菲收集的精神病人与囚犯的画：完全不受艺术史污染的表达。",
 "core": ["杜布菲提出的概念：未经文化训练者的创作",
          "作者多为精神病患者、囚徒、通灵者",
          "完全无视透视、比例与艺术史规范",
          "材料常为随手可得之物：废纸、炭、唾液颜料"],
 "visual": {"色彩": "随手可得的材料色：炭黑、铅笔灰、廉价颜料",
            "光影": "几乎不存在；画面是平面的",
            "笔触": "执拗、重复、密集的刻画",
            "构图": "填满画面、对称或强迫性重复、无视透视",
            "材质": "废纸、炭笔、圆珠笔、面包渣、唾液混合颜料",
            "情绪": "执拗、私密、强迫性、令人不安的真诚"},
 "palette": [("#3A3A38","炭黑"),("#8A8A85","铅笔灰"),("#C9A25A","旧纸黄"),
             ("#A8432A","廉价红"),("#4A5A6B","廉价蓝"),("#E8E4DA","废纸白")],
 "artists": [("阿道夫·沃夫利","1864–1930"),("阿洛伊斯·科尔巴兹","1886–1964"),
             ("玛奇·吉尔","1886–1961"),("杜布菲（收集者）","1901–1985"),
             ("亨利·达格","1892–1973")],
 "prompt": {"style": "art brut, outsider art, untrained compulsive creation, dense repetitive mark making, disregard for perspective and proportion",
            "lighting": "essentially absent, flat image",
            "color": "materials at hand, charcoal black, pencil grey, aged paper yellow, cheap pigment",
            "composition": "fills the entire surface, symmetry or obsessive repetition, no perspective",
            "medium": "scrap paper, charcoal, ballpoint pen, breadcrumb and spit pigment",
            "mood": "compulsive, private, obsessive, uncomfortably sincere",
            "camera": "flat frontal, entire sheet in frame"},
 "negative": "academic technique, correct perspective, professional finish, commercial polish, art historical reference",
 "video": {"motion": "几乎静止；或强迫性的重复动作（书写、雕刻）",
           "camera": "static 平面；像翻看档案",
           "note": "原生艺术的价值在「未被训练」——不要给它加技法"},
 "pitfalls": ["和稚拙艺术区分：原生艺术的作者确实未经训练且常处边缘处境；稚拙艺术可以是刻意的",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["art brut", "outsider art", "adolf wolfli"],
             "met": ["art brut", "outsider art"], "commons": []},
 "see_also": ["outsider-art", "naive-art", "art-informel"],
},
# ---------------------------------------------------------------- 域外艺术
{
 "slug": "outsider-art", "name_zh": "域外艺术", "name_en": "Outsider Art",
 "period": "1970–今", "region": "全球", "tier": "B",
 "one_liner": "在艺术世界的围墙之外：自学、精神困境、民间信仰与极端执念。",
 "core": ["比原生艺术更宽：包含民间艺术家、灵媒、自学者",
          "与主流艺术体制无关联",
          "常有极强的个人宇宙观与体系",
          "环境艺术：整栋房子、整个花园都是作品"],
 "visual": {"色彩": "强烈主观的色彩，常饱和到刺眼或极度阴郁",
            "光影": "无统一逻辑，服从作者的私人宇宙",
            "笔触": "执拗、重复、密不透风",
            "构图": "填满、对称、或无限重复的图案",
            "材质": "任何可得之物：废铁、瓶盖、水泥、毛线",
            "情绪": "执念、灵性、偏执、自成体系的美"},
 "palette": [("#C1272D","执念红"),("#2B6BB8","天启蓝"),("#E8C020","信仰黄"),
             ("#3A3A38","焦黑"),("#5FA85F","生机绿"),("#E8E4DA","底白")],
 "artists": [("亨利·达格","1892–1973"),("萨瓦·塞库利奇","1902–1942"),
             ("霍华德·芬斯特","1916–2001"),("尼科·皮罗斯马尼","1862–1918"),
             ("西斯特·盖茨（相关）","1973–")],
 "prompt": {"style": "outsider art, self-taught visionary environment, obsessive personal cosmology, dense repetitive pattern, untrained but driven",
            "lighting": "no consistent logic, subject to the author's private universe",
            "color": "subjectively intense, either glaringly saturated or deeply gloomy",
            "composition": "fills the surface, symmetry, or infinitely repeating motifs",
            "medium": "anything available: scrap metal, bottle caps, cement, yarn, plywood",
            "mood": "obsessive, visionary, paranoid, self-consistent beauty",
            "camera": "flat frontal, or wide environment documentation"},
 "negative": "professional training, institutional framing, detached irony, refined taste, conceptual distance",
 "video": {"motion": "环境缓慢展现；访客在其中行走",
           "camera": "缓慢 track 穿过环境艺术作品",
           "note": "域外艺术常常是「一整个环境」——镜头要进入其中"},
 "pitfalls": ["注意用词伦理：这些作者常处于弱势处境，避免猎奇化",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["outsider art", "henry darger"],
             "met": ["outsider art", "visionary art"], "commons": []},
 "see_also": ["art-brut", "naive-art", "outsider-art"],
},
# ---------------------------------------------------------------- 女性主义艺术
{
 "slug": "feminist-art", "name_zh": "女性主义艺术", "name_en": "Feminist Art",
 "period": "1960–今", "region": "全球", "tier": "B",
 "one_liner": "把「私人即政治」变成材料：身体、家务、工艺与被抹去的女性史。",
 "core": ["挑战艺术史中的男性标准与女性再现方式",
          "重新评估被贬低的「女性工艺」：刺绣、编织、瓷器",
          "身体作为材料与战场",
          "集体创作与意识觉醒小组"],
 "visual": {"色彩": "从粉色系到血肉色的政治化使用，或刻意使用工艺材料色",
            "光影": "常拒绝经典布光，或使用身体与镜面的反射",
            "笔触": "手工技法被重新启用：缝、绣、编、贴",
            "构图": "常打破经典裸体画的构图惯例，或直接引用再反转",
            "材质": "织物、刺绣、身体、录像、表演、瓷器",
            "情绪": "愤怒、机智、亲密、政治性的反抗"},
 "palette": [("#E85D75","政治粉"),("#8B1A3A","血肉红"),("#C9A8C0","藕荷"),
             ("#F2E0B8","织物米"),("#3A3A38","黑"),("#E8E4DA","画廊白")],
 "artists": [("朱迪·芝加哥","1939–"),("米里亚姆·夏皮罗","1923–2015"),
             ("芭芭拉·克鲁格","1945–"),("辛迪·舍曼","1954–"),
             ("路易丝·布尔乔亚","1911–2010"),("向京","1968–")],
 "prompt": {"style": "feminist art, personal is political, reclaimed craft technique, body as material, critique of art historical representation",
            "lighting": "often rejects classical lighting, uses mirrors, body reflection, video light",
            "color": "politicised pink or flesh tones, or reclaimed craft material colour",
            "composition": "disrupts the conventions of the classical nude, quotation and reversal",
            "medium": "textile, embroidery, body, video, performance, porcelain, collective work",
            "mood": "angry, witty, intimate, politically defiant",
            "camera": "eye-level, direct address to the viewer, 50mm"},
 "negative": "male gaze, passive objectification, classical nude convention, decorative passivity, neutral detachment",
 "video": {"motion": "身体的直接动作、手工劳作、集体行动",
           "camera": "直接对着镜头的凝视；手持参与感",
           "note": "关键在「直接面对观众」，不要被动的观赏视角"},
 "pitfalls": ["避免把女性主义简化为「画女人」——它是方法论与政治立场",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["feminist art"], "met": ["feminist art"], "commons": []},
 "see_also": ["conceptual-art", "postmodernism", "contemporary-art", "neo-dada"],
},
# ---------------------------------------------------------------- 街头艺术
{
 "slug": "street-art", "name_zh": "街头艺术", "name_en": "Street Art",
 "period": "1970–今", "region": "全球", "tier": "B",
 "one_liner": "把城市当画布：喷漆、模板、贴纸，和一场关于谁拥有公共空间的争论。",
 "core": ["非法或半合法地在公共空间创作",
          "喷漆、模板（stencil）、麦糊贴纸、体量雕塑",
          "与涂鸦（graffiti）同源但更图像化",
          "班克斯把它的反讽推向全球"],
 "visual": {"色彩": "高对比的喷漆色，常与墙面本身的脏旧形成反差",
            "光影": "城市光线：霓虹、路灯、日光下的墙体",
            "笔触": "喷漆的雾化边缘、模板的硬边、马克笔的粗线",
            "构图": "尺幅巨大、与建筑结构互动、常利用墙面缺陷",
            "材质": "喷漆、模板、贴纸、麦糊、瓷砖、混凝土墙",
            "情绪": "挑衅、幽默、政治、城市野生的生命力"},
 "palette": [("#C1272D","喷漆红"),("#111111","喷漆黑"),("#E8C020","喷漆黄"),
             ("#2B6BB8","喷漆蓝"),("#8A8A85","墙体灰"),("#F2EDE4","喷漆白")],
 "artists": [("班克斯","1974–"),("谢泼德·费尔雷","1970–"),
             ("布莱克·勒·拉特","1971–"),("让-米歇尔·巴斯奎特（涂鸦期）","1960–1988"),
             ("Os Gemeos","1974–")],
 "prompt": {"style": "street art, stencil and spray paint on urban wall, large scale mural, satirical political imagery, banksy and shepard fairey",
            "lighting": "city light, neon spill, raking daylight on textured wall",
            "color": "high contrast spray colour against dirty wall, red black yellow blue",
            "composition": "large scale interacting with architecture, exploiting wall defects",
            "medium": "spray paint, stencil, wheatpaste poster, tile, concrete wall",
            "mood": "provocative, humorous, political, feral urban energy",
            "camera": "eye-level from street, wide, slight low angle"},
 "negative": "gallery white cube, pristine surface, delicate detail, precious materials, polite restraint",
 "video": {"motion": "喷漆的过程、路人经过、墙面被发现",
           "camera": "timelapse 创作过程，或手持街头视角",
           "note": "街头艺术的语境是「墙与城市」——不要脱离环境"},
 "pitfalls": ["和涂鸦区分：街头艺术更图像化、更叙事；涂鸦更强调字体与签名",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["street art"], "met": ["street art"], "commons": []},
 "see_also": ["pop-art", "neo-pop", "contemporary-art", "dada"],
},
# ---------------------------------------------------------------- 超写实
{
 "slug": "hyper-realism", "name_zh": "超写实主义", "name_en": "Hyper-Realism",
 "period": "2000–今", "region": "全球", "tier": "B",
 "one_liner": "比照片更清楚：把皮肤毛孔、汗珠、瞳孔反光放大到令人不适。",
 "core": ["在照相写实基础上进一步加大尺幅与细节",
          "常画人体局部，尺度反差造成生理冲击",
          "强调触感与湿润感，而不是冷静的记录",
          "与照相写实的分界：更情绪化、更身体化"],
 "visual": {"色彩": "极其准确的肉色与湿润反光，冷暖过渡细腻",
            "光影": "复杂的多重光源，皮肤有真实的次表面散射",
            "笔触": "完全不可见，或极精细的笔触构建质感",
            "构图": "极端特写、巨大尺幅、裁切身体局部",
            "材质": "布面油画或丙烯、雕塑用硅胶与树脂",
            "情绪": "震撼、生理性的不适、对肉体存在的强烈意识"},
 "palette": [("#D9A898","皮肤暖"),("#C98B8B","血色"),("#8B9BA8","冷肤影"),
             ("#F2EDE4","高光白"),("#5A4A4A","深影"),("#A8B8C8","冷反光")],
 "artists": [("罗恩·穆克","1958–"),("帕特里夏·皮奇尼尼","1965–"),
             ("罗伯特·贝希特勒（相关）","1932–"),("冷军","1963–"),
             ("戈特弗里德·郝文","1948–")],
 "prompt": {"style": "hyper-realism, extreme close-up human detail, silicone and resin sculptural realism, pores sweat and capillary detail, ron mueck",
            "lighting": "complex multi-source, realistic subsurface scattering in skin, wet specular highlights",
            "color": "extremely accurate flesh tones, warm and cool transitions, wet reflections",
            "composition": "extreme close-up, enormous scale, cropped body fragment",
            "medium": "oil or acrylic on canvas, silicone and resin sculpture, hair and glass eyes",
            "mood": "shocking, physiologically uncomfortable, intense awareness of the body",
            "camera": "macro close-up, shallow depth of field, 100mm"},
 "negative": "stylisation, visible brushwork, abstraction, idealised beauty, cartoon, loose gesture",
 "video": {"motion": "极缓慢的呼吸级微动，皮肤与湿润表面的光变化",
           "camera": "极缓 push in 到皮肤细节",
           "note": "超写实的震撼来自尺度——镜头要贴得极近"},
 "pitfalls": ["和照相写实区分：超写实更情绪化、更身体化、尺幅更大",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["hyper-realism"], "met": ["hyperrealism"], "commons": []},
 "see_also": ["photorealism", "classical-realism", "biopunk"],
},
# ---------------------------------------------------------------- 动力艺术
{
 "slug": "kinetic-art", "name_zh": "动力艺术", "name_en": "Kinetic Art",
 "period": "1955–1975", "region": "欧洲 / 全球", "tier": "B",
 "one_liner": "作品真的在动：马达、气流、磁力让雕塑自己旋转起来。",
 "core": ["作品包含真实的物理运动（马达、风、观众触碰）",
          "光与运动结合，常产生视觉错觉",
          "与欧普艺术共享对视知觉的兴趣",
          "观众参与使作品每次呈现都不同"],
 "visual": {"色彩": "工业材料本色，或高纯度色彩用于强化运动的视觉",
            "光影": "运动产生闪烁与频闪，反光材料制造变化的光",
            "笔触": "不适用——金属、塑料、马达构成的机械结构",
            "构图": "悬挂或立式的机械结构，多单元重复",
            "材质": "铝、钢丝、马达、有机玻璃、镜面、霓虹",
            "情绪": "轻快、迷幻、技术乐观、永不停歇"},
 "palette": [("#C9CFD4","铝银"),("#29ABE2","电蓝"),("#F23D8E","荧光粉"),
             ("#111111","黑"),("#F2EDE4","白"),("#E8C020","警示黄")],
 "artists": [("考尔德","1898–1976"),("廷古利","1925–1991"),
             ("塔基斯","1925–2019"),("瓦萨雷里（相关）","1906–1997"),
             ("莉吉娅·克拉克","1920–1988")],
 "prompt": {"style": "kinetic art, motorised sculpture, actual physical movement, flashing reflections, tinguelly and takis, viewer activated",
            "lighting": "movement-generated flicker and strobe, reflective material shimmer",
            "color": "industrial material colour or high purity colour amplifying motion",
            "composition": "suspended or standing mechanical structure, repeated units",
            "medium": "aluminium, steel wire, motor, perspex, mirror, neon",
            "mood": "buoyant, hypnotic, techno-optimist, ceaseless",
            "camera": "circular dolly, long exposure light trails, static observing motion"},
 "negative": "static painting, still image, fixed composition, matte surface, quiet contemplation",
 "video": {"motion": "结构真实地旋转、部件往复、反光扫过",
           "camera": "环绕运镜配合作品自身的运动",
           "note": "动力艺术天生适合视频——运动就是作品本身"},
 "pitfalls": ["和欧普艺术区分：动力艺术是真实物理运动，欧普是视觉错觉",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["kinetic art", "calder"], "met": ["kinetic art", "calder"],
             "commons": ["Kinetic art sculpture"]},
 "see_also": ["op-art", "light-and-space", "bauhaus", "digital-art"],
},
# ---------------------------------------------------------------- 光与空间
{
 "slug": "light-and-space", "name_zh": "光与空间运动", "name_en": "Light and Space",
 "period": "1960–1975", "region": "美国加州", "tier": "B",
 "one_liner": "不是看作品，而是走进光里：树脂、雾气与感知本身成了材料。",
 "core": ["以感知经验而非物体为作品核心",
          "使用光、雾、树脂、镜面制造感官环境",
          "观众必须进入作品才能完成它",
          "与极简主义、加州光文化、冲浪美学相关"],
 "visual": {"色彩": "极淡或无色，依靠光本身的色温",
            "光影": "光是唯一材料：漫射、折射、渐隐",
            "笔触": "无；工业树脂与玻璃的光滑表面",
            "构图": "沉浸式空间、无边界、观众在内部",
            "材质": "玻璃纤维树脂、亚克力、荧光灯、雾、镜面",
            "情绪": "空灵、感官放大、近乎宗教的宁静"},
 "palette": [("#F2EDE4","雾白"),("#D9E8F0","冷光"),("#E8DCC8","暖光"),
             ("#A8C8D8","树脂蓝"),("#F2C9A8","树脂桃"),("#FFFFFF","纯白")],
 "artists": [("拉里·贝尔","1939–"),("詹姆斯·特瑞尔","1943–"),
             ("罗伯特·欧文","1928–"),("玛丽亚·诺德曼","1941–"),
             ("德万","1931–")],
 "prompt": {"style": "light and space movement, perceptual environment, resin cube and fog installation, james turrell skyspace, viewer immersed in light",
            "lighting": "light itself is the only material, diffused refraction, gradual fade, no visible source",
            "color": "near-colourless, dependent on the colour temperature of the light",
            "composition": "immersive space, no boundary, viewer inside the work",
            "medium": "fiberglass resin, acrylic, fluorescent tube, fog, mirror",
            "mood": "ethereal, heightened sensation, near-religious calm",
            "camera": "wide inside the space, slow rotation, no depth of field"},
 "negative": "object on a plinth, sharp focus, busy detail, saturated colour, narrative content",
 "video": {"motion": "光缓慢变化、雾流动、颜色渐变",
           "camera": "极缓 360 度旋转或缓慢在空间中移动",
           "note": "光与空间的作品只能用「身处其中」的方式拍"},
 "pitfalls": ["和极简主义区分：光与空间的核心是感知体验，不是物体",
              "版权：多数作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["light and space"], "met": ["light and space movement"], "commons": []},
 "see_also": ["minimalism-art", "kinetic-art", "zen-art", "digital-art"],
},
# ---------------------------------------------------------------- 数字艺术
{
 "slug": "digital-art", "name_zh": "数字艺术", "name_en": "Digital Art",
 "period": "1970–今", "region": "全球", "tier": "B",
 "one_liner": "用代码、像素和算法作画：从分形到生成对抗网络。",
 "core": ["以数字技术为创作媒介或主题",
          "包含算法艺术、分形、生成艺术、NFT、AI 生成",
          "可复制性与版本性挑战了原作概念",
          "近年与 AI 生成深度绑定"],
 "visual": {"色彩": "显示器色域内的饱和色，或算法生成的渐变",
            "光影": "发光体自明，BLOOM 与辉光是常见语汇",
            "笔触": "像素、矢量、噪点、分形结构",
            "构图": "算法生成的对称或有机结构，无限可缩放",
            "材质": "屏幕、投影、代码、数据集、区块链",
            "情绪": "技术乐观或技术焦虑，取决于作品立场"},
 "palette": [("#29D6E8","电子青"),("#F23D8E","霓虹粉"),("#7B3FA0","深紫"),
             ("#0A0E14","屏幕黑"),("#A8F23D","荧光绿"),("#FFFFFF","辉光白")],
 "artists": [("弗里德·纳克","1938–"),("曼弗雷德·莫尔","1938–"),
             ("哈罗德·科恩","1928–2016"),("雷菲克·阿纳多尔","1985–"),
             ("马里奥·克林格曼","1970–")],
 "prompt": {"style": "digital art, algorithmic and generative composition, fractal structure, screen-native imagery, glitch and data aesthetics",
            "lighting": "self-luminous screen, bloom and glow, additive light mixing",
            "color": "saturated display gamut, neon cyan magenta, screen black, luminous white",
            "composition": "algorithmic symmetry or organic growth, infinitely scalable structure",
            "medium": "screen, projection, code, dataset, blockchain token",
            "mood": "technologically optimistic or anxious depending on stance",
            "camera": "flat screen capture, or installation view"},
 "negative": "traditional canvas texture, handcrafted imperfection, analogue grain, oil paint",
 "video": {"motion": "算法参数持续演化、分形无限缩放、故障闪烁",
           "camera": "无限的 zoom in/out，或静态录屏",
           "note": "数字艺术的动可以是「参数的演化」而非物理运动"},
 "pitfalls": ["和 AI 生成的关系要说清：AI 是这一门类的最新工具，不是全部",
              "版权：作品与生成物版权状态复杂，只存提示词"],
 "sources": {"cleveland": ["digital art"], "met": ["digital art"], "commons": []},
 "see_also": ["kinetic-art", "op-art", "contemporary-art", "pixel-art"],
},
# ---------------------------------------------------------------- 禅艺术
{
 "slug": "zen-art", "name_zh": "禅艺术", "name_en": "Zen Art",
 "period": "1200–今", "region": "日本 / 东亚", "tier": "B",
 "one_liner": "圆相、枯山水、墨迹：用最少的动作表达最完整的当下。",
 "core": ["圆相（ensō）：一笔画成的圆，不完美即完整",
          "枯山水：用砂石代替水，极简到只剩关系",
          "墨迹与即兴书写，笔迹即心迹",
          "拒绝修饰与完成感"],
 "visual": {"色彩": "几乎无色：墨黑、砂白、石灰、苔绿",
            "光影": "极柔和或完全平面；枯山水靠砂纹的明暗",
            "笔触": "一笔连续；飞白、枯笔、速度可见",
            "构图": "大面积极简、不对称、留白占主导",
            "材质": "宣纸、墨、砂石、苔、原木、竹",
            "情绪": "静、空、不完美、当下的专注"},
 "palette": [("#1A1A1A","墨"),("#8A8A85","石灰"),("#E8E4DA","砂白"),
             ("#5A7A5A","苔绿"),("#A89878","原木"),("#D9D5CC","枯笔灰")],
 "artists": [("白隐慧鹤","1685–1768"),("仙厓义梵","1750–1837"),
             ("雪舟（相关）","1420–1506"),("枡野俊明（庭园）","1953–")],
 "prompt": {"style": "zen art, ensō circle drawn in one breath, dry landscape garden, sumi ink immediacy, radical minimalism and imperfection",
            "lighting": "extremely soft or entirely flat, sand ripple relief catching low raking light",
            "color": "almost no colour, ink black, sand white, stone grey, moss green",
            "composition": "vast emptiness, asymmetry, negative space dominant",
            "medium": "ink on paper, raked sand and stone, moss, raw wood, bamboo",
            "mood": "still, empty, imperfect, present-moment attention",
            "camera": "flat frontal or wide garden view, 50mm"},
 "negative": "ornament, symmetry, saturated colour, filled composition, detail density, decoration",
 "video": {"motion": "一笔缓慢画成；砂纹被耙出；苔藓上光影移动",
           "camera": "static 长镜头；让动作一次性完成不剪辑",
           "note": "禅艺术的动必须「一次完成」——剪辑会破坏它"},
 "pitfalls": ["和日本水墨画区分：禅艺术更强调修行行为与极简，水墨画是更大的绘画传统",
              "AI 会加装饰 → negative 写 ornament, decoration, filled composition"],
 "sources": {"cleveland": ["zen painting", "hakuin", "enso"],
             "met": ["zen painting", "japanese zen calligraphy"],
             "commons": ["Zen ensō circle painting"]},
 "see_also": ["suiboku-ga", "wabi-sabi", "ink-wash-xieyi", "light-and-space"],
},
]

ARTIST_KEYS = {
 "avant-garde": ["avant-garde", "manifesto", "situationis", "debord", "dada", "constructivis"],
 "contemporary-art": ["contemporary art", "installation", "biennale", "beuys", "sherman", "koons"],
 "postmodernism": ["postmodern", "rauschenberg", "kruger", "sherman", "levine", "venturi"],
 "abstract-art": ["abstract", "kandinsky", "mondrian", "malevich", "de kooning", "rothko"],
 "art-informel": ["informel", "fautrier", "tapies", "tàpies", "burri", "wols", "matter painting"],
 "tachisme": ["tachis", "hartung", "mathieu", "soulages", "bryen", "degoix"],
 "lyrical-abstraction": ["frankenthaler", "olitski", "louis", "jenkins", "natkin", "lyrical"],
 "hard-edge": ["hard-edge", "hard edge", "kelly", "stella", "noland", "liberman", "holds"],
 "post-painterly-abstraction": ["post-painterly", "post painterly", "olitski", "noland",
                                 "frankenthaler", "stella"],
 "neo-dada": ["neo-dada", "neodada", "rauschenberg", "jasper johns", "manzoni", "paik"],
 "neo-pop": ["neo-pop", "neopop", "murakami", "koons", "kaws", "brito"],
 "transavantgarde": ["transavanguardia", "transavantgarde", "chia", "cucchi", "clemente",
                      "paladino"],
 "art-brut": ["art brut", "wolfli", "wölfli", "corbeaux", "gilli", "darger", "dubuffet"],
 "outsider-art": ["outsider", "darger", "finster", "pirosmani", "seku", "visionary"],
 "feminist-art": ["feminist", "chicago", "schapiro", "kruger", "bourgeois", "sherman"],
 "street-art": ["street art", "banksy", "fairey", "blek le rat", "os gemeos", "stencil"],
 "hyper-realism": ["hyper-realis", "hyperrealis", "ron mueck", "piccinini", "leng jun",
                    "hao wei", "gottfried helnwein"],
 "kinetic-art": ["kinetic", "calder", "tinguelly", "takis", "clark", "mobile sculpture"],
 "light-and-space": ["light and space", "turrell", "irwin", "larry bell", "nordman", "dewan"],
 "digital-art": ["digital art", "generative", "algorithmic", "nake", "mohr", "cohen",
                  "anadol", "klingemann"],
 "zen-art": ["zen", "enso", "ensō", "hakuin", "sengai", "dry landscape", "karesansui"],
}
