# -*- coding: utf-8 -*-
"""流派定义 —— 对照 WikiArt 218 个风格补齐的西方/古典缺口（20 个）。

这批是跟 WikiArt 分类体系做差异比对后挑出来的：作品数多、视觉语言独立、
且对 AI 生成有实际参考价值的概念。像「Synthetic Cubism」这种已经包含在
立体主义里的子概念不重复建卡，只放进关键词图谱做映射。
"""

CATEGORY = "西方古典与近代"

MOVEMENTS = [
# ---------------------------------------------------------------- 早期文艺复兴
{
 "slug": "early-renaissance", "name_zh": "早期文艺复兴", "name_en": "Early Renaissance",
 "period": "1400–1490", "region": "意大利", "tier": "A",
 "one_liner": "透视法刚被发明出来：画面第一次有了可以走进去的空间。",
 "core": ["线性透视作为新工具，建筑与地面线严格汇聚",
          "人体解剖开始被真实研究，但仍带理想化",
          "宗教题材里出现当代人物肖像",
          "蛋彩仍是主流，油画刚传入"],
 "visual": {"色彩": "清亮的蛋彩：粉红、天蓝、草绿、金；比盛期文艺复兴更明亮",
            "光影": "均匀柔和，形体靠线条与淡淡的明暗塑造",
            "笔触": "细腻平涂，边缘清晰；可见蛋彩的粉质",
            "构图": "严格的单点透视，建筑框住画面，人物成排",
            "材质": "木板蛋彩、金箔、湿壁画",
            "情绪": "明朗、秩序感、虔敬中带着人间的亲切"},
 "palette": [("#E8A0A8","粉红"),("#7FA8D8","天蓝"),("#7FA86B","草绿"),
             ("#C9A227","金"),("#A8432A","砖红"),("#E8DCC8","蛋彩白")],
 "artists": [("马萨乔","1401–1428"),("弗拉·安吉利科","1395–1455"),
             ("波提切利","1445–1510"),("皮耶罗·德拉·弗朗切斯卡","1415–1492"),
             ("乌切洛","1397–1475")],
 "prompt": {"style": "early renaissance painting, quattrocento, linear perspective, tempera on panel, clear contours, classical architecture framing",
            "lighting": "even soft illumination, gentle modelling, clear but not dramatic shadows",
            "color": "bright egg tempera palette, rose pink, sky blue, grass green, gold, brick red",
            "composition": "strict single point perspective, architectural framing, figures arranged in ordered rows",
            "medium": "egg tempera on wood panel, gold leaf, fresco, powdery matte surface",
            "mood": "luminous, ordered, devout with human warmth",
            "camera": "eye-level, symmetrical, deep perspective, 50mm"},
 "negative": "baroque drama, tenebrism, impasto, impressionist brushwork, modern clothing, anachronism",
 "video": {"motion": "人物缓慢行走于透视空间中，衣袍轻摆",
           "camera": "沿透视线缓慢向前推进（这是早期文艺复兴独有的镜头语言）",
           "note": "透视法是这一派的核心发明——用镜头沿灭点推进最能体现它"},
 "pitfalls": ["AI 会做成盛期文艺复兴的厚重感 → 强调 tempera, bright, clear contours",
              "透视容易不对 → 加 linear perspective, single vanishing point"],
 "sources": {"cleveland": ["botticelli", "fra angelico", "piero della francesca"],
             "met": ["botticelli", "fra angelico", "early renaissance"],
             "commons": ["Sandro Botticelli painting", "Fra Angelico fresco"]},
 "see_also": ["renaissance", "international-gothic", "gothic"],
},
# ---------------------------------------------------------------- 国际哥特式
{
 "slug": "international-gothic", "name_zh": "国际哥特式", "name_en": "International Gothic",
 "period": "1375–1450", "region": "欧洲宫廷", "tier": "A",
 "one_liner": "宫廷的最后一首华丽长诗：飘动的衣褶、金箔、细密到奢侈的装饰。",
 "core": ["跨国的宫廷风格，从巴黎到布拉格到米兰共享同一套优雅语言",
          "极度精致的细密画与挂毯式构图",
          "优雅拉长的人物与流动的 S 形衣褶",
          "金箔与宝石色，装饰性压倒写实"],
 "visual": {"色彩": "宝石般的金、深蓝、朱红、翠绿，配大面积金箔",
            "光影": "柔和均匀，无强光源；人物像发光体",
            "笔触": "细密精致，几乎不见笔触；细节密度极高",
            "构图": "挂毯式平面构图、装饰性边框、人物沿弧线排列",
            "材质": "羊皮纸细密画、木板蛋彩、金箔、挂毯",
            "情绪": "优雅、梦幻、宫廷式的精致与轻微的忧郁"},
 "palette": [("#C9A227","金箔"),("#1B3A6B","深蓝"),("#8E1B1B","朱红"),
             ("#1E6B4F","翠绿"),("#7A1F3A","深紫红"),("#E8DCC8","羊皮纸白")],
 "artists": [("林堡兄弟","1400–1416"),("西莫内·马蒂尼","1284–1344"),
             ("真蒂莱·达·法布里亚诺","1370–1427"),("波西米亚画师","1400s"),
             ("斯特凡·洛赫纳","1410–1451")],
 "prompt": {"style": "international gothic, courtly international style, luminous gold leaf, flowing s-curve drapery, tapestry-like composition, illuminated manuscript detail",
            "lighting": "soft even glow, no strong source, figures appear self-luminous",
            "color": "jewel-like gold, deep blue, vermilion, emerald, generous gold leaf",
            "composition": "tapestry flat composition, ornamental border, figures along an arc",
            "medium": "illuminated parchment, egg tempera on panel, gold leaf, tapestry weave",
            "mood": "elegant, dreamlike, courtly refinement with faint melancholy",
            "camera": "flat frontal, decorative framing, no deep perspective"},
 "negative": "harsh lighting, heavy chiaroscuro, loose brushwork, modern subject, minimalism, photographic",
 "video": {"motion": "衣褶与织物缓慢流动，金箔随光闪烁",
           "camera": "static 或横向 pan 如展开挂毯",
           "note": "这一派的动感全部在衣褶里"},
 "pitfalls": ["和哥特式混淆 → 国际哥特式更华丽、更宫廷、金箔更多",
              "AI 会降低细节密度 → 加 tapestry-like, illuminated detail, gold leaf"],
 "sources": {"cleveland": ["international gothic", "gentile da fabriano"],
             "met": ["international gothic", "limbourg"], "commons": ["International Gothic painting gold"]},
 "see_also": ["gothic", "early-renaissance", "byzantine"],
},
# ---------------------------------------------------------------- 自然主义
{
 "slug": "naturalism", "name_zh": "自然主义", "name_en": "Naturalism",
 "period": "1870–1900", "region": "法国 / 欧洲", "tier": "A",
 "one_liner": "比现实主义更冷：把人物当成生物来观察，环境决定命运。",
 "core": ["受实证科学影响，用观察与记录的态度作画",
          "强调环境、遗传、阶级对人的塑造",
          "题材偏向底层与边缘，但不作道德评判",
          "色彩比现实主义更明亮，接近外光写生"],
 "visual": {"色彩": "明亮的自然色，户外光下的真实色调；比现实主义更亮",
            "光影": "真实的日光，包括刺眼的直射光，不美化",
            "笔触": "写实但不炫技，有时带印象派的松弛",
            "构图": "平视、无戏剧性，像社会调查的现场记录",
            "材质": "布面油画、写实厚涂、外光写生",
            "情绪": "冷静、客观、带有生理学式的直视"},
 "palette": [("#8B6B4A","土褐"),("#A8B86B","草黄"),("#6B8B9E","天蓝"),
             ("#A8432A","砖红"),("#5A6B4A","橄榄"),("#E8DCC8","日光白")],
 "artists": [("左拉（理论）","1840–1902"),("巴斯蒂安-勒帕热","1848–1884"),
             ("莱尔米特","1844–1925"),("佐恩","1860–1920"),("索罗拉","1863–1923")],
 "prompt": {"style": "naturalism painting, scientific observation, environmental determinism, unidealised rural labour, plein air realism",
            "lighting": "real daylight including harsh direct sun, no beautification, honest exposure",
            "color": "bright naturalistic palette, earth brown, grass yellow, open sky blue, brick red",
            "composition": "eye-level, undramatic, documentary framing of a scene",
            "medium": "oil on canvas, realistic handling, occasional loose plein air strokes",
            "mood": "cool, objective, physiological directness",
            "camera": "eye-level, medium wide, 35mm, documentary"},
 "negative": "idealised beauty, dramatic lighting, golden hour romance, pastel, fantasy, glamour",
 "video": {"motion": "劳作的重复动作、牲畜移动、麦浪摇动",
           "camera": "static 长镜头或极缓 pan；像观察记录",
           "note": "自然主义不加滤镜——保持日光的诚实"},
 "pitfalls": ["和现实主义混淆 → 自然主义更亮、更冷、更强调环境决定论",
              "AI 会加金色时光 → negative 写 golden hour romance, idealised beauty"],
 "sources": {"cleveland": ["naturalism", "anders zorn", "sorolla"],
             "met": ["anders zorn", "jules bastien-lepage"], "commons": ["Anders Zorn painting"]},
 "see_also": ["realism", "impressionism", "social-realism"],
},
# ---------------------------------------------------------------- 东方主义
{
 "slug": "orientalism", "name_zh": "东方主义", "name_en": "Orientalism",
 "period": "1800–1900", "region": "法国 / 英国", "tier": "A",
 "one_liner": "欧洲人想象中的东方：瓷砖、香料、后宫与刺眼的北非阳光。",
 "core": ["欧洲画家对北非、中东、奥斯曼的想象与记录",
          "高度装饰性的室内：瓷砖、地毯、镂空窗格",
          "强烈的沙漠阳光与深浓阴影",
          "常带殖民视角的异域凝视（今天的批评重点）"],
 "visual": {"色彩": "饱和的暖色：赭黄、钴蓝瓷砖、朱红地毯、白色长袍",
            "光影": "刺眼的直射阳光穿过镂空窗格，投下几何光斑",
            "笔触": "精细写实，织物与瓷砖的质感被极度珍视",
            "构图": "室内景深、拱廊与窗格框景、人物在装饰空间中",
            "材质": "油画、瓷砖、地毯、丝绸、镂空木格（mashrabiya）",
            "情绪": "异域、感官、慵懒、被阳光晒晕的迷醉"},
 "palette": [("#C9A227","赭黄"),("#1F5FA8","钴蓝砖"),("#A8432A","朱红毯"),
             ("#E8DCC8","长袍白"),("#8B6B4A","木褐"),("#2B3A4A","深影蓝")],
 "artists": [("热罗姆","1824–1904"),("德拉克罗瓦（摩洛哥）","1798–1863"),
             ("刘易斯","1804–1876"),("阿尔玛-塔德玛","1836–1912")],
 "prompt": {"style": "orientalist painting, 19th century exotic genre scene, ornate islamic interior, mashrabiya lattice, richly detailed textile and tile",
            "lighting": "harsh direct sunlight through latticed windows, geometric light patches, deep saturated shadows",
            "color": "saturated warm palette, ochre, cobalt tile blue, vermilion carpet red, robe white",
            "composition": "interior depth, arcade and lattice framing, figure within decorative space",
            "medium": "oil on canvas, meticulous rendering of tile, carpet, silk, carved wood",
            "mood": "exotic, sensuous, languid, sun-dazzled",
            "camera": "eye-level, medium shot, 50mm, deep focus"},
 "negative": "northern grey light, minimalism, modern clothing, cold palette, plain interior, documentary neutrality",
 "video": {"motion": "光斑缓慢移动、织物轻摆、香烟升起",
           "camera": "缓慢 pan 穿过装饰性室内空间",
           "note": "镂空窗格投下的几何光斑是这一派最强的视觉签名"},
 "pitfalls": ["AI 会做成奇幻中东 → 加 19th century orientalist, mashrabiya, meticulous textile",
              "提醒：这是欧洲视角的建构，写提示词时明确它是 historical painting style"],
 "sources": {"cleveland": ["orientalism", "jean-leon gerome", "john frederick lewis"],
             "met": ["orientalism", "jean-leon gerome"], "commons": ["Jean-Léon Gérôme painting"]},
 "see_also": ["academic-art", "romanticism", "japonism"],
},
# ---------------------------------------------------------------- 发光主义
{
 "slug": "luminism", "name_zh": "发光主义", "name_en": "Luminism",
 "period": "1850–1875", "region": "美国", "tier": "A",
 "one_liner": "把光本身画成主角：画面安静到能听见空气，光线几乎有实体。",
 "core": ["光线成为唯一主题，形体让位于光的氛围",
          "笔触被刻意隐藏，表面极其光滑",
          "水平构图、平静水面、极致的静谧",
          "与哈德逊河派同源但更内向、更形而上"],
 "visual": {"色彩": "清冷的蓝、银灰、淡金；明度高、对比低",
            "光影": "弥漫的晨雾光、水平的光带、水面反射，几乎没有阴影",
            "笔触": "完全隐藏，抛光般平滑；这是它与印象派最大的区别",
            "构图": "极宽的水平构图、低地平线、大面积天空与水面",
            "材质": "细纹布面油画、多层透明罩染、光滑表面",
            "情绪": "宁静、空灵、近乎宗教的冥想感"},
 "palette": [("#A8C8D8","晨雾蓝"),("#D9CFC0","银灰"),("#E8D5A8","淡金"),
             ("#7FA8B8","水色"),("#4A6B7A","远山蓝"),("#F2EDE4","光白")],
 "artists": [("肯塞特","1816–1872"),("莱恩","1804–1865"),
             ("希尔德","1836–1908"),("比尔施塔特（部分）","1830–1902"),
             ("丘奇（部分）","1826–1900")],
 "prompt": {"style": "american luminism, serene coastal or lake scene, invisible brushwork, polished surface, light as the true subject, transcendental stillness",
            "lighting": "diffused dawn haze, horizontal bands of light, mirror water reflection, almost no cast shadow",
            "color": "cool pale palette, misty blue, silver grey, pale gold, high key low contrast",
            "composition": "extremely wide horizontal format, low horizon, vast sky and water",
            "medium": "oil on fine canvas, many transparent glazes, glass-smooth finish",
            "mood": "serene, ethereal, near-religious contemplation",
            "camera": "extreme wide panoramic, eye-level, soft focus distance"},
 "negative": "visible brushwork, impasto, dramatic clouds, high contrast, busy detail, people, urban scene",
 "video": {"motion": "水面极缓的涟漪、雾气缓慢流动，其余静止",
           "camera": "static 长镜头；任何快速运动都会破坏它",
           "note": "发光主义的力量来自「几乎不动」"},
 "pitfalls": ["和哈德逊河派混淆 → 发光主义更平、更静、笔触完全隐藏",
              "AI 会加戏剧性云朵 → 加 calm, horizontal, low contrast, no drama"],
 "sources": {"cleveland": ["luminism", "john frederick kensett"],
             "met": ["fitz henry lane", "john frederick kensett", "luminism"],
             "commons": ["John Frederick Kensett painting"]},
 "see_also": ["hudson-river-school", "tonalism", "romanticism"],
},
# ---------------------------------------------------------------- 日本主义
{
 "slug": "japonism", "name_zh": "日本主义", "name_en": "Japonism",
 "period": "1860–1900", "region": "法国 / 欧洲", "tier": "A",
 "one_liner": "浮世绘登陆巴黎：欧洲画家第一次学会用平面、留白和裁切来看世界。",
 "core": ["欧洲艺术家对日本美术的接受与再创造",
          "非对称构图、大胆裁切、大面积留白",
          "平面色块与装饰性轮廓线",
          "扇面、屏风、浮世绘版画的格式被直接挪用"],
 "visual": {"色彩": "平涂的鲜明色块，靛蓝、朱红、草绿，不追求明暗过渡",
            "光影": "平面化，无立体塑造；靠色块与轮廓区分",
            "笔触": "平涂 + 装饰性线条，或模仿版画的均匀色面",
            "构图": "斜向裁切、主体偏置、前景遮挡、留白当空气",
            "材质": "油画、版画、装饰屏风、陶瓷",
            "情绪": "清新、装饰性、带着异国情调的现代感"},
 "palette": [("#1F3A6E","靛蓝"),("#B03A2E","朱红"),("#5A8A5A","草绿"),
             ("#C9A227","土黄"),("#E8DCC0","纸白"),("#2B2B2B","墨线")],
 "artists": [("梵高（临摹浮世绘）","1853–1890"),("惠斯勒","1834–1903"),
             ("马奈","1832–1883"),("德加","1834–1917"),("博纳尔","1867–1947")],
 "prompt": {"style": "japonism, european painting influenced by ukiyo-e, flat colour areas, bold asymmetric cropping, decorative outline, negative space",
            "lighting": "flattened, no volumetric modelling, form defined by colour and contour",
            "color": "flat vivid colour blocks, indigo, vermilion, grass green, ochre, paper white",
            "composition": "diagonal cropping, off-centre subject, foreground occlusion, empty space as air",
            "medium": "oil on canvas or woodblock print, flat even colour planes",
            "mood": "fresh, decorative, exotic modernism",
            "camera": "elevated or flattened viewpoint, asymmetric framing"},
 "negative": "academic chiaroscuro, deep perspective, heavy modelling, symmetrical composition, muted brown palette",
 "video": {"motion": "平面化的运动：雨丝斜落、帘幕平移、人物横向穿过",
           "camera": "横向 pan，模仿绘卷展开；避免纵深运动",
           "note": "日本主义的核心是「平面与裁切」，镜头不要给立体感"},
 "pitfalls": ["和浮世绘混淆 → 日本主义是欧洲画家的再创造，媒介仍是油画",
              "AI 会加透视 → negative 写 deep perspective, heavy modelling"],
 "sources": {"cleveland": ["japonism", "japanese influence"],
             "met": ["japonism", "japonisme"], "commons": ["Van Gogh Japanese print copy", "Utagawa Hiroshige print", "Japonisme painting"]},
 "see_also": ["ukiyo-e", "impressionism", "art-nouveau"],
},
# ---------------------------------------------------------------- 古典主义
{
 "slug": "classicism", "name_zh": "古典主义", "name_en": "Classicism",
 "period": "持续（17–19世纪为高峰）", "region": "欧洲", "tier": "A",
 "one_liner": "以古希腊罗马为永恒标准：比例、克制、清晰、理性。",
 "core": ["以古代为规范，追求普遍性与永恒性",
          "构图清晰、轮廓明确、色彩克制",
          "题材以神话、历史、寓意为主",
          "与浪漫主义构成西方艺术史的长期对立面"],
 "visual": {"色彩": "克制的暖褐与灰蓝，肉色与织物色精致但不高调",
            "光影": "清晰均匀的布光，形体塑造明确但不戏剧化",
            "笔触": "平滑、严谨，笔触服从形体",
            "构图": "金字塔或水平带式，人物姿态取自古代雕塑",
            "材质": "布面油画、抛光表面、大理石雕塑",
            "情绪": "庄重、均衡、理性的高贵"},
 "palette": [("#8B6B4A","暖褐"),("#A8B0B8","灰蓝"),("#D9B29A","肉色"),
             ("#7A1F2B","深红"),("#C9A227","金"),("#E8DCC8","象牙")],
 "artists": [("普桑","1594–1665"),("克劳德·洛兰","1600–1682"),
             ("大卫","1748–1825"),("安格尔","1780–1867"),("雷诺兹","1723–1792")],
 "prompt": {"style": "classicism, greco-roman ideal, clarity and restraint, balanced composition, sculptural figures, poussin and ingres",
            "lighting": "clear even illumination, defined but undramatic modelling",
            "color": "restrained warm brown and grey blue, refined flesh tones, deep red accent, gold",
            "composition": "pyramidal or horizontal frieze, poses drawn from antique sculpture, balanced",
            "medium": "oil on canvas, smooth polished handling, marble sculpture",
            "mood": "dignified, balanced, rational nobility",
            "camera": "eye-level, balanced symmetrical framing, 50mm"},
 "negative": "dramatic chiaroscuro, loose expressionist brushwork, asymmetry, modern subject, neon, chaos",
 "video": {"motion": "克制优雅的动作，衣袍有控制的飘动",
           "camera": "static 或极缓 crane；对称构图",
           "note": "古典主义的运镜要「正确」，不要炫技"},
 "pitfalls": ["和新古典主义区分：新古典主义是一个历史时期（1760–1830），古典主义是贯穿性的态度",
              "AI 会加戏剧光 → negative 写 dramatic chiaroscuro"],
 "sources": {"cleveland": ["poussin", "claude lorrain", "classicism"],
             "met": ["poussin", "claude lorrain"], "commons": ["Nicolas Poussin painting"]},
 "see_also": ["neoclassicism", "renaissance", "academic-art"],
},
# ---------------------------------------------------------------- 稚拙艺术
{
 "slug": "naive-art", "name_zh": "稚拙艺术（原始主义）", "name_en": "Naïve Art (Primitivism)",
 "period": "1880–今", "region": "全球", "tier": "A",
 "one_liner": "没受过训练反而自由：透视是错的、比例是怪的，但画面异常有生命力。",
 "core": ["未经学院训练的自学画家，或刻意模仿这种视角",
          "透视、比例、解剖被有意无意地「弄错」",
          "细节极其丰富且平均分配，不分主次",
          "色彩鲜艳、轮廓清晰、充满叙事欲望"],
 "visual": {"色彩": "鲜明饱和的平涂色，常不协调但生机勃勃",
            "光影": "几乎没有光影，物体是平面的",
            "笔触": "细致、均匀、有耐心的描绘；笔触不表现情绪",
            "构图": "俯视或平铺、细节铺满、多视点混杂",
            "材质": "布面油画、平涂、清晰轮廓线",
            "情绪": "天真、好奇、充满细节的喜悦、偶尔不安"},
 "palette": [("#3E8A5A","草绿"),("#E8C020","亮黄"),("#2B6BB8","亮蓝"),
             ("#C1272D","正红"),("#8B5E2A","土褐"),("#F2EDE4","亮白")],
 "artists": [("亨利·卢梭","1844–1910"),("塞拉菲娜","1864–1942"),
             ("格兰马·摩西","1860–1961"),("阿尔弗雷德·沃利斯","1855–1942")],
 "prompt": {"style": "naive art, self-taught painter, deliberately wrong perspective, flat vivid colour, obsessive even detail, henri rousseau",
            "lighting": "almost no shading, flat objects, even illumination",
            "color": "bold saturated flat colour, vivid green, bright yellow, bright blue, red, uncoordinated but alive",
            "composition": "high viewpoint or all-over, detail spread evenly with no hierarchy, multiple viewpoints",
            "medium": "oil on canvas, careful even painting, clear outlines",
            "mood": "innocent, curious, delight in detail, occasionally uncanny",
            "camera": "flat frontal or high angle, no perspective correction"},
 "negative": "correct anatomy, accurate perspective, academic finish, subtle gradation, muted palette, sophisticated shading",
 "video": {"motion": "平缓而均匀的运动：树叶齐摇、动物走动、云朵平移",
           "camera": "static 全景，或极缓横向 pan 展示细节",
           "note": "稚拙艺术的动要「笨拙而均匀」，不要有机的流畅"},
 "pitfalls": ["AI 会「修正」错误 → 必须写 deliberately wrong perspective, self-taught, flat",
              "细节容易不够密 → 加 obsessive even detail, all-over"],
 "sources": {"cleveland": ["henri rousseau", "naive art"],
             "met": ["henri rousseau", "naive painting"], "commons": ["Henri Rousseau painting"]},
 "see_also": ["post-impressionism", "art-brut", "outsider-art", "magic-realism"],
},
# ---------------------------------------------------------------- 社会现实主义
{
 "slug": "social-realism", "name_zh": "社会现实主义", "name_en": "Social Realism",
 "period": "1920–1950", "region": "美国 / 欧洲", "tier": "A",
 "one_liner": "大萧条的眼睛：罢工、排队领面包、空荡的厂房与疲惫的脸。",
 "core": ["以社会批判为目的的写实绘画",
          "聚焦工人、失业者、贫民窟与阶级冲突",
          "与宣传性的社会主义现实主义不同，它批判本国",
          "受摄影与新闻纪实影响，构图直接有力"],
 "visual": {"色彩": "灰褐、土黄、暗蓝，低饱和但结实有力",
            "光影": "硬朗的侧光或阴天散射，突出面部与手",
            "笔触": "明确的写实笔触，有时偏干、偏硬",
            "构图": "纪念碑式的人物特写、街景、工业场景",
            "材质": "布面油画、壁画、版画、素描",
            "情绪": "沉重、愤怒、同情、有尊严的抗争"},
 "palette": [("#6B5A4A","灰褐"),("#A89060","土黄"),("#4A5A6B","暗蓝"),
             ("#A8432A","锈红"),("#3A3A38","铁灰"),("#D9CFC0","灰白")],
 "artists": [("本·沙恩","1898–1969"),("迭戈·里维拉","1886–1957"),
             ("乔治·贝洛斯","1882–1925"),("奥罗斯科","1883–1949"),
             ("多萝西娅·兰格（摄影）","1895–1965")],
 "prompt": {"style": "social realism, 1930s depression era, monumental working class figures, documentary directness, ben shahn and diego rivera",
            "lighting": "harsh raking light or overcast grey, emphasising faces and hands, unglamorous",
            "color": "muted but sturdy, grey brown, ochre, dark blue, rust red",
            "composition": "monumental close figure, street or industrial scene, direct frontal confrontation",
            "medium": "oil on canvas, mural, lithograph, charcoal drawing",
            "mood": "heavy, angry, sympathetic, dignified protest",
            "camera": "eye-level, medium close, 35mm, documentary"},
 "negative": "glamour, idealised heroism, bright cheerful, pastel, abstraction, decorative, luxury",
 "video": {"motion": "人群行进、机器运转、沉默的静止面孔",
           "camera": "handheld 或 static，克制的纪录片式",
           "note": "不要美化——社会现实主义的力量来自不回避"},
 "pitfalls": ["和社会主义现实主义混淆 → 社会现实主义批判本国，社会主义现实主义歌颂体制",
              "AI 会加美颜 → negative 写 glamour, idealised heroism"],
 "sources": {"cleveland": ["social realism", "ben shahn", "diego rivera"],
             "met": ["social realism", "ben shahn"], "commons": ["Diego Rivera mural"]},
 "see_also": ["realism", "ashcan-school", "socialist-realism", "muralism"],
},
# ---------------------------------------------------------------- 社会主义现实主义
{
 "slug": "socialist-realism", "name_zh": "社会主义现实主义", "name_en": "Socialist Realism",
 "period": "1932–1980", "region": "苏联 / 中国 / 东欧", "tier": "A",
 "one_liner": "宣传画的美学：劳动者昂首向前，阳光永远从未来照过来。",
 "core": ["国家规定的创作方法：歌颂革命与劳动",
          "英雄化、理想化的工人农民形象",
          "乐观、明亮、向上，永远指向光明的未来",
          "中国版本融合年画的鲜艳与油画的写实"],
 "visual": {"色彩": "明快饱和：鲜红、金黄、天蓝、白；对比强烈且干净",
            "光影": "低角度阳光、逆光轮廓、英雄式打光",
            "笔触": "光滑写实，去掉个人手迹",
            "构图": "仰视、金字塔式、人物指向前方或上方",
            "材质": "布面油画、宣传海报、石版画",
            "情绪": "昂扬、集体主义、必胜的信念感（形式上极其有效）"},
 "palette": [("#C1272D","革命红"),("#E8C020","金黄"),("#2B6BB8","天蓝"),
             ("#F2EDE4","白"),("#4A7A3A","麦绿"),("#8B5E2A","土地褐")],
 "artists": [("格拉西莫夫","1881–1963"),("约甘松","1893–1965"),
             ("董希文","1914–1973"),("德伊涅卡","1899–1969"),("穆希娜","1889–1953")],
 "prompt": {"style": "socialist realism, soviet propaganda painting, heroic workers, optimistic bright future, monumental composition",
            "lighting": "low sun, backlit heroic rim light, clean bright illumination",
            "color": "bright saturated red, gold, sky blue, white, clean strong contrast",
            "composition": "low angle, pyramidal, figures pointing forward or upward, collective grouping",
            "medium": "oil on canvas, smooth realistic finish, lithograph poster",
            "mood": "exultant, collectivist, unwavering confidence",
            "camera": "low angle looking up, wide, heroic framing"},
 "negative": "irony, decay, muted colour, individual alienation, abstract, gritty realism, pessimism",
 "video": {"motion": "人群齐步向前、旗帜飘扬、收割与建设",
           "camera": "低角度缓慢推进；对称而向上",
           "note": "这是宣传美学——构图的昂扬感是它的技术核心"},
 "pitfalls": ["和社会现实主义区分清楚，两者政治立场相反但技法同源",
              "AI 会做得太阴沉 → 强调 bright, optimistic, heroic light"],
 "sources": {"cleveland": ["socialist realism"], "met": ["socialist realism"],
             "commons": ["Socialist realism painting Soviet", "Soviet poster 1930s", "Deineka painting"]},
 "see_also": ["social-realism", "muralism", "art-deco"],
},
# ---------------------------------------------------------------- 地域主义
{
 "slug": "regionalism", "name_zh": "美国地域主义", "name_en": "Regionalism",
 "period": "1930–1945", "region": "美国中西部", "tier": "A",
 "one_liner": "美国心脏地带的自我画像：农田、教堂、小镇，带着怀疑与乡愁。",
 "core": ["描绘美国中西部乡村生活，反对欧洲现代主义",
          "写实但带有刻意的夸张与戏剧化",
          "线条清晰、形体圆润，带插画感",
          "常带有保守主义或社会讽刺的暧昧立场"],
 "visual": {"色彩": "土黄、砖红、灰绿、暗蓝；温暖但克制",
            "光影": "戏剧化的斜射光，形体被清晰勾勒",
            "笔触": "精确、干净、有插画式的明确边缘",
            "构图": "风景成为主角，人物渺小或姿态僵硬；常有不安的空白",
            "材质": "布面油画、蛋彩、壁画",
            "情绪": "乡愁与不安并存、孤立、隐晦的批判"},
 "palette": [("#C9A25A","玉米黄"),("#A8432A","谷仓红"),("#6B7A5A","灰绿"),
             ("#4A5A6B","暗蓝"),("#8B6B4A","土褐"),("#D9CFC0","天白")],
 "artists": [("格兰特·伍德","1891–1942"),("托马斯·哈特·本顿","1889–1975"),
             ("约翰·斯图尔特·柯里","1897–1946")],
 "prompt": {"style": "american regionalism, midwest rural scene, precise illustrative realism, deliberately stylised forms, grant wood",
            "lighting": "dramatic raking light, crisp contour, slightly unnatural clarity",
            "color": "warm but restrained, corn yellow, barn red, grey green, dark blue",
            "composition": "landscape dominant, small or stiffly posed figures, uneasy empty space",
            "medium": "oil on canvas, egg tempera, mural, clean precise edges",
            "mood": "nostalgia mixed with unease, isolation, veiled critique",
            "camera": "eye-level, wide, precise framing"},
 "negative": "urban scene, european modernism, abstract, loose brushwork, glamour, cosmopolitan",
 "video": {"motion": "极少的动作：风吹麦田、窗帘微动、人物静止",
           "camera": "static 固定镜头；刻意的不动",
           "note": "地域主义的静止感是刻意的——它表达的是压抑"},
 "pitfalls": ["容易被当成普通田园画 → 加 deliberately stylised, uneasy, precise illustrative",
              "AI 会加浪漫光 → negative 写 glamour, loose brushwork"],
 "sources": {"cleveland": ["grant wood", "regionalism", "thomas hart benton"],
             "met": ["grant wood", "regionalism"], "commons": ["Grant Wood painting", "Thomas Hart Benton painting", "John Steuart Curry painting"]},
 "see_also": ["precisionism", "social-realism", "american-realism"],
},
# ---------------------------------------------------------------- 精确主义
{
 "slug": "precisionism", "name_zh": "精确主义", "name_en": "Precisionism",
 "period": "1920–1940", "region": "美国", "tier": "A",
 "one_liner": "把工厂和谷仓画成几何体：干净、锐利、没有人，像建筑渲染图。",
 "core": ["工业与农业建筑被还原为纯粹的几何形体",
          "边缘锐利、表面光滑、细节被剔除",
          "画面几乎无人，安静到不真实",
          "美国本土的早期现代主义，介于写实与抽象之间"],
 "visual": {"色彩": "干净的冷调：灰蓝、银白、砖红、深绿；平涂为主",
            "光影": "清晰锐利的光影，但形体被简化，几乎没有细节纹理",
            "笔触": "平滑无笔触，硬边几何",
            "构图": "低视角仰视建筑、强烈的几何切割、大面积空无",
            "材质": "布面油画、平涂硬边、工业感表面",
            "情绪": "冷静、孤立、工业时代的清冷诗意"},
 "palette": [("#8B9BB0","钢灰蓝"),("#D9CFC0","水泥白"),("#A8432A","砖红"),
             ("#3A4A3A","深绿"),("#2B2B33","阴影黑"),("#C9A227","照明黄")],
 "artists": [("查尔斯·希勒","1883–1965"),("查尔斯·德穆斯","1883–1935"),
             ("乔治亚·欧姬芙（早期）","1887–1986"),("普雷斯顿·迪金森","1889–1930")],
 "prompt": {"style": "precisionism, american industrial landscape, simplified geometric architecture, hard clean edges, no figures, charles sheeler",
            "lighting": "crisp sharp shadows, simplified volumes, almost no surface texture",
            "color": "clean cool palette, steel blue grey, cement white, brick red, dark green",
            "composition": "low angle on buildings, strong geometric cutting, large emptiness",
            "medium": "oil on canvas, smooth flat hard-edge painting, industrial surface",
            "mood": "cool, isolated, industrial quietude",
            "camera": "low angle, wide, straight architectural framing, deep focus"},
 "negative": "figures, organic detail, loose brushwork, romantic atmosphere, texture noise, people, soft focus",
 "video": {"motion": "几乎静止；只有烟囱的烟、云的移动",
           "camera": "极缓的直线平移或上升，机械而精确",
           "note": "精确主义的动是「建筑的静止」，人必须缺席"},
 "pitfalls": ["和立体主义混淆 → 精确主义仍是可辨识的写实，只是几何化",
              "AI 会加人 → negative 必须写 figures, people"],
 "sources": {"cleveland": ["precisionism", "charles sheeler", "charles demuth"],
             "met": ["precisionism", "charles sheeler"], "commons": ["Charles Sheeler painting"]},
 "see_also": ["cubism", "regionalism", "art-deco"],
},
# ---------------------------------------------------------------- 墨西哥壁画
{
 "slug": "muralism", "name_zh": "墨西哥壁画运动", "name_en": "Muralism",
 "period": "1920–1950", "region": "墨西哥", "tier": "A",
 "one_liner": "把革命史画满整面墙：农民、工人、印第安人和机器，全部挤在一起。",
 "core": ["公共壁画：艺术直接面向不识字的民众",
          "宏大的历史叙事与政治宣传",
          "融合前哥伦布艺术、民间艺术与欧洲现代主义",
          "人物密集、场景叠加、时间线被打乱"],
 "visual": {"色彩": "浓烈的土色与矿物色：赭红、钴蓝、玉米黄、黑",
            "光影": "平涂为主，用色块与粗轮廓塑造形体",
            "笔触": "壁画式的粗犷用笔，气势大于精微",
            "构图": "满墙铺陈、多场景叠加、人物密集、圆形与弧形分割",
            "材质": "湿壁画、水泥墙、矿物颜料、马赛克",
            "情绪": "史诗、愤怒、民间生命力、政治激情"},
 "palette": [("#A8432A","赭红"),("#1F5FA8","钴蓝"),("#E8C020","玉米黄"),
             ("#2B2B33","黑"),("#5A8A4A","龙舌兰绿"),("#C98A4A","土黄")],
 "artists": [("迭戈·里维拉","1886–1957"),("奥罗斯科","1883–1949"),
             ("西凯罗斯","1896–1974"),("塔马约","1899–1991"),("卡萝（相关）","1907–1954")],
 "prompt": {"style": "mexican muralism, monumental public fresco, dense historical narrative, pre-columbian and folk influence, rivera and orozco",
            "lighting": "flat mural illumination, form from colour blocks and heavy contour, no atmospheric depth",
            "color": "intense earth and mineral palette, ochre red, cobalt, corn yellow, black, agave green",
            "composition": "wall-filling, multiple scenes superimposed, dense crowds, circular divisions",
            "medium": "fresco on plaster wall, mineral pigment, mosaic",
            "mood": "epic, angry, folk vitality, political passion",
            "camera": "wide, slight low angle, flat depth, panoramic"},
 "negative": "intimate easel painting, minimalism, empty space, muted pastel, individual portrait focus, cool detachment",
 "video": {"motion": "人群推进、机器转动、旗帜挥舞；多个人物同时动作",
           "camera": "横向 pan 沿壁画展开（这是壁画的正确看法）",
           "note": "壁画是横向展开的——用 pan 而不是推拉"},
 "pitfalls": ["AI 会简化成少数人物 → 加 dense crowds, multiple scenes, wall-filling",
              "色彩容易不够浓 → 明确 mineral palette, intense"],
 "sources": {"cleveland": ["diego rivera", "muralism", "orozco"],
             "met": ["diego rivera", "mexican muralism"], "commons": ["Diego Rivera mural", "Jose Clemente Orozco mural", "David Alfaro Siqueiros mural"]},
 "see_also": ["social-realism", "socialist-realism", "art-brut"],
},
# ---------------------------------------------------------------- 魔幻现实主义
{
 "slug": "magic-realism", "name_zh": "魔幻现实主义（绘画）", "name_en": "Magic Realism",
 "period": "1925–1955", "region": "德国 / 美国 / 欧洲", "tier": "A",
 "one_liner": "不画梦境，而是把现实画得太清晰，清晰到它自己变得陌生。",
 "core": ["与超现实主义不同：不画潜意识，而是精确描绘现实中的奇异",
          "极度清晰、冷静、甚至冷酷的写实技法",
          "奇异感来自精确本身，而非拼贴或变形",
          "安静的、静止的、时间凝固的场景"],
 "visual": {"色彩": "清晰准确但偏冷的色，色调克制而均匀",
            "光影": "锐利、干净、不自然清晰的光，像冷光摄影",
            "笔触": "极其平滑精细，几乎看不见笔触",
            "构图": "静止的日常场景、人物僵住、精确的透视",
            "材质": "布面油画或蛋彩、极精细的罩染",
            "情绪": "诡异、静默、被凝固的时间、温柔的不安"},
 "palette": [("#8B9B9B","冷灰"),("#4A5A6B","暗蓝"),("#C9A25A","暗黄"),
             ("#A8432A","暗红"),("#3A4A3A","深绿"),("#E8E4DA","冷白")],
 "artists": [("乔治·德·基里科（形而上，相关）","1888–1978"),("德尔沃（相关）","1897–1994"),
             ("安德鲁·怀斯","1917–2009"),("亚历山大·卡诺尔德","1881–1955"),
             ("奥托·迪克斯（新客观）","1891–1969")],
 "prompt": {"style": "magic realism painting, hyper-clear depiction of the uncanny ordinary, frozen stillness, precise cool realism, not surrealist juxtaposition",
            "lighting": "razor-sharp clean cool light, unnatural clarity, precise cast shadows",
            "color": "accurate but cool restrained colour, even tonality, subtle and controlled",
            "composition": "still everyday scene, figures frozen mid-gesture, exact perspective",
            "medium": "oil or tempera on panel, extremely smooth glazing, invisible brushwork",
            "mood": "uncanny, silent, time suspended, gentle unease",
            "camera": "eye-level, medium shot, deep focus, perfectly level"},
 "negative": "dream imagery, melting objects, psychedelic, loose brushwork, warm romantic light, cartoon",
 "video": {"motion": "几乎没有；极缓慢的云影或窗帘移动",
           "camera": "static 长镜头；时间凝固感是关键",
           "note": "和超现实主义最大的区别：这里没有荒诞元素，只有过度清晰的现实"},
 "pitfalls": ["和超现实主义混淆 → 明确 not surrealist juxtaposition, no dream imagery",
              "AI 会加梦魇元素 → negative 写 melting objects, psychedelic"],
 "sources": {"cleveland": ["magic realism", "andrew wyeth"],
             "met": ["magic realism", "andrew wyeth"], "commons": ["Alexander Kanoldt painting", "Georg Schrimpf painting", "Christian Schad painting", "Magic realism painting 1920s"]},
 "see_also": ["surrealism", "metaphysical-art", "photorealism", "naive-art"],
},
# ---------------------------------------------------------------- 形而上绘画
{
 "slug": "metaphysical-art", "name_zh": "形而上绘画", "name_en": "Metaphysical Art",
 "period": "1910–1920", "region": "意大利", "tier": "A",
 "one_liner": "空荡的意大利广场、拉长的影子、没有人的雕像——超现实主义的直接源头。",
 "core": ["空旷的广场与拱廊，人极少或完全缺席",
          "极度拉长的影子，暗示画面外的低垂太阳",
          "日常物体的非逻辑并置（手套、球、雕像）",
          "透视正确但空间感觉不对，像舞台布景"],
 "visual": {"色彩": "土黄、赭石、暗绿、灰蓝；温暖而陈旧",
            "光影": "低角度长影，黄昏感，光很硬但氛围很静",
            "笔触": "平滑精确，几乎无笔触",
            "构图": "空旷广场、拱廊透视、物体如静物般并置",
            "材质": "布面油画、平滑罩染、古典建筑元素",
            "情绪": "忧郁、悬置、时间停止的形而上学不安"},
 "palette": [("#C9A25A","赭黄"),("#8B6B4A","土褐"),("#4A5A4A","暗绿"),
             ("#6B8B9E","灰蓝"),("#2B2B33","长影黑"),("#E8DCC8","石白")],
 "artists": [("乔治·德·基里科","1888–1978"),("卡洛·卡拉（早期）","1881–1966"),
             ("乔治·莫兰迪","1890–1964"),("菲利波·德·皮西斯","1896–1956")],
 "prompt": {"style": "metaphysical painting, pittura metafisica, empty italian piazza with arcades, elongated shadows, illogical object juxtaposition, de chirico",
            "lighting": "low late afternoon sun casting extremely long shadows, hard light with still atmosphere",
            "color": "ochre, burnt sienna, dark green, grey blue, aged warm tones",
            "composition": "empty square with arcade perspective, objects arranged like still life, mannequin figures",
            "medium": "oil on canvas, smooth precise glazing, classical architectural elements",
            "mood": "melancholic, suspended, metaphysical unease, time stopped",
            "camera": "eye-level, wide, strong one-point perspective"},
 "negative": "crowded scene, busy detail, bright daylight, loose impressionist brushwork, movement, cheerfulness",
 "video": {"motion": "几乎没有；或一个影子极缓慢地移动",
           "camera": "static 或极缓 dolly in 进入空旷广场",
           "note": "核心是「空」和「长影」——不要往画面里加人"},
 "pitfalls": ["和超现实主义混淆 → 形而上绘画更早、更克制、更建筑化",
              "AI 会填满场景 → negative 写 crowded scene, busy detail"],
 "sources": {"cleveland": ["de chirico", "metaphysical painting", "morandi"],
             "met": ["de chirico", "metaphysical"], "commons": ["Giorgio de Chirico painting", "Carlo Carra painting", "Giorgio Morandi painting"]},
 "see_also": ["surrealism", "magic-realism", "classicism"],
},
# ---------------------------------------------------------------- 新浪漫主义
{
 "slug": "neo-romanticism", "name_zh": "新浪漫主义", "name_en": "Neo-Romanticism",
 "period": "1930–1955", "region": "英国 / 欧洲", "tier": "A",
 "one_liner": "战后英国的忧郁风景：荒废的庄园、海岸、废墟，和一种温柔的绝望。",
 "core": ["浪漫主义情绪在 20 世纪的复现，但更内省、更破碎",
          "荒凉风景、废墟、海岸、废弃建筑",
          "人物孤独、背对观者、或完全缺席",
          "诗意的忧郁取代了 19 世纪的崇高"],
 "visual": {"色彩": "灰绿、暗蓝、沙褐、褪色的粉；低饱和",
            "光影": "阴天散射光、黄昏微光、湿润的空气",
            "笔触": "柔和、有质感，介于写实与表现之间",
            "构图": "孤独的物体置于空旷风景中，人物渺小",
            "材质": "布面油画、坦培拉、素描",
            "情绪": "忧郁、孤独、诗意的荒凉、战后的疲倦"},
 "palette": [("#6B7A6A","灰绿"),("#4A5A6B","暗蓝"),("#A89878","沙褐"),
             ("#C9A8A0","褪粉"),("#3A3A38","暗灰"),("#D9CFC0","雾白")],
 "artists": [("保罗·纳什","1889–1946"),("格雷厄姆·萨瑟兰","1903–1980"),
             ("约翰·派珀","1903–1992"),("卢西恩·弗洛伊德（早期）","1922–2011"),
             ("菲利克斯·凯利","1914–1994")],
 "prompt": {"style": "neo-romanticism, melancholic british landscape, ruins and deserted coast, solitary poetic mood, paul nash and graham sutherland",
            "lighting": "overcast diffused light, damp atmosphere, faint dusk glow, low contrast",
            "color": "desaturated grey green, dark blue, sand brown, faded pink",
            "composition": "solitary object in empty landscape, tiny or absent figure, wide empty sky",
            "medium": "oil on canvas, tempera, textured but restrained handling",
            "mood": "melancholic, solitary, poetic desolation, post-war weariness",
            "camera": "wide shot, eye-level, soft focus distance"},
 "negative": "bright cheerful, saturated colour, urban bustle, sharp digital clarity, heroic drama, minimalism",
 "video": {"motion": "风过荒草、云层缓慢移动、海浪拍岸",
           "camera": "极缓 pan 或 static 远景",
           "note": "新浪漫主义的动是「风景在呼吸，人不动」"},
 "pitfalls": ["和浪漫主义区分：新浪漫主义更安静、更灰、没有崇高感",
              "AI 会加戏剧性 → negative 写 heroic drama, bright cheerful"],
 "sources": {"cleveland": ["paul nash", "neo-romanticism", "graham sutherland"],
             "met": ["paul nash", "neo-romanticism"], "commons": ["Paul Nash painting"]},
 # 19 世纪版画家 Thomas Sutherland 与 Graham Sutherland 同姓不同人，
 # 实测他的两幅版画混进了这个流派（标题里虽有 Paul Nash，作者却是他）。
 "exclude_keys": ["thomas sutherland", "sutherland, thomas"],
 "see_also": ["romanticism", "tonalism", "symbolism"],
},
# ---------------------------------------------------------------- 美国现实主义
{
 "slug": "american-realism", "name_zh": "美国现实主义", "name_en": "American Realism",
 "period": "1865–1930", "region": "美国", "tier": "A",
 "one_liner": "霍默的海、埃金斯划船的下午：美国第一次用自己的眼睛看自己。",
 "core": ["摆脱欧洲学院传统，转向本土题材",
          "户外生活、体育、航海、市井日常",
          "以摄影般的精确与冷静观察",
          "光线明亮、色彩清透，带外光写生感"],
 "visual": {"色彩": "清透的自然色：海蓝、草绿、白衬衫、木褐",
            "光影": "明亮的户外日光，清晰的明暗但不过度戏剧化",
            "笔触": "写实、明确，有时偏干；不炫技",
            "构图": "抓取动作的瞬间、横向展开的水面或田野",
            "材质": "布面油画、水彩、写实厚涂",
            "情绪": "清爽、务实、克制的观察、带一丝孤独"},
 "palette": [("#4A7C9E","海蓝"),("#7FA86B","草绿"),("#E8E4DA","衬衫白"),
             ("#8B6B4A","木褐"),("#C9A25A","日光黄"),("#3A4A5A","深水蓝")],
 "artists": [("温斯洛·霍默","1836–1910"),("托马斯·埃金斯","1844–1917"),
             ("约翰·辛格·萨金特","1856–1925"),("威廉·梅里特·蔡斯","1849–1916")],
 "prompt": {"style": "american realism, 19th century outdoor genre scene, clear naturalistic observation, winslow homer and thomas eakins",
            "lighting": "bright clear outdoor daylight, distinct but not theatrical modelling",
            "color": "clear natural palette, sea blue, grass green, shirt white, wood brown",
            "composition": "moment of action captured, horizontal expanse of water or field",
            "medium": "oil on canvas, watercolour, direct realistic handling",
            "mood": "crisp, practical, restrained observation with a trace of solitude",
            "camera": "eye-level, medium wide, 50mm, deep focus"},
 "negative": "european academic allegory, dramatic chiaroscuro, symbolic content, idealised beauty, ornate",
 "video": {"motion": "划桨、扬帆、奔跑——明确的物理动作",
           "camera": "slight handheld 或固定远景；动作要真实可信",
           "note": "美国现实主义的力量在「动作的准确性」"},
 "pitfalls": ["和现实主义混淆 → 美国现实主义更亮、更户外、更本土",
              "AI 会加象征意味 → negative 写 symbolic content, allegory"],
 "sources": {"cleveland": ["winslow homer", "thomas eakins", "american realism"],
             "met": ["winslow homer", "thomas eakins"], "commons": ["Winslow Homer painting"]},
 "see_also": ["realism", "ashcan-school", "naturalism"],
},
# ---------------------------------------------------------------- 学院古典写实
{
 "slug": "classical-realism", "name_zh": "古典写实主义（当代）", "name_en": "Classical Realism",
 "period": "1970–今", "region": "欧美 / 全球", "tier": "B",
 "one_liner": "当代画家重新学会 19 世纪的技法，但用现代的眼睛看现代的身体。",
 "core": ["当代艺术家系统地复兴古典写实技法",
          "严格的比例、解剖与明暗训练",
          "题材现代，技法古典",
          "与照相写实不同：保留笔触与绘画性"],
 "visual": {"色彩": "古典的有限调色板，肉色被精细处理",
            "光影": "经典的明暗对照，光源明确而柔和",
            "笔触": "可见但有控制，不像照片那样消灭笔触",
            "构图": "人物为中心，古典比例的构图，背景简化",
            "材质": "布面油画、古典多层罩染、亚麻布",
            "情绪": "沉静、庄重、对技艺的敬意"},
 "palette": [("#8B6B4A","土褐"),("#D9B29A","肤"),("#4A5A6B","灰蓝"),
             ("#7A1F2B","深红"),("#C9A227","赭金"),("#E8DCC8","亚麻白")],
 "artists": [("雅各布·柯林斯","1964–"),("威廉·惠特克","1943–"),
             ("内尔森·尚克斯","1937–2015"),("奥迪·内尔德","1940–")],
 "prompt": {"style": "contemporary classical realism, revived old master technique on modern subject, controlled visible brushwork, rigorous anatomy",
            "lighting": "classical chiaroscuro, single soft directional source, deep but transparent shadows",
            "color": "limited classical palette, earth brown, refined flesh, grey blue, deep red, ochre",
            "composition": "figure-centred, classical proportions, simplified background",
            "medium": "oil on linen, layered glazing over direct painting, visible but controlled strokes",
            "mood": "quiet, dignified, reverence for craft",
            "camera": "eye-level, medium shot, 85mm, shallow depth of field"},
 "negative": "photographic flatness, abstract, concept art, loose sketch, cartoon, digital render",
 "video": {"motion": "缓慢的转身或抬手；庄重的动作",
           "camera": "static 或极缓 dolly in",
           "note": "当代古典写实的动应该是「肖像式的静止」"},
 "pitfalls": ["和照相写实区分：这里保留笔触和绘画性",
              "版权：当代艺术家作品在版权期内，只存提示词"],
 "sources": {"cleveland": ["classical realism"], "met": ["classical realism"], "commons": []},
 "see_also": ["academic-art", "photorealism", "renaissance"],
},
# ---------------------------------------------------------------- 媚俗
{
 "slug": "kitsch", "name_zh": "媚俗艺术", "name_en": "Kitsch",
 "period": "1930–今", "region": "全球", "tier": "B",
 "one_liner": "刻意的甜腻：太漂亮、太感伤、太讨喜，反而成了一种美学武器。",
 "core": ["对大众趣味的过度迎合：甜、亮、无害",
          "廉价复制品的美学（瓷盘、明信片、纪念品）",
          "被现代艺术视为敌人，又被后现代重新启用",
          "感伤、可爱、温馨到令人不适"],
 "visual": {"色彩": "过度饱和的粉、金、天蓝、雪白；甜到发腻",
            "光影": "柔和的、理想化的、没有阴影的光",
            "笔触": "商业插画式的光滑，或廉价印刷的网点",
            "构图": "正面居中、对称、装饰性边框",
            "材质": "瓷、亮片、塑料、廉价印刷品、金边",
            "情绪": "甜蜜、感伤、刻意廉价，看久了会不安"},
 "palette": [("#F2A8C8","糖粉"),("#E8C020","金"),("#7FC8E8","天蓝"),
             ("#FFFFFF","雪白"),("#C1272D","亮红"),("#8BC34A","嫩绿")],
 "artists": [("杰夫·昆斯","1955–"),("皮埃尔与吉尔","1950–"),("村上隆（相关）","1962–"),
             ("克莱门特·格林伯格（批评者）","1909–1994")],
 "prompt": {"style": "kitsch aesthetic, over-sweet sentimental imagery, porcelain figurine gloss, mass produced souvenir look, jeff koons",
            "lighting": "soft idealised shadowless glow, glossy specular highlights",
            "color": "oversaturated pastel and gold, sugar pink, sky blue, snow white, bright red",
            "composition": "frontal centred symmetry, decorative border, souvenir arrangement",
            "medium": "porcelain, glitter, plastic, cheap offset print, gold trim",
            "mood": "sweet, sentimental, deliberately cheap, unsettling on prolonged viewing",
            "camera": "flat frontal, centered, product-shot lighting"},
 "negative": "restraint, subtlety, muted palette, grit, authenticity, avant garde difficulty, natural materials",
 "video": {"motion": "过度流畅的旋转、闪光、粒子飘落",
           "camera": "完美的环绕镜头；刻意做得像广告",
           "note": "媚俗的动要像购物频道——过度顺滑"},
 "pitfalls": ["容易被做成真的低级 → 关键是「刻意的」，要加 deliberate, aesthetic weapon",
              "版权：当代作品在版权期内，只存提示词"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["pop-art", "neo-pop", "superflat", "art-deco"],
},
# ---------------------------------------------------------------- 新客观主义
{
 "slug": "new-objectivity", "name_zh": "新客观主义", "name_en": "New Objectivity",
 "period": "1920–1933", "region": "德国", "tier": "A",
 "one_liner": "魏玛德国的冷眼：战争伤残、夜店、妓女与投机商，画得像外科手术。",
 "core": ["对表现主义情绪化的反动，转向冷酷的写实",
          "社会批判肖像：把丑与病如实画出",
          "精确、锐利、干燥的技法",
          "与魏玛共和国的社会危机直接对应"],
 "visual": {"色彩": "干冷的色：灰绿、土黄、锌白、暗红；低饱和",
            "光影": "硬朗均匀的光，不留温情，细节清晰",
            "笔触": "极精细的写实，笔触被彻底隐藏",
            "构图": "正面肖像、拥挤的城市场景、对称而压迫",
            "材质": "木板或布面油画、极细罩染",
            "情绪": "冷酷、讽刺、临床式的直视、被压抑的暴烈"},
 "palette": [("#6B7A6A","灰绿"),("#C9A25A","土黄"),("#D9D5CC","锌白"),
             ("#8B1A2A","暗红"),("#3A3A38","炭灰"),("#8B6B4A","褐")],
 "artists": [("奥托·迪克斯","1891–1969"),("乔治·格罗兹","1893–1959"),
             ("马克斯·贝克曼","1884–1950"),("克里斯蒂安·沙德","1894–1982"),
             ("奥古斯特·桑德（摄影）","1876–1964")],
 "prompt": {"style": "new objectivity, neue sachlichkeit, cold clinical realism, weimar germany social critique, otto dix and george grosz",
            "lighting": "hard even light with no warmth, clinical clarity, unflattering",
            "color": "dry cool palette, grey green, ochre, zinc white, dark red",
            "composition": "frontal portrait or crowded urban scene, symmetrical and oppressive",
            "medium": "oil on panel or canvas, extremely fine glazing, invisible brushwork",
            "mood": "cold, satirical, clinical stare, suppressed violence",
            "camera": "eye-level frontal, medium close, 50mm, flat clinical lighting"},
 "negative": "expressionist distortion, warm sentiment, romantic glow, loose brushwork, idealised beauty",
 "video": {"motion": "几乎没有；人物僵直地直视镜头",
           "camera": "static 正面；像证件照一样的凝视",
           "note": "新客观主义的力量在「不动声色的直视」"},
 "pitfalls": ["和表现主义区分：新客观主义是冷写实，表现主义是热变形",
              "AI 会加温情 → negative 写 warm sentiment, romantic glow"],
 "sources": {"cleveland": ["otto dix", "new objectivity", "george grosz"],
             "met": ["otto dix", "max beckmann", "neue sachlichkeit"],
             "commons": ["Otto Dix painting"]},
 "see_also": ["expressionism", "magic-realism", "social-realism"],
},
]

ARTIST_KEYS = {
 "early-renaissance": ["masaccio", "fra angelico", "botticelli", "piero della francesca",
                        "paolo uccello", "ghirlandaio", "lippi", "perugino", "gozzoli"],
 "international-gothic": ["limbourg", "martini", "gentile da fabriano", "lorenzo monaco",
                           "stefan lochner", "bohemian", "international gothic", "theoderic"],
 "naturalism": ["bastien-lepage", "bastien lepage", "lempa", "zorn", "sorolla",
                 "lemoine", "rolle", "liebermann", "naturalis"],
 "orientalism": ["gérome", "gerome", "gérôme", "lewis", "deutsch", "fromentin",
                  "orientalis", "orientalist", "alma-tadema"],
 "luminism": ["kensett", "lane", "heade", "luminis", "gifford", "whittredge"],
 "japonism": ["japonis", "japonisme", "van gogh", "hiroshige", "eisens", "eisen", "whistler", "bracquemond"],
 "classicism": ["poussin", "claude lorrain", "reynolds", "david, jacques", "ingres",
                 "classicis", "vien", "mengs"],
 "naive-art": ["rousseau", "seraphine", "séraphine", "grandma moses", "wallis",
                "naive", "naïve", "primitiv", "vivin", "bauchant", "bombois"],
 "social-realism": ["shahn", "rivera", "orozco", "siqueiros", "bellows", "evergood",
                     "levine", "gropper", "social realis"],
 "socialist-realism": ["socialist realis", "gerasimov", "deineka", "joganson", "mukhina", "soviet poster"],
 "regionalism": ["grant wood", "benton", "curry", "regionalis", "marsh"],
 "precisionism": ["sheeler", "demuth", "dickinson", "o'keeffe", "okeefe", "precisionis",
                   "crawford", "lusk"],
 "muralism": ["rivera", "orozco", "siqueiros", "muralis", "charlot", "tamayo"],
 "magic-realism": ["magic realis", "kanoldt", "schrimpf", "radziwill", "schad", "davringhausen", "colville", "wyeth"],
 "metaphysical-art": ["de chirico", "chirico", "carra", "carrà", "morandi", "metaphysical", "de pisis"],
 "neo-romanticism": ["paul nash", "sutherland", "john piper", "neo-romantic", "neoromantic",
                      "felix kelly", "minton", "craxton"],
 "american-realism": ["homer", "eakins", "sargent", "chase", "harnett", "bellows",
                       "american realis", "henri"],
 "classical-realism": ["jacob collins", "whitaker", "shanks", "nelson shanks", "neerd",
                        "classical realis"],
 "kitsch": ["kitsch", "koons", "pierre et gilles", "souvenir"],
 "new-objectivity": ["otto dix", "grosz", "beckmann", "schad", "neue sachlichkeit",
                      "new objectivity", "sander", "davringhausen", "kanoldt"],
}
