# -*- coding: utf-8 -*-
"""流派定义 —— 现代主义与战后（19 个）。

注意：1950 年之后的流派大多仍在版权期内，开放数据源里基本拿不到图。
这些流派会生成为「纯提示词卡」——只存结构，不存图。这是有意为之，不是缺陷。
"""

CATEGORY = "现代主义与战后"

MOVEMENTS = [
# ---------------------------------------------------------------- 野兽派
{
 "slug": "fauvism", "name_zh": "野兽派", "name_en": "Fauvism",
 "period": "1905–1908", "region": "法国", "tier": "A",
 "one_liner": "把颜色从描述里解放出来：草地可以是红的，脸可以是绿的。",
 "core": ["纯色直接挤出，不做混色与明暗过渡",
          "色彩完全主观，与物体真实颜色无关",
          "笔触粗放、快速、有装饰性",
          "空间被压平，靠色块的冷暖推拉"],
 "visual": {"色彩": "极高纯度的大色块：朱红、钴蓝、翠绿、橙黄直接对撞",
            "光影": "没有光影塑造，明暗完全被色彩替代",
            "笔触": "宽大、果断、可见；有时直接留出画布白",
            "构图": "平面化、装饰性、视角略随意",
            "材质": "布面油画、厚涂纯色、可见画布纹理",
            "情绪": "欢愉、强烈、感官的爆发、生命力"},
 "palette": [("#D62828","朱红"),("#1F5FD6","钴蓝"),("#2E9B5B","翠绿"),
             ("#F2A93B","橙黄"),("#8B3FA0","紫"),("#F2EDE4","留白")],
 "artists": [("马蒂斯","1869–1954"),("德兰","1880–1954"),("弗拉曼克","1876–1958"),
             ("杜菲","1877–1953"),("马尔凯","1875–1947")],
 "prompt": {"style": "fauvism painting, pure unmixed colour, arbitrary non-descriptive palette, bold flat colour areas, decorative simplification",
            "lighting": "no tonal modelling, light replaced entirely by colour intensity, no shadows in the traditional sense",
            "color": "maximum saturation, vermilion, cobalt, emerald, orange yellow clashing side by side",
            "composition": "flattened space, decorative arrangement, colour temperature used for depth",
            "medium": "oil on canvas, thick direct application of pure pigment, visible canvas weave",
            "mood": "joyful, intense, sensuous, vital",
            "camera": "eye-level, medium shot, flattened perspective"},
 "negative": "realistic colour, tonal modelling, subtle gradients, muted palette, photorealistic, soft shading",
 "video": {"motion": "大色块缓慢流动变幻，物体形状轻微自由变形",
           "camera": "缓慢 pan；节奏明快",
           "note": "野兽派的动要「有颜色感」——让色彩本身在变"},
 "pitfalls": ["AI 会加明暗塑造 → negative 写 tonal modelling, realistic colour, soft shading",
              "纯度容易不够 → 明确 pure unmixed colour, maximum saturation"],
 "sources": {"cleveland": ["matisse", "fauvism", "derain"],
             "met": ["matisse", "andre derain", "raul dufy"], "commons": ["Henri Matisse painting", "Andre Derain painting", "Maurice de Vlaminck painting"]},
 "see_also": ["post-impressionism", "expressionism", "orphism"],
},
# ---------------------------------------------------------------- 青骑士
{
 "slug": "der-blaue-reiter", "name_zh": "青骑士", "name_en": "Der Blaue Reiter",
 "period": "1911–1914", "region": "德国 / 慕尼黑", "tier": "A",
 "one_liner": "从具象滑向抽象的路上：颜色和形状要直接作用于灵魂。",
 "core": ["色彩与形式被赋予精神性（康定斯基《论艺术的精神》）",
          "从具象逐步解离为抽象的过渡形态",
          "木刻与版画的粗粝语言"],
 "visual": {"色彩": "浓烈的蓝、黄、红原色并置，或完全抽象的色斑",
            "光影": "无真实光源，色彩自身发光",
            "笔触": "自由、表现性；后期是完全的抽象色块与线条",
            "构图": "中心松动、元素漂浮、边界解体",
            "材质": "布面油画、木刻版画、水彩",
            "情绪": "精神性、内省、神秘、向上的冲动"},
 "palette": [("#1F3FA8","深蓝"),("#E8C020","亮黄"),("#C1272D","正红"),
             ("#2E7A5B","蓝绿"),("#4A3A6B","深紫"),("#F2EDE4","光白")],
 "artists": [("康定斯基","1866–1944"),("弗朗茨·马尔克","1880–1916"),
             ("奥古斯特·马克","1887–1914"),("加布里埃尔·明特尔","1877–1962"),
             ("保罗·克利","1879–1940")],
 "prompt": {"style": "der blaue reiter, expressionist abstraction, spiritual colour symbolism, dissolving forms, kandinsky and franz marc style",
            "lighting": "no natural light source, colour emits its own light, no modelling",
            "color": "intense primary blue yellow red, or fully abstract colour patches, spiritual resonance",
            "composition": "loosened centre, floating elements, dissolving boundaries, dynamic balance",
            "medium": "oil on canvas, woodcut print, watercolour",
            "mood": "spiritual, introspective, mystical, upward striving",
            "camera": "eye-level, flat depth, no realism"},
 "negative": "realistic rendering, naturalistic light, photographic, mundane subject, muted grey, academic finish",
 "video": {"motion": "色块缓慢变形、线条自由游走、形态持续解离",
           "camera": "static 或极缓 zoom；让画面内部运动",
           "note": "青骑士的动是「形态在解体」，不是物体在移动"},
 "pitfalls": ["容易被做成普通抽象画 → 加 spiritual colour symbolism, kandinsky, dissolving forms",
              "注意和桥社（Die Brücke）区分：青骑士更精神化、更接近抽象"],
 "sources": {"cleveland": ["kandinsky", "franz marc"], "met": ["kandinsky", "franz marc", "august macke"],
             "commons": ["Franz Marc painting"]},
 "see_also": ["expressionism", "fauvism", "suprematism"],
},
# ---------------------------------------------------------------- 未来主义
{
 "slug": "futurism", "name_zh": "未来主义", "name_en": "Futurism",
 "period": "1909–1920", "region": "意大利 / 俄罗斯", "tier": "A",
 "exclude_keys": ["concourse of the birds", "habiballah"],
 "one_liner": "把速度画出来：一个动作同时画出它的所有瞬间，像频闪摄影。",
 "core": ["同时性（simultaneity）：同一物体画出多个时间切片",
          "力线（lines of force）表达运动的方向与能量",
          "崇拜机器、速度、战争与都市",
          "分割主义技法 + 立体主义形式的融合"],
 "visual": {"色彩": "高饱和的橙、红、蓝、绿，色彩如光一样发散",
            "光影": "光被画成放射状的力线；物体边缘不断重复",
            "笔触": "分割主义的短笔触 + 立体主义的几何面",
            "构图": "放射状、螺旋、被速度拉长的对角线",
            "材质": "布面油画、几何化的形体分解",
            "情绪": "狂热、速度、暴力、现代的亢奋"},
 "palette": [("#E85D2A","炽橙"),("#C1272D","正红"),("#1F5FD6","电蓝"),
             ("#3E9B6B","荧光绿"),("#C9A227","光黄"),("#2B2B33","烟黑")],
 "artists": [("巴拉","1871–1958"),("波丘尼","1882–1916"),("塞韦里尼","1883–1966"),
             ("卡拉","1881–1966"),("鲁索洛","1885–1947")],
 "prompt": {"style": "futurism painting, simultaneity of motion, lines of force, divisionist brushwork with cubist faceting, dynamic energy",
            "lighting": "light radiating as force lines, repeated edges, no fixed source, flickering illumination",
            "color": "high saturation orange, red, electric blue, vivid green, luminous yellow",
            "composition": "radial spiral composition, diagonals stretched by speed, multiple time slices",
            "medium": "oil on canvas, geometric decomposition, divisionist strokes",
            "mood": "frenzied, kinetic, violent, modern exhilaration",
            "camera": "wide angle, dynamic diagonal tilt, dutch angle, motion blur"},
 "negative": "static symmetrical composition, calm muted palette, still life, academic realism, soft shading",
 "video": {"motion": "频闪式的重复动作、物体同时向左向右、力线放射",
           "camera": "快速推拉、旋转、甩镜；模仿速度感",
           "note": "未来主义的动是「同一动作的多个瞬间叠加」，不是平滑运动"},
 "pitfalls": ["AI 会做成普通运动模糊 → 加 simultaneity, multiple time slices, lines of force",
              "容易和立体主义混淆 → 未来主义有更强的速度与色彩"],
 "sources": {"cleveland": ["futurism", "boccioni", "balla"],
             "met": ["futurism", "giacomo balla", "gino severini"],
             "commons": ["Umberto Boccioni painting", "Giacomo Balla painting", "Gino Severini painting"]},
 "see_also": ["cubism", "constructivism", "expressionism"],
},
# ---------------------------------------------------------------- 俄耳甫斯主义
{
 "slug": "orphism", "name_zh": "俄耳甫斯主义", "name_en": "Orphism",
 "period": "1912–1915", "region": "法国", "tier": "B",
 "exclude_keys": ["nicolas delaunay", "delaunay, nicolas",
                         # 19 世纪学院派画家 Jules-Élie Delaunay —— 和 Robert Delaunay
                         # 只是同姓。实测他的《但丁的炼狱》《Hutchinson 夫人像》混进了
                         # orphism，零样本自识率因此为 0、平均排名掉到 104/141。
                         "jules-élie delaunay", "jules-elie delaunay", "j.-e. delaunay"],
 "one_liner": "把立体主义变成音乐：纯粹的色彩圆盘与棱镜光谱。",
 "core": ["纯色彩构成画面，比立体主义更抽象、更明亮",
          "圆盘、同心圆、棱镜色散作为核心母题",
          "色彩被赋予类似音乐的结构与节奏",
          "从分析立体主义的灰褐走向光谱色"],
 "visual": {"色彩": "光谱式鲜艳色：橙红、青蓝、黄绿，圆盘式并置",
            "光影": "光由色彩自身发射，如棱镜分解后的纯色",
            "笔触": "平滑的几何色块与弧线，边缘清晰",
            "构图": "同心圆、圆盘、旋转的几何结构",
            "材质": "布面油画、平涂色块、几何弧线",
            "情绪": "明快、律动、音乐性、乐观的抽象"},
 "palette": [("#F26522","橙红"),("#29ABE2","青蓝"),("#8CC63F","黄绿"),
             ("#F2C230","光谱黄"),("#9B59B6","紫"),("#F2EDE4","棱镜白")],
 "artists": [("德劳内","1885–1941"),("库普卡","1871–1957"),
             ("索尼娅·德劳内","1885–1979"),("皮卡比亚","1879–1953")],
 "prompt": {"style": "orphism, robert delaunay, prismatic colour discs, pure colour abstraction, musical structure, simultaneous colour contrast",
            "lighting": "colour as emitted light, prismatic dispersion, no external source",
            "color": "spectral vivid colour, orange red, cyan, yellow green, concentric chromatic discs",
            "composition": "concentric circles, rotating geometric structure, rhythmic colour arrangement",
            "medium": "oil on canvas, smooth flat colour areas, crisp arcs",
            "mood": "buoyant, rhythmic, musical, optimistic abstraction",
            "camera": "flat frontal, no depth"},
 "negative": "earth tones, monochrome, realistic subject, chiaroscuro, muddy mixtures, dark moody",
 "video": {"motion": "色盘缓慢旋转、色彩如涟漪般扩散",
           "camera": "static，或极缓 zoom 穿过色层",
           "note": "俄耳甫斯主义的动是「色彩的旋转」，接近音乐的循环"},
 "pitfalls": ["AI 会做成普通抽象 → 加 concentric colour discs, prismatic dispersion, musical structure",
              "色彩容易脏 → 明确 spectral, pure, no muddy mixtures"],
 "sources": {"cleveland": ["orphism", "delaunay", "kupka"],
             "met": ["robert delaunay", "frantisek kupka"], "commons": ["Robert Delaunay painting"]},
 "see_also": ["cubism", "fauvism", "der-blaue-reiter"],
},
# ---------------------------------------------------------------- 至上主义
{
 "slug": "suprematism", "name_zh": "至上主义", "name_en": "Suprematism",
 "period": "1915–1925", "region": "俄国", "tier": "A",
 "one_liner": "绘画的终点：一个黑方块就够了，所有形象都是多余的。",
 "core": ["非具象的极致：基本几何形在纯白空间里漂浮",
          "黑方块、红方块、白底上的黑方块三部曲",
          "取消重力与透视，形体在无限中悬浮",
          "绘画作为「纯粹感受」的直接表达"],
 "visual": {"色彩": "极简：黑、红、白、黄、蓝，纯平涂无渐变",
            "光影": "完全没有，纯色块在白色虚空中",
            "笔触": "硬边几何，无笔触无肌理",
            "构图": "对角线、悬浮、无重力感、非对称",
            "材质": "布面油画、硬边平涂、哑光表面",
            "情绪": "绝对、冷峻、乌托邦、形而上"},
 "palette": [("#111111","黑方块"),("#C1272D","红方块"),("#F2EDE4","虚空白"),
             ("#F2C230","黄"),("#1F5FD6","蓝"),("#8A8A85","灰")],
 "artists": [("马列维奇","1879–1935"),("利西茨基","1890–1941"),
             ("克柳恩","1878–1935"),("苏耶京","1894–1954")],
 "prompt": {"style": "suprematism, malevich, pure geometric forms floating in white void, non-objective painting, hard-edged flat colour",
            "lighting": "no light, no shadow, colour floats in infinite white space",
            "color": "minimal black, red, white, yellow, blue, flat unmodulated",
            "composition": "diagonal floating arrangement, weightless, asymmetric, infinite void",
            "medium": "oil on canvas, hard-edge flat paint, matte surface",
            "mood": "absolute, austere, utopian, metaphysical",
            "camera": "flat orthographic, no perspective, no depth of field"},
 "negative": "gradient, shading, texture, representation, figurative subject, ornament, soft edges",
 "video": {"motion": "几何形缓慢悬浮漂移、旋转（模拟无重力）",
           "camera": "static 平面；不要用景深",
           "note": "至上主义的动是「无重力漂浮」，不是物体的物理运动"},
 "pitfalls": ["AI 会加渐变和立体感 → negative 必须写 gradient, shading, texture",
              "容易被做成包豪斯设计 → 加上 floating in white void, non-objective painting"],
 "sources": {"cleveland": ["malevich", "suprematism"], "met": ["malevich", "suprematism"],
             "commons": ["Kazimir Malevich painting", "Suprematist composition"]},
 "see_also": ["constructivism", "bauhaus", "minimalism-art"],
},
# ---------------------------------------------------------------- 构成主义
{
 "slug": "constructivism", "name_zh": "构成主义", "name_en": "Constructivism",
 "period": "1915–1935", "region": "俄国 / 苏联", "tier": "A",
 "one_liner": "艺术走出画框，去做海报、建筑和宣传：把画面变成工程。",
 "core": ["艺术进入生产：海报、书籍、舞台、建筑",
          "摄影蒙太奇与极端视角（仰视、斜角）",
          "红黑白三色 + 粗壮无衬线字体的宣传美学",
          "几何元素承担信息功能而非装饰"],
 "visual": {"色彩": "红、黑、白为主，偶尔加灰；极简高对比",
            "光影": "摄影蒙太奇的硬光；平面设计部分完全无光影",
            "笔触": "零笔触：照相拼贴、几何色块、模板字",
            "构图": "强烈对角线、极端仰视透视、倾斜的网格",
            "材质": "海报印刷、照片蒙太奇、钢材、玻璃、木构",
            "情绪": "激进、工业、乌托邦、宣传的号召力"},
 "palette": [("#C1272D","革命红"),("#111111","黑"),("#F2EDE4","白"),
             ("#8A8A85","工业灰"),("#C9A227","黄"),("#1F5FD6","蓝")],
 "artists": [("塔特林","1885–1953"),("罗德琴科","1891–1956"),
             ("波波娃","1889–1924"),("利西茨基","1890–1941"),("斯捷潘诺娃","1894–1958")],
 "prompt": {"style": "russian constructivism, photomontage, bold diagonal geometry, propaganda poster design, rodchenko, industrial typography",
            "lighting": "hard graphic contrast, photomontage cut-out edges, flat areas of colour",
            "color": "revolutionary red, black, white dominant, industrial grey, minimal palette",
            "composition": "aggressive diagonals, extreme low angle, tilted grid, asymmetric balance",
            "medium": "offset poster print, photo collage, steel and glass construction",
            "mood": "radical, industrial, utopian, agitational",
            "camera": "extreme low angle looking up, tilted dutch angle, wide lens"},
 "negative": "ornament, decorative flourishes, pastel, soft gradients, hand-drawn illustration, symmetry, sentimentality",
 "video": {"motion": "几何元素沿对角线快速位移、照片拼贴滑动",
           "camera": "快速的斜向推拉、仰视摇镜",
           "note": "构成主义的动是「机械的、有目的性的」，不要抒情"},
 "pitfalls": ["AI 会加装饰 → negative 写 ornament, decorative, pastel, hand-drawn",
              "把构成主义和至上主义混淆：构成主义有信息功能和社会目的，至上主义纯粹形而上"],
 "sources": {"cleveland": ["rodchenko", "constructivism", "lissitzky"],
             "met": ["rodchenko", "el lissitzky"], "commons": ["El Lissitzky poster", "Alexander Rodchenko photograph", "Varvara Stepanova design"]},
 "see_also": ["suprematism", "bauhaus", "de-stijl"],
},
# ---------------------------------------------------------------- 风格派
{
 "slug": "de-stijl", "name_zh": "风格派", "name_en": "De Stijl",
 "period": "1917–1931", "region": "荷兰", "tier": "A",
 "one_liner": "只用直线、直角和三原色，把世界简化成一个网格。",
 "core": ["新造型主义（Nieuwe Beelding）：只允许直线与直角",
          "红黄蓝 + 黑白灰，绝不用间色与曲线",
          "平面被黑线分割成不对称的矩形平衡",
          "绘画、家具、建筑共用同一套形式语言"],
 "visual": {"色彩": "三原色 + 黑、白、灰；极高纯度平涂",
            "光影": "完全没有，纯平面",
            "笔触": "零笔触；黑线是网格的骨架",
            "构图": "不对称的矩形网格、黑线分割、动态平衡",
            "材质": "布面油画、木构家具、彩色玻璃、混凝土",
            "情绪": "理性、秩序、平衡、冷静的和谐"},
 "palette": [("#D32027","红"),("#F2C300","黄"),("#1B4F9C","蓝"),
             ("#111111","黑线"),("#FFFFFF","白"),("#BFBFBF","灰")],
 "artists": [("蒙德里安","1872–1944"),("范杜斯堡","1883–1931"),
             ("里特费尔德","1888–1964"),("范德莱克","1876–1958")],
 "prompt": {"style": "de stijl, neoplasticism, mondrian grid, primary colours in rectangles bounded by black lines, asymmetric balance, pure abstraction",
            "lighting": "completely flat, no light, no shadow, no texture",
            "color": "primary red yellow blue with black white grey only, no intermediate hues",
            "composition": "asymmetric rectangular grid, black line armature, dynamic equilibrium",
            "medium": "oil on canvas, hard-edge flat paint, or wood and glass construction",
            "mood": "rational, ordered, balanced, cool harmony",
            "camera": "flat orthographic frontal, no perspective"},
 "negative": "curve, organic form, gradient, shading, texture, ornament, pastel, diagonal line",
 "video": {"motion": "色块在网格中替换、黑线缓慢生长",
           "camera": "static 平面构图；像版式动画",
           "note": "风格派只允许水平和垂直——任何旋转都是错的"},
 "pitfalls": ["AI 会加曲线和对角线 → negative 必须写 curve, organic form, diagonal line",
              "容易被做成包豪斯 → 包豪斯允许对角线和圆形，风格派只允许直角"],
 "sources": {"cleveland": ["mondrian", "de stijl"], "met": ["mondrian", "de stijl"],
             "commons": ["Piet Mondrian composition", "Theo van Doesburg painting"]},
 "see_also": ["bauhaus", "suprematism", "constructivism", "minimalism-art"],
},
# ---------------------------------------------------------------- 达达
{
 "slug": "dada", "name_zh": "达达主义", "name_en": "Dada",
 "period": "1916–1924", "region": "苏黎世 / 巴黎 / 纽约", "tier": "B",
 "one_liner": "反艺术：既然理性导致了战争，那就用荒诞把它拆掉。",
 "core": ["反艺术、反理性、反资产阶级",
          "现成品（readymade）：把日常物搬到展厅",
          "拼贴与偶然性（随机剪贴、掷骰子作画）",
          "挑衅与嘲讽代替审美"],
 "visual": {"色彩": "杂乱的现成印刷品色彩：报纸灰、票据色、旧照片的褐",
            "光影": "无统一光源；照片拼贴各元素自带不同光线",
            "笔触": "无笔触——剪贴、拼接、现成物",
            "构图": "刻意的混乱、偶然排布、元素互相不对齐",
            "材质": "报纸剪贴、照片蒙太奇、现成品、印刷品",
            "情绪": "荒诞、挑衅、虚无、黑色幽默"},
 "palette": [("#D9CFC0","报纸灰"),("#8B7A5A","旧纸褐"),("#111111","油墨黑"),
             ("#B03A2E","印章红"),("#5A6B7A","照片蓝"),("#E8DCC0","票据黄")],
 "artists": [("杜尚","1887–1968"),("阿尔普","1886–1966"),("施维特斯","1887–1948"),
             ("皮卡比亚","1879–1953"),("豪斯曼","1886–1971"),("霍赫","1889–1978")],
 "prompt": {"style": "dada collage, readymade, photomontage, deliberate absurdity, anti-art, random juxtaposition of printed matter",
            "lighting": "no unified light, each cut-out carries its own original lighting",
            "color": "newsprint grey, aged paper brown, ink black, stamp red, faded photo tones",
            "composition": "deliberate disorder, accidental arrangement, elements misaligned and colliding",
            "medium": "newspaper cut-out collage, photomontage, found object, printed ephemera",
            "mood": "absurd, provocative, nihilistic, blackly humorous",
            "camera": "flat scan-like frontal view, no depth"},
 "negative": "harmonious composition, beautiful rendering, classical beauty, balanced symmetry, polished painting, tasteful",
 "video": {"motion": "元素突然跳换位置、图像闪切、偶然的抖动",
           "camera": "不稳定的手持跳动、突然的跳切",
           "note": "达达的运动应该是「不连贯的」，平滑运镜是反效果的"},
 "pitfalls": ["AI 会把它做得太好看 → negative 写 harmonious, beautiful, tasteful, polished",
              "容易做成普通拼贴 → 加 readymade, absurdity, anti-art"],
 "sources": {"cleveland": ["dada", "schwitters", "arp"], "met": ["dada", "kurt schwitters"],
             "commons": ["Kurt Schwitters collage", "Hannah Hoch photomontage", "Jean Arp relief"]},
 "see_also": ["surrealism", "pop-art", "conceptual-art"],
},
# ---------------------------------------------------------------- 抽象表现主义
{
 "slug": "abstract-expressionism", "name_zh": "抽象表现主义", "name_en": "Abstract Expressionism",
 "period": "1943–1960", "region": "美国", "tier": "B",
 "one_liner": "画布变成行动的场地：笔触记录的是身体的运动，不是图像。",
 "core": ["行动绘画（action painting）：过程即作品",
          "尺幅巨大，观者被画面包围",
          "无中心、无焦点、满幅构图（all-over）",
          "抽象但承载强烈情绪与存在主义焦虑"],
 "visual": {"色彩": "两极：要么全黑白的书法性笔触，要么大面积的强烈色域",
            "光影": "无光源，画面自身是光的场域",
            "笔触": "滴洒、泼溅、横扫、厚涂；身体动作的痕迹",
            "构图": "满幅铺陈、无中心、无留白、边缘被突破",
            "材质": "巨大画布、工业油漆、厚涂与未打底画布",
            "情绪": "激烈、宏大、焦虑、原始的爆发"},
 "palette": [("#111111","漆黑"),("#D9CFC0","画布白"),("#B03A2E","血红"),
             ("#1F3A6B","深蓝"),("#C9A227","赭黄"),("#8A8A85","灰")],
 "artists": [("波洛克","1912–1956"),("德库宁","1904–1997"),("罗斯科","1903–1970"),
             ("克莱因","1910–1962"),("马瑟韦尔","1915–1991")],
 "prompt": {"style": "abstract expressionism, action painting, drip and splash technique, all-over composition, gestural mark making, existential intensity",
            "lighting": "no light source, the painted surface is itself a field of energy",
            "color": "either stark black and white calligraphic, or vast saturated colour fields",
            "composition": "all-over, no centre, no focal point, edges broken, monumental scale",
            "medium": "huge raw canvas, industrial enamel, thick impasto and poured paint",
            "mood": "violent, monumental, anxious, primal",
            "camera": "flat frontal, wide, filling the whole frame with surface"},
 "negative": "representational subject, focal point, delicate detail, fine brushwork, pastel, decorative, symmetrical",
 "video": {"motion": "颜料持续滴落飞溅、笔触生长、色彩涌动",
           "camera": "缓慢 push in 到画布表面，或 static 让表面自身运动",
           "note": "重点是「身体动作的痕迹」，可以暗示画外的手"},
 "pitfalls": ["AI 容易做成随意涂鸦 → 加 gesture, drip and splash, all-over composition, monumental scale",
              "版权：1950 年后作品基本都在版权期内，仓库只存提示词"],
 "sources": {"cleveland": ["abstract expressionism"], "met": ["abstract expressionism"],
             "commons": []},
 "see_also": ["color-field", "expressionism", "dada"],
},
# ---------------------------------------------------------------- 色域绘画
{
 "slug": "color-field", "name_zh": "色域绘画", "name_en": "Color Field",
 "period": "1948–1970", "region": "美国", "tier": "B",
 "one_liner": "把颜色铺满整张画布，让你站在它面前被颜色淹没。",
 "core": ["大面积单一色域，取消笔触与形象",
          "色彩关系本身即内容（罗斯科、纽曼）",
          "尺幅巨大，制造沉浸式的身体体验",
          "与抽象表现主义同源但转向平静与冥想"],
 "visual": {"色彩": "柔和的边缘模糊的大色块；罗斯科式的层叠色晕",
            "光影": "色彩自身发光，边缘互相渗透产生光晕",
            "笔触": "被抹平或被染色（staining），几乎看不到手",
            "构图": "满幅或对称的色块分割，无中心焦点",
            "材质": "巨大画布、稀释丙烯渗染、多层薄涂",
            "情绪": "沉静、崇高、冥想的重量、情绪压迫"},
 "palette": [("#8B3A3A","暗红"),("#2B3A5A","深蓝"),("#C9A227","赭金"),
             ("#4A3A3A","褐黑"),("#D9A25A","暖橙"),("#8A7A7A","灰紫")],
 "artists": [("罗斯科","1903–1970"),("纽曼","1905–1970"),("斯蒂尔","1904–1980"),
             ("路易斯","1912–1962"),("诺兰","1924–2010")],
 "prompt": {"style": "color field painting, rothko style, vast soft-edged colour rectangles, stained canvas, meditative abstraction, sublime scale",
            "lighting": "colour emits its own glow, edges bleed into each other, no external light",
            "color": "layered translucent hues, dark red, deep blue, ochre, warm orange, soft blurred boundaries",
            "composition": "full-field or stacked colour blocks, no focal point, monumental scale",
            "medium": "huge canvas, thinned acrylic soaked into raw fabric, many thin translucent layers",
            "mood": "still, sublime, meditative weight, emotional pressure",
            "camera": "flat frontal, extreme close, surface filling the frame"},
 "negative": "representational, hard edges, visible gestural brushwork, small scale, busy detail, figurative",
 "video": {"motion": "色块缓慢呼吸般的明暗变化、颜色互相渗透",
           "camera": "极缓 push in 直到颜色充满画面",
           "note": "几乎没有运动——色域绘画的动是「呼吸」"},
 "pitfalls": ["AI 会加笔触和细节 → negative 写 visible gestural brushwork, busy detail",
              "版权：罗斯科、纽曼作品均在版权期内，只存提示词"],
 "sources": {"cleveland": ["color field painting"], "met": ["color field"], "commons": []},
 "see_also": ["abstract-expressionism", "minimalism-art", "tonalism"],
},
# ---------------------------------------------------------------- 欧普艺术
{
 "slug": "op-art", "name_zh": "欧普艺术", "name_en": "Op Art",
 "period": "1960–1975", "region": "欧美", "tier": "B",
 "one_liner": "用几何图案骗你的眼睛：画面不动，但你觉得它在抖、在转、在陷进去。",
 "core": ["利用视觉错觉：摩尔纹、闪烁、深度反转",
          "黑白高对比条纹与网格是经典手法",
          "观众的眼睛成为作品的组成部分",
          "与设计、时尚、平面广告高度互通"],
 "visual": {"色彩": "常为纯黑白，或极高对比的互补色（红/绿、蓝/橙）",
            "光影": "无真实光影，错觉本身制造出「光」",
            "笔触": "零笔触，机械般精确的几何线条",
            "构图": "重复的网格、同心圆、波浪条纹，满幅铺陈",
            "材质": "布面丙烯、丝网印、印刷品、装置",
            "情绪": "眩晕、眩晕后的愉悦、视觉的亢奋"},
 "palette": [("#111111","黑"),("#FFFFFF","白"),("#D32027","红"),
             ("#1B7A4A","绿"),("#1B4F9C","蓝"),("#F2A93B","橙")],
 "artists": [("瓦萨雷里","1906–1997"),("布里奇特·赖利","1931–"),
             ("彭斯","1928–"),("阿纳斯基维茨","1930–"),("克鲁兹-迭斯","1923–2019")],
 "prompt": {"style": "op art, optical illusion, moire interference pattern, high contrast geometric repetition, retinal vibration, bridget riley style",
            "lighting": "no real light, the illusion pattern itself generates apparent light and depth",
            "color": "usually pure black and white, or maximum contrast complementary pairs",
            "composition": "repeating grid, concentric circles, wave stripes, full-field all-over",
            "medium": "acrylic on canvas, silkscreen print, mechanically precise geometry",
            "mood": "dizzying, hypnotic, retinal excitement, playful disorientation",
            "camera": "flat frontal, no depth of field, pattern fills the frame"},
 "negative": "visible brushwork, texture, soft shading, representational subject, asymmetry, muted colour",
 "video": {"motion": "图案滚动、缩放、相位偏移制造闪烁",
           "camera": "缓慢 push in 或 pan，让摩尔纹自然产生",
           "note": "欧普的动必须由图案相位变化产生，不是物体移动"},
 "pitfalls": ["AI 很难做出真正的错觉 → 加 mathematically precise, moire, interference, retinal vibration",
              "容易画成普通条纹 → 强调 optical illusion, perceptual effect"],
 "sources": {"cleveland": ["op art", "vasarely"], "met": ["op art", "victor vasarely"], "commons": []},
 "see_also": ["pop-art", "islamic-geometric", "bauhaus"],
},
# ---------------------------------------------------------------- 波普艺术
{
 "slug": "pop-art", "name_zh": "波普艺术", "name_en": "Pop Art",
 "period": "1955–1970", "region": "英国 / 美国", "tier": "B",
 "one_liner": "把广告、漫画和罐头汤搬进美术馆：商业图像就是时代的神话。",
 "core": ["挪用大众媒介图像（广告、漫画、商品）",
          "丝网印刷、机械复制，取消手工痕迹",
          "鲜艳的平涂色块 + 粗黑轮廓",
          "讽刺消费社会，同时拥抱它"],
 "visual": {"色彩": "高饱和平涂：荧光粉、亮黄、青蓝、正红，常并置夸张",
            "光影": "无光影，平涂色块 + 黑色轮廓线",
            "笔触": "零笔触（丝网印），或刻意的商业插画式平涂",
            "构图": "重复网格（同一图像反复排列）、特写裁切",
            "材质": "丝网印、丙烯、商业印刷品、拼贴",
            "情绪": "明快、讽刺、冷感、消费主义的眩晕"},
 "palette": [("#F23D8E","荧光粉"),("#F2C230","亮黄"),("#29ABE2","青蓝"),
             ("#D32027","正红"),("#111111","轮廓黑"),("#FFFFFF","白")],
 "artists": [("沃霍尔","1928–1987"),("利希滕斯坦","1923–1997"),
             ("汉密尔顿","1922–2011"),("罗森奎斯特","1933–2017"),("韦塞尔曼","1931–2004")],
 "prompt": {"style": "pop art, silkscreen print, commercial imagery appropriation, ben-day dots, flat saturated colour with bold black outline, repetition grid",
            "lighting": "no shading, flat colour areas bounded by heavy black line",
            "color": "high saturation flat fills, fluorescent pink, bright yellow, cyan, red, unmodulated",
            "composition": "repeated image grid, tight commercial crop, centred product-shot framing",
            "medium": "silkscreen print on canvas, acrylic, commercial offset printing",
            "mood": "bright, ironic, cool, consumerist dazzle",
            "camera": "flat frontal, tight crop, no depth"},
 "negative": "visible brushwork, impasto, naturalistic shading, muted earthy colour, classical composition, painterly texture",
 "video": {"motion": "同一图像快速重复替换、色板轮换",
           "camera": "static 平面；节奏感来自图像的切换",
           "note": "波普的动是「复制和重复」，像印刷机在运行"},
 "pitfalls": ["AI 会加手工笔触 → negative 写 visible brushwork, impasto, painterly",
              "版权：波普作品几乎全在版权期内，只存提示词"],
 "sources": {"cleveland": ["pop art"], "met": ["pop art"], "commons": []},
 "see_also": ["dada", "op-art", "conceptual-art"],
},
# ---------------------------------------------------------------- 极简主义
{
 "slug": "minimalism-art", "name_zh": "极简主义（艺术）", "name_en": "Minimalism",
 "period": "1960–1975", "region": "美国", "tier": "B",
 "one_liner": "去掉一切：不叙事、不隐喻、不修饰，只留下物本身。",
 "core": ["减法到只剩最基本的几何体与工业材料",
          "拒绝叙事、象征与艺术家手迹",
          "强调物体与观众所处的真实空间关系",
          "重复与序列（seriality）代替构图"],
 "visual": {"色彩": "工业色：灰、黑、白、荧光灯管的冷白，或单一鲜艳工业漆",
            "光影": "真实光线作用于真实物体表面，而非画出来的光",
            "笔触": "零笔触，工业制造的光滑表面",
            "构图": "单一几何体、重复序列、对称或严格等距排列",
            "材质": "胶合板、有机玻璃、荧光灯管、耐候钢、工业漆",
            "情绪": "冷静、中立、去情绪化、现象学的在场"},
 "palette": [("#8A8A85","工业灰"),("#111111","黑"),("#FFFFFF","白"),
             ("#C9CFD4","冷白灯"),("#F2C230","荧光黄"),("#4A7C9E","钢蓝")],
 "artists": [("贾德","1928–1994"),("安德烈","1935–"),("弗莱文","1933–1996"),
             ("马丁","1912–2004"),("勒维特","1928–2007")],
 "prompt": {"style": "minimalism art, industrial fabrication, single geometric form, serial repetition, no narrative, donald judd and dan flavin",
            "lighting": "real fluorescent light on real surfaces, or cool even studio light, no painted light",
            "color": "industrial grey, black, white, cold fluorescent glow, or one saturated industrial lacquer",
            "composition": "single geometric body, serial repetition, strict equidistant arrangement, symmetry",
            "medium": "plywood, plexiglass, fluorescent tube, weathering steel, industrial lacquer",
            "mood": "cool, neutral, de-emotionalised, phenomenological presence",
            "camera": "flat frontal, straight-on, neutral studio framing"},
 "negative": "ornament, narrative content, expressive brushwork, texture, decoration, metaphor, warm cosy atmosphere",
 "video": {"motion": "几乎无运动；只有荧光灯的闪烁或极缓慢的镜头位移",
           "camera": "极缓的直线平移，或 static",
           "note": "极简主义的体验来自身体在空间中的移动，不是画面的运动"},
 "pitfalls": ["AI 会加质感与细节 → negative 写 texture, ornament, expressive brushwork",
              "版权：几乎全在版权期内，只存提示词"],
 "sources": {"cleveland": ["minimalism art"], "met": ["minimalism"], "commons": []},
 "see_also": ["de-stijl", "suprematism", "color-field", "minimalist-design"],
},
# ---------------------------------------------------------------- 观念艺术
{
 "slug": "conceptual-art", "name_zh": "观念艺术", "name_en": "Conceptual Art",
 "period": "1965–1980", "region": "欧美", "tier": "B",
 "one_liner": "想法比物体重要：作品可以是一段文字、一次行动、一份说明书。",
 "core": ["观念本身即作品，物质形态可被省略",
          "文字、指令、档案、文件成为主要媒介",
          "质疑艺术制度、作者身份与市场",
          "去技能化（deskilling）：不需要手工技巧"],
 "visual": {"色彩": "常为档案的中性色：白纸、灰、黑；或照片的记录色",
            "光影": "记录性摄影的平光，无审美化处理",
            "笔触": "无；文字排版、打字机、复印件",
            "构图": "文献式排版、说明文字、极简的图示",
            "材质": "文字、照片、复印件、档案文件、录像",
            "情绪": "冷静、智性、质疑、去审美化"},
 "palette": [("#E8E4DA","档案白"),("#8A8A85","灰"),("#111111","打字黑"),
             ("#5A6B7A","复印件蓝"),("#B03A2E","标记红"),("#D9CFC0","旧纸")],
 "artists": [("科苏斯","1945–"),("韦纳","1942–2007"),("许布勒","1924–1997"),
             ("巴尔代萨里","1931–2020"),("布罗德萨","1940–1994")],
 "prompt": {"style": "conceptual art documentation, text as artwork, typed instruction, archival photograph, institutional critique, deskilled presentation",
            "lighting": "flat documentary light, unglamorous, no aesthetic lighting",
            "color": "neutral archival tones, paper white, grey, typewriter black, photocopy blue",
            "composition": "documentary framing, text panel, minimal diagrammatic layout",
            "medium": "typewritten text, photograph, photocopy, file document, video documentation",
            "mood": "cool, intellectual, questioning, deliberately un-aesthetic",
            "camera": "flat documentary frontal, neutral framing"},
 "negative": "beautiful rendering, expressive brushwork, dramatic lighting, decorative, romantic, painterly craft",
 "video": {"motion": "文字逐行打出、档案页翻动；克制的记录性运动",
           "camera": "static 记录镜头；不要审美化的运镜",
           "note": "观念艺术的力量在「不表演」——任何炫技都削弱它"},
 "pitfalls": ["AI 会把它做得太好看到失去观念性 → negative 写 beautiful rendering, dramatic lighting",
              "版权：全在版权期内，只存提示词"],
 "sources": {"cleveland": ["conceptual art"], "met": ["conceptual art"], "commons": []},
 "see_also": ["minimalism-art", "dada", "pop-art"],
},
# ---------------------------------------------------------------- 照相写实
{
 "slug": "photorealism", "name_zh": "照相写实主义", "name_en": "Photorealism",
 "period": "1968–1985", "region": "美国", "tier": "B",
 "one_liner": "照着照片画到比照片还清楚：把摄影的冷感放大到令人不安。",
 "core": ["以照片为唯一依据，追求摄影般的清晰与客观",
          "常放大到巨大尺幅，暴露照片的缺陷（失焦、过曝）",
          "取消个人笔触与情感表达",
          "玻璃反射、霓虹、镀铬、都市街景是常见母题"],
 "visual": {"色彩": "摄影式的准确色，高饱和的都市霓虹与镀铬反光",
            "光影": "完全复制照片的光：闪光灯、橱窗反光、夜间霓虹",
            "笔触": "肉眼不可见，极致平滑；或刻意保留喷枪的均匀",
            "构图": "摄影取景框、浅景深、裁切随意",
            "材质": "布面油画或丙烯、喷枪、极致平滑的表面",
            "情绪": "冷静、疏离、消费社会的空洞、技术性的震撼"},
 "palette": [("#29ABE2","霓虹蓝"),("#F23D8E","霓虹粉"),("#C9CFD4","铬银"),
             ("#2B2B33","夜黑"),("#C9A227","橱窗金"),("#E8E4DA","闪光白")],
 "artists": [("埃斯蒂斯","1932–"),("戈因斯","1928–"),("克洛斯","1940–2021"),
             ("汉森","1925–1996"),("弗拉克","1931–")],
 "prompt": {"style": "photorealism, hyperrealistic painting from photograph, extreme surface detail, chrome and glass reflection, chuck close and richard estes",
            "lighting": "exactly copied photographic light, flash, window reflection, neon at night",
            "color": "photographically accurate, saturated urban neon, chrome silver, precise colour",
            "composition": "camera viewfinder framing, shallow depth of field, casual crop",
            "medium": "oil or acrylic on canvas, airbrush, invisible brushwork, glass-smooth surface",
            "mood": "cool, alienated, consumerist emptiness, technical astonishment",
            "camera": "50mm photographic framing, shallow depth of field, precise perspective"},
 "negative": "visible brushwork, impressionist, loose gesture, expressive colour, soft focus, painterly abstraction",
 "video": {"motion": "玻璃反光流动、霓虹闪烁、镜头极缓平移",
           "camera": "steadiest possible slow dolly；像摄影机的凝视",
           "note": "照相写实的动必须「像镜头」，绝不能像画笔"},
 "pitfalls": ["AI 会加绘画感 → negative 写 visible brushwork, painterly, loose gesture",
              "和超现实主义区分：照相写实没有荒诞元素，只有客观记录"],
 "sources": {"cleveland": ["photorealism"], "met": ["photorealism"], "commons": []},
 "see_also": ["pop-art", "realism", "surrealism"],
},
# ---------------------------------------------------------------- 大地艺术
{
 "slug": "land-art", "name_zh": "大地艺术", "name_en": "Land Art",
 "period": "1968–1980", "region": "美国 / 英国", "tier": "B",
 "one_liner": "走出美术馆，在沙漠和盐湖上挖出巨大的几何形状——只能从空中看见。",
 "core": ["作品在自然中，尺幅巨大，无法被收藏",
          "只有照片和影像留作记录",
          "几何干预自然地貌，强调时间与侵蚀",
          "反商业、反博物馆体制"],
 "visual": {"色彩": "自然材料的本色：土黄、盐白、岩灰、沥青黑",
            "光影": "自然光为主，航拍视角下的长阴影强化几何形状",
            "笔触": "无笔触；推土机与工程机械的作业痕迹",
            "构图": "航拍俯瞰、巨大几何形（螺旋、直线、圆）嵌入地貌",
            "材质": "泥土、盐湖、岩石、玄武岩、混凝土、钢管",
            "情绪": "宏大、崇高、时间感、人类尺度的渺小"},
 "palette": [("#C98A4A","土黄"),("#E8E4DA","盐白"),("#8A7A6A","岩灰"),
             ("#2B2B33","沥青黑"),("#4A7C9E","湖水蓝"),("#A8432A","赭红")],
 "artists": [("史密森","1938–1973"),("克里斯托","1935–2020"),
             ("让娜-克劳德","1935–2009"),("海泽","1944–"),("朗","1944–")],
 "prompt": {"style": "land art, earthwork, monumental geometry carved into landscape, aerial documentary photograph, smithson spiral jetty",
            "lighting": "natural sunlight, long raking shadows revealing geometry, aerial perspective",
            "color": "raw natural material colour, ochre earth, salt white, rock grey, asphalt black",
            "composition": "aerial overhead view, huge geometric form embedded in terrain, vast scale",
            "medium": "earth, salt lake, rock, concrete, steel pipe, documentary photograph",
            "mood": "monumental, sublime, temporal, human insignificance",
            "camera": "aerial drone shot, top-down, extreme wide, infrastructure scale"},
 "negative": "indoor gallery, small scale, decorative, close-up portrait, painterly, ornate",
 "video": {"motion": "缓慢航拍移动揭示几何全貌、水面波动、云影掠过大地",
           "camera": "缓慢 aerial push out 揭示尺度，或高空环绕",
           "note": "大地艺术的动必须是航拍——尺度感来自空中视角"},
 "pitfalls": ["AI 容易做成普通风景 → 加 monumental geometry, earthwork, aerial view, human intervention",
              "版权：多数有影像版权，只存提示词"],
 "sources": {"cleveland": ["land art"], "met": ["land art", "earth art"], "commons": []},
 "see_also": ["conceptual-art", "minimalism-art", "hudson-river-school"],
},
# ---------------------------------------------------------------- 超扁平
{
 "slug": "superflat", "name_zh": "超扁平", "name_en": "Superflat",
 "period": "1990–今", "region": "日本", "tier": "B",
 "one_liner": "把动漫、浮世绘和消费文化压成同一个平面：可爱与暴力没有边界。",
 "core": ["消除高雅与低俗、艺术与动漫的界限",
          "极致的平面性，继承浮世绘的装饰传统",
          "可爱（kawaii）与黑暗、情色、暴力并置",
          "高饱和平涂 + 明确的轮廓线"],
 "visual": {"色彩": "高饱和平涂：荧光粉、亮蓝、柠檬黄；对比强烈",
            "光影": "完全平面，无体积光；靠色块区分",
            "笔触": "零笔触，数码或喷绘般的均匀平涂 + 硬轮廓",
            "构图": "满版、重复、图案化；人物与图案无层级差别",
            "材质": "丙烯、数码打印、雕塑、周边商品",
            "情绪": "可爱与不安并存、消费主义的眩晕、虚无"},
 "palette": [("#F23D8E","荧光粉"),("#29ABE2","亮蓝"),("#F2E33D","柠檬黄"),
             ("#111111","轮廓黑"),("#7B3FA0","紫"),("#FFFFFF","平涂白")],
 "artists": [("村上隆","1962–"),("奈良美智","1959–"),("会田诚","1965–"),
             ("青岛千穗","1974–"),("Mr.","1969–")],
 "prompt": {"style": "superflat, takashi murakami, japanese pop surrealism, anime-influenced flat colour, kawaii with dark undertone, decorative repetition",
            "lighting": "completely flat, no volume, colour separated by hard outline",
            "color": "high saturation flat fills, fluorescent pink, bright cyan, lemon yellow, strong contrast",
            "composition": "all-over patterning, repeated motifs, no hierarchy between figure and pattern",
            "medium": "acrylic on canvas, digital print, vinyl sculpture, merchandise surface",
            "mood": "cute and unsettling at once, consumerist vertigo, nihilistic",
            "camera": "flat frontal, no depth of field"},
 "negative": "realistic shading, oil impasto, classical composition, muted colour, perspective depth, gritty texture",
 "video": {"motion": "图案循环流动、角色重复增生、花朵开合",
           "camera": "static 或极缓 zoom；让图案自身动",
           "note": "超扁平的动是「图案的无限增殖」"},
 "pitfalls": ["AI 会加立体和阴影 → negative 写 realistic shading, perspective depth",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": [], "met": [], "commons": []},
 "see_also": ["ukiyo-e", "pop-art", "anime-cel"],
},
# ---------------------------------------------------------------- 新表现主义
{
 "slug": "neo-expressionism", "name_zh": "新表现主义", "name_en": "Neo-Expressionism",
 "period": "1978–1990", "region": "德国 / 美国 / 意大利", "tier": "B",
 "one_liner": "在观念艺术之后重新拿起画笔：大幅、粗野、情绪外露的形象回归。",
 "core": ["回归具象与绘画性，反对极简与观念的冷",
          "粗野、快速、近乎暴力的笔触",
          "神话、历史、身体、政治作为题材",
          "大尺幅，强调物质性与手感"],
 "visual": {"色彩": "泥泞的强烈色：土黄、暗红、脏绿，暴力地堆叠",
            "光影": "无统一光源，明暗为情绪服务",
            "笔触": "极厚 impasto、刮擦、倾倒；材料本身可见",
            "构图": "失衡、粗暴、形象在画面中被撕扯",
            "材质": "巨大画布、厚涂颜料、现成材料拼贴",
            "情绪": "愤怒、痛苦、狂躁、历史的重量"},
 "palette": [("#A8432A","暗红"),("#C9A227","土黄"),("#4A5A3A","脏绿"),
             ("#2B2B33","焦黑"),("#8B5E2A","泥褐"),("#D9CFC0","生白")],
 "artists": [("巴塞利茨","1938–"),("基弗","1945–"),("伊门多夫","1945–2007"),
             ("克莱门特","1952–"),("施纳贝尔","1951–")],
 "prompt": {"style": "neo-expressionism, raw figurative painting, violent impasto, mythological and historical subject, anselm kiefer and georg baselitz",
            "lighting": "no unified light source, chiaroscuro serving emotion rather than description",
            "color": "muddy intense colour, dark red, ochre, dirty green, burnt black, violent layering",
            "composition": "unbalanced and brutal, figure torn across the picture plane",
            "medium": "huge canvas, extremely thick impasto, scraping, poured paint, found materials",
            "mood": "angry, anguished, manic, weighted by history",
            "camera": "eye-level, wide, coarse texture visible"},
 "negative": "clean minimal, flat design, delicate detail, pastel, digital smoothness, cool detachment",
 "video": {"motion": "粗野的笔触生长、材料剥落、画面被撕扯",
           "camera": "handheld 粗粝推进；不要平滑的滑轨",
           "note": "新表现主义的动应该粗鲁、不稳定"},
 "pitfalls": ["AI 会清理画面 → negative 写 clean minimal, digital smoothness",
              "版权：全部在版权期内，只存提示词"],
 "sources": {"cleveland": ["neo-expressionism"], "met": ["neo-expressionism"], "commons": []},
 "see_also": ["expressionism", "abstract-expressionism", "dada"],
},
]

ARTIST_KEYS = {
 "fauvism": ["matisse", "derain", "vlaminck", "dufy", "marquet", "camoin", "manguin", "friesz", "fauvism", "fauve"],
 "der-blaue-reiter": ["kandinsky", "franz marc", "macke", "muenter", "münter", "klee",
                       "jawlensky", "blauer reiter", "blue rider"],
 "futurism": ["balla", "boccioni", "severini", "carra", "carrà", "russolo",
               "soffici", "pratella", "sant'elia", "futuris"],
 "orphism": ["delaunay", "kupka", "sonia delaunay", "picabia", "orphism", "orphique"],
 "suprematism": ["malevich", "lissitzky", "kljun", "kliun", "suedeikin", "suetin",
                  "suprematis", "black square"],
 "constructivism": ["tatlin", "rodchenko", "popova", "lissitzky", "lissitsky", "stepanova",
                     "stiepanova", "rozanova", "klutsis", "constructivis", "constructivist"],
 "de-stijl": ["mondrian", "van doesburg", "rietveld", "van der leck", "vantongerloo",
               "de stijl", "neoplasticism"],
 "dada": ["duchamp", "arp", "schwitters", "picabia", "hausmann", "hoch", "höch",
           "tristan tzara", "man ray", "dada"],
 "abstract-expressionism": ["pollock", "de kooning", "rothko", "kline", "motherwell",
                             "gorky", "hofmann", "still", "newman"],
 "color-field": ["rothko", "newman", "still", "louis", "noland", "olitski", "frankenthaler"],
 "op-art": ["vasarely", "riley", "poons", "anuskiewicz", "cruz-diez", "op art"],
 "pop-art": ["warhol", "lichtenstein", "hamilton", "rosenquist", "wesselmann",
              "oldenburg", "indiana", "hockney"],
 "minimalism-art": ["judd", "andre", "flavin", "martin", "le wit", "lewitt", "morris",
                     "serra", "nauman"],
 "conceptual-art": ["kossuth", "kosuth", "weiner", "huebler", "baldessari", "brodthaers",
                     "broodthaers", "art & language"],
 "photorealism": ["estes", "goings", "close", "hanson", "flack", "cottingham",
                   "bechtle", "eddy"],
 "land-art": ["smithson", "christo", "jeanne-claude", "heizer", "long", "de maria",
               "holt", "earthwork", "land art"],
 "superflat": ["murakami", "nara", "aida", "aoshima", "mr.", "superflat"],
 "neo-expressionism": ["baselitz", "kiefer", "immendorff", "clemente", "schnabel",
                        "lupertz", "penck", "chia", "cucchi"],
}
