# -*- coding: utf-8 -*-
"""流派定义 —— 西方古典与近代扩展（16 个）。"""

CATEGORY = "西方古典与近代"

MOVEMENTS = [
# ---------------------------------------------------------------- 拜占庭
{
 "slug": "byzantine", "name_zh": "拜占庭艺术", "name_en": "Byzantine Art",
 "period": "330–1453", "region": "东罗马 / 东正教世界", "tier": "A",
 "one_liner": "放弃写实，用金底和正面律把人间变成永恒的神圣空间。",
 "core": ["金色背景取代真实空间，人物悬浮而非站立",
          "正面律（frontal）：圣像直视观者，不做透视缩短",
          "严格的图像程序（iconography），姿势和手势都有固定含义",
          "平面化、装饰化，拒绝自然主义解剖"],
 "visual": {"色彩": "金箔底 + 朱红、群青、祖母绿；高纯度平涂，极少过渡",
            "光影": "无光源、无投影——光来自金色本身，是神性的而非物理的",
            "笔触": "细腻平涂 + 硬边轮廓；镶嵌画则是马赛克颗粒的硬质闪烁",
            "构图": "中轴对称、等级比例（重要的人物画得更大）、平面排列",
            "材质": "金箔木板蛋彩、玻璃马赛克、湿壁画、象牙",
            "情绪": "庄严、超验、静穆、非人间的永恒感"},
 "palette": [("#C9A227","金箔"),("#8E1B1B","朱红"),("#1F3A8A","群青"),
             ("#1E6B4F","祖母绿"),("#6B3FA0","紫"),("#2B2B33","炭黑")],
 "artists": [("西奈山圣像画师","6世纪"),("狄奥法内斯","1340–1410"),
             ("鲁布廖夫","1360–1428"),("克里特画派","15–17世纪")],
 "prompt": {"style": "byzantine icon painting, gold leaf background, flattened sacred space, frontal hieratic figures, mosaic tessellation",
            "lighting": "no physical light source, no cast shadows, luminous gold ground, unmodulated divine glow",
            "color": "gold ground with vermilion, ultramarine, emerald, high purity flat colour, almost no blending",
            "composition": "central axis symmetry, hierarchical scale, flat frontal arrangement, no perspective",
            "medium": "egg tempera on gold-leafed wood panel, glass mosaic tesserae, gesso relief",
            "mood": "solemn, transcendent, eternal, otherworldly stillness",
            "camera": "flat frontal view, orthographic, no depth of field"},
 "negative": "perspective, cast shadows, realistic anatomy, 3d render, moving figures, modern clothing, photographic",
 "video": {"motion": "几乎完全静止；只有烛光在金箔上流动、香烟缓慢上升",
           "camera": "static shot，绝不移动；任何运镜都会破坏圣像的永恒感",
           "note": "拜占庭要的是「不动的画」——加运动就变成奇幻片"},
 "pitfalls": ["AI 会自动加透视和阴影 → 必须写 no perspective, no cast shadows, flat frontal",
              "金底容易被做成黄色背景 → 要写 gold leaf ground, luminous, mosaic"],
 "sources": {"cleveland": ["byzantine icon", "byzantine mosaic"],
             "met": ["byzantine icon", "byzantine"], "commons": ["Byzantine icon gold"]},
 "see_also": ["gothic", "early-netherlandish"],
},
# ---------------------------------------------------------------- 罗马式
{
 "slug": "romanesque", "name_zh": "罗马式艺术", "name_en": "Romanesque",
 "period": "1000–1150", "region": "西欧", "tier": "A",
 "one_liner": "厚重的墙、粗壮的比例、扭曲而有力的人物——为教堂服务的严肃艺术。",
 "core": ["形体厚重、比例拉长或扭曲，不为美服务而为表达服务",
          "壁画与手抄本装饰以粗轮廓和强烈色块为主",
          "叙事性图像程序：圣经故事按空间顺序铺满墙面",
          "拒绝古典解剖，回到象征性的有力造型"],
 "visual": {"色彩": "赭红、土黄、暗绿、群青；色块分明，颜料多为矿物",
            "光影": "几乎无立体塑造，只有轮廓和色块；光来自建筑本身",
            "笔触": "粗犷、直接、有力；线条比调子重要",
            "构图": "带状叙事排列、填满不留白、中轴象征性布局",
            "材质": "湿壁画、木板蛋彩、彩绘手抄本羊皮纸、石雕",
            "情绪": "严肃、虔敬、有力、略带粗野"},
 "palette": [("#9C4A2A","赭红"),("#C9A227","土黄"),("#3E5A3A","暗绿"),
             ("#2B3E6B","群青"),("#6B4A2A","褐"),("#E8DCC0","羊皮纸米")],
 "artists": [("加泰罗尼亚壁画师","12世纪"),("圣萨文修道院画师","11世纪"),
             ("温彻斯特圣经画师","12世纪"),("希尔德斯海姆作坊","11世纪")],
 "prompt": {"style": "romanesque fresco, medieval manuscript illumination, heavy distorted figures, bold outline, flat symbolic colour",
            "lighting": "no modelling, no realistic light, flat areas of colour, contour defines form",
            "color": "mineral earth palette, ochre red, earth yellow, dark green, ultramarine, parchment cream",
            "composition": "banded narrative frieze, horror vacui, symbolic central axis, no perspective",
            "medium": "wall fresco, egg tempera on panel, illuminated parchment, gesso",
            "mood": "solemn, devout, vigorous, slightly crude",
            "camera": "flat frontal view, no depth"},
 "negative": "classical anatomy, perspective, sfumato, polished finish, 3d render, soft gradients, photorealistic",
 "video": {"motion": "几近静止；火焰、旗帜、衣褶有粗重的摆动",
           "camera": "static 或极缓横向 pan，模仿壁画带叙事",
           "note": "罗马式的动应该是「笨重的」，不要流体感"},
 "pitfalls": ["AI 会把它做成文艺复兴 → negative 写 perspective, classical anatomy, sfumato",
              "色彩容易过艳 → 用矿物土色并压饱和"],
 "sources": {"cleveland": ["romanesque", "romanesque fresco"],
             "met": ["romanesque"], "commons": ["Sant Climent de Taull fresco", "Romanesque fresco Spain", "Romanesque capital sculpture"]},
 "see_also": ["byzantine", "gothic"],
},
# ---------------------------------------------------------------- 哥特式
{
 "slug": "gothic", "name_zh": "哥特式艺术", "name_en": "Gothic Art",
 "period": "1150–1450", "region": "西欧", "tier": "A",
 "one_liner": "让光穿过彩色玻璃，把石头变成骨架，让一切向上生长。",
 "core": ["垂直线条主导，一切向上升腾",
          "彩色玻璃把光染成宝石色，是哥特真正的光源",
          "从平面象征走向自然观察，逐渐出现体积与情感",
          "国际哥特式的优雅曲线与华丽服饰"],
 "visual": {"色彩": "宝石玻璃色：深蓝、猩红、金、翠绿；深底上的发光色块",
            "光影": "透过彩色玻璃的散射光，彩色光斑落在石地上",
            "笔触": "手抄本为精细平涂 + 金箔；晚期面板画出现柔和体积",
            "构图": "垂直升腾、尖拱、玫瑰窗的放射对称",
            "材质": "彩绘玻璃、木板蛋彩、金箔、石雕、羊皮纸",
            "情绪": "神秘、虔敬、华丽、向上的渴望"},
 "palette": [("#1B3A6B","玻璃深蓝"),("#8E1B1B","猩红"),("#C9A227","金"),
             ("#1E6B4F","翠绿"),("#4A3B6B","紫"),("#2B2B33","石影黑")],
 "artists": [("林堡兄弟","1400–1416"),("杜乔","1255–1319"),
             ("西莫内·马蒂尼","1284–1344"),("扬·范艾克","1390–1441")],
 "prompt": {"style": "gothic art, stained glass window, international gothic elegance, elongated vertical figures, gold leaf detail",
            "lighting": "coloured light filtering through stained glass, luminous jewel-toned glow, shafts of tinted light",
            "color": "jewel glass palette, deep sapphire blue, crimson, gold, emerald, rich and luminous",
            "composition": "strong verticality, pointed arch framing, rose window radial symmetry",
            "medium": "stained glass, egg tempera on panel, gold leaf, illuminated parchment",
            "mood": "mystical, devotional, ornate, yearning upward",
            "camera": "low angle looking up, vertical composition, wide shot"},
 "negative": "horizontal composition, flat modern lighting, neon, digital, minimalism, casual contemporary setting",
 "video": {"motion": "光斑缓慢移动（模拟日光位移）、烛火、衣袍轻摆",
           "camera": "缓慢 tilt up 沿垂直线上升",
           "note": "哥特的运动核心是「光在动」，不是人在动"},
 "pitfalls": ["AI 会做成暗黑哥特亚文化 → 明确写 stained glass, jewel tones, devotional",
              "容易丢掉垂直性 → composition 里写 strong verticality, pointed arch"],
 "sources": {"cleveland": ["gothic art", "stained glass"], "met": ["gothic art", "gothic stained glass"],
             "commons": ["Giotto fresco", "Cimabue painting", "Gothic stained glass window", "Duccio painting"]},
 "see_also": ["byzantine", "early-netherlandish", "romanesque"],
},
# ---------------------------------------------------------------- 早期尼德兰
{
 "slug": "early-netherlandish", "name_zh": "早期尼德兰绘画", "name_en": "Early Netherlandish",
 "period": "1420–1550", "region": "佛兰德斯 / 荷兰", "tier": "A",
 "one_liner": "油画技术的发明者：用一层层透明釉把布料的每一根毛都画出来。",
 "core": ["油性媒介的早期掌握者，能画出前所未有的细节与光泽",
          "微观写实：织物、金属、地板纹理全部精确",
          "隐藏的象征物（disguised symbolism）布满日常场景",
          "室内空间与镜子、窗户构成的复杂反射"],
 "visual": {"色彩": "深沉的宝石色，红、绿、蓝都很厚；黑是真正的深黑",
            "光影": "细致的窗光与烛光，金属高光锐利，阴影通透",
            "笔触": "几乎不可见——层层透明罩染（glaze），表面如镜",
            "构图": "室内中景，人物居中，背景细节填满每个角落",
            "材质": "橡木板油画、亚麻布、金箔、镜面与铅玻璃",
            "情绪": "冷静、精密、虔敬中带着世俗的富足"},
 "palette": [("#7A1F2B","深酒红"),("#1E4A3A","深绿"),("#1B3A6B","深蓝"),
             ("#C9A227","金"),("#2B2B2B","真黑"),("#E8DCC0","亚麻白")],
 "artists": [("扬·范艾克","1390–1441"),("罗希尔·范德魏登","1399–1464"),
             ("汉斯·梅姆林","1430–1494"),("博斯","1450–1516"),("彼得鲁斯·克里斯蒂","1410–1475")],
 "prompt": {"style": "early netherlandish painting, flemish primitive, microscopic realism, layered translucent glazes, disguised symbolism",
            "lighting": "precise window light, razor-sharp metallic specular highlights, transparent shadows, candle accent",
            "color": "deep jewel tones, burgundy, forest green, midnight blue, gold, true black, linen white",
            "composition": "interior middle ground, centrally placed figures, richly detailed every corner",
            "medium": "oil on oak panel, invisible brushwork, mirror-smooth glazed surface",
            "mood": "cool, meticulous, devout yet opulent",
            "camera": "eye-level, medium shot, 50mm, deep focus, symmetrical"},
 "negative": "loose brushwork, impressionist, visible strokes, blurry, soft focus, modern interior, minimalist",
 "video": {"motion": "极其细微：烛火、翻书、布料褶皱的微动",
           "camera": "static 或极缓 dolly in 展示细节",
           "note": "这一派的力量在细节密度，运镜要慢到让人看清细节"},
 "pitfalls": ["AI 会给油画加厚涂 → 必须写 invisible brushwork, glazed smooth surface",
              "细节密度容易不足 → 加 microscopic realism, every detail resolved"],
 "sources": {"cleveland": ["van eyck", "memling", "early netherlandish"],
             "met": ["van eyck", "rogier van der weyden", "memling"],
             "commons": ["Jan van Eyck painting"]},
 "see_also": ["renaissance", "gothic", "dutch-golden-age"],
},
# ---------------------------------------------------------------- 威尼斯画派
{
 "slug": "venetian-school", "name_zh": "威尼斯画派", "name_en": "Venetian School",
 "period": "1500–1600", "region": "威尼斯", "tier": "A",
 "one_liner": "不画线条，用颜色本身造形——油画史上第一次「色彩优先」。",
 "core": ["色建构形（colorito）对抗佛罗伦萨的素描优先（disegno）",
          "温暖的威尼斯光，大气与湿度可见",
          "感官性：丝绸、肌肤、水面的质感被极度珍视",
          "松散的晚期笔触预示了印象派"],
 "visual": {"色彩": "温暖浓郁：威尼斯红、金褐、深绿、天青；饱和度高于同期佛罗伦萨",
            "光影": "柔和温暖的环境光，明暗过渡丰富，空气有湿度感",
            "笔触": "早期柔和，晚期（提香、丁托列托）松弛奔放、可见笔痕",
            "构图": "斜向与对角线，人物在开阔的风景或建筑中，空间感来自色彩而非线条",
            "材质": "粗纹亚麻布油画、暖色底子、厚涂与罩染并用",
            "情绪": "感官、丰饶、抒情、带着肉体的温度"},
 "palette": [("#A8322D","威尼斯红"),("#8B5E2A","金褐"),("#1E4A3A","深绿"),
             ("#4A7C9E","天青"),("#D9B26A","暖金"),("#2B2318","暖褐黑")],
 "artists": [("提香","1488–1576"),("乔尔乔内","1477–1510"),("丁托列托","1518–1594"),
             ("委罗内塞","1528–1588"),("贝利尼","1430–1516")],
 "prompt": {"style": "venetian school oil painting, colorito, sensuous handling, atmospheric warmth, loose late brushwork, tonal construction",
            "lighting": "warm humid ambient light, rich tonal transitions, glowing golden atmosphere, soft reflected light",
            "color": "warm saturated palette, venetian red, golden brown, deep green, cerulean, glowing flesh tones",
            "composition": "diagonal arrangement, figures in open landscape or architecture, depth built by colour not line",
            "medium": "oil on coarse linen, warm ground, glazing over visible brushwork",
            "mood": "sensuous, opulent, lyrical, bodily warmth",
            "camera": "eye-level, medium wide shot, 50mm"},
 "negative": "linear drawing, crisp outlines, cool grey palette, hard edges, impressionist dots, flat lighting",
 "video": {"motion": "布料滑落、水面波动、人物转身；动作流畅而肉感",
           "camera": "缓慢 arc shot 环绕，或 slow dolly in",
           "note": "威尼斯派的运动要有「重量和温度」，不要轻飘"},
 "pitfalls": ["AI 会加硬轮廓线 → negative 写 linear drawing, crisp outlines",
              "容易变成普通古典画 → 强调 colorito, warm humid atmosphere"],
 "sources": {"cleveland": ["titian", "veronese", "tintoretto"],
             "met": ["titian", "paolo veronese"], "commons": ["Titian painting"]},
 "see_also": ["renaissance", "baroque", "mannerism"],
},
# ---------------------------------------------------------------- 样式主义
{
 "slug": "mannerism", "name_zh": "样式主义", "name_en": "Mannerism",
 "period": "1520–1600", "region": "意大利 / 欧洲宫廷", "tier": "A",
 "one_liner": "拉斐尔之后无路可走，于是把比例拉长、颜色变酸、姿态拧成螺旋。",
 "core": ["figura serpentinata：螺旋上升的扭曲姿态",
          "比例刻意拉长，头小颈长手指细",
          "色彩转向酸性的粉、绿、紫，不再自然",
          "空间被压扁，人物堆叠在画面前沿"],
 "visual": {"色彩": "酸性、不自然的粉绿紫橙并置；冷暖冲突强烈",
            "光影": "冷调的均匀光，形体如瓷器般光滑；阴影少而硬",
            "笔触": "高度抛光、无笔触，追求优雅的表面",
            "构图": "拥挤的前景、压扁的空间、螺旋扭动的人体、不稳定的平衡",
            "材质": "抛光油画、冷色底子、青铜雕塑",
            "情绪": "优雅、不安、造作、智性的焦虑"},
 "palette": [("#C98BA5","酸粉"),("#8FA86B","酸绿"),("#6B4A8B","紫"),
             ("#D98B4A","橙"),("#4A6B8B","冷蓝"),("#E8DCC8","瓷白")],
 "artists": [("蓬托尔莫","1494–1557"),("布龙齐诺","1503–1572"),("帕米贾尼诺","1503–1540"),
             ("切利尼","1500–1571"),("埃尔·格列柯","1541–1614")],
 "prompt": {"style": "mannerism painting, figura serpentinata, elongated proportions, acid unnatural colour, polished porcelain finish, courtly artifice",
            "lighting": "cool even light, porcelain-smooth modelling, few hard shadows, no warm atmosphere",
            "color": "acid palette, pink, acidic green, violet, orange, cool blue, clashing and unnatural",
            "composition": "crowded foreground, compressed space, spiralling twisted figures, unstable balance",
            "medium": "highly polished oil on panel or canvas, invisible brushwork",
            "mood": "elegant, uneasy, artificial, intellectual anxiety",
            "camera": "slightly low angle, medium shot, compressed perspective, 85mm"},
 "negative": "natural proportions, naturalistic colour, warm venetian light, loose brushwork, realistic anatomy, comfortable symmetry",
 "video": {"motion": "缓慢扭动的优雅动作，肢体像被拉长的弹簧",
           "camera": "缓慢 arc 环绕，突出螺旋姿态",
           "note": "样式主义的动是「优雅地不舒服」——流畅里带一点错位"},
 "pitfalls": ["AI 会修正成正常比例 → 必须写 elongated proportions, small head, long neck",
              "颜色容易被拉回自然 → 明确 acid unnatural colour"],
 "sources": {"cleveland": ["pontormo", "bronzino", "mannerism"],
             "met": ["bronzino", "pontormo", "el greco"], "commons": ["Bronzino painting"]},
 "see_also": ["renaissance", "venetian-school", "baroque"],
},
# ---------------------------------------------------------------- 荷兰黄金时代
{
 "slug": "dutch-golden-age", "name_zh": "荷兰黄金时代", "name_en": "Dutch Golden Age",
 "period": "1600–1680", "region": "荷兰", "tier": "A",
 "one_liner": "把光变成一种物质：从窗口斜进来的一束光，照亮整个日常世界。",
 "core": ["室内光作为绝对主角，光源明确来自左侧窗户",
          "日常题材的尊严化：厨娘、账房、静物、街景",
          "精密的材质再现：锡罐、面包、蕾丝、玻璃",
          "暧昧的道德寓意藏在最平常的物品里"],
 "visual": {"色彩": "暖褐与铅灰为主，点缀朱红与钴蓝；克制的饱和度",
            "光影": "单一窗光，明确的明暗分区，暗部有细节，亮部有质感",
            "笔触": "精微处几乎无笔触；伦勃朗式则是厚涂与刮刀并用",
            "构图": "室内一角，人物常侧身或背对，视线望向画外",
            "材质": "细纹亚麻布、铅白底子、透明罩染",
            "情绪": "宁静、克制、日常的庄重、略带私密感"},
 "palette": [("#6B4A2A","暖褐"),("#8B8B85","锡灰"),("#A8322D","朱红"),
             ("#2B4C7A","钴蓝"),("#C9A227","黄铜"),("#E8DCC8","窗光白")],
 "artists": [("维米尔","1632–1675"),("伦勃朗","1606–1669"),("哈尔斯","1582–1666"),
             ("扬·斯特恩","1626–1679"),("彼得·德·霍赫","1629–1684")],
 "prompt": {"style": "dutch golden age painting, genre interior, meticulous material rendering, quiet realism, hidden moral symbolism",
            "lighting": "single window light from the left, clear light and shade division, detail held in shadows, luminous highlights",
            "color": "warm brown and lead grey dominant, vermilion and cobalt accents, restrained saturation",
            "composition": "corner of an interior, figure turned away or in profile, gaze out of frame, quiet arrangement",
            "medium": "oil on fine linen, lead white ground, transparent glazing, subtle impasto",
            "mood": "serene, restrained, everyday dignity, intimate",
            "camera": "eye-level, medium shot, 50mm, deep focus"},
 "negative": "dramatic multiple light sources, saturated colour, loose expressionist brushwork, modern interior, neon",
 "video": {"motion": "倒水、翻书、抬头；动作缓慢而精确",
           "camera": "static 或极缓 dolly in；尊重单一光源",
           "note": "光源必须唯一且来自画外，多光源会立刻杀死荷兰味"},
 "pitfalls": ["AI 会给多光源 → 明确 single window light from the left",
              "容易做成普通静物照 → 加 oil painting, glazed surface, 17th century interior"],
 "sources": {"cleveland": ["vermeer", "pieter de hooch", "frans hals"],
             "met": ["vermeer", "frans hals", "jan steen"], "commons": ["Johannes Vermeer painting"]},
 "see_also": ["baroque", "caravaggisti", "early-netherlandish"],
},
# ---------------------------------------------------------------- 卡拉瓦乔主义
{
 "slug": "caravaggisti", "name_zh": "卡拉瓦乔主义", "name_en": "Caravaggisti",
 "period": "1600–1650", "region": "意大利 / 欧洲", "tier": "A",
 "one_liner": "把圣人画成街上的穷人，用地下室的光照着他们。",
 "core": ["tenebrism 的极端形式：背景全黑，光只打在关键局部",
          "宗教人物用当代穷人做模特，神圣与粗俗并置",
          "无叙事背景，人物被推到画面最前沿",
          "强烈的肉体感与戏剧性的明暗对照"],
 "visual": {"色彩": "极暗的褐黑底 + 少数几个高亮颜色（红、白、肤）",
            "光影": "单一强侧光，大面积死黑，边缘被光切出锐利轮廓",
            "笔触": "写实的精细 + 松弛的暗部；不追求优雅表面",
            "构图": "近距离、浅空间、人物占满画面、常有画框外的动作",
            "材质": "粗布油画、深色底子、直接画法（alla prima）",
            "情绪": "戏剧、粗粝、虔诚与暴力并存、令人不安的临场感"},
 "palette": [("#141210","沥青黑"),("#6B3A2A","焦褐"),("#A8322D","血red"),
             ("#E8DCC8","高光白"),("#8B6B3A","土黄"),("#2B3A4A","冷蓝影")],
 "artists": [("卡拉瓦乔","1571–1610"),("阿尔泰米西娅","1593–1656"),
             ("奥拉齐奥·真蒂莱斯基","1563–1639"),("鲁本斯（早期）","1577–1640"),
             ("德·拉·图尔","1593–1652")],
 "prompt": {"style": "caravaggesque painting, extreme tenebrism, contemporary street models for sacred figures, direct observation, dramatic realism",
            "lighting": "single hard raking light from off-frame, vast dead black background, razor-sharp lit contours, no fill light",
            "color": "bituminous near-black ground, few high-key accents, blood red, stark white, warm flesh",
            "composition": "close cropped shallow space, figures filling the frame, action entering from outside the picture",
            "medium": "oil on coarse canvas, dark ground, direct alla prima painting",
            "mood": "dramatic, raw, devout and violent, uncomfortably immediate",
            "camera": "slight low angle, medium close-up, 85mm, shallow depth of field"},
 "negative": "even ambient lighting, pastel colours, multiple light sources, cartoon, cel shading, clean digital, comfortable composition",
 "video": {"motion": "突然的转身、举刀、伸手；动作有明确的爆发点",
           "camera": "缓慢 push in 逼近，或 static 让光自己说话",
           "note": "背景必须全黑且只有一个光源——这是卡拉瓦乔唯一不可让步的地方"},
 "pitfalls": ["只写 dark 不够 → 必须写 tenebrism, single hard raking light, dead black background",
              "AI 会自动补环境光 → negative 写 multiple light sources, even ambient lighting"],
 "sources": {"cleveland": ["caravaggio", "artemisia gentileschi"],
             "met": ["caravaggio", "georges de la tour"], "commons": ["Caravaggio painting"]},
 "see_also": ["baroque", "dutch-golden-age", "realism"],
},
# ---------------------------------------------------------------- 学院派
{
 "slug": "academic-art", "name_zh": "学院派艺术", "name_en": "Academic Art",
 "period": "1750–1900", "region": "法国 / 欧洲", "tier": "A",
 "one_liner": "沙龙的标准答案：完美素描、光滑表面、神话与历史的正确姿势。",
 "core": ["素描高于色彩（disegno 传统的延续）",
          "光滑无笔触的「舔过」表面（licked finish）",
          "历史画与神话题材，严格的构图与解剖规范",
          "理想化的人体，绝不出现现实的不完美"],
 "visual": {"色彩": "柔和协调的棕调体系，肉色与织物色精致过渡",
            "光影": "均匀的影棚式布光，形体圆润，阴影透明",
            "笔触": "完全看不见笔触，表面如照片般光滑",
            "构图": "金字塔或舞台式排列，清晰的视觉引导线",
            "材质": "细纹亚麻布、多层罩染、抛光表面",
            "情绪": "端庄、理想化、叙事性、无可指摘的完美"},
 "palette": [("#8B6B4A","棕调"),("#D9B29A","肤"),("#7A1F2B","深红"),
             ("#1B3A6B","深蓝"),("#C9A227","金"),("#E8DCC8","象牙")],
 "artists": [("布格罗","1825–1905"),("卡巴内尔","1823–1889"),("热罗姆","1824–1904"),
             ("阿尔玛-塔德玛","1836–1912"),("勒布伦","1755–1842")],
 "prompt": {"style": "academic art, french salon painting, licked finish, idealized classical figures, impeccable draughtsmanship, mythological subject",
            "lighting": "even studio lighting, rounded modelling, transparent soft shadows, no drama",
            "color": "harmonised brown tonal system, refined flesh tones, muted crimson, deep blue, gold",
            "composition": "pyramidal or staged arrangement, clear leading lines, balanced and legible",
            "medium": "oil on fine linen, many glazes, polished invisible surface",
            "mood": "dignified, idealized, narrative, faultlessly polished",
            "camera": "eye-level, wide shot, 50mm, deep focus"},
 "negative": "visible brushwork, impasto, gritty realism, unfinished, modern subject, loose sketch, messy",
 "video": {"motion": "优雅克制的动作，衣袍与旗帜有控制的飘动",
           "camera": "缓慢 crane 或 static；对称而庄重",
           "note": "学院派的运镜也要「正确」——稳定、对称、无可指摘"},
 "pitfalls": ["AI 会加厚涂 → 明确 licked finish, invisible brushwork, polished surface",
              "容易变得平庸 → 加 mythological subject, idealised classical figures"],
 "sources": {"cleveland": ["bouguereau", "cabanel", "academic art"],
             "met": ["bouguereau", "jean-leon gerome"], "commons": ["William-Adolphe Bouguereau painting"]},
 "see_also": ["neoclassicism", "realism", "pre-raphaelite"],
},
# ---------------------------------------------------------------- 新印象派
{
 "slug": "neo-impressionism", "name_zh": "新印象派（点彩）", "name_en": "Neo-Impressionism",
 "period": "1884–1900", "region": "法国", "tier": "A",
 "one_liner": "把印象派的直觉变成科学：用纯色小点让眼睛自己调色。",
 "core": ["点彩法（pointillism）：细小纯色笔触并置，由视网膜混合",
          "补色对比与光学理论（修拉、西涅克）",
          "追求数学化的构图与黄金分割",
          "画面因此极其稳定、静止，失去了印象派的即兴"],
 "visual": {"色彩": "纯色小点并置：橙与蓝、黄与紫、红与绿成对出现",
            "光影": "均匀明亮的户外光，阴影也由彩色点构成",
            "笔触": "统一大小的小圆点或短笔触，覆盖全画面，无一处随意",
            "构图": "几何化、稳定、常带黄金分割与明确边框",
            "材质": "细纹布面、平涂排列的纯色小点、哑光表面",
            "情绪": "静谧、理性、近乎数学的秩序感"},
 "palette": [("#E8A33D","橙"),("#2B4C9B","钴蓝"),("#F0C420","黄"),
             ("#6B3FA0","紫"),("#C1272D","红"),("#5A8F6B","绿")],
 "artists": [("修拉","1859–1891"),("西涅克","1863–1935"),("克罗斯","1856–1910"),
             ("毕沙罗（晚期）","1830–1903"),("吕斯","1867–1935")],
 "prompt": {"style": "neo-impressionism, pointillism, divisionism, small pure colour dots, optical colour mixture, scientific colour theory",
            "lighting": "even bright outdoor light, shadows also built from coloured dots, no black",
            "color": "pure complementary dots side by side, orange against blue, yellow against violet, red against green",
            "composition": "geometric stable structure, golden section, clear framing, deliberate balance",
            "medium": "oil on fine canvas, uniform small dots of pure pigment, matte surface",
            "mood": "still, rational, near-mathematical order, tranquil",
            "camera": "eye-level, wide shot, 35mm, flattened depth"},
 "negative": "large loose brushstrokes, impasto, black shadows, muddy colour mixing, spontaneous sketchiness, blurry",
 "video": {"motion": "极缓慢：水面微光闪动、人群几乎静止",
           "camera": "static 为主；点彩画不适合运动镜头",
           "note": "点彩的动感应只在「光的闪烁」层面，人物动多了画面就碎了"},
 "pitfalls": ["AI 会把点彩做成模糊噪点 → 明确 uniform small dots, pure pigment, optical mixture",
              "容易丢失稳定性 → 强调 geometric stable composition, golden section"],
 "sources": {"cleveland": ["seurat", "signac", "neo-impressionism"],
             "met": ["georges seurat", "paul signac"], "commons": ["Georges Seurat painting"]},
 "see_also": ["impressionism", "post-impressionism"],
},
# ---------------------------------------------------------------- 纳比派
{
 "slug": "nabis", "name_zh": "纳比派", "name_en": "Les Nabis",
 "period": "1888–1900", "region": "法国", "tier": "A",
 "one_liner": "把画变成装饰：平面色块、粗轮廓、日常室内的一层温柔滤镜。",
 "core": ["平面化与装饰性，受浮世绘与高更影响",
          "室内日常题材：餐桌、浴室、花园、孩子",
          "柔和而饱和的色块，轮廓被弱化或消失",
          "绘画与装饰艺术（屏风、壁纸、剧场）打通"],
 "visual": {"色彩": "柔和却饱满：赭黄、玫瑰、青绿、灰蓝；色块之间关系微妙",
            "光影": "光被主观化，没有明确光源，只有色块的明度差",
            "笔触": "平涂为主，边缘模糊，偶有布料般的哑光肌理",
            "构图": "摄影式裁切、装饰性图案铺满、视点常被抬高",
            "材质": "布面蛋彩或油画、哑光胶质表面、装饰屏风",
            "情绪": "亲密、温柔、日常的诗意、略带忧郁"},
 "palette": [("#D9A25A","赭黄"),("#C98BA5","玫瑰"),("#5A8F7A","青绿"),
             ("#7A8FA8","灰蓝"),("#B03A2E","砖红"),("#E8DCC8","米白")],
 "artists": [("博纳尔","1867–1947"),("维亚尔","1868–1940"),("德尼","1870–1943"),
             ("塞律西埃","1864–1927"),("瓦洛东","1865–1925")],
 "prompt": {"style": "les nabis painting, decorative flat colour areas, intimate domestic interior, synthetist simplification, japonisme influence",
            "lighting": "subjective light, no defined source, tonal difference between flat colour areas only",
            "color": "soft yet saturated, ochre yellow, rose, teal green, grey blue, brick red, matte harmony",
            "composition": "photographic cropping, decorative pattern filling the surface, raised viewpoint",
            "medium": "oil or distemper on canvas, matte surface, decorative screen format",
            "mood": "intimate, tender, domestic poetry, faint melancholy",
            "camera": "eye-level or slightly raised, medium shot, 35mm"},
 "negative": "realistic lighting, chiaroscuro, sharp outlines, dramatic subject, photorealistic texture, dark moody",
 "video": {"motion": "缓慢的日常动作：倒茶、孩子跑过、窗帘飘动",
           "camera": "static 生活片段，或极缓 pan",
           "note": "纳比派的动是「被温柔注视的日常」，别加戏剧性"},
 "pitfalls": ["AI 会加写实光影 → negative 写 realistic lighting, chiaroscuro",
              "色彩容易过艳 → 强调 matte, soft harmony, 装饰性而非刺激"],
 "sources": {"cleveland": ["bonnard", "vuillard", "nabis"],
             "met": ["pierre bonnard", "edouard vuillard"], "commons": ["Pierre Bonnard painting"]},
 "see_also": ["post-impressionism", "symbolism", "ukiyo-e"],
},
# ---------------------------------------------------------------- 维也纳分离派
{
 "slug": "vienna-secession", "name_zh": "维也纳分离派", "name_en": "Vienna Secession",
 "period": "1897–1918", "region": "奥地利", "tier": "A",
 "one_liner": "金箔、几何纹样与情欲：把世纪末维也纳的华丽与焦虑压进画面。",
 "core": ["装饰性金箔与几何图案大面积使用",
          "人物与图案互相渗透，边界消失",
          "情欲、死亡、女性身体作为核心母题",
          "整体艺术（Gesamtkunstwerk）：绘画、建筑、设计同一语言"],
 "visual": {"色彩": "金箔 + 深色底 + 局部鲜亮色块；装饰性极强",
            "光影": "平面化，人物像被压进图案；没有真实光源",
            "笔触": "细腻平涂 + 马赛克式小色块；装饰线条精确",
            "构图": "垂直构图、方框套方框、图案填满背景",
            "材质": "金箔、油画、马赛克、彩色玻璃、金属装饰",
            "情绪": "华丽、感官、不安、濒死的绚烂"},
 "palette": [("#C9A227","金箔"),("#1B3A4A","深蓝绿"),("#7A1F3A","深紫红"),
             ("#2B2B33","黑"),("#D98B4A","橙金"),("#E8DCC8","象牙")],
 "artists": [("克里姆特","1862–1918"),("席勒","1890–1918"),("霍夫曼","1870–1956"),
             ("莫泽","1868–1918"),("科科施卡","1886–1980")],
 "prompt": {"style": "vienna secession, art nouveau gold ornament, geometric pattern interpenetrating figures, symbolist eroticism, gesamtkunstwerk",
            "lighting": "flat decorative, figures pressed into pattern, no realistic light source",
            "color": "gold leaf on dark ground, deep teal, dark magenta, black, orange gold, ivory",
            "composition": "vertical format, frame within frame, ornament filling the background",
            "medium": "oil with gold leaf, mosaic, stained glass, metal inlay",
            "mood": "opulent, sensuous, anxious, gorgeous decay",
            "camera": "eye-level, vertical portrait composition, flat depth"},
 "negative": "realistic perspective, plain background, naturalistic lighting, minimalist, gritty, documentary",
 "video": {"motion": "金箔闪烁、图案缓慢流动、布料与发丝轻摆",
           "camera": "极缓 dolly in，或 static 让图案呼吸",
           "note": "装饰图案是主体，镜头不要抢戏"},
 "pitfalls": ["容易只做成「金色装饰画」→ 加 interpenetrating figures, symbolist eroticism",
              "和穆夏混淆 → 克里姆特更几何、更暗、更情欲；穆夏更海报化"],
 "sources": {"cleveland": ["klimt", "schiele"], "met": ["gustav klimt", "egon schiele"],
             "commons": ["Gustav Klimt painting", "Egon Schiele painting"]},
 "see_also": ["symbolism", "art-nouveau", "expressionism"],
},
# ---------------------------------------------------------------- 工艺美术运动
{
 "slug": "arts-and-crafts", "name_zh": "工艺美术运动", "name_en": "Arts and Crafts",
 "period": "1860–1910", "region": "英国", "tier": "A",
 "exclude_keys": ["morris hunt", "hunt, william morris"],
 "one_liner": "反工业化：用手工、自然纹样和中世纪精神对抗机器生产。",
 "core": ["手工至上，反对机器量产（拉斯金、莫里斯）",
          "自然纹样高度风格化：藤蔓、花卉、鸟类",
          "中世纪与民间传统的复兴",
          "装饰与实用合一：壁纸、织物、家具、书籍"],
 "visual": {"色彩": "植物染色系的柔和色：苔绿、赭黄、砖红、靛蓝",
            "光影": "平面装饰为主，无立体塑造",
            "笔触": "图案化的平涂线条，重复单元构成纹样",
            "构图": "满版重复图案，或带边框的叙事性插图",
            "材质": "手工印刷壁纸、木刻版画、羊毛织物、染色玻璃",
            "情绪": "温厚、自然、诚恳、带着道德感的朴素"},
 "palette": [("#5A7A4A","苔绿"),("#C9A227","赭黄"),("#A8322D","砖红"),
             ("#2B4C7A","靛蓝"),("#8B6B4A","木褐"),("#E8DCC8","纸白")],
 "artists": [("威廉·莫里斯","1834–1896"),("伯恩-琼斯","1833–1898"),
             ("沃伊齐","1857–1941"),("麦克默多","1851–1942"),("克兰","1845–1915")],
 "prompt": {"style": "arts and crafts movement, william morris wallpaper pattern, stylised botanical repeat, medieval revival, handcrafted ornament",
            "lighting": "flat decorative, no modelling, pattern over form",
            "color": "vegetable dye softness, moss green, ochre, brick red, indigo, wood brown, paper cream",
            "composition": "all-over repeating pattern, or framed narrative illustration, dense but ordered",
            "medium": "hand block-printed wallpaper, woodcut, wool textile, stained glass",
            "mood": "warm, natural, sincere, morally earnest simplicity",
            "camera": "flat frontal, pattern fills the frame, orthographic"},
 "negative": "3d render, glossy plastic, industrial mass production, metallic chrome, neon, photographic realism",
 "video": {"motion": "纹样单元循环生长、藤蔓缓慢蔓延",
           "camera": "static 平面构图；图案动画而非摄影动画",
           "note": "工艺美术运动是图案思维，镜头语言要平面化"},
 "pitfalls": ["和新艺术运动混淆 → 工艺美术更朴素、更中世纪；新艺术更曲线化、更感官",
              "AI 会加立体感 → negative 写 3d render, glossy, modelling"],
 "sources": {"cleveland": ["william morris", "arts and crafts"],
             "met": ["william morris textile"], "commons": ["William Morris design", "Walter Crane illustration", "Arts and Crafts textile pattern"]},
 "see_also": ["pre-raphaelite", "art-nouveau", "vienna-secession"],
},
# ---------------------------------------------------------------- 哈德逊河派
{
 "slug": "hudson-river-school", "name_zh": "哈德逊河派", "name_en": "Hudson River School",
 "period": "1825–1875", "region": "美国", "tier": "A",
 "exclude_keys": ["sketchbook", "sketch book", "sketch-book"],
 "one_liner": "美国第一场本土画派：用巨大的荒野风景表达国家天命与宗教敬畏。",
 "core": ["宏大风景，人极其渺小甚至缺席",
          "发光主义（luminism）：光线从云缝或地平线射出",
          "细致的植物与地质观察，兼具科学性与象征性",
          "荒野作为神圣空间，暗含「昭昭天命」"],
 "visual": {"色彩": "清晨与黄昏的暖金、淡紫、灰绿；天空层次极丰富",
            "光影": "低角度阳光穿透云层，湿润大气产生光晕与无穷层次",
            "笔触": "精细写实，局部细腻；晚年趋向大气与简化",
            "构图": "前景引导（岩石、树木）+ 中景水面 + 远景山脉的三段式",
            "材质": "细纹布面油画、多层罩染、透明大气效果",
            "情绪": "崇高、宁静、敬畏、爱国式的壮阔"},
 "palette": [("#C9A227","晨曦金"),("#8B9BB0","远山蓝"),("#3E5A3A","森林绿"),
             ("#D9A25A","晚霞橙"),("#6B5A7A","云影紫"),("#E8DCC8","云白")],
 "artists": [("科尔","1801–1848"),("丘奇","1826–1900"),("比尔施塔特","1830–1902"),
             ("英尼斯","1825–1894"),("杜兰德","1796–1886")],
 "prompt": {"style": "hudson river school landscape, american luminism, vast wilderness, meticulous geological detail, transcendental awe",
            "lighting": "low sun breaking through clouds, luminous god rays, humid atmospheric perspective, infinite depth layers",
            "color": "dawn gold, distant blue-violet mountains, forest green, sunset orange, cloud shadow purple",
            "composition": "foreground repoussoir, middle water plane, distant mountain range, three-part depth",
            "medium": "oil on fine canvas, many transparent glazes, luminous atmospheric finish",
            "mood": "sublime, serene, reverent, national grandeur",
            "camera": "extreme wide establishing shot, 24mm, deep focus"},
 "negative": "close-up, urban scene, small intimate scale, impressionist loose strokes, flat lighting, modern elements",
 "video": {"motion": "云层缓慢移动、水面涟漪、树叶微动",
           "camera": "极缓 crane up 或 static wide；强调尺度",
           "note": "关键是人小景大——镜头必须给到宏大的远景"},
 "pitfalls": ["AI 容易只给「漂亮风景照」→ 加 sublime, vast scale, luminism, god rays",
              "层次不够 → 明确 three-part depth, atmospheric perspective"],
 "sources": {"cleveland": ["hudson river school", "church", "bierstadt"],
             "met": ["frederic edwin church", "albert bierstadt", "thomas cole"],
             "commons": ["Frederic Edwin Church painting", "Albert Bierstadt painting", "Thomas Cole painting"]},
 "see_also": ["romanticism", "tonalism"],
},
# ---------------------------------------------------------------- 色调主义
{
 "slug": "tonalism", "name_zh": "色调主义", "name_en": "Tonalism",
 "period": "1880–1915", "region": "美国", "tier": "A",
 "one_liner": "把风景化成一种颜色气氛：黄昏、雾气、模糊边界与安静的忧郁。",
 "core": ["统一的色调笼罩全画（多为灰、褐、紫灰）",
          "边界模糊，形体被氛围溶解",
          "黄昏、月夜、雨雾是首选时刻",
          "情绪高于细节，接近音乐性的氛围"],
 "visual": {"色彩": "极窄的调色板：灰紫、褐绿、暗金、银灰；低饱和低对比",
            "光影": "漫射的暮光，没有明确光源，一切浸在雾里",
            "笔触": "柔和、羽化、笔触之间互相渗透；wet-in-wet",
            "构图": "简约、留白多、地平线低、单一母题（一棵树、一片水）",
            "材质": "布面油画、薄涂多层、柔和的哑光表面",
            "情绪": "忧郁、静谧、冥想、时间停止的感觉"},
 "palette": [("#6B6B7A","雾灰紫"),("#5A6B5A","褐绿"),("#8B7A5A","暗金"),
             ("#A8A8B0","银灰"),("#3A3A4A","暮蓝"),("#D9CFC0","雾白")],
 "artists": [("英尼斯","1825–1894"),("惠斯勒","1834–1903"),("德怀特·特赖恩","1849–1925"),
             ("墨菲","1853–1921"),("马丁","1836–1897")],
 "prompt": {"style": "tonalism landscape, unified muted tonality, atmospheric dissolution, twilight mood, musical abstraction",
            "lighting": "diffused twilight, no defined source, everything veiled in mist, low contrast",
            "color": "narrow tonal palette, grey violet, brownish green, muted gold, silver grey, low saturation",
            "composition": "minimal and sparse, lots of empty space, low horizon, single motif",
            "medium": "oil on canvas, thin layered washes, soft matte surface, wet-in-wet",
            "mood": "melancholic, hushed, meditative, time suspended",
            "camera": "wide shot, soft focus, 50mm, hazy atmosphere"},
 "negative": "high contrast, saturated colour, sharp detail, bright daylight, busy composition, crisp edges",
 "video": {"motion": "雾气缓慢流动、水面微澜、几乎静止",
           "camera": "static 长镜头；任何快速运动都会破坏氛围",
           "note": "色调主义靠「什么都没有发生」取胜"},
 "pitfalls": ["AI 会加对比和清晰度 → negative 写 high contrast, sharp detail, crisp edges",
              "容易被当成「曝光不足」→ 强调 intentional muted tonality, atmospheric"],
 "sources": {"cleveland": ["tonalism", "whistler"], "met": ["george inness", "james mcneill whistler"],
             "commons": ["George Inness painting"]},
 "see_also": ["hudson-river-school", "romanticism", "symbolism"],
},
# ---------------------------------------------------------------- 阿什坎学派
{
 "slug": "ashcan-school", "name_zh": "阿什坎学派", "name_en": "Ashcan School",
 "period": "1900–1915", "region": "美国", "tier": "A",
 "exclude_keys": ["fantin", "guérard", "guerard", "sérusier", "serusier", "schumann"],
 "one_liner": "把镜头对准城市的脏乱：后巷、酒馆、拳击场和挤满人的街道。",
 "core": ["城市底层日常作为正当题材",
          "快速、粗糙、有新闻速写感的笔触",
          "暗调、泥泞的色彩，拒绝美化",
          "群像与瞬间抓取，接近摄影纪实"],
 "visual": {"色彩": "暗沉的泥色：褐、灰、墨绿、脏白；饱和度低",
            "光影": "街灯的昏黄、阴天的灰光；对比不强烈但很脏",
            "笔触": "粗放、快速、可见；干笔与刮擦并用",
            "构图": "拥挤、裁切随意、视点来自街面",
            "材质": "布面油画、粗纹、厚薄不均的颜料层",
            "情绪": "粗粝、同情、活力与疲惫并存"},
 "palette": [("#5A4A3A","泥褐"),("#6B6B60","脏灰"),("#3E4A3A","墨绿"),
             ("#C9A227","街灯黄"),("#8B3A2A","砖红"),("#D9CFC0","脏白")],
 "artists": [("亨利","1865–1929"),("斯隆","1871–1951"),("贝洛斯","1882–1925"),
             ("格拉肯斯","1870–1938"),("卢克斯","1867–1933")],
 "prompt": {"style": "ashcan school painting, urban realism, gritty city life, rapid sketchy brushwork, newspaper illustration energy",
            "lighting": "sickly street lamp yellow, overcast grey daylight, muddy unglamorous light",
            "color": "muddy tonal palette, brown, dirty grey, dark green, dull white, low saturation",
            "composition": "crowded, casually cropped, street-level viewpoint, figures in motion",
            "medium": "oil on coarse canvas, dry brush and scraping, uneven paint film",
            "mood": "gritty, sympathetic, vigorous and weary at once",
            "camera": "eye-level, medium wide, 35mm, documentary snapshot"},
 "negative": "glamorous, idealised, golden hour glow, clean studio lighting, pastel, polished finish, empty scene",
 "video": {"motion": "人群穿梭、蒸汽升腾、马车经过；繁忙的街头节奏",
           "camera": "handheld 轻微晃动；街面视角",
           "note": "不要清理画面——阿什坎的魅力来自脏和挤"},
 "pitfalls": ["AI 会自动美化 → negative 写 glamorous, idealised, golden hour",
              "容易变成怀旧明信片 → 加 gritty, unglamorous, muddy"],
 "sources": {"cleveland": ["ashcan school", "robert henri", "george bellows"],
             "met": ["john sloan", "george bellows", "robert henri"],
             "commons": ["George Bellows painting", "John Sloan painting", "Robert Henri painting"]},
 "see_also": ["realism", "impressionism", "tonalism"],
},
]

ARTIST_KEYS = {
 "byzantine": ["byzantine", "theophanes", "rublev", "icon painter", "crete", "sinai"],
 "romanesque": ["romanesque", "románico", "romanico", "winchester bible", "saint-savin",
                 "hildesheim", "catalan", "sant climent", "taüll", "taull", "moissac",
                 "vézelay", "vezelay", "bayeux", "cluny", "fresco romanesque", "capital romanesque"],
 "gothic": ["limbourg", "duccio", "martini", "van eyck", "gothic", "gothique", "gotisch",
             "sienese", "cimabue", "giotto", "daddi", "di nerio", "lorenzetti", "bartolo",
             "stained glass", "vitrail", "chartres", "notre-dame", "international gothic"],
 "early-netherlandish": ["van eyck", "van der weyden", "memling", "bosch", "christus",
                          "campin", "gossaert", "bruegel", "massys", "david, gerard"],
 "venetian-school": ["titian", "giorgione", "tintoretto", "veronese", "bellini", "lotto",
                      "palma", "bassano"],
 "mannerism": ["pontormo", "bronzino", "parmigianino", "cellini", "el greco", "rossso",
                "rosso", "vasari", "salviati", "spranger"],
 "dutch-golden-age": ["vermeer", "rembrandt", "frans hals", "jan steen", "de hooch",
                       "ter borch", "van ruisdael", "kalf", "heeda", "claesz", "hobbema"],
 "caravaggisti": ["caravaggio", "gentileschi", "la tour", "honthorst", "terbrugghen",
                   "stomer", "manfredi", "saraceni", "baglione"],
 "academic-art": ["bouguereau", "cabanel", "gérome", "gerome", "alma-tadema", "le brun",
                   "couture", "gleyre", "chaplin", "leighton", "poynter", "tadema"],
 "neo-impressionism": ["seurat", "signac", "cross", "luce", "pissarro", "angrand",
                        "van rysselberghe", "thery", "petitjean"],
 "nabis": ["bonnard", "vuillard", "denis", "sérusier", "serusier", "vallotton",
            "ranson", "ibels", "k-x", "maillol"],
 "vienna-secession": ["klimt", "schiele", "hoffmann", "moser", "kokoschka", "wagner",
                       "olbrich", "moll"],
 "arts-and-crafts": ["william morris", "morris, william", "morris & co", "burne-jones",
                      "voysey", "mackmurdo", "walter crane", "ashbee", "gimson", "dearle"],
 "hudson-river-school": ["cole", "frederic edwin church", "church, frederic", "bierstadt",
                          "inness", "durand", "kensett", "moran", "whittredge", "gifford",
                          "cropsey", "bristol"],
 "tonalism": ["innes", "whistler", "tryon", "murphy", "martin", "blakelock",
               "dewitt", "bruce crane", "ranger"],
 "ashcan-school": ["robert henri", "henri, robert", "sloan", "bellows", "glackens",
                    "luks", "shinn", "lawson", "prendergast", "prenderast"],
}
